In [1]:
import pandas as pd
import time
import numpy as np

In [2]:
# Import Dataset
curated_bow = pd.read_csv('FrontendMavenPlugin.csv', sep='$')
curated_bow.dropna()
# Remove Trailing Spaces in Column Names
curated_bow.columns = [col.strip() for col in curated_bow.columns]
curated_bow

,id,,,,.,a,if,return,throw,void,...,"} """,} ',} :,} <,~,~ /,~ dp0node,class_name,class_value,contents
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,++ b/README.md
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,"1,23 @@"
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,This plugin downloads/installs Node and NPM lo...
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,"It's supposed to work on Windows, OS X and Linux."
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,++ b/frontend-maven-plugin/src/main/java/com/g...
4990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,}
4991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,"39,6 @@ public final class BowerMojo extends A..."
4992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,this.additionalEnvironment = additiona...
4993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,++ b/frontend-plugin-core/src/main/java/com/gi...

In [3]:
# Duplicate Columns Removed
curated_bow = curated_bow.loc[:,~curated_bow.columns.duplicated()].copy()
curated_bow

,id,,.,a,if,return,throw,void,},!,...,| |,"} """,} ',} :,} <,~ /,~ dp0node,class_name,class_value,contents
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,++ b/README.md
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,"1,23 @@"
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,This plugin downloads/installs Node and NPM lo...
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,"It's supposed to work on Windows, OS X and Linux."
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,++ b/frontend-maven-plugin/src/main/java/com/g...
4990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,}
4991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,"39,6 @@ public final class BowerMojo extends A..."
4992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,this.additionalEnvironment = additiona...
4993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,++ b/frontend-plugin-core/src/main/java/com/gi...

In [4]:
partitions_ = 1
bin_size = len(curated_bow.index)//partitions_ 
print(bin_size)

4994

In [5]:
def run_Panda():
    bins_counter = 0
    partition_values = pd.DataFrame()
    j_col= pd.DataFrame()
#     k_col= pd.DataFrame()
    
#     for j in range(len(curated_bow.columns)-3): 
    for j in range(len(curated_bow.columns)-3):
        start_j = time.time()
        clustered_att = curated_bow.sort_values(by = curated_bow.columns[j])
        
        bins_counter = 0
#         if j != j:
        for y in range(partitions_): 
            parition_mean = clustered_att.iloc[bins_counter: bins_counter + bin_size, j].values.mean()
            partition_sd = clustered_att.iloc[bins_counter: bins_counter + bin_size, j].values.std()
            mean_over_sd = parition_mean/partition_sd if partition_sd else 0

            noise_score = pd.DataFrame([np.nan_to_num(abs(x - (mean_over_sd)))
                                        for x in clustered_att.iloc[bins_counter:bins_counter + bin_size, j]])

            partition_values = pd.concat([partition_values, noise_score], axis=0)
                    
            #dropping existing indices with the same name and replacing them with new, using reset index
            partition_values= partition_values.reset_index(drop=True) 
            bins_counter = bins_counter + bin_size
#         else:
#             continue
            
        j_col= pd.concat([j_col, partition_values], axis= 1)
        partition_values.drop(partition_values.index, inplace=True)
        
        end_j = time.time()
        print("column j: " + str(j))
        print(f"Runtime of the program for j {end_j - start_j}")
        
    return j_col

In [6]:
sss = run_Panda()
sss['max_noise'] = sss.max(axis=1)

column j: 0
Runtime of the program for j 0.12500882148742676
column j: 1
Runtime of the program for j 0.1306922435760498
column j: 2
Runtime of the program for j 0.14119720458984375
column j: 3
Runtime of the program for j 0.149277925491333
column j: 4
Runtime of the program for j 0.12806034088134766
column j: 5
Runtime of the program for j 0.1205911636352539
column j: 6
Runtime of the program for j 0.11036300659179688
column j: 7
Runtime of the program for j 0.1244051456451416
column j: 8
Runtime of the program for j 0.14451241493225098
column j: 9
Runtime of the program for j 0.15283632278442383
column j: 10
Runtime of the program for j 0.11893081665039062
column j: 11
Runtime of the program for j 0.09237051010131836
column j: 12
Runtime of the program for j 0.15131783485412598
column j: 13
Runtime of the program for j 0.13643527030944824
column j: 14
Runtime of the program for j 0.15345525741577148
column j: 15
Runtime of the program for j 0.1411430835723877
column j: 16
Runtime of the program for j 0.1275796890258789
column j: 17
Runtime of the program for j 0.1253805160522461
column j: 18
Runtime of the program for j 0.15850234031677246
column j: 19
Runtime of the program for j 0.14203596115112305
column j: 20
Runtime of the program for j 0.12511110305786133
column j: 21
Runtime of the program for j 0.12520742416381836
column j: 22
Runtime of the program for j 0.13433480262756348
column j: 23
Runtime of the program for j 0.1400618553161621
column j: 24
Runtime of the program for j 0.1366426944732666
column j: 25
Runtime of the program for j 0.1187291145324707
column j: 26
Runtime of the program for j 0.14104771614074707
column j: 27
Runtime of the program for j 0.13417434692382812
column j: 28
Runtime of the program for j 0.12493371963500977
column j: 29
Runtime of the program for j 0.15063047409057617
column j: 30
Runtime of the program for j 0.1354842185974121
column j: 31
Runtime of the program for j 0.10980463027954102
column j: 32
Runtime of the program for j 0.14102673530578613
column j: 33
Runtime of the program for j 0.1348896026611328
column j: 34
Runtime of the program for j 0.13856005668640137
column j: 35
Runtime of the program for j 0.08526134490966797
column j: 36
Runtime of the program for j 0.15901565551757812
column j: 37
Runtime of the program for j 0.13684511184692383
column j: 38
Runtime of the program for j 0.13004446029663086
column j: 39
Runtime of the program for j 0.0894474983215332
column j: 40
Runtime of the program for j 0.1415255069732666
column j: 41
Runtime of the program for j 0.12373208999633789
column j: 42
Runtime of the program for j 0.15610647201538086
column j: 43
Runtime of the program for j 0.12573623657226562
column j: 44
Runtime of the program for j 0.12692999839782715
column j: 45
Runtime of the program for j 0.1419820785522461
column j: 46
Runtime of the program for j 0.1158151626586914
column j: 47
Runtime of the program for j 0.07024073600769043
column j: 48
Runtime of the program for j 0.06651687622070312
column j: 49
Runtime of the program for j 0.14172720909118652
column j: 50
Runtime of the program for j 0.11750340461730957
column j: 51
Runtime of the program for j 0.10948491096496582
column j: 52
Runtime of the program for j 0.1250009536743164
column j: 53
Runtime of the program for j 0.12144279479980469
column j: 54
Runtime of the program for j 0.13377809524536133
column j: 55
Runtime of the program for j 0.12525343894958496
column j: 56
Runtime of the program for j 0.16209125518798828
column j: 57
Runtime of the program for j 0.08320927619934082
column j: 58
Runtime of the program for j 0.13123726844787598
column j: 59
Runtime of the program for j 0.1307237148284912
column j: 60
Runtime of the program for j 0.13509154319763184
column j: 61
Runtime of the program for j 0.1330122947692871
column j: 62
Runtime of the program for j 0.12813377380371094
column j: 63
Runtime of the program for j 0.13860535621643066
column j: 64
Runtime of the program for j 0.0731198787689209
column j: 65
Runtime of the program for j 0.1495654582977295
column j: 66
Runtime of the program for j 0.16436481475830078
column j: 67
Runtime of the program for j 0.1361536979675293
column j: 68
Runtime of the program for j 0.07190704345703125
column j: 69
Runtime of the program for j 0.1280834674835205
column j: 70
Runtime of the program for j 0.1584014892578125
column j: 71
Runtime of the program for j 0.13739800453186035
column j: 72
Runtime of the program for j 0.12922978401184082
column j: 73
Runtime of the program for j 0.11942744255065918
column j: 74
Runtime of the program for j 0.15135526657104492
column j: 75
Runtime of the program for j 0.15077543258666992
column j: 76
Runtime of the program for j 0.1282181739807129
column j: 77
Runtime of the program for j 0.07816481590270996
column j: 78
Runtime of the program for j 0.07613277435302734
column j: 79
Runtime of the program for j 0.1762228012084961
column j: 80
Runtime of the program for j 0.1439681053161621
column j: 81
Runtime of the program for j 0.12557506561279297
column j: 82
Runtime of the program for j 0.13512420654296875
column j: 83
Runtime of the program for j 0.10926389694213867
column j: 84
Runtime of the program for j 0.13092803955078125
column j: 85
Runtime of the program for j 0.12932085990905762
column j: 86
Runtime of the program for j 0.11313796043395996
column j: 87
Runtime of the program for j 0.1380023956298828
column j: 88
Runtime of the program for j 0.12474274635314941
column j: 89
Runtime of the program for j 0.11889004707336426
column j: 90
Runtime of the program for j 0.15266108512878418
column j: 91
Runtime of the program for j 0.14089751243591309
column j: 92
Runtime of the program for j 0.12968111038208008
column j: 93
Runtime of the program for j 0.13291645050048828
column j: 94
Runtime of the program for j 0.13512229919433594
column j: 95
Runtime of the program for j 0.14240431785583496
column j: 96
Runtime of the program for j 0.15177464485168457
column j: 97
Runtime of the program for j 0.1496598720550537
column j: 98
Runtime of the program for j 0.10937118530273438
column j: 99
Runtime of the program for j 0.12525606155395508
column j: 100
Runtime of the program for j 0.13268256187438965
column j: 101
Runtime of the program for j 0.1371309757232666
column j: 102
Runtime of the program for j 0.1160283088684082
column j: 103
Runtime of the program for j 0.13926100730895996
column j: 104
Runtime of the program for j 0.11856245994567871
column j: 105
Runtime of the program for j 0.12543106079101562
column j: 106
Runtime of the program for j 0.1361074447631836
column j: 107
Runtime of the program for j 0.12348580360412598
column j: 108
Runtime of the program for j 0.1371622085571289
column j: 109
Runtime of the program for j 0.07813644409179688
column j: 110
Runtime of the program for j 0.14163708686828613
column j: 111
Runtime of the program for j 0.14843320846557617
column j: 112
Runtime of the program for j 0.13164305686950684
column j: 113
Runtime of the program for j 0.15840721130371094
column j: 114
Runtime of the program for j 0.06196761131286621
column j: 115
Runtime of the program for j 0.11013674736022949
column j: 116
Runtime of the program for j 0.14139771461486816
column j: 117
Runtime of the program for j 0.11808276176452637
column j: 118
Runtime of the program for j 0.14069581031799316
column j: 119
Runtime of the program for j 0.1249246597290039
column j: 120
Runtime of the program for j 0.1406254768371582
column j: 121
Runtime of the program for j 0.12608599662780762
column j: 122
Runtime of the program for j 0.12510108947753906
column j: 123
Runtime of the program for j 0.12489891052246094
column j: 124
Runtime of the program for j 0.12523818016052246
column j: 125
Runtime of the program for j 0.12622308731079102
column j: 126
Runtime of the program for j 0.11104559898376465
column j: 127
Runtime of the program for j 0.1250603199005127
column j: 128
Runtime of the program for j 0.10936260223388672
column j: 129
Runtime of the program for j 0.13407015800476074
column j: 130
Runtime of the program for j 0.12612032890319824
column j: 131
Runtime of the program for j 0.07752490043640137
column j: 132
Runtime of the program for j 0.10984587669372559

column j: 133
Runtime of the program for j 0.12508058547973633
column j: 134
Runtime of the program for j 0.1342761516571045
column j: 135
Runtime of the program for j 0.12564635276794434
column j: 136
Runtime of the program for j 0.13511133193969727
column j: 137
Runtime of the program for j 0.15619683265686035
column j: 138
Runtime of the program for j 0.15411829948425293
column j: 139
Runtime of the program for j 0.1360912322998047
column j: 140
Runtime of the program for j 0.1630697250366211
column j: 141
Runtime of the program for j 0.13354015350341797
column j: 142
Runtime of the program for j 0.11764383316040039
column j: 143
Runtime of the program for j 0.12500429153442383
column j: 144
Runtime of the program for j 0.1651449203491211
column j: 145
Runtime of the program for j 0.1495983600616455
column j: 146
Runtime of the program for j 0.14578747749328613
column j: 147
Runtime of the program for j 0.1435232162475586
column j: 148
Runtime of the program for j 0.12819194793701172
column j: 149
Runtime of the program for j 0.14478039741516113
column j: 150
Runtime of the program for j 0.07224011421203613
column j: 151
Runtime of the program for j 0.1289215087890625
column j: 152
Runtime of the program for j 0.11702251434326172
column j: 153
Runtime of the program for j 0.12854528427124023
column j: 154
Runtime of the program for j 0.11928653717041016
column j: 155
Runtime of the program for j 0.12502670288085938
column j: 156
Runtime of the program for j 0.1255936622619629
column j: 157
Runtime of the program for j 0.1282367706298828
column j: 158
Runtime of the program for j 0.14932966232299805
column j: 159
Runtime of the program for j 0.10968494415283203
column j: 160
Runtime of the program for j 0.12517404556274414
column j: 161
Runtime of the program for j 0.152923583984375
column j: 162
Runtime of the program for j 0.1250767707824707
column j: 163
Runtime of the program for j 0.0780637264251709
column j: 164
Runtime of the program for j 0.12499070167541504
column j: 165
Runtime of the program for j 0.13564062118530273
column j: 166
Runtime of the program for j 0.1529557704925537
column j: 167
Runtime of the program for j 0.12799811363220215
column j: 168
Runtime of the program for j 0.08013296127319336
column j: 169
Runtime of the program for j 0.1447606086730957
column j: 170
Runtime of the program for j 0.14449787139892578
column j: 171
Runtime of the program for j 0.13894176483154297
column j: 172
Runtime of the program for j 0.12619590759277344
column j: 173
Runtime of the program for j 0.1263120174407959
column j: 174
Runtime of the program for j 0.12800836563110352
column j: 175
Runtime of the program for j 0.1425015926361084
column j: 176
Runtime of the program for j 0.14324450492858887
column j: 177
Runtime of the program for j 0.15328025817871094
column j: 178
Runtime of the program for j 0.15455865859985352
column j: 179
Runtime of the program for j 0.14214420318603516
column j: 180
Runtime of the program for j 0.14839696884155273
column j: 181
Runtime of the program for j 0.1440896987915039
column j: 182
Runtime of the program for j 0.1323857307434082
column j: 183
Runtime of the program for j 0.10937190055847168
column j: 184
Runtime of the program for j 0.1637580394744873
column j: 185
Runtime of the program for j 0.14208674430847168
column j: 186
Runtime of the program for j 0.13428616523742676
column j: 187
Runtime of the program for j 0.12501907348632812
column j: 188
Runtime of the program for j 0.07972478866577148
column j: 189
Runtime of the program for j 0.1250460147857666
column j: 190
Runtime of the program for j 0.12780380249023438
column j: 191
Runtime of the program for j 0.12556838989257812
column j: 192
Runtime of the program for j 0.12439918518066406
column j: 193
Runtime of the program for j 0.12603473663330078
column j: 194
Runtime of the program for j 0.13393187522888184
column j: 195
Runtime of the program for j 0.12560343742370605
column j: 196
Runtime of the program for j 0.1405646800994873
column j: 197
Runtime of the program for j 0.12498784065246582
column j: 198
Runtime of the program for j 0.1255040168762207
column j: 199
Runtime of the program for j 0.12569022178649902
column j: 200
Runtime of the program for j 0.12439274787902832
column j: 201
Runtime of the program for j 0.12500309944152832
column j: 202
Runtime of the program for j 0.12553000450134277
column j: 203
Runtime of the program for j 0.11052894592285156
column j: 204
Runtime of the program for j 0.10930418968200684
column j: 205
Runtime of the program for j 0.1249690055847168
column j: 206
Runtime of the program for j 0.1254575252532959
column j: 207
Runtime of the program for j 0.14263558387756348
column j: 208
Runtime of the program for j 0.11828446388244629
column j: 209
Runtime of the program for j 0.1260077953338623
column j: 210
Runtime of the program for j 0.12500500679016113
column j: 211
Runtime of the program for j 0.15625858306884766
column j: 212
Runtime of the program for j 0.12595844268798828
column j: 213
Runtime of the program for j 0.12499880790710449
column j: 214
Runtime of the program for j 0.11089706420898438
column j: 215
Runtime of the program for j 0.14002537727355957
column j: 216
Runtime of the program for j 0.13320612907409668
column j: 217
Runtime of the program for j 0.1283409595489502
column j: 218
Runtime of the program for j 0.1292736530303955
column j: 219
Runtime of the program for j 0.15201163291931152
column j: 220
Runtime of the program for j 0.1345973014831543
column j: 221
Runtime of the program for j 0.13135170936584473
column j: 222
Runtime of the program for j 0.1260216236114502
column j: 223
Runtime of the program for j 0.14162611961364746
column j: 224
Runtime of the program for j 0.12134289741516113
column j: 225
Runtime of the program for j 0.1344916820526123
column j: 226
Runtime of the program for j 0.1249992847442627
column j: 227
Runtime of the program for j 0.12502384185791016
column j: 228
Runtime of the program for j 0.14940214157104492
column j: 229
Runtime of the program for j 0.11794328689575195
column j: 230
Runtime of the program for j 0.13312244415283203
column j: 231
Runtime of the program for j 0.14070510864257812
column j: 232
Runtime of the program for j 0.12642717361450195
column j: 233
Runtime of the program for j 0.11005687713623047
column j: 234
Runtime of the program for j 0.14640593528747559
column j: 235
Runtime of the program for j 0.07812261581420898
column j: 236
Runtime of the program for j 0.10941147804260254
column j: 237
Runtime of the program for j 0.13637161254882812
column j: 238
Runtime of the program for j 0.12514781951904297
column j: 239
Runtime of the program for j 0.1311328411102295
column j: 240
Runtime of the program for j 0.12649011611938477
column j: 241
Runtime of the program for j 0.13361215591430664
column j: 242
Runtime of the program for j 0.12500667572021484
column j: 243
Runtime of the program for j 0.11767888069152832
column j: 244
Runtime of the program for j 0.1447899341583252
column j: 245
Runtime of the program for j 0.07825660705566406
column j: 246
Runtime of the program for j 0.10939693450927734
column j: 247
Runtime of the program for j 0.12507009506225586
column j: 248
Runtime of the program for j 0.12498259544372559
column j: 249
Runtime of the program for j 0.1147298812866211
column j: 250
Runtime of the program for j 0.12507200241088867
column j: 251
Runtime of the program for j 0.12495231628417969
column j: 252
Runtime of the program for j 0.13517427444458008
column j: 253
Runtime of the program for j 0.14111638069152832
column j: 254
Runtime of the program for j 0.10937190055847168
column j: 255
Runtime of the program for j 0.15793156623840332
column j: 256
Runtime of the program for j 0.13476300239562988
column j: 257
Runtime of the program for j 0.12495160102844238
column j: 258
Runtime of the program for j 0.12614989280700684
column j: 259
Runtime of the program for j 0.125901460647583
column j: 260
Runtime of the program for j 0.1406235694885254
column j: 261
Runtime of the program for j 0.14123058319091797
column j: 262
Runtime of the program for j 0.12414193153381348
column j: 263
Runtime of the program for j 0.06792426109313965

column j: 264
Runtime of the program for j 0.12191009521484375
column j: 265
Runtime of the program for j 0.15632867813110352
column j: 266
Runtime of the program for j 0.12578225135803223
column j: 267
Runtime of the program for j 0.13726401329040527
column j: 268
Runtime of the program for j 0.1255354881286621
column j: 269
Runtime of the program for j 0.1256086826324463
column j: 270
Runtime of the program for j 0.07812714576721191
column j: 271
Runtime of the program for j 0.14439773559570312
column j: 272
Runtime of the program for j 0.13472843170166016
column j: 273
Runtime of the program for j 0.12506914138793945
column j: 274
Runtime of the program for j 0.11789679527282715
column j: 275
Runtime of the program for j 0.08850693702697754
column j: 276
Runtime of the program for j 0.11921310424804688
column j: 277
Runtime of the program for j 0.1561880111694336
column j: 278
Runtime of the program for j 0.15633344650268555
column j: 279
Runtime of the program for j 0.13582253456115723
column j: 280
Runtime of the program for j 0.13411641120910645
column j: 281
Runtime of the program for j 0.13507342338562012
column j: 282
Runtime of the program for j 0.12823772430419922
column j: 283
Runtime of the program for j 0.16380047798156738
column j: 284
Runtime of the program for j 0.1257648468017578
column j: 285
Runtime of the program for j 0.13648319244384766
column j: 286
Runtime of the program for j 0.14581799507141113
column j: 287
Runtime of the program for j 0.14934492111206055
column j: 288
Runtime of the program for j 0.13601040840148926
column j: 289
Runtime of the program for j 0.14412426948547363
column j: 290
Runtime of the program for j 0.14473676681518555
column j: 291
Runtime of the program for j 0.1526343822479248
column j: 292
Runtime of the program for j 0.12873387336730957
column j: 293
Runtime of the program for j 0.12704157829284668
column j: 294
Runtime of the program for j 0.1332545280456543
column j: 295
Runtime of the program for j 0.13320302963256836
column j: 296
Runtime of the program for j 0.13418102264404297
column j: 297
Runtime of the program for j 0.12499856948852539
column j: 298
Runtime of the program for j 0.14122700691223145
column j: 299
Runtime of the program for j 0.15366244316101074
column j: 300
Runtime of the program for j 0.11895012855529785
column j: 301
Runtime of the program for j 0.16016936302185059
column j: 302
Runtime of the program for j 0.12957382202148438
column j: 303
Runtime of the program for j 0.1412043571472168
column j: 304
Runtime of the program for j 0.12807297706604004
column j: 305
Runtime of the program for j 0.16516470909118652
column j: 306
Runtime of the program for j 0.1498706340789795
column j: 307
Runtime of the program for j 0.12829327583312988
column j: 308
Runtime of the program for j 0.1371774673461914
column j: 309
Runtime of the program for j 0.12817859649658203
column j: 310
Runtime of the program for j 0.1445465087890625
column j: 311
Runtime of the program for j 0.12666916847229004
column j: 312
Runtime of the program for j 0.13325786590576172
column j: 313
Runtime of the program for j 0.14055848121643066
column j: 314
Runtime of the program for j 0.08080601692199707
column j: 315
Runtime of the program for j 0.13959550857543945
column j: 316
Runtime of the program for j 0.15624666213989258
column j: 317
Runtime of the program for j 0.14300060272216797
column j: 318
Runtime of the program for j 0.14977407455444336
column j: 319
Runtime of the program for j 0.14074134826660156
column j: 320
Runtime of the program for j 0.1562356948852539
column j: 321
Runtime of the program for j 0.07812190055847168
column j: 322
Runtime of the program for j 0.14179587364196777
column j: 323
Runtime of the program for j 0.14035296440124512
column j: 324
Runtime of the program for j 0.13453269004821777
column j: 325
Runtime of the program for j 0.16019344329833984
column j: 326
Runtime of the program for j 0.12854981422424316
column j: 327
Runtime of the program for j 0.13346409797668457
column j: 328
Runtime of the program for j 0.13060474395751953
column j: 329
Runtime of the program for j 0.1312267780303955
column j: 330
Runtime of the program for j 0.14046216011047363
column j: 331
Runtime of the program for j 0.11974620819091797
column j: 332
Runtime of the program for j 0.15157270431518555
column j: 333
Runtime of the program for j 0.11753678321838379
column j: 334
Runtime of the program for j 0.1440117359161377
column j: 335
Runtime of the program for j 0.1285412311553955
column j: 336
Runtime of the program for j 0.1445610523223877
column j: 337
Runtime of the program for j 0.14447498321533203
column j: 338
Runtime of the program for j 0.16814470291137695
column j: 339
Runtime of the program for j 0.1288607120513916
column j: 340
Runtime of the program for j 0.1477975845336914
column j: 341
Runtime of the program for j 0.16004610061645508
column j: 342
Runtime of the program for j 0.15839266777038574
column j: 343
Runtime of the program for j 0.0789642333984375
column j: 344
Runtime of the program for j 0.14626193046569824
column j: 345
Runtime of the program for j 0.14313292503356934
column j: 346
Runtime of the program for j 0.13619685173034668
column j: 347
Runtime of the program for j 0.13684821128845215
column j: 348
Runtime of the program for j 0.1476278305053711
column j: 349
Runtime of the program for j 0.1571962833404541
column j: 350
Runtime of the program for j 0.12951278686523438
column j: 351
Runtime of the program for j 0.08864760398864746
column j: 352
Runtime of the program for j 0.11435818672180176
column j: 353
Runtime of the program for j 0.14321231842041016
column j: 354
Runtime of the program for j 0.12932515144348145
column j: 355
Runtime of the program for j 0.12832307815551758
column j: 356
Runtime of the program for j 0.13692879676818848
column j: 357
Runtime of the program for j 0.16065144538879395
column j: 358
Runtime of the program for j 0.12825465202331543
column j: 359
Runtime of the program for j 0.15189051628112793
column j: 360
Runtime of the program for j 0.08014106750488281
column j: 361
Runtime of the program for j 0.11727356910705566
column j: 362
Runtime of the program for j 0.15632891654968262
column j: 363
Runtime of the program for j 0.11188340187072754
column j: 364
Runtime of the program for j 0.13362979888916016
column j: 365
Runtime of the program for j 0.12627816200256348
column j: 366
Runtime of the program for j 0.12725138664245605
column j: 367
Runtime of the program for j 0.12818694114685059
column j: 368
Runtime of the program for j 0.1350114345550537
column j: 369
Runtime of the program for j 0.13875079154968262
column j: 370
Runtime of the program for j 0.12039566040039062
column j: 371
Runtime of the program for j 0.14062929153442383
column j: 372
Runtime of the program for j 0.12690186500549316
column j: 373
Runtime of the program for j 0.14050960540771484
column j: 374
Runtime of the program for j 0.14269685745239258
column j: 375
Runtime of the program for j 0.14425992965698242
column j: 376
Runtime of the program for j 0.12549901008605957
column j: 377
Runtime of the program for j 0.14529705047607422
column j: 378
Runtime of the program for j 0.13436126708984375
column j: 379
Runtime of the program for j 0.14061975479125977
column j: 380
Runtime of the program for j 0.13539361953735352
column j: 381
Runtime of the program for j 0.11002016067504883
column j: 382
Runtime of the program for j 0.12679505348205566
column j: 383
Runtime of the program for j 0.15625667572021484
column j: 384
Runtime of the program for j 0.12499499320983887
column j: 385
Runtime of the program for j 0.12537693977355957
column j: 386
Runtime of the program for j 0.13239288330078125
column j: 387
Runtime of the program for j 0.10954475402832031
column j: 388
Runtime of the program for j 0.12502741813659668
column j: 389
Runtime of the program for j 0.12551546096801758
column j: 390
Runtime of the program for j 0.1345067024230957
column j: 391
Runtime of the program for j 0.1406240463256836
column j: 392
Runtime of the program for j 0.1406245231628418
column j: 393
Runtime of the program for j 0.06262564659118652
column j: 394
Runtime of the program for j 0.07814574241638184

column j: 395
Runtime of the program for j 0.13376975059509277
column j: 396
Runtime of the program for j 0.1406569480895996
column j: 397
Runtime of the program for j 0.0938253402709961
column j: 398
Runtime of the program for j 0.1253032684326172
column j: 399
Runtime of the program for j 0.15557384490966797
column j: 400
Runtime of the program for j 0.15107035636901855
column j: 401
Runtime of the program for j 0.1407470703125
column j: 402
Runtime of the program for j 0.1256694793701172
column j: 403
Runtime of the program for j 0.14052677154541016
column j: 404
Runtime of the program for j 0.1219782829284668
column j: 405
Runtime of the program for j 0.1852254867553711
column j: 406
Runtime of the program for j 0.13118624687194824
column j: 407
Runtime of the program for j 0.12781763076782227
column j: 408
Runtime of the program for j 0.14068174362182617
column j: 409
Runtime of the program for j 0.1261613368988037
column j: 410
Runtime of the program for j 0.1251356601715088
column j: 411
Runtime of the program for j 0.12552905082702637
column j: 412
Runtime of the program for j 0.1575608253479004
column j: 413
Runtime of the program for j 0.14399099349975586
column j: 414
Runtime of the program for j 0.1442258358001709
column j: 415
Runtime of the program for j 0.14244627952575684
column j: 416
Runtime of the program for j 0.14060592651367188
column j: 417
Runtime of the program for j 0.12500405311584473
column j: 418
Runtime of the program for j 0.14062023162841797
column j: 419
Runtime of the program for j 0.1458141803741455
column j: 420
Runtime of the program for j 0.16150331497192383
column j: 421
Runtime of the program for j 0.1267843246459961
column j: 422
Runtime of the program for j 0.14053630828857422
column j: 423
Runtime of the program for j 0.15185165405273438
column j: 424
Runtime of the program for j 0.14459896087646484
column j: 425
Runtime of the program for j 0.15206694602966309
column j: 426
Runtime of the program for j 0.14431142807006836
column j: 427
Runtime of the program for j 0.15308737754821777
column j: 428
Runtime of the program for j 0.12180805206298828
column j: 429
Runtime of the program for j 0.13714241981506348
column j: 430
Runtime of the program for j 0.07942938804626465
column j: 431
Runtime of the program for j 0.08664083480834961
column j: 432
Runtime of the program for j 0.07919812202453613
column j: 433
Runtime of the program for j 0.12500500679016113
column j: 434
Runtime of the program for j 0.13439273834228516
column j: 435
Runtime of the program for j 0.1416788101196289
column j: 436
Runtime of the program for j 0.14063525199890137
column j: 437
Runtime of the program for j 0.13352465629577637
column j: 438
Runtime of the program for j 0.07848858833312988
column j: 439
Runtime of the program for j 0.11033439636230469
column j: 440
Runtime of the program for j 0.1565389633178711
column j: 441
Runtime of the program for j 0.13545680046081543
column j: 442
Runtime of the program for j 0.13610363006591797
column j: 443
Runtime of the program for j 0.08841109275817871
column j: 444
Runtime of the program for j 0.1520538330078125
column j: 445
Runtime of the program for j 0.12823724746704102
column j: 446
Runtime of the program for j 0.13648724555969238
column j: 447
Runtime of the program for j 0.1364765167236328
column j: 448
Runtime of the program for j 0.1523890495300293
column j: 449
Runtime of the program for j 0.13609838485717773
column j: 450
Runtime of the program for j 0.12049627304077148
column j: 451
Runtime of the program for j 0.15609169006347656
column j: 452
Runtime of the program for j 0.15717864036560059
column j: 453
Runtime of the program for j 0.13053083419799805
column j: 454
Runtime of the program for j 0.15315628051757812
column j: 455
Runtime of the program for j 0.13035798072814941
column j: 456
Runtime of the program for j 0.18036675453186035
column j: 457
Runtime of the program for j 0.1463298797607422
column j: 458
Runtime of the program for j 0.1839900016784668
column j: 459
Runtime of the program for j 0.13483119010925293
column j: 460
Runtime of the program for j 0.15683197975158691
column j: 461
Runtime of the program for j 0.15047836303710938
column j: 462
Runtime of the program for j 0.15778851509094238
column j: 463
Runtime of the program for j 0.15036463737487793
column j: 464
Runtime of the program for j 0.16648530960083008
column j: 465
Runtime of the program for j 0.15115094184875488
column j: 466
Runtime of the program for j 0.1820380687713623
column j: 467
Runtime of the program for j 0.16673541069030762
column j: 468
Runtime of the program for j 0.16130733489990234
column j: 469
Runtime of the program for j 0.15537142753601074
column j: 470
Runtime of the program for j 0.16263222694396973
column j: 471
Runtime of the program for j 0.13722681999206543
column j: 472
Runtime of the program for j 0.1667625904083252
column j: 473
Runtime of the program for j 0.08310151100158691
column j: 474
Runtime of the program for j 0.13356518745422363
column j: 475
Runtime of the program for j 0.14963817596435547
column j: 476
Runtime of the program for j 0.16724205017089844
column j: 477
Runtime of the program for j 0.157562255859375
column j: 478
Runtime of the program for j 0.14227509498596191
column j: 479
Runtime of the program for j 0.14959955215454102
column j: 480
Runtime of the program for j 0.14981865882873535
column j: 481
Runtime of the program for j 0.1334214210510254
column j: 482
Runtime of the program for j 0.16684365272521973
column j: 483
Runtime of the program for j 0.15161609649658203
column j: 484
Runtime of the program for j 0.1438453197479248
column j: 485
Runtime of the program for j 0.15394306182861328
column j: 486
Runtime of the program for j 0.17525744438171387
column j: 487
Runtime of the program for j 0.15041422843933105
column j: 488
Runtime of the program for j 0.1412029266357422
column j: 489
Runtime of the program for j 0.13015198707580566
column j: 490
Runtime of the program for j 0.15548157691955566
column j: 491
Runtime of the program for j 0.13731908798217773
column j: 492
Runtime of the program for j 0.12702512741088867
column j: 493
Runtime of the program for j 0.1360642910003662
column j: 494
Runtime of the program for j 0.14408111572265625
column j: 495
Runtime of the program for j 0.15250229835510254
column j: 496
Runtime of the program for j 0.12498784065246582
column j: 497
Runtime of the program for j 0.09375882148742676
column j: 498
Runtime of the program for j 0.1252124309539795
column j: 499
Runtime of the program for j 0.14064598083496094
column j: 500
Runtime of the program for j 0.1253049373626709
column j: 501
Runtime of the program for j 0.1406402587890625
column j: 502
Runtime of the program for j 0.12499642372131348
column j: 503
Runtime of the program for j 0.1605212688446045
column j: 504
Runtime of the program for j 0.14463496208190918
column j: 505
Runtime of the program for j 0.1271352767944336
column j: 506
Runtime of the program for j 0.12578511238098145
column j: 507
Runtime of the program for j 0.1496129035949707
column j: 508
Runtime of the program for j 0.16860747337341309
column j: 509
Runtime of the program for j 0.142167329788208
column j: 510
Runtime of the program for j 0.15728211402893066
column j: 511
Runtime of the program for j 0.16558337211608887
column j: 512
Runtime of the program for j 0.15144944190979004
column j: 513
Runtime of the program for j 0.13839340209960938
column j: 514
Runtime of the program for j 0.1651780605316162
column j: 515
Runtime of the program for j 0.07899737358093262
column j: 516
Runtime of the program for j 0.1410379409790039
column j: 517
Runtime of the program for j 0.12715840339660645
column j: 518
Runtime of the program for j 0.18869781494140625
column j: 519
Runtime of the program for j 0.15683770179748535
column j: 520
Runtime of the program for j 0.1419360637664795
column j: 521
Runtime of the program for j 0.12508153915405273
column j: 522
Runtime of the program for j 0.15618467330932617
column j: 523
Runtime of the program for j 0.1718745231628418
column j: 524
Runtime of the program for j 0.1468822956085205
column j: 525
Runtime of the program for j 0.0886690616607666

column j: 526
Runtime of the program for j 0.12584853172302246
column j: 527
Runtime of the program for j 0.15581083297729492
column j: 528
Runtime of the program for j 0.14190936088562012
column j: 529
Runtime of the program for j 0.1403801441192627
column j: 530
Runtime of the program for j 0.15641283988952637
column j: 531
Runtime of the program for j 0.15640759468078613
column j: 532
Runtime of the program for j 0.14076757431030273
column j: 533
Runtime of the program for j 0.12500357627868652
column j: 534
Runtime of the program for j 0.15693116188049316
column j: 535
Runtime of the program for j 0.0781247615814209
column j: 536
Runtime of the program for j 0.15697312355041504
column j: 537
Runtime of the program for j 0.18750333786010742
column j: 538
Runtime of the program for j 0.09374022483825684
column j: 539
Runtime of the program for j 0.07812619209289551
column j: 540
Runtime of the program for j 0.07812070846557617
column j: 541
Runtime of the program for j 0.1564497947692871
column j: 542
Runtime of the program for j 0.15663886070251465
column j: 543
Runtime of the program for j 0.16450738906860352
column j: 544
Runtime of the program for j 0.1427288055419922
column j: 545
Runtime of the program for j 0.1668379306793213
column j: 546
Runtime of the program for j 0.16785955429077148
column j: 547
Runtime of the program for j 0.14453935623168945
column j: 548
Runtime of the program for j 0.1435379981994629
column j: 549
Runtime of the program for j 0.12496685981750488
column j: 550
Runtime of the program for j 0.09255051612854004
column j: 551
Runtime of the program for j 0.08812880516052246
column j: 552
Runtime of the program for j 0.12698984146118164
column j: 553
Runtime of the program for j 0.15956425666809082
column j: 554
Runtime of the program for j 0.15195536613464355
column j: 555
Runtime of the program for j 0.1519927978515625
column j: 556
Runtime of the program for j 0.15111160278320312
column j: 557
Runtime of the program for j 0.15114212036132812
column j: 558
Runtime of the program for j 0.128098726272583
column j: 559
Runtime of the program for j 0.16272330284118652
column j: 560
Runtime of the program for j 0.13501596450805664
column j: 561
Runtime of the program for j 0.15261101722717285
column j: 562
Runtime of the program for j 0.11878705024719238
column j: 563
Runtime of the program for j 0.12624692916870117
column j: 564
Runtime of the program for j 0.17632651329040527
column j: 565
Runtime of the program for j 0.13362407684326172
column j: 566
Runtime of the program for j 0.12507987022399902
column j: 567
Runtime of the program for j 0.16588783264160156
column j: 568
Runtime of the program for j 0.1508340835571289
column j: 569
Runtime of the program for j 0.14063692092895508
column j: 570
Runtime of the program for j 0.1486952304840088
column j: 571
Runtime of the program for j 0.08701968193054199
column j: 572
Runtime of the program for j 0.13418102264404297
column j: 573
Runtime of the program for j 0.13450217247009277
column j: 574
Runtime of the program for j 0.14064574241638184
column j: 575
Runtime of the program for j 0.14324569702148438
column j: 576
Runtime of the program for j 0.11751055717468262
column j: 577
Runtime of the program for j 0.14200329780578613
column j: 578
Runtime of the program for j 0.13566064834594727
column j: 579
Runtime of the program for j 0.1441664695739746
column j: 580
Runtime of the program for j 0.1444382667541504
column j: 581
Runtime of the program for j 0.15218591690063477
column j: 582
Runtime of the program for j 0.1288135051727295
column j: 583
Runtime of the program for j 0.15277671813964844
column j: 584
Runtime of the program for j 0.1381824016571045
column j: 585
Runtime of the program for j 0.14939212799072266
column j: 586
Runtime of the program for j 0.15024352073669434
column j: 587
Runtime of the program for j 0.11824226379394531
column j: 588
Runtime of the program for j 0.12499189376831055
column j: 589
Runtime of the program for j 0.1335744857788086
column j: 590
Runtime of the program for j 0.13672399520874023
column j: 591
Runtime of the program for j 0.1412343978881836
column j: 592
Runtime of the program for j 0.16136741638183594
column j: 593
Runtime of the program for j 0.1443939208984375
column j: 594
Runtime of the program for j 0.14860820770263672
column j: 595
Runtime of the program for j 0.0880134105682373
column j: 596
Runtime of the program for j 0.1975998878479004
column j: 597
Runtime of the program for j 0.16877508163452148
column j: 598
Runtime of the program for j 0.18558692932128906
column j: 599
Runtime of the program for j 0.16008925437927246
column j: 600
Runtime of the program for j 0.1685621738433838
column j: 601
Runtime of the program for j 0.13597869873046875
column j: 602
Runtime of the program for j 0.1608428955078125
column j: 603
Runtime of the program for j 0.14431500434875488
column j: 604
Runtime of the program for j 0.14464235305786133
column j: 605
Runtime of the program for j 0.14362144470214844
column j: 606
Runtime of the program for j 0.15003681182861328
column j: 607
Runtime of the program for j 0.15993332862854004
column j: 608
Runtime of the program for j 0.16123509407043457
column j: 609
Runtime of the program for j 0.2110757827758789
column j: 610
Runtime of the program for j 0.14433789253234863
column j: 611
Runtime of the program for j 0.13819527626037598
column j: 612
Runtime of the program for j 0.15476322174072266
column j: 613
Runtime of the program for j 0.1578221321105957
column j: 614
Runtime of the program for j 0.14982056617736816
column j: 615
Runtime of the program for j 0.15089988708496094
column j: 616
Runtime of the program for j 0.14829206466674805
column j: 617
Runtime of the program for j 0.15683722496032715
column j: 618
Runtime of the program for j 0.17269182205200195
column j: 619
Runtime of the program for j 0.1563429832458496
column j: 620
Runtime of the program for j 0.13359570503234863
column j: 621
Runtime of the program for j 0.13350176811218262
column j: 622
Runtime of the program for j 0.15719389915466309
column j: 623
Runtime of the program for j 0.15714406967163086
column j: 624
Runtime of the program for j 0.1414656639099121
column j: 625
Runtime of the program for j 0.14043521881103516
column j: 626
Runtime of the program for j 0.15737009048461914
column j: 627
Runtime of the program for j 0.12497973442077637
column j: 628
Runtime of the program for j 0.14170360565185547
column j: 629
Runtime of the program for j 0.12784743309020996
column j: 630
Runtime of the program for j 0.14108705520629883
column j: 631
Runtime of the program for j 0.1566469669342041
column j: 632
Runtime of the program for j 0.1417548656463623
column j: 633
Runtime of the program for j 0.14092206954956055
column j: 634
Runtime of the program for j 0.15810537338256836
column j: 635
Runtime of the program for j 0.14063382148742676
column j: 636
Runtime of the program for j 0.19764089584350586
column j: 637
Runtime of the program for j 0.14084291458129883
column j: 638
Runtime of the program for j 0.15784502029418945
column j: 639
Runtime of the program for j 0.07817554473876953
column j: 640
Runtime of the program for j 0.14110350608825684
column j: 641
Runtime of the program for j 0.12580013275146484
column j: 642
Runtime of the program for j 0.17187857627868652
column j: 643
Runtime of the program for j 0.14374756813049316
column j: 644
Runtime of the program for j 0.13384699821472168
column j: 645
Runtime of the program for j 0.15086722373962402
column j: 646
Runtime of the program for j 0.16027379035949707
column j: 647
Runtime of the program for j 0.1496720314025879
column j: 648
Runtime of the program for j 0.18151473999023438
column j: 649
Runtime of the program for j 0.14325213432312012
column j: 650
Runtime of the program for j 0.1725912094116211
column j: 651
Runtime of the program for j 0.08264923095703125
column j: 652
Runtime of the program for j 0.15142130851745605
column j: 653
Runtime of the program for j 0.13317131996154785
column j: 654
Runtime of the program for j 0.15727734565734863
column j: 655
Runtime of the program for j 0.13200855255126953
column j: 656
Runtime of the program for j 0.14933443069458008
column j: 657
Runtime of the program for j 0.1306910514831543

column j: 658
Runtime of the program for j 0.15808939933776855
column j: 659
Runtime of the program for j 0.14026165008544922
column j: 660
Runtime of the program for j 0.12530231475830078
column j: 661
Runtime of the program for j 0.13106727600097656
column j: 662
Runtime of the program for j 0.12583374977111816
column j: 663
Runtime of the program for j 0.14609980583190918
column j: 664
Runtime of the program for j 0.14086365699768066
column j: 665
Runtime of the program for j 0.1254279613494873
column j: 666
Runtime of the program for j 0.14061975479125977
column j: 667
Runtime of the program for j 0.12561845779418945
column j: 668
Runtime of the program for j 0.14064288139343262
column j: 669
Runtime of the program for j 0.18714690208435059
column j: 670
Runtime of the program for j 0.15688848495483398
column j: 671
Runtime of the program for j 0.13069820404052734
column j: 672
Runtime of the program for j 0.1249856948852539
column j: 673
Runtime of the program for j 0.14066767692565918
column j: 674
Runtime of the program for j 0.1273021697998047
column j: 675
Runtime of the program for j 0.14898061752319336
column j: 676
Runtime of the program for j 0.16333937644958496
column j: 677
Runtime of the program for j 0.15446996688842773
column j: 678
Runtime of the program for j 0.14480328559875488
column j: 679
Runtime of the program for j 0.1369173526763916
column j: 680
Runtime of the program for j 0.15262842178344727
column j: 681
Runtime of the program for j 0.07256603240966797
column j: 682
Runtime of the program for j 0.15231847763061523
column j: 683
Runtime of the program for j 0.13356995582580566
column j: 684
Runtime of the program for j 0.17419147491455078
column j: 685
Runtime of the program for j 0.1337261199951172
column j: 686
Runtime of the program for j 0.16333675384521484
column j: 687
Runtime of the program for j 0.14771556854248047
column j: 688
Runtime of the program for j 0.13607358932495117
column j: 689
Runtime of the program for j 0.16396546363830566
column j: 690
Runtime of the program for j 0.15809082984924316
column j: 691
Runtime of the program for j 0.13526415824890137
column j: 692
Runtime of the program for j 0.1496284008026123
column j: 693
Runtime of the program for j 0.16889166831970215
column j: 694
Runtime of the program for j 0.1447587013244629
column j: 695
Runtime of the program for j 0.1205282211303711
column j: 696
Runtime of the program for j 0.16537785530090332
column j: 697
Runtime of the program for j 0.11982369422912598
column j: 698
Runtime of the program for j 0.14064717292785645
column j: 699
Runtime of the program for j 0.16451358795166016
column j: 700
Runtime of the program for j 0.15178489685058594
column j: 701
Runtime of the program for j 0.13407182693481445
column j: 702
Runtime of the program for j 0.16309452056884766
column j: 703
Runtime of the program for j 0.1697251796722412
column j: 704
Runtime of the program for j 0.16454696655273438
column j: 705
Runtime of the program for j 0.16616582870483398
column j: 706
Runtime of the program for j 0.16024208068847656
column j: 707
Runtime of the program for j 0.1452348232269287
column j: 708
Runtime of the program for j 0.14404082298278809
column j: 709
Runtime of the program for j 0.18112444877624512
column j: 710
Runtime of the program for j 0.193040132522583
column j: 711
Runtime of the program for j 0.1394519805908203
column j: 712
Runtime of the program for j 0.16653847694396973
column j: 713
Runtime of the program for j 0.1675577163696289
column j: 714
Runtime of the program for j 0.16673731803894043
column j: 715
Runtime of the program for j 0.15770578384399414
column j: 716
Runtime of the program for j 0.15115737915039062
column j: 717
Runtime of the program for j 0.16708064079284668
column j: 718
Runtime of the program for j 0.15637445449829102
column j: 719
Runtime of the program for j 0.14989256858825684
column j: 720
Runtime of the program for j 0.13344120979309082
column j: 721
Runtime of the program for j 0.1671924591064453
column j: 722
Runtime of the program for j 0.14960765838623047
column j: 723
Runtime of the program for j 0.14207720756530762
column j: 724
Runtime of the program for j 0.15763163566589355
column j: 725
Runtime of the program for j 0.15224170684814453
column j: 726
Runtime of the program for j 0.1475667953491211
column j: 727
Runtime of the program for j 0.13342928886413574
column j: 728
Runtime of the program for j 0.1687910556793213
column j: 729
Runtime of the program for j 0.16456985473632812
column j: 730
Runtime of the program for j 0.2160508632659912
column j: 731
Runtime of the program for j 0.1514124870300293
column j: 732
Runtime of the program for j 0.16819119453430176
column j: 733
Runtime of the program for j 0.16428351402282715
column j: 734
Runtime of the program for j 0.1499776840209961
column j: 735
Runtime of the program for j 0.1676192283630371
column j: 736
Runtime of the program for j 0.16653704643249512
column j: 737
Runtime of the program for j 0.14930295944213867
column j: 738
Runtime of the program for j 0.16637945175170898
column j: 739
Runtime of the program for j 0.1499190330505371
column j: 740
Runtime of the program for j 0.15872716903686523
column j: 741
Runtime of the program for j 0.14619922637939453
column j: 742
Runtime of the program for j 0.09586334228515625
column j: 743
Runtime of the program for j 0.15643835067749023
column j: 744
Runtime of the program for j 0.15065693855285645
column j: 745
Runtime of the program for j 0.15025067329406738
column j: 746
Runtime of the program for j 0.16709280014038086
column j: 747
Runtime of the program for j 0.1660301685333252
column j: 748
Runtime of the program for j 0.14560985565185547
column j: 749
Runtime of the program for j 0.15087080001831055
column j: 750
Runtime of the program for j 0.1838700771331787
column j: 751
Runtime of the program for j 0.15560054779052734
column j: 752
Runtime of the program for j 0.17764568328857422
column j: 753
Runtime of the program for j 0.16580438613891602
column j: 754
Runtime of the program for j 0.16028213500976562
column j: 755
Runtime of the program for j 0.14057254791259766
column j: 756
Runtime of the program for j 0.1660926342010498
column j: 757
Runtime of the program for j 0.14927983283996582
column j: 758
Runtime of the program for j 0.15657973289489746
column j: 759
Runtime of the program for j 0.144423246383667
column j: 760
Runtime of the program for j 0.1440718173980713
column j: 761
Runtime of the program for j 0.14400053024291992
column j: 762
Runtime of the program for j 0.16007661819458008
column j: 763
Runtime of the program for j 0.1525106430053711
column j: 764
Runtime of the program for j 0.13473868370056152
column j: 765
Runtime of the program for j 0.14566993713378906
column j: 766
Runtime of the program for j 0.09599876403808594
column j: 767
Runtime of the program for j 0.1439352035522461
column j: 768
Runtime of the program for j 0.08698582649230957
column j: 769
Runtime of the program for j 0.1510300636291504
column j: 770
Runtime of the program for j 0.14130568504333496
column j: 771
Runtime of the program for j 0.15622854232788086
column j: 772
Runtime of the program for j 0.1406257152557373
column j: 773
Runtime of the program for j 0.12621855735778809
column j: 774
Runtime of the program for j 0.17133140563964844
column j: 775
Runtime of the program for j 0.15631675720214844
column j: 776
Runtime of the program for j 0.14110541343688965
column j: 777
Runtime of the program for j 0.14139437675476074
column j: 778
Runtime of the program for j 0.15583324432373047
column j: 779
Runtime of the program for j 0.1250755786895752
column j: 780
Runtime of the program for j 0.09368586540222168
column j: 781
Runtime of the program for j 0.14111638069152832
column j: 782
Runtime of the program for j 0.1407155990600586
column j: 783
Runtime of the program for j 0.14062285423278809
column j: 784
Runtime of the program for j 0.12523317337036133
column j: 785
Runtime of the program for j 0.15210628509521484
column j: 786
Runtime of the program for j 0.1658468246459961
column j: 787
Runtime of the program for j 0.15624046325683594
column j: 788
Runtime of the program for j 0.1406266689300537
column j: 789
Runtime of the program for j 0.12623953819274902

column j: 790
Runtime of the program for j 0.15673208236694336
column j: 791
Runtime of the program for j 0.1411728858947754
column j: 792
Runtime of the program for j 0.17285776138305664
column j: 793
Runtime of the program for j 0.14090633392333984
column j: 794
Runtime of the program for j 0.1573498249053955
column j: 795
Runtime of the program for j 0.18783116340637207
column j: 796
Runtime of the program for j 0.14126133918762207
column j: 797
Runtime of the program for j 0.1412971019744873
column j: 798
Runtime of the program for j 0.14509320259094238
column j: 799
Runtime of the program for j 0.16559410095214844
column j: 800
Runtime of the program for j 0.15752649307250977
column j: 801
Runtime of the program for j 0.1255662441253662
column j: 802
Runtime of the program for j 0.15627646446228027
column j: 803
Runtime of the program for j 0.1410665512084961
column j: 804
Runtime of the program for j 0.15666508674621582
column j: 805
Runtime of the program for j 0.1412060260772705
column j: 806
Runtime of the program for j 0.12493085861206055
column j: 807
Runtime of the program for j 0.1413123607635498
column j: 808
Runtime of the program for j 0.15607857704162598
column j: 809
Runtime of the program for j 0.14087939262390137
column j: 810
Runtime of the program for j 0.15661239624023438
column j: 811
Runtime of the program for j 0.1568284034729004
column j: 812
Runtime of the program for j 0.1566479206085205
column j: 813
Runtime of the program for j 0.18743515014648438
column j: 814
Runtime of the program for j 0.12530779838562012
column j: 815
Runtime of the program for j 0.14069104194641113
column j: 816
Runtime of the program for j 0.1569361686706543
column j: 817
Runtime of the program for j 0.20522427558898926
column j: 818
Runtime of the program for j 0.17296981811523438
column j: 819
Runtime of the program for j 0.18779516220092773
column j: 820
Runtime of the program for j 0.1720139980316162
column j: 821
Runtime of the program for j 0.15706276893615723
column j: 822
Runtime of the program for j 0.15701985359191895
column j: 823
Runtime of the program for j 0.1568307876586914
column j: 824
Runtime of the program for j 0.1587543487548828
column j: 825
Runtime of the program for j 0.15226054191589355
column j: 826
Runtime of the program for j 0.15758895874023438
column j: 827
Runtime of the program for j 0.14942693710327148
column j: 828
Runtime of the program for j 0.1664881706237793
column j: 829
Runtime of the program for j 0.1658039093017578
column j: 830
Runtime of the program for j 0.23116278648376465
column j: 831
Runtime of the program for j 0.16369056701660156
column j: 832
Runtime of the program for j 0.25144028663635254
column j: 833
Runtime of the program for j 0.1572885513305664
column j: 834
Runtime of the program for j 0.15692138671875
column j: 835
Runtime of the program for j 0.14927959442138672
column j: 836
Runtime of the program for j 0.15594172477722168
column j: 837
Runtime of the program for j 0.14089536666870117
column j: 838
Runtime of the program for j 0.15633559226989746
column j: 839
Runtime of the program for j 0.12505435943603516
column j: 840
Runtime of the program for j 0.14056038856506348
column j: 841
Runtime of the program for j 0.15674567222595215
column j: 842
Runtime of the program for j 0.1332254409790039
column j: 843
Runtime of the program for j 0.14061570167541504
column j: 844
Runtime of the program for j 0.1406266689300537
column j: 845
Runtime of the program for j 0.14063000679016113
column j: 846
Runtime of the program for j 0.14128851890563965
column j: 847
Runtime of the program for j 0.14091038703918457
column j: 848
Runtime of the program for j 0.15696477890014648
column j: 849
Runtime of the program for j 0.09316062927246094
column j: 850
Runtime of the program for j 0.15696334838867188
column j: 851
Runtime of the program for j 0.16578102111816406
column j: 852
Runtime of the program for j 0.16806960105895996
column j: 853
Runtime of the program for j 0.14399361610412598
column j: 854
Runtime of the program for j 0.13712358474731445
column j: 855
Runtime of the program for j 0.14564299583435059
column j: 856
Runtime of the program for j 0.16047954559326172
column j: 857
Runtime of the program for j 0.1679978370666504
column j: 858
Runtime of the program for j 0.16065239906311035
column j: 859
Runtime of the program for j 0.14400005340576172
column j: 860
Runtime of the program for j 0.16000795364379883
column j: 861
Runtime of the program for j 0.12684273719787598
column j: 862
Runtime of the program for j 0.14093637466430664
column j: 863
Runtime of the program for j 0.14144659042358398
column j: 864
Runtime of the program for j 0.14069914817810059
column j: 865
Runtime of the program for j 0.1251370906829834
column j: 866
Runtime of the program for j 0.17237257957458496
column j: 867
Runtime of the program for j 0.14107656478881836
column j: 868
Runtime of the program for j 0.1562480926513672
column j: 869
Runtime of the program for j 0.12606167793273926
column j: 870
Runtime of the program for j 0.172515869140625
column j: 871
Runtime of the program for j 0.14075160026550293
column j: 872
Runtime of the program for j 0.14061951637268066
column j: 873
Runtime of the program for j 0.14109468460083008
column j: 874
Runtime of the program for j 0.1406269073486328
column j: 875
Runtime of the program for j 0.15625429153442383
column j: 876
Runtime of the program for j 0.15644097328186035
column j: 877
Runtime of the program for j 0.17280077934265137
column j: 878
Runtime of the program for j 0.14120769500732422
column j: 879
Runtime of the program for j 0.15671348571777344
column j: 880
Runtime of the program for j 0.14140772819519043
column j: 881
Runtime of the program for j 0.1664121150970459
column j: 882
Runtime of the program for j 0.1455535888671875
column j: 883
Runtime of the program for j 0.16789674758911133
column j: 884
Runtime of the program for j 0.16062641143798828
column j: 885
Runtime of the program for j 0.14418315887451172
column j: 886
Runtime of the program for j 0.1436309814453125
column j: 887
Runtime of the program for j 0.12047839164733887
column j: 888
Runtime of the program for j 0.15305089950561523
column j: 889
Runtime of the program for j 0.19359898567199707
column j: 890
Runtime of the program for j 0.14210987091064453
column j: 891
Runtime of the program for j 0.14262175559997559
column j: 892
Runtime of the program for j 0.15621447563171387
column j: 893
Runtime of the program for j 0.18586206436157227
column j: 894
Runtime of the program for j 0.14531493186950684
column j: 895
Runtime of the program for j 0.08768916130065918
column j: 896
Runtime of the program for j 0.1447916030883789
column j: 897
Runtime of the program for j 0.14500904083251953
column j: 898
Runtime of the program for j 0.136613130569458
column j: 899
Runtime of the program for j 0.09383535385131836
column j: 900
Runtime of the program for j 0.14075422286987305
column j: 901
Runtime of the program for j 0.1427478790283203
column j: 902
Runtime of the program for j 0.14051604270935059
column j: 903
Runtime of the program for j 0.1733236312866211
column j: 904
Runtime of the program for j 0.15677785873413086
column j: 905
Runtime of the program for j 0.1249995231628418
column j: 906
Runtime of the program for j 0.14983177185058594
column j: 907
Runtime of the program for j 0.1421060562133789
column j: 908
Runtime of the program for j 0.15625286102294922
column j: 909
Runtime of the program for j 0.1250004768371582
column j: 910
Runtime of the program for j 0.14107966423034668
column j: 911
Runtime of the program for j 0.16169452667236328
column j: 912
Runtime of the program for j 0.13719582557678223
column j: 913
Runtime of the program for j 0.1417381763458252
column j: 914
Runtime of the program for j 0.1405630111694336
column j: 915
Runtime of the program for j 0.14102387428283691
column j: 916
Runtime of the program for j 0.14065098762512207
column j: 917
Runtime of the program for j 0.22017908096313477
column j: 918
Runtime of the program for j 0.14061951637268066
column j: 919
Runtime of the program for j 0.14104437828063965
column j: 920
Runtime of the program for j 0.18225884437561035

column j: 921
Runtime of the program for j 0.16184711456298828
column j: 922
Runtime of the program for j 0.15244364738464355
column j: 923
Runtime of the program for j 0.1326310634613037
column j: 924
Runtime of the program for j 0.1350250244140625
column j: 925
Runtime of the program for j 0.19119954109191895
column j: 926
Runtime of the program for j 0.15172863006591797
column j: 927
Runtime of the program for j 0.15323543548583984
column j: 928
Runtime of the program for j 0.1613140106201172
column j: 929
Runtime of the program for j 0.14409446716308594
column j: 930
Runtime of the program for j 0.18563222885131836
column j: 931
Runtime of the program for j 0.15247464179992676
column j: 932
Runtime of the program for j 0.16103744506835938
column j: 933
Runtime of the program for j 0.09436655044555664
column j: 934
Runtime of the program for j 0.15970945358276367
column j: 935
Runtime of the program for j 0.15996789932250977
column j: 936
Runtime of the program for j 0.17272353172302246
column j: 937
Runtime of the program for j 0.17550063133239746
column j: 938
Runtime of the program for j 0.14336466789245605
column j: 939
Runtime of the program for j 0.15050363540649414
column j: 940
Runtime of the program for j 0.1759943962097168
column j: 941
Runtime of the program for j 0.15244293212890625
column j: 942
Runtime of the program for j 0.1520519256591797
column j: 943
Runtime of the program for j 0.15244841575622559
column j: 944
Runtime of the program for j 0.22410964965820312
column j: 945
Runtime of the program for j 0.16178584098815918
column j: 946
Runtime of the program for j 0.19191551208496094
column j: 947
Runtime of the program for j 0.19275212287902832
column j: 948
Runtime of the program for j 0.15198826789855957
column j: 949
Runtime of the program for j 0.1517012119293213
column j: 950
Runtime of the program for j 0.1527261734008789
column j: 951
Runtime of the program for j 0.17522668838500977
column j: 952
Runtime of the program for j 0.15195369720458984
column j: 953
Runtime of the program for j 0.1853344440460205
column j: 954
Runtime of the program for j 0.1678159236907959
column j: 955
Runtime of the program for j 0.19264841079711914
column j: 956
Runtime of the program for j 0.17651605606079102
column j: 957
Runtime of the program for j 0.15218281745910645
column j: 958
Runtime of the program for j 0.16869139671325684
column j: 959
Runtime of the program for j 0.16042184829711914
column j: 960
Runtime of the program for j 0.17699527740478516
column j: 961
Runtime of the program for j 0.15952658653259277
column j: 962
Runtime of the program for j 0.1525876522064209
column j: 963
Runtime of the program for j 0.13854694366455078
column j: 964
Runtime of the program for j 0.16144919395446777
column j: 965
Runtime of the program for j 0.13472533226013184
column j: 966
Runtime of the program for j 0.16038918495178223
column j: 967
Runtime of the program for j 0.16000056266784668
column j: 968
Runtime of the program for j 0.16827630996704102
column j: 969
Runtime of the program for j 0.20122385025024414
column j: 970
Runtime of the program for j 0.17680716514587402
column j: 971
Runtime of the program for j 0.15998601913452148
column j: 972
Runtime of the program for j 0.17634844779968262
column j: 973
Runtime of the program for j 0.18523836135864258
column j: 974
Runtime of the program for j 0.17638587951660156
column j: 975
Runtime of the program for j 0.17650270462036133
column j: 976
Runtime of the program for j 0.17751359939575195
column j: 977
Runtime of the program for j 0.15668153762817383
column j: 978
Runtime of the program for j 0.1520981788635254
column j: 979
Runtime of the program for j 0.1519162654876709
column j: 980
Runtime of the program for j 0.1527082920074463
column j: 981
Runtime of the program for j 0.15199971199035645
column j: 982
Runtime of the program for j 0.16057062149047852
column j: 983
Runtime of the program for j 0.18405818939208984
column j: 984
Runtime of the program for j 0.13737773895263672
column j: 985
Runtime of the program for j 0.17656373977661133
column j: 986
Runtime of the program for j 0.15654706954956055
column j: 987
Runtime of the program for j 0.14063358306884766
column j: 988
Runtime of the program for j 0.17272186279296875
column j: 989
Runtime of the program for j 0.1574714183807373
column j: 990
Runtime of the program for j 0.14153170585632324
column j: 991
Runtime of the program for j 0.1418299674987793
column j: 992
Runtime of the program for j 0.1928863525390625
column j: 993
Runtime of the program for j 0.14629340171813965
column j: 994
Runtime of the program for j 0.13693761825561523
column j: 995
Runtime of the program for j 0.12783360481262207
column j: 996
Runtime of the program for j 0.19133234024047852
column j: 997
Runtime of the program for j 0.10984253883361816
column j: 998
Runtime of the program for j 0.20583796501159668
column j: 999
Runtime of the program for j 0.1321239471435547
column j: 1000
Runtime of the program for j 0.15407371520996094
column j: 1001
Runtime of the program for j 0.14588594436645508
column j: 1002
Runtime of the program for j 0.1600503921508789
column j: 1003
Runtime of the program for j 0.2041633129119873
column j: 1004
Runtime of the program for j 0.21906566619873047
column j: 1005
Runtime of the program for j 0.14570236206054688
column j: 1006
Runtime of the program for j 0.16837048530578613
column j: 1007
Runtime of the program for j 0.15437746047973633
column j: 1008
Runtime of the program for j 0.16772127151489258
column j: 1009
Runtime of the program for j 0.14530539512634277
column j: 1010
Runtime of the program for j 0.14414215087890625
column j: 1011
Runtime of the program for j 0.13654351234436035
column j: 1012
Runtime of the program for j 0.15206170082092285
column j: 1013
Runtime of the program for j 0.20025253295898438
column j: 1014
Runtime of the program for j 0.14266657829284668
column j: 1015
Runtime of the program for j 0.1610703468322754
column j: 1016
Runtime of the program for j 0.1430213451385498
column j: 1017
Runtime of the program for j 0.16838669776916504
column j: 1018
Runtime of the program for j 0.13617372512817383
column j: 1019
Runtime of the program for j 0.15772318840026855
column j: 1020
Runtime of the program for j 0.16662168502807617
column j: 1021
Runtime of the program for j 0.16079354286193848
column j: 1022
Runtime of the program for j 0.0965261459350586
column j: 1023
Runtime of the program for j 0.14392518997192383
column j: 1024
Runtime of the program for j 0.15199756622314453
column j: 1025
Runtime of the program for j 0.16843962669372559
column j: 1026
Runtime of the program for j 0.1605544090270996
column j: 1027
Runtime of the program for j 0.20947265625
column j: 1028
Runtime of the program for j 0.1516735553741455
column j: 1029
Runtime of the program for j 0.09376645088195801
column j: 1030
Runtime of the program for j 0.14105892181396484
column j: 1031
Runtime of the program for j 0.16599106788635254
column j: 1032
Runtime of the program for j 0.12663602828979492
column j: 1033
Runtime of the program for j 0.09386181831359863
column j: 1034
Runtime of the program for j 0.16460180282592773
column j: 1035
Runtime of the program for j 0.1506493091583252
column j: 1036
Runtime of the program for j 0.11750507354736328
column j: 1037
Runtime of the program for j 0.19225382804870605
column j: 1038
Runtime of the program for j 0.16048073768615723
column j: 1039
Runtime of the program for j 0.16228246688842773
column j: 1040
Runtime of the program for j 0.13541388511657715
column j: 1041
Runtime of the program for j 0.1646571159362793
column j: 1042
Runtime of the program for j 0.19498920440673828
column j: 1043
Runtime of the program for j 0.20983338356018066
column j: 1044
Runtime of the program for j 0.1600184440612793
column j: 1045
Runtime of the program for j 0.1551060676574707
column j: 1046
Runtime of the program for j 0.14083552360534668
column j: 1047
Runtime of the program for j 0.17586636543273926
column j: 1048
Runtime of the program for j 0.15227007865905762
column j: 1049
Runtime of the program for j 0.14451956748962402
column j: 1050
Runtime of the program for j 0.13653016090393066

column j: 1051
Runtime of the program for j 0.18692541122436523
column j: 1052
Runtime of the program for j 0.18500518798828125
column j: 1053
Runtime of the program for j 0.2097482681274414
column j: 1054
Runtime of the program for j 0.16931581497192383
column j: 1055
Runtime of the program for j 0.16238713264465332
column j: 1056
Runtime of the program for j 0.20431756973266602
column j: 1057
Runtime of the program for j 0.14153361320495605
column j: 1058
Runtime of the program for j 0.1629319190979004
column j: 1059
Runtime of the program for j 0.21567273139953613
column j: 1060
Runtime of the program for j 0.19355010986328125
column j: 1061
Runtime of the program for j 0.16130614280700684
column j: 1062
Runtime of the program for j 0.16098284721374512
column j: 1063
Runtime of the program for j 0.18519806861877441
column j: 1064
Runtime of the program for j 0.18767118453979492
column j: 1065
Runtime of the program for j 0.15659046173095703
column j: 1066
Runtime of the program for j 0.14086604118347168
column j: 1067
Runtime of the program for j 0.12601995468139648
column j: 1068
Runtime of the program for j 0.20447468757629395
column j: 1069
Runtime of the program for j 0.2158961296081543
column j: 1070
Runtime of the program for j 0.14583063125610352
column j: 1071
Runtime of the program for j 0.1564774513244629
column j: 1072
Runtime of the program for j 0.09382843971252441
column j: 1073
Runtime of the program for j 0.18906807899475098
column j: 1074
Runtime of the program for j 0.14084339141845703
column j: 1075
Runtime of the program for j 0.15649652481079102
column j: 1076
Runtime of the program for j 0.1406238079071045
column j: 1077
Runtime of the program for j 0.1565544605255127
column j: 1078
Runtime of the program for j 0.1408705711364746
column j: 1079
Runtime of the program for j 0.16379880905151367
column j: 1080
Runtime of the program for j 0.15224075317382812
column j: 1081
Runtime of the program for j 0.13830137252807617
column j: 1082
Runtime of the program for j 0.20555567741394043
column j: 1083
Runtime of the program for j 0.15642738342285156
column j: 1084
Runtime of the program for j 0.17291903495788574
column j: 1085
Runtime of the program for j 0.14180636405944824
column j: 1086
Runtime of the program for j 0.15625786781311035
column j: 1087
Runtime of the program for j 0.14133381843566895
column j: 1088
Runtime of the program for j 0.15662097930908203
column j: 1089
Runtime of the program for j 0.1727581024169922
column j: 1090
Runtime of the program for j 0.15676045417785645
column j: 1091
Runtime of the program for j 0.15870165824890137
column j: 1092
Runtime of the program for j 0.14090371131896973
column j: 1093
Runtime of the program for j 0.15678668022155762
column j: 1094
Runtime of the program for j 0.12500381469726562
column j: 1095
Runtime of the program for j 0.14181017875671387
column j: 1096
Runtime of the program for j 0.1712937355041504
column j: 1097
Runtime of the program for j 0.16327905654907227
column j: 1098
Runtime of the program for j 0.14391589164733887
column j: 1099
Runtime of the program for j 0.1526041030883789
column j: 1100
Runtime of the program for j 0.12823104858398438
column j: 1101
Runtime of the program for j 0.1601879596710205
column j: 1102
Runtime of the program for j 0.13612842559814453
column j: 1103
Runtime of the program for j 0.1415112018585205
column j: 1104
Runtime of the program for j 0.18457365036010742
column j: 1105
Runtime of the program for j 0.14861726760864258
column j: 1106
Runtime of the program for j 0.15954279899597168
column j: 1107
Runtime of the program for j 0.15072107315063477
column j: 1108
Runtime of the program for j 0.1750946044921875
column j: 1109
Runtime of the program for j 0.20463132858276367
column j: 1110
Runtime of the program for j 0.14102697372436523
column j: 1111
Runtime of the program for j 0.1563405990600586
column j: 1112
Runtime of the program for j 0.14186358451843262
column j: 1113
Runtime of the program for j 0.15947222709655762
column j: 1114
Runtime of the program for j 0.1408703327178955
column j: 1115
Runtime of the program for j 0.16608619689941406
column j: 1116
Runtime of the program for j 0.1532604694366455
column j: 1117
Runtime of the program for j 0.14157915115356445
column j: 1118
Runtime of the program for j 0.1264653205871582
column j: 1119
Runtime of the program for j 0.14088892936706543
column j: 1120
Runtime of the program for j 0.16182446479797363
column j: 1121
Runtime of the program for j 0.1474292278289795
column j: 1122
Runtime of the program for j 0.17186880111694336
column j: 1123
Runtime of the program for j 0.15628290176391602
column j: 1124
Runtime of the program for j 0.15625333786010742
column j: 1125
Runtime of the program for j 0.15257787704467773
column j: 1126
Runtime of the program for j 0.16098785400390625
column j: 1127
Runtime of the program for j 0.16838979721069336
column j: 1128
Runtime of the program for j 0.13636445999145508
column j: 1129
Runtime of the program for j 0.1528012752532959
column j: 1130
Runtime of the program for j 0.15111017227172852
column j: 1131
Runtime of the program for j 0.15757036209106445
column j: 1132
Runtime of the program for j 0.167860746383667
column j: 1133
Runtime of the program for j 0.14149022102355957
column j: 1134
Runtime of the program for j 0.14482331275939941
column j: 1135
Runtime of the program for j 0.19196724891662598
column j: 1136
Runtime of the program for j 0.13340210914611816
column j: 1137
Runtime of the program for j 0.15325570106506348
column j: 1138
Runtime of the program for j 0.09601640701293945
column j: 1139
Runtime of the program for j 0.10473465919494629
column j: 1140
Runtime of the program for j 0.1686112880706787
column j: 1141
Runtime of the program for j 0.1510450839996338
column j: 1142
Runtime of the program for j 0.15361452102661133
column j: 1143
Runtime of the program for j 0.1875474452972412
column j: 1144
Runtime of the program for j 0.12500405311584473
column j: 1145
Runtime of the program for j 0.16506052017211914
column j: 1146
Runtime of the program for j 0.14618396759033203
column j: 1147
Runtime of the program for j 0.14176344871520996
column j: 1148
Runtime of the program for j 0.18079376220703125
column j: 1149
Runtime of the program for j 0.1775672435760498
column j: 1150
Runtime of the program for j 0.1810927391052246
column j: 1151
Runtime of the program for j 0.14064478874206543
column j: 1152
Runtime of the program for j 0.1575300693511963
column j: 1153
Runtime of the program for j 0.14419174194335938
column j: 1154
Runtime of the program for j 0.16460204124450684
column j: 1155
Runtime of the program for j 0.17046523094177246
column j: 1156
Runtime of the program for j 0.16158294677734375
column j: 1157
Runtime of the program for j 0.1127312183380127
column j: 1158
Runtime of the program for j 0.11200881004333496
column j: 1159
Runtime of the program for j 0.13457274436950684
column j: 1160
Runtime of the program for j 0.0955958366394043
column j: 1161
Runtime of the program for j 0.14102864265441895
column j: 1162
Runtime of the program for j 0.15669655799865723
column j: 1163
Runtime of the program for j 0.12581610679626465
column j: 1164
Runtime of the program for j 0.16590619087219238
column j: 1165
Runtime of the program for j 0.12498784065246582
column j: 1166
Runtime of the program for j 0.15718340873718262
column j: 1167
Runtime of the program for j 0.17883610725402832
column j: 1168
Runtime of the program for j 0.1497514247894287
column j: 1169
Runtime of the program for j 0.1447141170501709
column j: 1170
Runtime of the program for j 0.1355302333831787
column j: 1171
Runtime of the program for j 0.14951801300048828
column j: 1172
Runtime of the program for j 0.198075532913208
column j: 1173
Runtime of the program for j 0.17520833015441895
column j: 1174
Runtime of the program for j 0.19738483428955078
column j: 1175
Runtime of the program for j 0.1522691249847412
column j: 1176
Runtime of the program for j 0.16051840782165527
column j: 1177
Runtime of the program for j 0.16063165664672852
column j: 1178
Runtime of the program for j 0.1630856990814209
column j: 1179
Runtime of the program for j 0.17781853675842285

column j: 1180
Runtime of the program for j 0.1555805206298828
column j: 1181
Runtime of the program for j 0.1562662124633789
column j: 1182
Runtime of the program for j 0.15680789947509766
column j: 1183
Runtime of the program for j 0.214857816696167
column j: 1184
Runtime of the program for j 0.1650247573852539
column j: 1185
Runtime of the program for j 0.17015695571899414
column j: 1186
Runtime of the program for j 0.14449000358581543
column j: 1187
Runtime of the program for j 0.21533203125
column j: 1188
Runtime of the program for j 0.18565034866333008
column j: 1189
Runtime of the program for j 0.15538263320922852
column j: 1190
Runtime of the program for j 0.18892645835876465
column j: 1191
Runtime of the program for j 0.14893865585327148
column j: 1192
Runtime of the program for j 0.09376239776611328
column j: 1193
Runtime of the program for j 0.09454345703125
column j: 1194
Runtime of the program for j 0.15627074241638184
column j: 1195
Runtime of the program for j 0.1441025733947754
column j: 1196
Runtime of the program for j 0.18758535385131836
column j: 1197
Runtime of the program for j 0.14069056510925293
column j: 1198
Runtime of the program for j 0.16595888137817383
column j: 1199
Runtime of the program for j 0.14070773124694824
column j: 1200
Runtime of the program for j 0.14092636108398438
column j: 1201
Runtime of the program for j 0.17107677459716797
column j: 1202
Runtime of the program for j 0.13392043113708496
column j: 1203
Runtime of the program for j 0.140700101852417
column j: 1204
Runtime of the program for j 0.1415407657623291
column j: 1205
Runtime of the program for j 0.14200067520141602
column j: 1206
Runtime of the program for j 0.1567246913909912
column j: 1207
Runtime of the program for j 0.15808534622192383
column j: 1208
Runtime of the program for j 0.1557636260986328
column j: 1209
Runtime of the program for j 0.14371895790100098
column j: 1210
Runtime of the program for j 0.14481139183044434
column j: 1211
Runtime of the program for j 0.15230488777160645
column j: 1212
Runtime of the program for j 0.08735013008117676
column j: 1213
Runtime of the program for j 0.10653519630432129
column j: 1214
Runtime of the program for j 0.07936501502990723
column j: 1215
Runtime of the program for j 0.13572955131530762
column j: 1216
Runtime of the program for j 0.14164400100708008
column j: 1217
Runtime of the program for j 0.15052485466003418
column j: 1218
Runtime of the program for j 0.17682647705078125
column j: 1219
Runtime of the program for j 0.1500849723815918
column j: 1220
Runtime of the program for j 0.18214774131774902
column j: 1221
Runtime of the program for j 0.14154291152954102
column j: 1222
Runtime of the program for j 0.1723494529724121
column j: 1223
Runtime of the program for j 0.20163846015930176
column j: 1224
Runtime of the program for j 0.17768335342407227
column j: 1225
Runtime of the program for j 0.14128661155700684
column j: 1226
Runtime of the program for j 0.14657926559448242
column j: 1227
Runtime of the program for j 0.1441037654876709
column j: 1228
Runtime of the program for j 0.15023231506347656
column j: 1229
Runtime of the program for j 0.14120960235595703
column j: 1230
Runtime of the program for j 0.19081807136535645
column j: 1231
Runtime of the program for j 0.20368266105651855
column j: 1232
Runtime of the program for j 0.15618371963500977
column j: 1233
Runtime of the program for j 0.14330196380615234
column j: 1234
Runtime of the program for j 0.14917850494384766
column j: 1235
Runtime of the program for j 0.14121127128601074
column j: 1236
Runtime of the program for j 0.15708708763122559
column j: 1237
Runtime of the program for j 0.15642523765563965
column j: 1238
Runtime of the program for j 0.15625858306884766
column j: 1239
Runtime of the program for j 0.18567180633544922
column j: 1240
Runtime of the program for j 0.1467444896697998
column j: 1241
Runtime of the program for j 0.1556859016418457
column j: 1242
Runtime of the program for j 0.21510696411132812
column j: 1243
Runtime of the program for j 0.1683213710784912
column j: 1244
Runtime of the program for j 0.16934990882873535
column j: 1245
Runtime of the program for j 0.1564769744873047
column j: 1246
Runtime of the program for j 0.09622073173522949
column j: 1247
Runtime of the program for j 0.15837478637695312
column j: 1248
Runtime of the program for j 0.15218853950500488
column j: 1249
Runtime of the program for j 0.16009068489074707
column j: 1250
Runtime of the program for j 0.18519878387451172
column j: 1251
Runtime of the program for j 0.14406824111938477
column j: 1252
Runtime of the program for j 0.15625762939453125
column j: 1253
Runtime of the program for j 0.20030856132507324
column j: 1254
Runtime of the program for j 0.14990973472595215
column j: 1255
Runtime of the program for j 0.15679264068603516
column j: 1256
Runtime of the program for j 0.13695788383483887
column j: 1257
Runtime of the program for j 0.10877513885498047
column j: 1258
Runtime of the program for j 0.16764307022094727
column j: 1259
Runtime of the program for j 0.1537342071533203
column j: 1260
Runtime of the program for j 0.1568150520324707
column j: 1261
Runtime of the program for j 0.1564650535583496
column j: 1262
Runtime of the program for j 0.14908123016357422
column j: 1263
Runtime of the program for j 0.1755387783050537
column j: 1264
Runtime of the program for j 0.1634228229522705
column j: 1265
Runtime of the program for j 0.15226507186889648
column j: 1266
Runtime of the program for j 0.1555032730102539
column j: 1267
Runtime of the program for j 0.15564894676208496
column j: 1268
Runtime of the program for j 0.16485047340393066
column j: 1269
Runtime of the program for j 0.16808414459228516
column j: 1270
Runtime of the program for j 0.14388346672058105
column j: 1271
Runtime of the program for j 0.14768648147583008
column j: 1272
Runtime of the program for j 0.16654515266418457
column j: 1273
Runtime of the program for j 0.16039180755615234
column j: 1274
Runtime of the program for j 0.16677284240722656
column j: 1275
Runtime of the program for j 0.1800992488861084
column j: 1276
Runtime of the program for j 0.14128994941711426
column j: 1277
Runtime of the program for j 0.15623235702514648
column j: 1278
Runtime of the program for j 0.080078125
column j: 1279
Runtime of the program for j 0.1214292049407959
column j: 1280
Runtime of the program for j 0.14986181259155273
column j: 1281
Runtime of the program for j 0.1407167911529541
column j: 1282
Runtime of the program for j 0.16972875595092773
column j: 1283
Runtime of the program for j 0.16165995597839355
column j: 1284
Runtime of the program for j 0.14063501358032227
column j: 1285
Runtime of the program for j 0.1406238079071045
column j: 1286
Runtime of the program for j 0.1886887550354004
column j: 1287
Runtime of the program for j 0.09379220008850098
column j: 1288
Runtime of the program for j 0.10929536819458008
column j: 1289
Runtime of the program for j 0.1408689022064209
column j: 1290
Runtime of the program for j 0.17707395553588867
column j: 1291
Runtime of the program for j 0.15631842613220215
column j: 1292
Runtime of the program for j 0.1609973907470703
column j: 1293
Runtime of the program for j 0.15537047386169434
column j: 1294
Runtime of the program for j 0.16923785209655762
column j: 1295
Runtime of the program for j 0.1447925567626953
column j: 1296
Runtime of the program for j 0.18208098411560059
column j: 1297
Runtime of the program for j 0.1968832015991211
column j: 1298
Runtime of the program for j 0.1406247615814209
column j: 1299
Runtime of the program for j 0.17205500602722168
column j: 1300
Runtime of the program for j 0.09508132934570312
column j: 1301
Runtime of the program for j 0.07867312431335449
column j: 1302
Runtime of the program for j 0.1564338207244873
column j: 1303
Runtime of the program for j 0.09385371208190918
column j: 1304
Runtime of the program for j 0.14119935035705566
column j: 1305
Runtime of the program for j 0.1892096996307373
column j: 1306
Runtime of the program for j 0.14062190055847168
column j: 1307
Runtime of the program for j 0.17738866806030273
column j: 1308
Runtime of the program for j 0.1958773136138916
column j: 1309
Runtime of the program for j 0.14232230186462402

column j: 1310
Runtime of the program for j 0.17188000679016113
column j: 1311
Runtime of the program for j 0.1459059715270996
column j: 1312
Runtime of the program for j 0.14116668701171875
column j: 1313
Runtime of the program for j 0.15626144409179688
column j: 1314
Runtime of the program for j 0.17215228080749512
column j: 1315
Runtime of the program for j 0.14315509796142578
column j: 1316
Runtime of the program for j 0.20366477966308594
column j: 1317
Runtime of the program for j 0.16593694686889648
column j: 1318
Runtime of the program for j 0.1954939365386963
column j: 1319
Runtime of the program for j 0.17623472213745117
column j: 1320
Runtime of the program for j 0.1676497459411621
column j: 1321
Runtime of the program for j 0.14157342910766602
column j: 1322
Runtime of the program for j 0.15784764289855957
column j: 1323
Runtime of the program for j 0.1562807559967041
column j: 1324
Runtime of the program for j 0.16388273239135742
column j: 1325
Runtime of the program for j 0.16258645057678223
column j: 1326
Runtime of the program for j 0.1566619873046875
column j: 1327
Runtime of the program for j 0.1407785415649414
column j: 1328
Runtime of the program for j 0.14148998260498047
column j: 1329
Runtime of the program for j 0.2035503387451172
column j: 1330
Runtime of the program for j 0.1354050636291504
column j: 1331
Runtime of the program for j 0.15787291526794434
column j: 1332
Runtime of the program for j 0.15062546730041504
column j: 1333
Runtime of the program for j 0.13389158248901367
column j: 1334
Runtime of the program for j 0.17286014556884766
column j: 1335
Runtime of the program for j 0.16273069381713867
column j: 1336
Runtime of the program for j 0.15220189094543457
column j: 1337
Runtime of the program for j 0.10364556312561035
column j: 1338
Runtime of the program for j 0.1726832389831543
column j: 1339
Runtime of the program for j 0.17413926124572754
column j: 1340
Runtime of the program for j 0.1634078025817871
column j: 1341
Runtime of the program for j 0.18844819068908691
column j: 1342
Runtime of the program for j 0.14096665382385254
column j: 1343
Runtime of the program for j 0.14061784744262695
column j: 1344
Runtime of the program for j 0.177384614944458
column j: 1345
Runtime of the program for j 0.15790319442749023
column j: 1346
Runtime of the program for j 0.1752171516418457
column j: 1347
Runtime of the program for j 0.1892695426940918
column j: 1348
Runtime of the program for j 0.1579456329345703
column j: 1349
Runtime of the program for j 0.24997472763061523
column j: 1350
Runtime of the program for j 0.16054487228393555
column j: 1351
Runtime of the program for j 0.08794403076171875
column j: 1352
Runtime of the program for j 0.11198902130126953
column j: 1353
Runtime of the program for j 0.1526632308959961
column j: 1354
Runtime of the program for j 0.16861629486083984
column j: 1355
Runtime of the program for j 0.17394185066223145
column j: 1356
Runtime of the program for j 0.15201520919799805
column j: 1357
Runtime of the program for j 0.1496891975402832
column j: 1358
Runtime of the program for j 0.17883968353271484
column j: 1359
Runtime of the program for j 0.20041728019714355
column j: 1360
Runtime of the program for j 0.14267420768737793
column j: 1361
Runtime of the program for j 0.1769726276397705
column j: 1362
Runtime of the program for j 0.17549538612365723
column j: 1363
Runtime of the program for j 0.14106345176696777
column j: 1364
Runtime of the program for j 0.11069822311401367
column j: 1365
Runtime of the program for j 0.1893784999847412
column j: 1366
Runtime of the program for j 0.150984525680542
column j: 1367
Runtime of the program for j 0.15792322158813477
column j: 1368
Runtime of the program for j 0.15229153633117676
column j: 1369
Runtime of the program for j 0.14766526222229004
column j: 1370
Runtime of the program for j 0.1884629726409912
column j: 1371
Runtime of the program for j 0.16712522506713867
column j: 1372
Runtime of the program for j 0.09409785270690918
column j: 1373
Runtime of the program for j 0.1589975357055664
column j: 1374
Runtime of the program for j 0.16155409812927246
column j: 1375
Runtime of the program for j 0.18393182754516602
column j: 1376
Runtime of the program for j 0.13361620903015137
column j: 1377
Runtime of the program for j 0.18190956115722656
column j: 1378
Runtime of the program for j 0.16341638565063477
column j: 1379
Runtime of the program for j 0.14361834526062012
column j: 1380
Runtime of the program for j 0.21839642524719238
column j: 1381
Runtime of the program for j 0.1567244529724121
column j: 1382
Runtime of the program for j 0.15563321113586426
column j: 1383
Runtime of the program for j 0.17228460311889648
column j: 1384
Runtime of the program for j 0.15706515312194824
column j: 1385
Runtime of the program for j 0.1491994857788086
column j: 1386
Runtime of the program for j 0.1612241268157959
column j: 1387
Runtime of the program for j 0.16911530494689941
column j: 1388
Runtime of the program for j 0.16047263145446777
column j: 1389
Runtime of the program for j 0.1527247428894043
column j: 1390
Runtime of the program for j 0.20468902587890625
column j: 1391
Runtime of the program for j 0.16045260429382324
column j: 1392
Runtime of the program for j 0.15281248092651367
column j: 1393
Runtime of the program for j 0.17529034614562988
column j: 1394
Runtime of the program for j 0.15279579162597656
column j: 1395
Runtime of the program for j 0.17392277717590332
column j: 1396
Runtime of the program for j 0.15111947059631348
column j: 1397
Runtime of the program for j 0.15636086463928223
column j: 1398
Runtime of the program for j 0.15955138206481934
column j: 1399
Runtime of the program for j 0.18396520614624023
column j: 1400
Runtime of the program for j 0.15684127807617188
column j: 1401
Runtime of the program for j 0.17203164100646973
column j: 1402
Runtime of the program for j 0.1512131690979004
column j: 1403
Runtime of the program for j 0.17095422744750977
column j: 1404
Runtime of the program for j 0.15625452995300293
column j: 1405
Runtime of the program for j 0.1448533535003662
column j: 1406
Runtime of the program for j 0.17676568031311035
column j: 1407
Runtime of the program for j 0.15798640251159668
column j: 1408
Runtime of the program for j 0.1822056770324707
column j: 1409
Runtime of the program for j 0.16224098205566406
column j: 1410
Runtime of the program for j 0.16131019592285156
column j: 1411
Runtime of the program for j 0.1520233154296875
column j: 1412
Runtime of the program for j 0.15866804122924805
column j: 1413
Runtime of the program for j 0.16424036026000977
column j: 1414
Runtime of the program for j 0.15650415420532227
column j: 1415
Runtime of the program for j 0.12589621543884277
column j: 1416
Runtime of the program for j 0.18202638626098633
column j: 1417
Runtime of the program for j 0.1879279613494873
column j: 1418
Runtime of the program for j 0.14069461822509766
column j: 1419
Runtime of the program for j 0.12491440773010254
column j: 1420
Runtime of the program for j 0.11748480796813965
column j: 1421
Runtime of the program for j 0.15669488906860352
column j: 1422
Runtime of the program for j 0.14055752754211426
column j: 1423
Runtime of the program for j 0.15752506256103516
column j: 1424
Runtime of the program for j 0.14922189712524414
column j: 1425
Runtime of the program for j 0.14070630073547363
column j: 1426
Runtime of the program for j 0.18776822090148926
column j: 1427
Runtime of the program for j 0.19620251655578613
column j: 1428
Runtime of the program for j 0.15691423416137695
column j: 1429
Runtime of the program for j 0.1406259536743164
column j: 1430
Runtime of the program for j 0.1497969627380371
column j: 1431
Runtime of the program for j 0.14060115814208984
column j: 1432
Runtime of the program for j 0.1417241096496582
column j: 1433
Runtime of the program for j 0.14063572883605957
column j: 1434
Runtime of the program for j 0.17999505996704102
column j: 1435
Runtime of the program for j 0.18817687034606934
column j: 1436
Runtime of the program for j 0.1250147819519043
column j: 1437
Runtime of the program for j 0.1655406951904297
column j: 1438
Runtime of the program for j 0.12510037422180176
column j: 1439
Runtime of the program for j 0.14062023162841797

column j: 1440
Runtime of the program for j 0.17154479026794434
column j: 1441
Runtime of the program for j 0.13388705253601074
column j: 1442
Runtime of the program for j 0.16786861419677734
column j: 1443
Runtime of the program for j 0.1596965789794922
column j: 1444
Runtime of the program for j 0.20043253898620605
column j: 1445
Runtime of the program for j 0.15822839736938477
column j: 1446
Runtime of the program for j 0.1464688777923584
column j: 1447
Runtime of the program for j 0.17080950736999512
column j: 1448
Runtime of the program for j 0.17240238189697266
column j: 1449
Runtime of the program for j 0.15673232078552246
column j: 1450
Runtime of the program for j 0.1553940773010254
column j: 1451
Runtime of the program for j 0.17625212669372559
column j: 1452
Runtime of the program for j 0.16059112548828125
column j: 1453
Runtime of the program for j 0.20576882362365723
column j: 1454
Runtime of the program for j 0.14263081550598145
column j: 1455
Runtime of the program for j 0.1731104850769043
column j: 1456
Runtime of the program for j 0.16867446899414062
column j: 1457
Runtime of the program for j 0.14183688163757324
column j: 1458
Runtime of the program for j 0.14066076278686523
column j: 1459
Runtime of the program for j 0.14769792556762695
column j: 1460
Runtime of the program for j 0.15092015266418457
column j: 1461
Runtime of the program for j 0.17533159255981445
column j: 1462
Runtime of the program for j 0.15730786323547363
column j: 1463
Runtime of the program for j 0.15359234809875488
column j: 1464
Runtime of the program for j 0.13767051696777344
column j: 1465
Runtime of the program for j 0.15643668174743652
column j: 1466
Runtime of the program for j 0.15667724609375
column j: 1467
Runtime of the program for j 0.16761112213134766
column j: 1468
Runtime of the program for j 0.13975000381469727
column j: 1469
Runtime of the program for j 0.1316666603088379
column j: 1470
Runtime of the program for j 0.20466136932373047
column j: 1471
Runtime of the program for j 0.13445329666137695
column j: 1472
Runtime of the program for j 0.1659073829650879
column j: 1473
Runtime of the program for j 0.1801140308380127
column j: 1474
Runtime of the program for j 0.14151978492736816
column j: 1475
Runtime of the program for j 0.15365242958068848
column j: 1476
Runtime of the program for j 0.102996826171875
column j: 1477
Runtime of the program for j 0.15720725059509277
column j: 1478
Runtime of the program for j 0.15699267387390137
column j: 1479
Runtime of the program for j 0.16406655311584473
column j: 1480
Runtime of the program for j 0.14197826385498047
column j: 1481
Runtime of the program for j 0.17976117134094238
column j: 1482
Runtime of the program for j 0.15879583358764648
column j: 1483
Runtime of the program for j 0.1502366065979004
column j: 1484
Runtime of the program for j 0.13376307487487793
column j: 1485
Runtime of the program for j 0.15635919570922852
column j: 1486
Runtime of the program for j 0.16206622123718262
column j: 1487
Runtime of the program for j 0.15667104721069336
column j: 1488
Runtime of the program for j 0.21094107627868652
column j: 1489
Runtime of the program for j 0.1723775863647461
column j: 1490
Runtime of the program for j 0.1418287754058838
column j: 1491
Runtime of the program for j 0.14221882820129395
column j: 1492
Runtime of the program for j 0.15721416473388672
column j: 1493
Runtime of the program for j 0.1495380401611328
column j: 1494
Runtime of the program for j 0.18215394020080566
column j: 1495
Runtime of the program for j 0.17459583282470703
column j: 1496
Runtime of the program for j 0.17407536506652832
column j: 1497
Runtime of the program for j 0.15912818908691406
column j: 1498
Runtime of the program for j 0.15326929092407227
column j: 1499
Runtime of the program for j 0.15251731872558594
column j: 1500
Runtime of the program for j 0.17287778854370117
column j: 1501
Runtime of the program for j 0.1565871238708496
column j: 1502
Runtime of the program for j 0.20720553398132324
column j: 1503
Runtime of the program for j 0.14409947395324707
column j: 1504
Runtime of the program for j 0.1924896240234375
column j: 1505
Runtime of the program for j 0.16036081314086914
column j: 1506
Runtime of the program for j 0.17017316818237305
column j: 1507
Runtime of the program for j 0.15239500999450684
column j: 1508
Runtime of the program for j 0.16101336479187012
column j: 1509
Runtime of the program for j 0.18527889251708984
column j: 1510
Runtime of the program for j 0.15464401245117188
column j: 1511
Runtime of the program for j 0.1641993522644043
column j: 1512
Runtime of the program for j 0.1891329288482666
column j: 1513
Runtime of the program for j 0.1595630645751953
column j: 1514
Runtime of the program for j 0.15744829177856445
column j: 1515
Runtime of the program for j 0.14402151107788086
column j: 1516
Runtime of the program for j 0.1562516689300537
column j: 1517
Runtime of the program for j 0.1504044532775879
column j: 1518
Runtime of the program for j 0.1575150489807129
column j: 1519
Runtime of the program for j 0.17272686958312988
column j: 1520
Runtime of the program for j 0.15687990188598633
column j: 1521
Runtime of the program for j 0.19150280952453613
column j: 1522
Runtime of the program for j 0.15037035942077637
column j: 1523
Runtime of the program for j 0.18039226531982422
column j: 1524
Runtime of the program for j 0.14891314506530762
column j: 1525
Runtime of the program for j 0.15043354034423828
column j: 1526
Runtime of the program for j 0.16739606857299805
column j: 1527
Runtime of the program for j 0.13746404647827148
column j: 1528
Runtime of the program for j 0.1797924041748047
column j: 1529
Runtime of the program for j 0.21413564682006836
column j: 1530
Runtime of the program for j 0.15232276916503906
column j: 1531
Runtime of the program for j 0.12499809265136719
column j: 1532
Runtime of the program for j 0.1758115291595459
column j: 1533
Runtime of the program for j 0.15685319900512695
column j: 1534
Runtime of the program for j 0.16362714767456055
column j: 1535
Runtime of the program for j 0.12742400169372559
column j: 1536
Runtime of the program for j 0.16603899002075195
column j: 1537
Runtime of the program for j 0.21215248107910156
column j: 1538
Runtime of the program for j 0.12291121482849121
column j: 1539
Runtime of the program for j 0.18817520141601562
column j: 1540
Runtime of the program for j 0.15723657608032227
column j: 1541
Runtime of the program for j 0.14154529571533203
column j: 1542
Runtime of the program for j 0.16090631484985352
column j: 1543
Runtime of the program for j 0.14080142974853516
column j: 1544
Runtime of the program for j 0.12498044967651367
column j: 1545
Runtime of the program for j 0.1740868091583252
column j: 1546
Runtime of the program for j 0.19478845596313477
column j: 1547
Runtime of the program for j 0.16721439361572266
column j: 1548
Runtime of the program for j 0.17179608345031738
column j: 1549
Runtime of the program for j 0.17295622825622559
column j: 1550
Runtime of the program for j 0.18460416793823242
column j: 1551
Runtime of the program for j 0.19240593910217285
column j: 1552
Runtime of the program for j 0.19131016731262207
column j: 1553
Runtime of the program for j 0.15234589576721191
column j: 1554
Runtime of the program for j 0.19625401496887207
column j: 1555
Runtime of the program for j 0.1705944538116455
column j: 1556
Runtime of the program for j 0.15759706497192383
column j: 1557
Runtime of the program for j 0.151092529296875
column j: 1558
Runtime of the program for j 0.18193626403808594
column j: 1559
Runtime of the program for j 0.1529395580291748
column j: 1560
Runtime of the program for j 0.1691279411315918
column j: 1561
Runtime of the program for j 0.15686392784118652
column j: 1562
Runtime of the program for j 0.21643877029418945
column j: 1563
Runtime of the program for j 0.12099695205688477
column j: 1564
Runtime of the program for j 0.13376760482788086
column j: 1565
Runtime of the program for j 0.15626168251037598
column j: 1566
Runtime of the program for j 0.1562490463256836
column j: 1567
Runtime of the program for j 0.09406161308288574
column j: 1568
Runtime of the program for j 0.15617823600769043
column j: 1569
Runtime of the program for j 0.14062809944152832

column j: 1570
Runtime of the program for j 0.14061450958251953
column j: 1571
Runtime of the program for j 0.1903841495513916
column j: 1572
Runtime of the program for j 0.16846227645874023
column j: 1573
Runtime of the program for j 0.1739673614501953
column j: 1574
Runtime of the program for j 0.14310193061828613
column j: 1575
Runtime of the program for j 0.13104009628295898
column j: 1576
Runtime of the program for j 0.17207098007202148
column j: 1577
Runtime of the program for j 0.14062881469726562
column j: 1578
Runtime of the program for j 0.23229312896728516
column j: 1579
Runtime of the program for j 0.07813358306884766
column j: 1580
Runtime of the program for j 0.09375596046447754
column j: 1581
Runtime of the program for j 0.17412090301513672
column j: 1582
Runtime of the program for j 0.1495046615600586
column j: 1583
Runtime of the program for j 0.20686078071594238
column j: 1584
Runtime of the program for j 0.14773321151733398
column j: 1585
Runtime of the program for j 0.15190362930297852
column j: 1586
Runtime of the program for j 0.20870494842529297
column j: 1587
Runtime of the program for j 0.14160871505737305
column j: 1588
Runtime of the program for j 0.15624570846557617
column j: 1589
Runtime of the program for j 0.1407463550567627
column j: 1590
Runtime of the program for j 0.1405642032623291
column j: 1591
Runtime of the program for j 0.1718761920928955
column j: 1592
Runtime of the program for j 0.14063262939453125
column j: 1593
Runtime of the program for j 0.10937094688415527
column j: 1594
Runtime of the program for j 0.1958315372467041
column j: 1595
Runtime of the program for j 0.18282461166381836
column j: 1596
Runtime of the program for j 0.18903350830078125
column j: 1597
Runtime of the program for j 0.14877581596374512
column j: 1598
Runtime of the program for j 0.17179107666015625
column j: 1599
Runtime of the program for j 0.15642976760864258
column j: 1600
Runtime of the program for j 0.16754436492919922
column j: 1601
Runtime of the program for j 0.18608736991882324
column j: 1602
Runtime of the program for j 0.21634149551391602
column j: 1603
Runtime of the program for j 0.18772506713867188
column j: 1604
Runtime of the program for j 0.165510892868042
column j: 1605
Runtime of the program for j 0.13891077041625977
column j: 1606
Runtime of the program for j 0.19359207153320312
column j: 1607
Runtime of the program for j 0.16641497611999512
column j: 1608
Runtime of the program for j 0.10378003120422363
column j: 1609
Runtime of the program for j 0.14399933815002441
column j: 1610
Runtime of the program for j 0.19388413429260254
column j: 1611
Runtime of the program for j 0.16826581954956055
column j: 1612
Runtime of the program for j 0.11176156997680664
column j: 1613
Runtime of the program for j 0.16472125053405762
column j: 1614
Runtime of the program for j 0.16347575187683105
column j: 1615
Runtime of the program for j 0.16325139999389648
column j: 1616
Runtime of the program for j 0.17274045944213867
column j: 1617
Runtime of the program for j 0.16643619537353516
column j: 1618
Runtime of the program for j 0.22618794441223145
column j: 1619
Runtime of the program for j 0.1360797882080078
column j: 1620
Runtime of the program for j 0.15981364250183105
column j: 1621
Runtime of the program for j 0.18092727661132812
column j: 1622
Runtime of the program for j 0.14806747436523438
column j: 1623
Runtime of the program for j 0.17818236351013184
column j: 1624
Runtime of the program for j 0.15741634368896484
column j: 1625
Runtime of the program for j 0.1956796646118164
column j: 1626
Runtime of the program for j 0.1148831844329834
column j: 1627
Runtime of the program for j 0.12607502937316895
column j: 1628
Runtime of the program for j 0.16892242431640625
column j: 1629
Runtime of the program for j 0.1492292881011963
column j: 1630
Runtime of the program for j 0.16670870780944824
column j: 1631
Runtime of the program for j 0.17518091201782227
column j: 1632
Runtime of the program for j 0.15841412544250488
column j: 1633
Runtime of the program for j 0.23304247856140137
column j: 1634
Runtime of the program for j 0.07737493515014648
column j: 1635
Runtime of the program for j 0.1093757152557373
column j: 1636
Runtime of the program for j 0.11085367202758789
column j: 1637
Runtime of the program for j 0.09427523612976074
column j: 1638
Runtime of the program for j 0.11805582046508789
column j: 1639
Runtime of the program for j 0.14114642143249512
column j: 1640
Runtime of the program for j 0.1661975383758545
column j: 1641
Runtime of the program for j 0.21465206146240234
column j: 1642
Runtime of the program for j 0.15114188194274902
column j: 1643
Runtime of the program for j 0.17561912536621094
column j: 1644
Runtime of the program for j 0.13374662399291992
column j: 1645
Runtime of the program for j 0.15869617462158203
column j: 1646
Runtime of the program for j 0.1724991798400879
column j: 1647
Runtime of the program for j 0.1580193042755127
column j: 1648
Runtime of the program for j 0.17220354080200195
column j: 1649
Runtime of the program for j 0.1844921112060547
column j: 1650
Runtime of the program for j 0.13363099098205566
column j: 1651
Runtime of the program for j 0.13005638122558594
column j: 1652
Runtime of the program for j 0.17368650436401367
column j: 1653
Runtime of the program for j 0.15796780586242676
column j: 1654
Runtime of the program for j 0.0788578987121582
column j: 1655
Runtime of the program for j 0.1711740493774414
column j: 1656
Runtime of the program for j 0.16571831703186035
column j: 1657
Runtime of the program for j 0.1818087100982666
column j: 1658
Runtime of the program for j 0.18663763999938965
column j: 1659
Runtime of the program for j 0.1490013599395752
column j: 1660
Runtime of the program for j 0.15779781341552734
column j: 1661
Runtime of the program for j 0.14298701286315918
column j: 1662
Runtime of the program for j 0.1474747657775879
column j: 1663
Runtime of the program for j 0.1691148281097412
column j: 1664
Runtime of the program for j 0.2040390968322754
column j: 1665
Runtime of the program for j 0.17563509941101074
column j: 1666
Runtime of the program for j 0.15626144409179688
column j: 1667
Runtime of the program for j 0.1779494285583496
column j: 1668
Runtime of the program for j 0.12700748443603516
column j: 1669
Runtime of the program for j 0.14366507530212402
column j: 1670
Runtime of the program for j 0.1657123565673828
column j: 1671
Runtime of the program for j 0.1474442481994629
column j: 1672
Runtime of the program for j 0.23631715774536133
column j: 1673
Runtime of the program for j 0.11778068542480469
column j: 1674
Runtime of the program for j 0.17483901977539062
column j: 1675
Runtime of the program for j 0.19293904304504395
column j: 1676
Runtime of the program for j 0.13468670845031738
column j: 1677
Runtime of the program for j 0.16654539108276367
column j: 1678
Runtime of the program for j 0.13713574409484863
column j: 1679
Runtime of the program for j 0.18266510963439941
column j: 1680
Runtime of the program for j 0.1529092788696289
column j: 1681
Runtime of the program for j 0.14111661911010742
column j: 1682
Runtime of the program for j 0.17988872528076172
column j: 1683
Runtime of the program for j 0.1568160057067871
column j: 1684
Runtime of the program for j 0.1752018928527832
column j: 1685
Runtime of the program for j 0.14117169380187988
column j: 1686
Runtime of the program for j 0.20743894577026367
column j: 1687
Runtime of the program for j 0.15044021606445312
column j: 1688
Runtime of the program for j 0.1626746654510498
column j: 1689
Runtime of the program for j 0.17775988578796387
column j: 1690
Runtime of the program for j 0.16052556037902832
column j: 1691
Runtime of the program for j 0.16907739639282227
column j: 1692
Runtime of the program for j 0.15795135498046875
column j: 1693
Runtime of the program for j 0.14438295364379883
column j: 1694
Runtime of the program for j 0.23622536659240723
column j: 1695
Runtime of the program for j 0.1651139259338379
column j: 1696
Runtime of the program for j 0.16151165962219238
column j: 1697
Runtime of the program for j 0.15305089950561523
column j: 1698
Runtime of the program for j 0.17448091506958008
column j: 1699
Runtime of the program for j 0.20487260818481445

column j: 1700
Runtime of the program for j 0.19075870513916016
column j: 1701
Runtime of the program for j 0.22090792655944824
column j: 1702
Runtime of the program for j 0.1416642665863037
column j: 1703
Runtime of the program for j 0.17421412467956543
column j: 1704
Runtime of the program for j 0.1721045970916748
column j: 1705
Runtime of the program for j 0.15894460678100586
column j: 1706
Runtime of the program for j 0.17559409141540527
column j: 1707
Runtime of the program for j 0.14260339736938477
column j: 1708
Runtime of the program for j 0.20504307746887207
column j: 1709
Runtime of the program for j 0.14575457572937012
column j: 1710
Runtime of the program for j 0.17959022521972656
column j: 1711
Runtime of the program for j 0.16750335693359375
column j: 1712
Runtime of the program for j 0.16643023490905762
column j: 1713
Runtime of the program for j 0.18093323707580566
column j: 1714
Runtime of the program for j 0.141340970993042
column j: 1715
Runtime of the program for j 0.17382574081420898
column j: 1716
Runtime of the program for j 0.23687195777893066
column j: 1717
Runtime of the program for j 0.18396854400634766
column j: 1718
Runtime of the program for j 0.17362380027770996
column j: 1719
Runtime of the program for j 0.17409229278564453
column j: 1720
Runtime of the program for j 0.16605520248413086
column j: 1721
Runtime of the program for j 0.1425158977508545
column j: 1722
Runtime of the program for j 0.1620020866394043
column j: 1723
Runtime of the program for j 0.20964765548706055
column j: 1724
Runtime of the program for j 0.143280029296875
column j: 1725
Runtime of the program for j 0.14805030822753906
column j: 1726
Runtime of the program for j 0.15688085556030273
column j: 1727
Runtime of the program for j 0.19142365455627441
column j: 1728
Runtime of the program for j 0.17198657989501953
column j: 1729
Runtime of the program for j 0.17827129364013672
column j: 1730
Runtime of the program for j 0.18854117393493652
column j: 1731
Runtime of the program for j 0.17717647552490234
column j: 1732
Runtime of the program for j 0.1647169589996338
column j: 1733
Runtime of the program for j 0.16339826583862305
column j: 1734
Runtime of the program for j 0.1828930377960205
column j: 1735
Runtime of the program for j 0.1657087802886963
column j: 1736
Runtime of the program for j 0.1969165802001953
column j: 1737
Runtime of the program for j 0.18030858039855957
column j: 1738
Runtime of the program for j 0.23721718788146973
column j: 1739
Runtime of the program for j 0.16307616233825684
column j: 1740
Runtime of the program for j 0.169158935546875
column j: 1741
Runtime of the program for j 0.16565585136413574
column j: 1742
Runtime of the program for j 0.15806984901428223
column j: 1743
Runtime of the program for j 0.19006562232971191
column j: 1744
Runtime of the program for j 0.16646862030029297
column j: 1745
Runtime of the program for j 0.16590666770935059
column j: 1746
Runtime of the program for j 0.15166735649108887
column j: 1747
Runtime of the program for j 0.15551352500915527
column j: 1748
Runtime of the program for j 0.17797493934631348
column j: 1749
Runtime of the program for j 0.157059907913208
column j: 1750
Runtime of the program for j 0.16632866859436035
column j: 1751
Runtime of the program for j 0.15176987648010254
column j: 1752
Runtime of the program for j 0.23871803283691406
column j: 1753
Runtime of the program for j 0.14810991287231445
column j: 1754
Runtime of the program for j 0.16994476318359375
column j: 1755
Runtime of the program for j 0.16438603401184082
column j: 1756
Runtime of the program for j 0.14739274978637695
column j: 1757
Runtime of the program for j 0.1906757354736328
column j: 1758
Runtime of the program for j 0.14264416694641113
column j: 1759
Runtime of the program for j 0.16503190994262695
column j: 1760
Runtime of the program for j 0.10427045822143555
column j: 1761
Runtime of the program for j 0.16493773460388184
column j: 1762
Runtime of the program for j 0.1513049602508545
column j: 1763
Runtime of the program for j 0.15761876106262207
column j: 1764
Runtime of the program for j 0.16435718536376953
column j: 1765
Runtime of the program for j 0.17369532585144043
column j: 1766
Runtime of the program for j 0.22504210472106934
column j: 1767
Runtime of the program for j 0.14425373077392578
column j: 1768
Runtime of the program for j 0.2038118839263916
column j: 1769
Runtime of the program for j 0.14055442810058594
column j: 1770
Runtime of the program for j 0.15723752975463867
column j: 1771
Runtime of the program for j 0.15735363960266113
column j: 1772
Runtime of the program for j 0.17229604721069336
column j: 1773
Runtime of the program for j 0.21958208084106445
column j: 1774
Runtime of the program for j 0.15624761581420898
column j: 1775
Runtime of the program for j 0.15693283081054688
column j: 1776
Runtime of the program for j 0.14041948318481445
column j: 1777
Runtime of the program for j 0.17267537117004395
column j: 1778
Runtime of the program for j 0.15647530555725098
column j: 1779
Runtime of the program for j 0.15649127960205078
column j: 1780
Runtime of the program for j 0.20314407348632812
column j: 1781
Runtime of the program for j 0.15729641914367676
column j: 1782
Runtime of the program for j 0.1562504768371582
column j: 1783
Runtime of the program for j 0.14477300643920898
column j: 1784
Runtime of the program for j 0.1723039150238037
column j: 1785
Runtime of the program for j 0.14069199562072754
column j: 1786
Runtime of the program for j 0.14054393768310547
column j: 1787
Runtime of the program for j 0.18758940696716309
column j: 1788
Runtime of the program for j 0.1932981014251709
column j: 1789
Runtime of the program for j 0.18625569343566895
column j: 1790
Runtime of the program for j 0.1413276195526123
column j: 1791
Runtime of the program for j 0.18079018592834473
column j: 1792
Runtime of the program for j 0.15604448318481445
column j: 1793
Runtime of the program for j 0.17251873016357422
column j: 1794
Runtime of the program for j 0.2118840217590332
column j: 1795
Runtime of the program for j 0.1592540740966797
column j: 1796
Runtime of the program for j 0.16637635231018066
column j: 1797
Runtime of the program for j 0.16898488998413086
column j: 1798
Runtime of the program for j 0.18603110313415527
column j: 1799
Runtime of the program for j 0.15847229957580566
column j: 1800
Runtime of the program for j 0.1718761920928955
column j: 1801
Runtime of the program for j 0.18886542320251465
column j: 1802
Runtime of the program for j 0.1567835807800293
column j: 1803
Runtime of the program for j 0.15674805641174316
column j: 1804
Runtime of the program for j 0.17218947410583496
column j: 1805
Runtime of the program for j 0.16808342933654785
column j: 1806
Runtime of the program for j 0.1786191463470459
column j: 1807
Runtime of the program for j 0.15625977516174316
column j: 1808
Runtime of the program for j 0.20669245719909668
column j: 1809
Runtime of the program for j 0.17286396026611328
column j: 1810
Runtime of the program for j 0.1406874656677246
column j: 1811
Runtime of the program for j 0.1723787784576416
column j: 1812
Runtime of the program for j 0.17221736907958984
column j: 1813
Runtime of the program for j 0.18785500526428223
column j: 1814
Runtime of the program for j 0.17738628387451172
column j: 1815
Runtime of the program for j 0.24605226516723633
column j: 1816
Runtime of the program for j 0.1714487075805664
column j: 1817
Runtime of the program for j 0.18072962760925293
column j: 1818
Runtime of the program for j 0.20004510879516602
column j: 1819
Runtime of the program for j 0.15302109718322754
column j: 1820
Runtime of the program for j 0.15625977516174316
column j: 1821
Runtime of the program for j 0.16502857208251953
column j: 1822
Runtime of the program for j 0.21874213218688965
column j: 1823
Runtime of the program for j 0.1406402587890625
column j: 1824
Runtime of the program for j 0.15761613845825195
column j: 1825
Runtime of the program for j 0.1400306224822998
column j: 1826
Runtime of the program for j 0.1730823516845703
column j: 1827
Runtime of the program for j 0.17188382148742676
column j: 1828
Runtime of the program for j 0.15626215934753418
column j: 1829
Runtime of the program for j 0.2036736011505127

column j: 1830
Runtime of the program for j 0.1411762237548828
column j: 1831
Runtime of the program for j 0.15565109252929688
column j: 1832
Runtime of the program for j 0.15624570846557617
column j: 1833
Runtime of the program for j 0.17187261581420898
column j: 1834
Runtime of the program for j 0.156266450881958
column j: 1835
Runtime of the program for j 0.140824556350708
column j: 1836
Runtime of the program for j 0.2031240463256836
column j: 1837
Runtime of the program for j 0.17310023307800293
column j: 1838
Runtime of the program for j 0.1873922348022461
column j: 1839
Runtime of the program for j 0.15627002716064453
column j: 1840
Runtime of the program for j 0.17233610153198242
column j: 1841
Runtime of the program for j 0.15725421905517578
column j: 1842
Runtime of the program for j 0.18118023872375488
column j: 1843
Runtime of the program for j 0.203718900680542
column j: 1844
Runtime of the program for j 0.128983736038208
column j: 1845
Runtime of the program for j 0.18406248092651367
column j: 1846
Runtime of the program for j 0.11261725425720215
column j: 1847
Runtime of the program for j 0.09473657608032227
column j: 1848
Runtime of the program for j 0.14428377151489258
column j: 1849
Runtime of the program for j 0.18806862831115723
column j: 1850
Runtime of the program for j 0.20233416557312012
column j: 1851
Runtime of the program for j 0.1756749153137207
column j: 1852
Runtime of the program for j 0.14978790283203125
column j: 1853
Runtime of the program for j 0.17659282684326172
column j: 1854
Runtime of the program for j 0.1654198169708252
column j: 1855
Runtime of the program for j 0.17192554473876953
column j: 1856
Runtime of the program for j 0.21196842193603516
column j: 1857
Runtime of the program for j 0.20301127433776855
column j: 1858
Runtime of the program for j 0.171891450881958
column j: 1859
Runtime of the program for j 0.1594867706298828
column j: 1860
Runtime of the program for j 0.1410198211669922
column j: 1861
Runtime of the program for j 0.17325520515441895
column j: 1862
Runtime of the program for j 0.11479830741882324
column j: 1863
Runtime of the program for j 0.18439555168151855
column j: 1864
Runtime of the program for j 0.1859743595123291
column j: 1865
Runtime of the program for j 0.17963004112243652
column j: 1866
Runtime of the program for j 0.18974542617797852
column j: 1867
Runtime of the program for j 0.15709543228149414
column j: 1868
Runtime of the program for j 0.16975045204162598
column j: 1869
Runtime of the program for j 0.18738412857055664
column j: 1870
Runtime of the program for j 0.17966270446777344
column j: 1871
Runtime of the program for j 0.15695858001708984
column j: 1872
Runtime of the program for j 0.13442611694335938
column j: 1873
Runtime of the program for j 0.1401045322418213
column j: 1874
Runtime of the program for j 0.13926935195922852
column j: 1875
Runtime of the program for j 0.21395540237426758
column j: 1876
Runtime of the program for j 0.18750524520874023
column j: 1877
Runtime of the program for j 0.17239689826965332
column j: 1878
Runtime of the program for j 0.15116095542907715
column j: 1879
Runtime of the program for j 0.17254376411437988
column j: 1880
Runtime of the program for j 0.16895246505737305
column j: 1881
Runtime of the program for j 0.17395973205566406
column j: 1882
Runtime of the program for j 0.15624141693115234
column j: 1883
Runtime of the program for j 0.19732928276062012
column j: 1884
Runtime of the program for j 0.17368173599243164
column j: 1885
Runtime of the program for j 0.178269624710083
column j: 1886
Runtime of the program for j 0.08793330192565918
column j: 1887
Runtime of the program for j 0.11182260513305664
column j: 1888
Runtime of the program for j 0.1549086570739746
column j: 1889
Runtime of the program for j 0.1944732666015625
column j: 1890
Runtime of the program for j 0.18863606452941895
column j: 1891
Runtime of the program for j 0.1516714096069336
column j: 1892
Runtime of the program for j 0.13248944282531738
column j: 1893
Runtime of the program for j 0.1627960205078125
column j: 1894
Runtime of the program for j 0.17911338806152344
column j: 1895
Runtime of the program for j 0.1575784683227539
column j: 1896
Runtime of the program for j 0.22255873680114746
column j: 1897
Runtime of the program for j 0.1616687774658203
column j: 1898
Runtime of the program for j 0.16482901573181152
column j: 1899
Runtime of the program for j 0.1406383514404297
column j: 1900
Runtime of the program for j 0.19614839553833008
column j: 1901
Runtime of the program for j 0.14112567901611328
column j: 1902
Runtime of the program for j 0.18735408782958984
column j: 1903
Runtime of the program for j 0.1719493865966797
column j: 1904
Runtime of the program for j 0.14095830917358398
column j: 1905
Runtime of the program for j 0.1502375602722168
column j: 1906
Runtime of the program for j 0.1558523178100586
column j: 1907
Runtime of the program for j 0.15668272972106934
column j: 1908
Runtime of the program for j 0.17270112037658691
column j: 1909
Runtime of the program for j 0.21181106567382812
column j: 1910
Runtime of the program for j 0.1535661220550537
column j: 1911
Runtime of the program for j 0.18093585968017578
column j: 1912
Runtime of the program for j 0.17250347137451172
column j: 1913
Runtime of the program for j 0.22054386138916016
column j: 1914
Runtime of the program for j 0.14355778694152832
column j: 1915
Runtime of the program for j 0.16460156440734863
column j: 1916
Runtime of the program for j 0.21637344360351562
column j: 1917
Runtime of the program for j 0.1672654151916504
column j: 1918
Runtime of the program for j 0.15786004066467285
column j: 1919
Runtime of the program for j 0.1653590202331543
column j: 1920
Runtime of the program for j 0.16274380683898926
column j: 1921
Runtime of the program for j 0.16630911827087402
column j: 1922
Runtime of the program for j 0.1501471996307373
column j: 1923
Runtime of the program for j 0.2272803783416748
column j: 1924
Runtime of the program for j 0.14255070686340332
column j: 1925
Runtime of the program for j 0.14077520370483398
column j: 1926
Runtime of the program for j 0.12790465354919434
column j: 1927
Runtime of the program for j 0.15772366523742676
column j: 1928
Runtime of the program for j 0.17194485664367676
column j: 1929
Runtime of the program for j 0.21837401390075684
column j: 1930
Runtime of the program for j 0.1735093593597412
column j: 1931
Runtime of the program for j 0.14956402778625488
column j: 1932
Runtime of the program for j 0.18727827072143555
column j: 1933
Runtime of the program for j 0.13705134391784668
column j: 1934
Runtime of the program for j 0.19693350791931152
column j: 1935
Runtime of the program for j 0.18898749351501465
column j: 1936
Runtime of the program for j 0.18829131126403809
column j: 1937
Runtime of the program for j 0.09369850158691406
column j: 1938
Runtime of the program for j 0.18002080917358398
column j: 1939
Runtime of the program for j 0.16755437850952148

In [7]:
curated_bow['max_noise'] = sss['max_noise']
curated_bow['noise'] = 0
curated_bow

,id,,.,a,if,return,throw,void,},!,...,} ',} :,} <,~ /,~ dp0node,class_name,class_value,contents,max_noise,noise
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,++ b/README.md,0.725794,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,"1,23 @@",0.725794,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,This plugin downloads/installs Node and NPM lo...,0.725794,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,"It's supposed to work on Windows, OS X and Linux.",0.725794,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,NaN,0.725794,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,++ b/frontend-maven-plugin/src/main/java/com/g...,4.420658,0
4990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,},4.420658,0
4991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,"39,6 @@ public final class BowerMojo extends A...",5.420658,0
4992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,this.additionalEnvironment = additiona...,5.420658,0
4993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,++ b/frontend-plugin-core/src/main/java/com/gi...,8.925107,0

In [8]:
s = sss.sort_values(by='max_noise', ascending = False)
s = s.drop_duplicates(subset = 'max_noise')

values = []
for x in s['max_noise'].iloc[0:10]:
    values.append(x)

In [9]:
# noise_sorted = curated_bow.sort_values(by='max_noise', ascending = False)
noise_sorted = curated_bow

for df in noise_sorted.index:
    for val in values:
        if noise_sorted['max_noise'][df] == val:
            noise_sorted.loc[df, 'noise'] = 1
#             noise_sorted['noise'][df] = 1
# noise_sorted.drop(noise_sorted[noise_sorted['max_noise'].isin(values) == True].index, axis = 0, inplace = True)
noise_sorted['noise'] = noise_sorted['noise'] // 1
noise_sorted = noise_sorted.reset_index()
noise_sorted = noise_sorted.drop('index', axis=1)
noise_sorted

,id,,.,a,if,return,throw,void,},!,...,} ',} :,} <,~ /,~ dp0node,class_name,class_value,contents,max_noise,noise
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,++ b/README.md,0.725794,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,"1,23 @@",0.725794,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,This plugin downloads/installs Node and NPM lo...,0.725794,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,"It's supposed to work on Windows, OS X and Linux.",0.725794,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,NaN,0.725794,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,++ b/frontend-maven-plugin/src/main/java/com/g...,4.420658,1
4990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,},4.420658,1
4991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,"39,6 @@ public final class BowerMojo extends A...",5.420658,1
4992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,this.additionalEnvironment = additiona...,5.420658,1
4993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,++ b/frontend-plugin-core/src/main/java/com/gi...,8.925107,1

In [10]:
noise_sorted.to_csv('attribute_noise_cleaned.csv')
noise_sorted

,id,,.,a,if,return,throw,void,},!,...,} ',} :,} <,~ /,~ dp0node,class_name,class_value,contents,max_noise,noise
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,++ b/README.md,0.725794,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,"1,23 @@",0.725794,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,This plugin downloads/installs Node and NPM lo...,0.725794,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,"It's supposed to work on Windows, OS X and Linux.",0.725794,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,NaN,0.725794,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,++ b/frontend-maven-plugin/src/main/java/com/g...,4.420658,1
4990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,},4.420658,1
4991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,"39,6 @@ public final class BowerMojo extends A...",5.420658,1
4992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,this.additionalEnvironment = additiona...,5.420658,1
4993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,++ b/frontend-plugin-core/src/main/java/com/gi...,8.925107,1

In [11]:
zeros = int(0)
ones = int(0)

for df in noise_sorted.index:
    if noise_sorted['noise'][df] == 0:
        zeros += 1
    elif noise_sorted['noise'][df] == 1:
        ones += 1

print('Zeros: ', zeros)
print('Ones: ', ones)

Zeros:  1061
Ones:  3933