In [1]:
import pandas as pd
import time
import numpy as np

In [2]:
# Import Dataset
curated_bow = pd.read_csv('FrontendMavenPlugin.csv', sep='$')
curated_bow.dropna()
# Remove Trailing Spaces in Column Names
curated_bow.columns = [col.strip() for col in curated_bow.columns]
curated_bow

,id,,,,.,a,if,return,throw,void,...,"} """,} ',} :,} <,~,~ /,~ dp0node,class_name,class_value,contents
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,++ b/README.md
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,"1,23 @@"
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,This plugin downloads/installs Node and NPM lo...
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,"It's supposed to work on Windows, OS X and Linux."
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,++ b/frontend-maven-plugin/src/main/java/com/g...
4990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,}
4991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,"39,6 @@ public final class BowerMojo extends A..."
4992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,this.additionalEnvironment = additiona...
4993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,++ b/frontend-plugin-core/src/main/java/com/gi...

In [3]:
# Duplicate Columns Removed
curated_bow = curated_bow.loc[:,~curated_bow.columns.duplicated()].copy()
curated_bow

,id,,.,a,if,return,throw,void,},!,...,| |,"} """,} ',} :,} <,~ /,~ dp0node,class_name,class_value,contents
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,++ b/README.md
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,"1,23 @@"
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,This plugin downloads/installs Node and NPM lo...
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,"It's supposed to work on Windows, OS X and Linux."
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,++ b/frontend-maven-plugin/src/main/java/com/g...
4990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,}
4991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,"39,6 @@ public final class BowerMojo extends A..."
4992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,this.additionalEnvironment = additiona...
4993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,++ b/frontend-plugin-core/src/main/java/com/gi...

In [4]:
partitions_ = 1
bin_size = len(curated_bow.index)//partitions_ 
print(bin_size)

4994

In [5]:
def run_Panda():
    bins_counter = 0
    partition_values = pd.DataFrame()
    j_col= pd.DataFrame()
#     k_col= pd.DataFrame()
    
#     for j in range(len(curated_bow.columns)-3): 
    for j in range(len(curated_bow.columns)-3):
        start_j = time.time()
        clustered_att = curated_bow.sort_values(by = curated_bow.columns[j])
        
        bins_counter = 0
#         if j != j:
        for y in range(partitions_): 
            parition_mean = clustered_att.iloc[bins_counter: bins_counter + bin_size, j].values.mean()
            partition_sd = clustered_att.iloc[bins_counter: bins_counter + bin_size, j].values.std()
            mean_over_sd = parition_mean/partition_sd if partition_sd else 0

            noise_score = pd.DataFrame([np.nan_to_num(abs(x - (mean_over_sd)))
                                        for x in clustered_att.iloc[bins_counter:bins_counter + bin_size, j]])

            partition_values = pd.concat([partition_values, noise_score], axis=0)
                    
            #dropping existing indices with the same name and replacing them with new, using reset index
            partition_values= partition_values.reset_index(drop=True) 
            bins_counter = bins_counter + bin_size
#         else:
#             continue
            
        j_col= pd.concat([j_col, partition_values], axis= 1)
        partition_values.drop(partition_values.index, inplace=True)
        
        end_j = time.time()
        print("column j: " + str(j))
        print(f"Runtime of the program for j {end_j - start_j}")
        
    return j_col

In [6]:
sss = run_Panda()
sss['max_noise'] = sss.max(axis=1)

column j: 0
Runtime of the program for j 0.16278314590454102
column j: 1
Runtime of the program for j 0.1713719367980957
column j: 2
Runtime of the program for j 0.1620934009552002
column j: 3
Runtime of the program for j 0.14696288108825684
column j: 4
Runtime of the program for j 0.17113137245178223
column j: 5
Runtime of the program for j 0.17581415176391602
column j: 6
Runtime of the program for j 0.15995192527770996
column j: 7
Runtime of the program for j 0.14999103546142578
column j: 8
Runtime of the program for j 0.1654679775238037
column j: 9
Runtime of the program for j 0.1566143035888672
column j: 10
Runtime of the program for j 0.18081212043762207
column j: 11
Runtime of the program for j 0.09018540382385254
column j: 12
Runtime of the program for j 0.15358924865722656
column j: 13
Runtime of the program for j 0.1894843578338623
column j: 14
Runtime of the program for j 0.1305253505706787
column j: 15
Runtime of the program for j 0.1746821403503418
column j: 16
Runtime of the program for j 0.1801910400390625
column j: 17
Runtime of the program for j 0.17484688758850098
column j: 18
Runtime of the program for j 0.176436185836792
column j: 19
Runtime of the program for j 0.1736125946044922
column j: 20
Runtime of the program for j 0.1847238540649414
column j: 21
Runtime of the program for j 0.16014504432678223
column j: 22
Runtime of the program for j 0.24040794372558594
column j: 23
Runtime of the program for j 0.3497347831726074
column j: 24
Runtime of the program for j 0.34989142417907715
column j: 25
Runtime of the program for j 0.3431277275085449
column j: 26
Runtime of the program for j 0.349653959274292
column j: 27
Runtime of the program for j 0.33948802947998047
column j: 28
Runtime of the program for j 0.362363338470459
column j: 29
Runtime of the program for j 0.3707869052886963
column j: 30
Runtime of the program for j 0.3560450077056885
column j: 31
Runtime of the program for j 0.34548163414001465
column j: 32
Runtime of the program for j 0.3633239269256592
column j: 33
Runtime of the program for j 0.3565030097961426
column j: 34
Runtime of the program for j 0.35369253158569336
column j: 35
Runtime of the program for j 0.1812877655029297
column j: 36
Runtime of the program for j 0.40167856216430664
column j: 37
Runtime of the program for j 0.3509371280670166
column j: 38
Runtime of the program for j 0.33885645866394043
column j: 39
Runtime of the program for j 0.19731831550598145
column j: 40
Runtime of the program for j 0.3555593490600586
column j: 41
Runtime of the program for j 0.3444797992706299
column j: 42
Runtime of the program for j 0.3521275520324707
column j: 43
Runtime of the program for j 0.3597424030303955
column j: 44
Runtime of the program for j 0.353604793548584
column j: 45
Runtime of the program for j 0.35338497161865234
column j: 46
Runtime of the program for j 0.3502309322357178
column j: 47
Runtime of the program for j 0.1885688304901123
column j: 48
Runtime of the program for j 0.19139981269836426
column j: 49
Runtime of the program for j 0.30469250679016113
column j: 50
Runtime of the program for j 0.3517448902130127
column j: 51
Runtime of the program for j 0.3833291530609131
column j: 52
Runtime of the program for j 0.3897104263305664
column j: 53
Runtime of the program for j 0.3503749370574951
column j: 54
Runtime of the program for j 0.421720027923584
column j: 55
Runtime of the program for j 0.3680903911590576
column j: 56
Runtime of the program for j 0.43546223640441895
column j: 57
Runtime of the program for j 0.19594883918762207
column j: 58
Runtime of the program for j 0.3802297115325928
column j: 59
Runtime of the program for j 0.3648848533630371
column j: 60
Runtime of the program for j 0.36015915870666504
column j: 61
Runtime of the program for j 0.3534698486328125
column j: 62
Runtime of the program for j 0.35654211044311523
column j: 63
Runtime of the program for j 0.35146093368530273
column j: 64
Runtime of the program for j 0.1895580291748047
column j: 65
Runtime of the program for j 0.3533039093017578
column j: 66
Runtime of the program for j 0.37985897064208984
column j: 67
Runtime of the program for j 0.37124180793762207
column j: 68
Runtime of the program for j 0.19427967071533203
column j: 69
Runtime of the program for j 0.35558080673217773
column j: 70
Runtime of the program for j 0.37053823471069336
column j: 71
Runtime of the program for j 0.36945128440856934
column j: 72
Runtime of the program for j 0.35335373878479004
column j: 73
Runtime of the program for j 0.35558557510375977
column j: 74
Runtime of the program for j 0.3543429374694824
column j: 75
Runtime of the program for j 0.34961986541748047
column j: 76
Runtime of the program for j 0.39047980308532715
column j: 77
Runtime of the program for j 0.20343279838562012
column j: 78
Runtime of the program for j 0.18996024131774902
column j: 79
Runtime of the program for j 0.39431190490722656
column j: 80
Runtime of the program for j 0.33571672439575195
column j: 81
Runtime of the program for j 0.34303879737854004
column j: 82
Runtime of the program for j 0.3484230041503906
column j: 83
Runtime of the program for j 0.38997387886047363
column j: 84
Runtime of the program for j 0.3679184913635254
column j: 85
Runtime of the program for j 0.3886992931365967
column j: 86
Runtime of the program for j 0.36612796783447266
column j: 87
Runtime of the program for j 0.3899857997894287
column j: 88
Runtime of the program for j 0.36699461936950684
column j: 89
Runtime of the program for j 0.39784693717956543
column j: 90
Runtime of the program for j 0.3723890781402588
column j: 91
Runtime of the program for j 0.3570089340209961
column j: 92
Runtime of the program for j 0.35431838035583496
column j: 93
Runtime of the program for j 0.32811760902404785
column j: 94
Runtime of the program for j 0.31038832664489746
column j: 95
Runtime of the program for j 0.3345036506652832
column j: 96
Runtime of the program for j 0.3301575183868408
column j: 97
Runtime of the program for j 0.3698897361755371
column j: 98
Runtime of the program for j 0.3604600429534912
column j: 99
Runtime of the program for j 0.38177967071533203
column j: 100
Runtime of the program for j 0.37000489234924316
column j: 101
Runtime of the program for j 0.36998987197875977
column j: 102
Runtime of the program for j 0.38191771507263184
column j: 103
Runtime of the program for j 0.3911130428314209
column j: 104
Runtime of the program for j 0.36669158935546875
column j: 105
Runtime of the program for j 0.3317902088165283
column j: 106
Runtime of the program for j 0.3118917942047119
column j: 107
Runtime of the program for j 0.3426971435546875
column j: 108
Runtime of the program for j 0.36017346382141113
column j: 109
Runtime of the program for j 0.18985700607299805
column j: 110
Runtime of the program for j 0.36124467849731445
column j: 111
Runtime of the program for j 0.3515591621398926
column j: 112
Runtime of the program for j 0.3685762882232666
column j: 113
Runtime of the program for j 0.363067626953125
column j: 114
Runtime of the program for j 0.19867444038391113
column j: 115
Runtime of the program for j 0.36054277420043945
column j: 116
Runtime of the program for j 0.366178035736084
column j: 117
Runtime of the program for j 0.3631398677825928
column j: 118
Runtime of the program for j 0.3605663776397705
column j: 119
Runtime of the program for j 0.3561737537384033
column j: 120
Runtime of the program for j 0.36649489402770996
column j: 121
Runtime of the program for j 0.36411404609680176
column j: 122
Runtime of the program for j 0.3193092346191406
column j: 123
Runtime of the program for j 0.32763051986694336
column j: 124
Runtime of the program for j 0.3688647747039795
column j: 125
Runtime of the program for j 0.34967970848083496
column j: 126
Runtime of the program for j 0.34318017959594727
column j: 127
Runtime of the program for j 0.32824015617370605
column j: 128
Runtime of the program for j 0.3524436950683594
column j: 129
Runtime of the program for j 0.3243675231933594
column j: 130
Runtime of the program for j 0.3797316551208496
column j: 131
Runtime of the program for j 0.20296311378479004
column j: 132
Runtime of the program for j 0.36705470085144043

column j: 133
Runtime of the program for j 0.39057111740112305
column j: 134
Runtime of the program for j 0.35207343101501465
column j: 135
Runtime of the program for j 0.33548426628112793
column j: 136
Runtime of the program for j 0.30212950706481934
column j: 137
Runtime of the program for j 0.3095219135284424
column j: 138
Runtime of the program for j 0.34881162643432617
column j: 139
Runtime of the program for j 0.3259620666503906
column j: 140
Runtime of the program for j 0.3340756893157959
column j: 141
Runtime of the program for j 0.36098289489746094
column j: 142
Runtime of the program for j 0.3599863052368164
column j: 143
Runtime of the program for j 0.3650553226470947
column j: 144
Runtime of the program for j 0.36502528190612793
column j: 145
Runtime of the program for j 0.395174503326416
column j: 146
Runtime of the program for j 0.39392924308776855
column j: 147
Runtime of the program for j 0.37966370582580566
column j: 148
Runtime of the program for j 0.36065125465393066
column j: 149
Runtime of the program for j 0.32925987243652344
column j: 150
Runtime of the program for j 0.18031001091003418
column j: 151
Runtime of the program for j 0.379763126373291
column j: 152
Runtime of the program for j 0.29143333435058594
column j: 153
Runtime of the program for j 0.34137487411499023
column j: 154
Runtime of the program for j 0.3787107467651367
column j: 155
Runtime of the program for j 0.37859582901000977
column j: 156
Runtime of the program for j 0.3521251678466797
column j: 157
Runtime of the program for j 0.37507128715515137
column j: 158
Runtime of the program for j 0.3175315856933594
column j: 159
Runtime of the program for j 0.36646604537963867
column j: 160
Runtime of the program for j 0.357039213180542
column j: 161
Runtime of the program for j 0.3400721549987793
column j: 162
Runtime of the program for j 0.36005687713623047
column j: 163
Runtime of the program for j 0.21012425422668457
column j: 164
Runtime of the program for j 0.3998703956604004
column j: 165
Runtime of the program for j 0.41571950912475586
column j: 166
Runtime of the program for j 0.33538365364074707
column j: 167
Runtime of the program for j 0.36072421073913574
column j: 168
Runtime of the program for j 0.1978611946105957
column j: 169
Runtime of the program for j 0.3105790615081787
column j: 170
Runtime of the program for j 0.32988452911376953
column j: 171
Runtime of the program for j 0.34986114501953125
column j: 172
Runtime of the program for j 0.3514542579650879
column j: 173
Runtime of the program for j 0.3786168098449707
column j: 174
Runtime of the program for j 0.37996459007263184
column j: 175
Runtime of the program for j 0.3865852355957031
column j: 176
Runtime of the program for j 0.3550577163696289
column j: 177
Runtime of the program for j 0.3950371742248535
column j: 178
Runtime of the program for j 0.3612711429595947
column j: 179
Runtime of the program for j 0.3690013885498047
column j: 180
Runtime of the program for j 0.38108277320861816
column j: 181
Runtime of the program for j 0.37995266914367676
column j: 182
Runtime of the program for j 0.39499640464782715
column j: 183
Runtime of the program for j 0.3648204803466797
column j: 184
Runtime of the program for j 0.3560774326324463
column j: 185
Runtime of the program for j 0.3568539619445801
column j: 186
Runtime of the program for j 0.3390994071960449
column j: 187
Runtime of the program for j 0.36986303329467773
column j: 188
Runtime of the program for j 0.1921541690826416
column j: 189
Runtime of the program for j 0.3686356544494629
column j: 190
Runtime of the program for j 0.35925912857055664
column j: 191
Runtime of the program for j 0.3604438304901123
column j: 192
Runtime of the program for j 0.36953115463256836
column j: 193
Runtime of the program for j 0.3599376678466797
column j: 194
Runtime of the program for j 0.3616294860839844
column j: 195
Runtime of the program for j 0.32837986946105957
column j: 196
Runtime of the program for j 0.3397941589355469
column j: 197
Runtime of the program for j 0.36037659645080566
column j: 198
Runtime of the program for j 0.36372876167297363
column j: 199
Runtime of the program for j 0.35688185691833496
column j: 200
Runtime of the program for j 0.36595654487609863
column j: 201
Runtime of the program for j 0.35323452949523926
column j: 202
Runtime of the program for j 0.36148738861083984
column j: 203
Runtime of the program for j 0.35857105255126953
column j: 204
Runtime of the program for j 0.2000882625579834
column j: 205
Runtime of the program for j 0.376359224319458
column j: 206
Runtime of the program for j 0.3698122501373291
column j: 207
Runtime of the program for j 0.3723564147949219
column j: 208
Runtime of the program for j 0.362396240234375
column j: 209
Runtime of the program for j 0.5544202327728271
column j: 210
Runtime of the program for j 0.3753964900970459
column j: 211
Runtime of the program for j 0.35956549644470215
column j: 212
Runtime of the program for j 0.34174275398254395
column j: 213
Runtime of the program for j 0.35001063346862793
column j: 214
Runtime of the program for j 0.3634212017059326
column j: 215
Runtime of the program for j 0.3747999668121338
column j: 216
Runtime of the program for j 0.367046594619751
column j: 217
Runtime of the program for j 0.34524965286254883
column j: 218
Runtime of the program for j 0.34510350227355957
column j: 219
Runtime of the program for j 0.37005090713500977
column j: 220
Runtime of the program for j 0.340167760848999
column j: 221
Runtime of the program for j 0.3499128818511963
column j: 222
Runtime of the program for j 0.3656768798828125
column j: 223
Runtime of the program for j 0.3659501075744629
column j: 224
Runtime of the program for j 0.3582441806793213
column j: 225
Runtime of the program for j 0.36461734771728516
column j: 226
Runtime of the program for j 0.36023902893066406
column j: 227
Runtime of the program for j 0.39505553245544434
column j: 228
Runtime of the program for j 0.3875892162322998
column j: 229
Runtime of the program for j 0.3773360252380371
column j: 230
Runtime of the program for j 0.4199411869049072
column j: 231
Runtime of the program for j 0.357105016708374
column j: 232
Runtime of the program for j 0.3802516460418701
column j: 233
Runtime of the program for j 0.3610363006591797
column j: 234
Runtime of the program for j 0.3932640552520752
column j: 235
Runtime of the program for j 0.20703721046447754
column j: 236
Runtime of the program for j 0.38539671897888184
column j: 237
Runtime of the program for j 0.39766716957092285
column j: 238
Runtime of the program for j 0.38686513900756836
column j: 239
Runtime of the program for j 0.3833773136138916
column j: 240
Runtime of the program for j 0.3929901123046875
column j: 241
Runtime of the program for j 0.40187835693359375
column j: 242
Runtime of the program for j 0.39315271377563477
column j: 243
Runtime of the program for j 0.3685038089752197
column j: 244
Runtime of the program for j 0.3705940246582031
column j: 245
Runtime of the program for j 0.18796682357788086
column j: 246
Runtime of the program for j 0.33184337615966797
column j: 247
Runtime of the program for j 0.3188509941101074
column j: 248
Runtime of the program for j 0.3569498062133789
column j: 249
Runtime of the program for j 0.37320995330810547
column j: 250
Runtime of the program for j 0.3699522018432617
column j: 251
Runtime of the program for j 0.32695960998535156
column j: 252
Runtime of the program for j 0.3701894283294678
column j: 253
Runtime of the program for j 0.37105894088745117
column j: 254
Runtime of the program for j 0.351193904876709
column j: 255
Runtime of the program for j 0.3614470958709717
column j: 256
Runtime of the program for j 0.3627908229827881
column j: 257
Runtime of the program for j 0.38051366806030273
column j: 258
Runtime of the program for j 0.3497812747955322
column j: 259
Runtime of the program for j 0.3453497886657715
column j: 260
Runtime of the program for j 0.3546280860900879
column j: 261
Runtime of the program for j 0.34007811546325684
column j: 262
Runtime of the program for j 0.36293983459472656
column j: 263
Runtime of the program for j 0.19997453689575195
column j: 264
Runtime of the program for j 0.3169422149658203

column j: 265
Runtime of the program for j 0.3463912010192871
column j: 266
Runtime of the program for j 0.36688923835754395
column j: 267
Runtime of the program for j 0.37497806549072266
column j: 268
Runtime of the program for j 0.3659646511077881
column j: 269
Runtime of the program for j 0.3760542869567871
column j: 270
Runtime of the program for j 0.18833303451538086
column j: 271
Runtime of the program for j 0.3641023635864258
column j: 272
Runtime of the program for j 0.36057043075561523
column j: 273
Runtime of the program for j 0.35526418685913086
column j: 274
Runtime of the program for j 0.37856388092041016
column j: 275
Runtime of the program for j 0.1993255615234375
column j: 276
Runtime of the program for j 0.3783125877380371
column j: 277
Runtime of the program for j 0.42734789848327637
column j: 278
Runtime of the program for j 0.3654956817626953
column j: 279
Runtime of the program for j 0.37013959884643555
column j: 280
Runtime of the program for j 0.3523366451263428
column j: 281
Runtime of the program for j 0.3674290180206299
column j: 282
Runtime of the program for j 0.3600773811340332
column j: 283
Runtime of the program for j 0.36614012718200684
column j: 284
Runtime of the program for j 0.36017870903015137
column j: 285
Runtime of the program for j 0.36009645462036133
column j: 286
Runtime of the program for j 0.35962343215942383
column j: 287
Runtime of the program for j 0.3809220790863037
column j: 288
Runtime of the program for j 0.35915279388427734
column j: 289
Runtime of the program for j 0.38984084129333496
column j: 290
Runtime of the program for j 0.3602113723754883
column j: 291
Runtime of the program for j 0.375091552734375
column j: 292
Runtime of the program for j 0.3370537757873535
column j: 293
Runtime of the program for j 0.3664264678955078
column j: 294
Runtime of the program for j 0.3731682300567627
column j: 295
Runtime of the program for j 0.35367774963378906
column j: 296
Runtime of the program for j 0.3563873767852783
column j: 297
Runtime of the program for j 0.3668513298034668
column j: 298
Runtime of the program for j 0.36129093170166016
column j: 299
Runtime of the program for j 0.34871387481689453
column j: 300
Runtime of the program for j 0.371610164642334
column j: 301
Runtime of the program for j 0.3485074043273926
column j: 302
Runtime of the program for j 0.3626883029937744
column j: 303
Runtime of the program for j 0.34979867935180664
column j: 304
Runtime of the program for j 0.3723585605621338
column j: 305
Runtime of the program for j 0.37514233589172363
column j: 306
Runtime of the program for j 0.3602938652038574
column j: 307
Runtime of the program for j 0.3347196578979492
column j: 308
Runtime of the program for j 0.3797445297241211
column j: 309
Runtime of the program for j 0.3710358142852783
column j: 310
Runtime of the program for j 0.3690676689147949
column j: 311
Runtime of the program for j 0.37198710441589355
column j: 312
Runtime of the program for j 0.35814833641052246
column j: 313
Runtime of the program for j 0.3761098384857178
column j: 314
Runtime of the program for j 0.19420456886291504
column j: 315
Runtime of the program for j 0.3645181655883789
column j: 316
Runtime of the program for j 0.36942243576049805
column j: 317
Runtime of the program for j 0.32732629776000977
column j: 318
Runtime of the program for j 0.32840514183044434
column j: 319
Runtime of the program for j 0.39089512825012207
column j: 320
Runtime of the program for j 0.3817932605743408
column j: 321
Runtime of the program for j 0.1899275779724121
column j: 322
Runtime of the program for j 0.3701932430267334
column j: 323
Runtime of the program for j 0.3594546318054199
column j: 324
Runtime of the program for j 0.36336517333984375
column j: 325
Runtime of the program for j 0.3643064498901367
column j: 326
Runtime of the program for j 0.37687206268310547
column j: 327
Runtime of the program for j 0.3665163516998291
column j: 328
Runtime of the program for j 0.3554039001464844
column j: 329
Runtime of the program for j 0.42961621284484863
column j: 330
Runtime of the program for j 0.35773682594299316
column j: 331
Runtime of the program for j 0.3795461654663086
column j: 332
Runtime of the program for j 0.3601820468902588
column j: 333
Runtime of the program for j 0.35988807678222656
column j: 334
Runtime of the program for j 0.3600006103515625
column j: 335
Runtime of the program for j 0.3603630065917969
column j: 336
Runtime of the program for j 0.3406236171722412
column j: 337
Runtime of the program for j 0.3626687526702881
column j: 338
Runtime of the program for j 0.3656628131866455
column j: 339
Runtime of the program for j 0.3725278377532959
column j: 340
Runtime of the program for j 0.3881208896636963
column j: 341
Runtime of the program for j 0.3601515293121338
column j: 342
Runtime of the program for j 0.3638443946838379
column j: 343
Runtime of the program for j 0.20780038833618164
column j: 344
Runtime of the program for j 0.3651900291442871
column j: 345
Runtime of the program for j 0.3623349666595459
column j: 346
Runtime of the program for j 0.3709988594055176
column j: 347
Runtime of the program for j 0.3567941188812256
column j: 348
Runtime of the program for j 0.3523750305175781
column j: 349
Runtime of the program for j 0.3499455451965332
column j: 350
Runtime of the program for j 0.37087011337280273
column j: 351
Runtime of the program for j 0.2116413116455078
column j: 352
Runtime of the program for j 0.36873364448547363
column j: 353
Runtime of the program for j 0.3824121952056885
column j: 354
Runtime of the program for j 0.35616469383239746
column j: 355
Runtime of the program for j 0.3716244697570801
column j: 356
Runtime of the program for j 0.35927343368530273
column j: 357
Runtime of the program for j 0.3500974178314209
column j: 358
Runtime of the program for j 0.37248849868774414
column j: 359
Runtime of the program for j 0.36737585067749023
column j: 360
Runtime of the program for j 0.20039629936218262
column j: 361
Runtime of the program for j 0.35500311851501465
column j: 362
Runtime of the program for j 0.37462854385375977
column j: 363
Runtime of the program for j 0.3700089454650879
column j: 364
Runtime of the program for j 0.3540971279144287
column j: 365
Runtime of the program for j 0.36611223220825195
column j: 366
Runtime of the program for j 0.38478779792785645
column j: 367
Runtime of the program for j 0.37701940536499023
column j: 368
Runtime of the program for j 0.3701016902923584
column j: 369
Runtime of the program for j 0.37997913360595703
column j: 370
Runtime of the program for j 0.3803238868713379
column j: 371
Runtime of the program for j 0.3706340789794922
column j: 372
Runtime of the program for j 0.37222909927368164
column j: 373
Runtime of the program for j 0.363353967666626
column j: 374
Runtime of the program for j 0.3750131130218506
column j: 375
Runtime of the program for j 0.3684971332550049
column j: 376
Runtime of the program for j 0.3727846145629883
column j: 377
Runtime of the program for j 0.3602256774902344
column j: 378
Runtime of the program for j 0.36998462677001953
column j: 379
Runtime of the program for j 0.3847973346710205
column j: 380
Runtime of the program for j 0.39986562728881836
column j: 381
Runtime of the program for j 0.390225887298584
column j: 382
Runtime of the program for j 0.3756887912750244
column j: 383
Runtime of the program for j 0.35901737213134766
column j: 384
Runtime of the program for j 0.3772714138031006
column j: 385
Runtime of the program for j 0.3706626892089844
column j: 386
Runtime of the program for j 0.3690314292907715
column j: 387
Runtime of the program for j 0.37697935104370117
column j: 388
Runtime of the program for j 0.3760569095611572
column j: 389
Runtime of the program for j 0.38457679748535156
column j: 390
Runtime of the program for j 0.388012170791626
column j: 391
Runtime of the program for j 0.38028836250305176
column j: 392
Runtime of the program for j 0.37005114555358887
column j: 393
Runtime of the program for j 0.20316600799560547
column j: 394
Runtime of the program for j 0.21657776832580566
column j: 395
Runtime of the program for j 0.392838716506958
column j: 396
Runtime of the program for j 0.38673830032348633

column j: 397
Runtime of the program for j 0.2052626609802246
column j: 398
Runtime of the program for j 0.3701143264770508
column j: 399
Runtime of the program for j 0.3798685073852539
column j: 400
Runtime of the program for j 0.44730448722839355
column j: 401
Runtime of the program for j 0.4339156150817871
column j: 402
Runtime of the program for j 0.3844795227050781
column j: 403
Runtime of the program for j 0.38714599609375
column j: 404
Runtime of the program for j 0.376950740814209
column j: 405
Runtime of the program for j 0.37532973289489746
column j: 406
Runtime of the program for j 0.3848245143890381
column j: 407
Runtime of the program for j 0.454148530960083
column j: 408
Runtime of the program for j 0.38111162185668945
column j: 409
Runtime of the program for j 0.39505577087402344
column j: 410
Runtime of the program for j 0.35708189010620117
column j: 411
Runtime of the program for j 0.37250304222106934
column j: 412
Runtime of the program for j 0.3789949417114258
column j: 413
Runtime of the program for j 0.3833029270172119
column j: 414
Runtime of the program for j 0.3879995346069336
column j: 415
Runtime of the program for j 0.37013959884643555
column j: 416
Runtime of the program for j 0.3898191452026367
column j: 417
Runtime of the program for j 0.3699681758880615
column j: 418
Runtime of the program for j 0.37442517280578613
column j: 419
Runtime of the program for j 0.36548328399658203
column j: 420
Runtime of the program for j 0.37001609802246094
column j: 421
Runtime of the program for j 0.35993099212646484
column j: 422
Runtime of the program for j 0.38300037384033203
column j: 423
Runtime of the program for j 0.35921597480773926
column j: 424
Runtime of the program for j 0.3789083957672119
column j: 425
Runtime of the program for j 0.36064910888671875
column j: 426
Runtime of the program for j 0.3684258460998535
column j: 427
Runtime of the program for j 0.37648916244506836
column j: 428
Runtime of the program for j 0.369354248046875
column j: 429
Runtime of the program for j 0.38130617141723633
column j: 430
Runtime of the program for j 0.21511387825012207
column j: 431
Runtime of the program for j 0.21499323844909668
column j: 432
Runtime of the program for j 0.20815801620483398
column j: 433
Runtime of the program for j 0.3801407814025879
column j: 434
Runtime of the program for j 0.38019633293151855
column j: 435
Runtime of the program for j 0.34624767303466797
column j: 436
Runtime of the program for j 0.3700270652770996
column j: 437
Runtime of the program for j 0.38982367515563965
column j: 438
Runtime of the program for j 0.22024011611938477
column j: 439
Runtime of the program for j 0.3900277614593506
column j: 440
Runtime of the program for j 0.39298462867736816
column j: 441
Runtime of the program for j 0.3970968723297119
column j: 442
Runtime of the program for j 0.37981295585632324
column j: 443
Runtime of the program for j 0.22023320198059082
column j: 444
Runtime of the program for j 0.3801126480102539
column j: 445
Runtime of the program for j 0.38100528717041016
column j: 446
Runtime of the program for j 0.3582026958465576
column j: 447
Runtime of the program for j 0.36501073837280273
column j: 448
Runtime of the program for j 0.3553147315979004
column j: 449
Runtime of the program for j 0.38623666763305664
column j: 450
Runtime of the program for j 0.38039708137512207
column j: 451
Runtime of the program for j 0.3898282051086426
column j: 452
Runtime of the program for j 0.3716466426849365
column j: 453
Runtime of the program for j 0.3842742443084717
column j: 454
Runtime of the program for j 0.3598051071166992
column j: 455
Runtime of the program for j 0.3754608631134033
column j: 456
Runtime of the program for j 0.3880748748779297
column j: 457
Runtime of the program for j 0.3717067241668701
column j: 458
Runtime of the program for j 0.3834950923919678
column j: 459
Runtime of the program for j 0.37986040115356445
column j: 460
Runtime of the program for j 0.3697938919067383
column j: 461
Runtime of the program for j 0.36844849586486816
column j: 462
Runtime of the program for j 0.34631848335266113
column j: 463
Runtime of the program for j 0.42120838165283203
column j: 464
Runtime of the program for j 0.3771979808807373
column j: 465
Runtime of the program for j 0.3722953796386719
column j: 466
Runtime of the program for j 0.38965559005737305
column j: 467
Runtime of the program for j 0.38978075981140137
column j: 468
Runtime of the program for j 0.392956018447876
column j: 469
Runtime of the program for j 0.38719916343688965
column j: 470
Runtime of the program for j 0.3997197151184082
column j: 471
Runtime of the program for j 0.40329742431640625
column j: 472
Runtime of the program for j 0.38706231117248535
column j: 473
Runtime of the program for j 0.21674299240112305
column j: 474
Runtime of the program for j 0.3892858028411865
column j: 475
Runtime of the program for j 0.38387417793273926
column j: 476
Runtime of the program for j 0.3836088180541992
column j: 477
Runtime of the program for j 0.3862416744232178
column j: 478
Runtime of the program for j 0.4101371765136719
column j: 479
Runtime of the program for j 0.38330554962158203
column j: 480
Runtime of the program for j 0.4020500183105469
column j: 481
Runtime of the program for j 0.40447402000427246
column j: 482
Runtime of the program for j 0.40322017669677734
column j: 483
Runtime of the program for j 0.3770124912261963
column j: 484
Runtime of the program for j 0.3909926414489746
column j: 485
Runtime of the program for j 0.39989566802978516
column j: 486
Runtime of the program for j 0.3886229991912842
column j: 487
Runtime of the program for j 0.3752129077911377
column j: 488
Runtime of the program for j 0.37990808486938477
column j: 489
Runtime of the program for j 0.39678525924682617
column j: 490
Runtime of the program for j 0.3884084224700928
column j: 491
Runtime of the program for j 0.3949732780456543
column j: 492
Runtime of the program for j 0.3812541961669922
column j: 493
Runtime of the program for j 0.3787424564361572
column j: 494
Runtime of the program for j 0.379955530166626
column j: 495
Runtime of the program for j 0.37989282608032227
column j: 496
Runtime of the program for j 0.36009931564331055
column j: 497
Runtime of the program for j 0.20092463493347168
column j: 498
Runtime of the program for j 0.36897778511047363
column j: 499
Runtime of the program for j 0.3944668769836426
column j: 500
Runtime of the program for j 0.37470579147338867
column j: 501
Runtime of the program for j 0.379697322845459
column j: 502
Runtime of the program for j 0.22032928466796875
column j: 503
Runtime of the program for j 0.37981700897216797
column j: 504
Runtime of the program for j 0.3773684501647949
column j: 505
Runtime of the program for j 0.3723139762878418
column j: 506
Runtime of the program for j 0.3875279426574707
column j: 507
Runtime of the program for j 0.45249319076538086
column j: 508
Runtime of the program for j 0.3800935745239258
column j: 509
Runtime of the program for j 0.3602316379547119
column j: 510
Runtime of the program for j 0.3597414493560791
column j: 511
Runtime of the program for j 0.36660027503967285
column j: 512
Runtime of the program for j 0.3851141929626465
column j: 513
Runtime of the program for j 0.37961316108703613
column j: 514
Runtime of the program for j 0.393524169921875
column j: 515
Runtime of the program for j 0.2153301239013672
column j: 516
Runtime of the program for j 0.37968921661376953
column j: 517
Runtime of the program for j 0.3917980194091797
column j: 518
Runtime of the program for j 0.3933558464050293
column j: 519
Runtime of the program for j 0.38126063346862793
column j: 520
Runtime of the program for j 0.384868860244751
column j: 521
Runtime of the program for j 0.38579511642456055
column j: 522
Runtime of the program for j 0.38307833671569824
column j: 523
Runtime of the program for j 0.38985681533813477
column j: 524
Runtime of the program for j 0.3850698471069336
column j: 525
Runtime of the program for j 0.21670985221862793
column j: 526
Runtime of the program for j 0.3590259552001953
column j: 527
Runtime of the program for j 0.36433911323547363
column j: 528
Runtime of the program for j 0.384995698928833

column j: 529
Runtime of the program for j 0.37523794174194336
column j: 530
Runtime of the program for j 0.38479089736938477
column j: 531
Runtime of the program for j 0.3828868865966797
column j: 532
Runtime of the program for j 0.40204310417175293
column j: 533
Runtime of the program for j 0.4017481803894043
column j: 534
Runtime of the program for j 0.4098994731903076
column j: 535
Runtime of the program for j 0.22039294242858887
column j: 536
Runtime of the program for j 0.3838207721710205
column j: 537
Runtime of the program for j 0.3903794288635254
column j: 538
Runtime of the program for j 0.20660996437072754
column j: 539
Runtime of the program for j 0.21891283988952637
column j: 540
Runtime of the program for j 0.19998955726623535
column j: 541
Runtime of the program for j 0.32317423820495605
column j: 542
Runtime of the program for j 0.37683820724487305
column j: 543
Runtime of the program for j 0.40267348289489746
column j: 544
Runtime of the program for j 0.4029679298400879
column j: 545
Runtime of the program for j 0.4046041965484619
column j: 546
Runtime of the program for j 0.34035372734069824
column j: 547
Runtime of the program for j 0.3750143051147461
column j: 548
Runtime of the program for j 0.3600904941558838
column j: 549
Runtime of the program for j 0.41010236740112305
column j: 550
Runtime of the program for j 0.20810413360595703
column j: 551
Runtime of the program for j 0.25006914138793945
column j: 552
Runtime of the program for j 0.43709492683410645
column j: 553
Runtime of the program for j 0.38294506072998047
column j: 554
Runtime of the program for j 0.3607480525970459
column j: 555
Runtime of the program for j 0.40622901916503906
column j: 556
Runtime of the program for j 0.38610243797302246
column j: 557
Runtime of the program for j 0.3701446056365967
column j: 558
Runtime of the program for j 0.38393282890319824
column j: 559
Runtime of the program for j 0.4063684940338135
column j: 560
Runtime of the program for j 0.39426350593566895
column j: 561
Runtime of the program for j 0.4054257869720459
column j: 562
Runtime of the program for j 0.4600961208343506
column j: 563
Runtime of the program for j 0.44000816345214844
column j: 564
Runtime of the program for j 0.4602944850921631
column j: 565
Runtime of the program for j 0.39998388290405273
column j: 566
Runtime of the program for j 0.4194979667663574
column j: 567
Runtime of the program for j 0.4031636714935303
column j: 568
Runtime of the program for j 0.3885643482208252
column j: 569
Runtime of the program for j 0.39019131660461426
column j: 570
Runtime of the program for j 0.47855138778686523
column j: 571
Runtime of the program for j 0.2317671775817871
column j: 572
Runtime of the program for j 0.42000412940979004
column j: 573
Runtime of the program for j 0.401263952255249
column j: 574
Runtime of the program for j 0.3685317039489746
column j: 575
Runtime of the program for j 0.4001619815826416
column j: 576
Runtime of the program for j 0.40305662155151367
column j: 577
Runtime of the program for j 0.40714216232299805
column j: 578
Runtime of the program for j 0.40286874771118164
column j: 579
Runtime of the program for j 0.4083681106567383
column j: 580
Runtime of the program for j 0.4085252285003662
column j: 581
Runtime of the program for j 0.3921682834625244
column j: 582
Runtime of the program for j 0.4079282283782959
column j: 583
Runtime of the program for j 0.4101572036743164
column j: 584
Runtime of the program for j 0.39420199394226074
column j: 585
Runtime of the program for j 0.3753199577331543
column j: 586
Runtime of the program for j 0.4039463996887207
column j: 587
Runtime of the program for j 0.4062213897705078
column j: 588
Runtime of the program for j 0.36890721321105957
column j: 589
Runtime of the program for j 0.43982505798339844
column j: 590
Runtime of the program for j 0.4011859893798828
column j: 591
Runtime of the program for j 0.4203963279724121
column j: 592
Runtime of the program for j 0.42185497283935547
column j: 593
Runtime of the program for j 0.408236026763916
column j: 594
Runtime of the program for j 0.40161848068237305
column j: 595
Runtime of the program for j 0.2083432674407959
column j: 596
Runtime of the program for j 0.3968639373779297
column j: 597
Runtime of the program for j 0.4099149703979492
column j: 598
Runtime of the program for j 0.4201803207397461
column j: 599
Runtime of the program for j 0.4147224426269531
column j: 600
Runtime of the program for j 0.40598034858703613
column j: 601
Runtime of the program for j 0.23914289474487305
column j: 602
Runtime of the program for j 0.39980196952819824
column j: 603
Runtime of the program for j 0.446563720703125
column j: 604
Runtime of the program for j 0.3968532085418701
column j: 605
Runtime of the program for j 0.3966188430786133
column j: 606
Runtime of the program for j 0.40544891357421875
column j: 607
Runtime of the program for j 0.3965902328491211
column j: 608
Runtime of the program for j 0.4143412113189697
column j: 609
Runtime of the program for j 0.40547752380371094
column j: 610
Runtime of the program for j 0.4070131778717041
column j: 611
Runtime of the program for j 0.40876007080078125
column j: 612
Runtime of the program for j 0.39693498611450195
column j: 613
Runtime of the program for j 0.40743374824523926
column j: 614
Runtime of the program for j 0.4009370803833008
column j: 615
Runtime of the program for j 0.4182436466217041
column j: 616
Runtime of the program for j 0.4109830856323242
column j: 617
Runtime of the program for j 0.38672947883605957
column j: 618
Runtime of the program for j 0.40422892570495605
column j: 619
Runtime of the program for j 0.4049053192138672
column j: 620
Runtime of the program for j 0.3961038589477539
column j: 621
Runtime of the program for j 0.3939664363861084
column j: 622
Runtime of the program for j 0.4575376510620117
column j: 623
Runtime of the program for j 0.40973806381225586
column j: 624
Runtime of the program for j 0.40010809898376465
column j: 625
Runtime of the program for j 0.39273977279663086
column j: 626
Runtime of the program for j 0.4006814956665039
column j: 627
Runtime of the program for j 0.3951089382171631
column j: 628
Runtime of the program for j 0.40169310569763184
column j: 629
Runtime of the program for j 0.38840460777282715
column j: 630
Runtime of the program for j 0.4098069667816162
column j: 631
Runtime of the program for j 0.4031524658203125
column j: 632
Runtime of the program for j 0.37883663177490234
column j: 633
Runtime of the program for j 0.3588440418243408
column j: 634
Runtime of the program for j 0.4002549648284912
column j: 635
Runtime of the program for j 0.39968156814575195
column j: 636
Runtime of the program for j 0.39002108573913574
column j: 637
Runtime of the program for j 0.4042356014251709
column j: 638
Runtime of the program for j 0.3960294723510742
column j: 639
Runtime of the program for j 0.2319316864013672
column j: 640
Runtime of the program for j 0.4024350643157959
column j: 641
Runtime of the program for j 0.3954803943634033
column j: 642
Runtime of the program for j 0.4100322723388672
column j: 643
Runtime of the program for j 0.40065598487854004
column j: 644
Runtime of the program for j 0.40081214904785156
column j: 645
Runtime of the program for j 0.39012956619262695
column j: 646
Runtime of the program for j 0.4100968837738037
column j: 647
Runtime of the program for j 0.3898148536682129
column j: 648
Runtime of the program for j 0.41426610946655273
column j: 649
Runtime of the program for j 0.39179253578186035
column j: 650
Runtime of the program for j 0.4006059169769287
column j: 651
Runtime of the program for j 0.22312641143798828
column j: 652
Runtime of the program for j 0.3957822322845459
column j: 653
Runtime of the program for j 0.40345096588134766
column j: 654
Runtime of the program for j 0.38975048065185547
column j: 655
Runtime of the program for j 0.43691205978393555
column j: 656
Runtime of the program for j 0.4808037281036377
column j: 657
Runtime of the program for j 0.38925695419311523
column j: 658
Runtime of the program for j 0.40465545654296875
column j: 659
Runtime of the program for j 0.39396071434020996
column j: 660
Runtime of the program for j 0.38951826095581055

column j: 661
Runtime of the program for j 0.4102640151977539
column j: 662
Runtime of the program for j 0.400895357131958
column j: 663
Runtime of the program for j 0.4204576015472412
column j: 664
Runtime of the program for j 0.4086761474609375
column j: 665
Runtime of the program for j 0.40679430961608887
column j: 666
Runtime of the program for j 0.373288631439209
column j: 667
Runtime of the program for j 0.4046669006347656
column j: 668
Runtime of the program for j 0.4052436351776123
column j: 669
Runtime of the program for j 0.4112205505371094
column j: 670
Runtime of the program for j 0.39702773094177246
column j: 671
Runtime of the program for j 0.4051072597503662
column j: 672
Runtime of the program for j 0.39125585556030273
column j: 673
Runtime of the program for j 0.4031684398651123
column j: 674
Runtime of the program for j 0.40524768829345703
column j: 675
Runtime of the program for j 0.3999459743499756
column j: 676
Runtime of the program for j 0.41015052795410156
column j: 677
Runtime of the program for j 0.40049028396606445
column j: 678
Runtime of the program for j 0.39252161979675293
column j: 679
Runtime of the program for j 0.40306735038757324
column j: 680
Runtime of the program for j 0.387026309967041
column j: 681
Runtime of the program for j 0.2303156852722168
column j: 682
Runtime of the program for j 0.40525102615356445
column j: 683
Runtime of the program for j 0.412200927734375
column j: 684
Runtime of the program for j 0.39928555488586426
column j: 685
Runtime of the program for j 0.4001796245574951
column j: 686
Runtime of the program for j 0.401334285736084
column j: 687
Runtime of the program for j 0.391157865524292
column j: 688
Runtime of the program for j 0.4687929153442383
column j: 689
Runtime of the program for j 0.4000871181488037
column j: 690
Runtime of the program for j 0.3903651237487793
column j: 691
Runtime of the program for j 0.3951911926269531
column j: 692
Runtime of the program for j 0.40992307662963867
column j: 693
Runtime of the program for j 0.39961934089660645
column j: 694
Runtime of the program for j 0.4000730514526367
column j: 695
Runtime of the program for j 0.3903689384460449
column j: 696
Runtime of the program for j 0.39257216453552246
column j: 697
Runtime of the program for j 0.41017985343933105
column j: 698
Runtime of the program for j 0.40721702575683594
column j: 699
Runtime of the program for j 0.38990163803100586
column j: 700
Runtime of the program for j 0.416623592376709
column j: 701
Runtime of the program for j 0.4042365550994873
column j: 702
Runtime of the program for j 0.4037668704986572
column j: 703
Runtime of the program for j 0.3974475860595703
column j: 704
Runtime of the program for j 0.39773035049438477
column j: 705
Runtime of the program for j 0.41317296028137207
column j: 706
Runtime of the program for j 0.4136676788330078
column j: 707
Runtime of the program for j 0.4073619842529297
column j: 708
Runtime of the program for j 0.3989593982696533
column j: 709
Runtime of the program for j 0.40508079528808594
column j: 710
Runtime of the program for j 0.4757397174835205
column j: 711
Runtime of the program for j 0.3944697380065918
column j: 712
Runtime of the program for j 0.43687915802001953
column j: 713
Runtime of the program for j 0.39794063568115234
column j: 714
Runtime of the program for j 0.3798964023590088
column j: 715
Runtime of the program for j 0.3997769355773926
column j: 716
Runtime of the program for j 0.42034053802490234
column j: 717
Runtime of the program for j 0.420072078704834
column j: 718
Runtime of the program for j 0.4045844078063965
column j: 719
Runtime of the program for j 0.3951451778411865
column j: 720
Runtime of the program for j 0.43009066581726074
column j: 721
Runtime of the program for j 0.40938425064086914
column j: 722
Runtime of the program for j 0.42422056198120117
column j: 723
Runtime of the program for j 0.4246346950531006
column j: 724
Runtime of the program for j 0.4646739959716797
column j: 725
Runtime of the program for j 0.45789527893066406
column j: 726
Runtime of the program for j 0.40134215354919434
column j: 727
Runtime of the program for j 0.42619967460632324
column j: 728
Runtime of the program for j 0.43793201446533203
column j: 729
Runtime of the program for j 0.4259512424468994
column j: 730
Runtime of the program for j 0.469696044921875
column j: 731
Runtime of the program for j 0.4106607437133789
column j: 732
Runtime of the program for j 0.3594188690185547
column j: 733
Runtime of the program for j 0.4133942127227783
column j: 734
Runtime of the program for j 0.4928762912750244
column j: 735
Runtime of the program for j 0.41660046577453613
column j: 736
Runtime of the program for j 0.40720057487487793
column j: 737
Runtime of the program for j 0.4601292610168457
column j: 738
Runtime of the program for j 0.4255073070526123
column j: 739
Runtime of the program for j 0.424285888671875
column j: 740
Runtime of the program for j 0.4509611129760742
column j: 741
Runtime of the program for j 0.41088128089904785
column j: 742
Runtime of the program for j 0.244185209274292
column j: 743
Runtime of the program for j 0.37677526473999023
column j: 744
Runtime of the program for j 0.3884425163269043
column j: 745
Runtime of the program for j 0.40039849281311035
column j: 746
Runtime of the program for j 0.42118000984191895
column j: 747
Runtime of the program for j 0.4071919918060303
column j: 748
Runtime of the program for j 0.43979668617248535
column j: 749
Runtime of the program for j 0.4125096797943115
column j: 750
Runtime of the program for j 0.4076220989227295
column j: 751
Runtime of the program for j 0.403670072555542
column j: 752
Runtime of the program for j 0.42823219299316406
column j: 753
Runtime of the program for j 0.40967559814453125
column j: 754
Runtime of the program for j 0.3984670639038086
column j: 755
Runtime of the program for j 0.40019869804382324
column j: 756
Runtime of the program for j 0.4795372486114502
column j: 757
Runtime of the program for j 0.4202768802642822
column j: 758
Runtime of the program for j 0.4150214195251465
column j: 759
Runtime of the program for j 0.39514636993408203
column j: 760
Runtime of the program for j 0.41004228591918945
column j: 761
Runtime of the program for j 0.3979172706604004
column j: 762
Runtime of the program for j 0.4167146682739258
column j: 763
Runtime of the program for j 0.3999145030975342
column j: 764
Runtime of the program for j 0.3906693458557129
column j: 765
Runtime of the program for j 0.4007289409637451
column j: 766
Runtime of the program for j 0.23593449592590332
column j: 767
Runtime of the program for j 0.3991684913635254
column j: 768
Runtime of the program for j 0.24085521697998047
column j: 769
Runtime of the program for j 0.40404820442199707
column j: 770
Runtime of the program for j 0.397658109664917
column j: 771
Runtime of the program for j 0.3984217643737793
column j: 772
Runtime of the program for j 0.3986823558807373
column j: 773
Runtime of the program for j 0.4013364315032959
column j: 774
Runtime of the program for j 0.40384721755981445
column j: 775
Runtime of the program for j 0.41086530685424805
column j: 776
Runtime of the program for j 0.3958570957183838
column j: 777
Runtime of the program for j 0.42994165420532227
column j: 778
Runtime of the program for j 0.4932699203491211
column j: 779
Runtime of the program for j 0.3961312770843506
column j: 780
Runtime of the program for j 0.2396864891052246
column j: 781
Runtime of the program for j 0.4065670967102051
column j: 782
Runtime of the program for j 0.4004395008087158
column j: 783
Runtime of the program for j 0.3998286724090576
column j: 784
Runtime of the program for j 0.41001343727111816
column j: 785
Runtime of the program for j 0.4024665355682373
column j: 786
Runtime of the program for j 0.3888270854949951
column j: 787
Runtime of the program for j 0.4100503921508789
column j: 788
Runtime of the program for j 0.412891149520874
column j: 789
Runtime of the program for j 0.40014076232910156
column j: 790
Runtime of the program for j 0.38684654235839844
column j: 791
Runtime of the program for j 0.4035038948059082
column j: 792
Runtime of the program for j 0.40625882148742676

column j: 793
Runtime of the program for j 0.3969404697418213
column j: 794
Runtime of the program for j 0.40587949752807617
column j: 795
Runtime of the program for j 0.4073958396911621
column j: 796
Runtime of the program for j 0.4031867980957031
column j: 797
Runtime of the program for j 0.4737839698791504
column j: 798
Runtime of the program for j 0.3929555416107178
column j: 799
Runtime of the program for j 0.4000701904296875
column j: 800
Runtime of the program for j 0.39507579803466797
column j: 801
Runtime of the program for j 0.40506410598754883
column j: 802
Runtime of the program for j 0.410062313079834
column j: 803
Runtime of the program for j 0.4136629104614258
column j: 804
Runtime of the program for j 0.41072654724121094
column j: 805
Runtime of the program for j 0.4005849361419678
column j: 806
Runtime of the program for j 0.4134032726287842
column j: 807
Runtime of the program for j 0.4054677486419678
column j: 808
Runtime of the program for j 0.4101064205169678
column j: 809
Runtime of the program for j 0.40712404251098633
column j: 810
Runtime of the program for j 0.397625207901001
column j: 811
Runtime of the program for j 0.4167189598083496
column j: 812
Runtime of the program for j 0.40967464447021484
column j: 813
Runtime of the program for j 0.4003281593322754
column j: 814
Runtime of the program for j 0.40842342376708984
column j: 815
Runtime of the program for j 0.39270853996276855
column j: 816
Runtime of the program for j 0.497056245803833
column j: 817
Runtime of the program for j 0.40512537956237793
column j: 818
Runtime of the program for j 0.4251699447631836
column j: 819
Runtime of the program for j 0.4235091209411621
column j: 820
Runtime of the program for j 0.4166572093963623
column j: 821
Runtime of the program for j 0.4097898006439209
column j: 822
Runtime of the program for j 0.41318178176879883
column j: 823
Runtime of the program for j 0.4086892604827881
column j: 824
Runtime of the program for j 0.4148404598236084
column j: 825
Runtime of the program for j 0.4131927490234375
column j: 826
Runtime of the program for j 0.4176323413848877
column j: 827
Runtime of the program for j 0.39885473251342773
column j: 828
Runtime of the program for j 0.41805434226989746
column j: 829
Runtime of the program for j 0.4200601577758789
column j: 830
Runtime of the program for j 0.4098947048187256
column j: 831
Runtime of the program for j 0.40366172790527344
column j: 832
Runtime of the program for j 0.4165506362915039
column j: 833
Runtime of the program for j 0.37518310546875
column j: 834
Runtime of the program for j 0.4079933166503906
column j: 835
Runtime of the program for j 0.4864051342010498
column j: 836
Runtime of the program for j 0.40706467628479004
column j: 837
Runtime of the program for j 0.39987969398498535
column j: 838
Runtime of the program for j 0.41022229194641113
column j: 839
Runtime of the program for j 0.4019300937652588
column j: 840
Runtime of the program for j 0.40802860260009766
column j: 841
Runtime of the program for j 0.40007567405700684
column j: 842
Runtime of the program for j 0.39994168281555176
column j: 843
Runtime of the program for j 0.40496253967285156
column j: 844
Runtime of the program for j 0.41500186920166016
column j: 845
Runtime of the program for j 0.40013837814331055
column j: 846
Runtime of the program for j 0.4101424217224121
column j: 847
Runtime of the program for j 0.4118514060974121
column j: 848
Runtime of the program for j 0.4233832359313965
column j: 849
Runtime of the program for j 0.2549586296081543
column j: 850
Runtime of the program for j 0.4149343967437744
column j: 851
Runtime of the program for j 0.41623973846435547
column j: 852
Runtime of the program for j 0.4088273048400879
column j: 853
Runtime of the program for j 0.40494608879089355
column j: 854
Runtime of the program for j 0.4898219108581543
column j: 855
Runtime of the program for j 0.41645240783691406
column j: 856
Runtime of the program for j 0.4137389659881592
column j: 857
Runtime of the program for j 0.40991878509521484
column j: 858
Runtime of the program for j 0.4204139709472656
column j: 859
Runtime of the program for j 0.4092676639556885
column j: 860
Runtime of the program for j 0.39037084579467773
column j: 861
Runtime of the program for j 0.41467857360839844
column j: 862
Runtime of the program for j 0.4351162910461426
column j: 863
Runtime of the program for j 0.3928399085998535
column j: 864
Runtime of the program for j 0.3696589469909668
column j: 865
Runtime of the program for j 0.41879892349243164
column j: 866
Runtime of the program for j 0.38344812393188477
column j: 867
Runtime of the program for j 0.3634171485900879
column j: 868
Runtime of the program for j 0.39148998260498047
column j: 869
Runtime of the program for j 0.4055938720703125
column j: 870
Runtime of the program for j 0.39467930793762207
column j: 871
Runtime of the program for j 0.41481661796569824
column j: 872
Runtime of the program for j 0.40683794021606445
column j: 873
Runtime of the program for j 0.48874950408935547
column j: 874
Runtime of the program for j 0.40489792823791504
column j: 875
Runtime of the program for j 0.399669885635376
column j: 876
Runtime of the program for j 0.40543532371520996
column j: 877
Runtime of the program for j 0.39983463287353516
column j: 878
Runtime of the program for j 0.4047996997833252
column j: 879
Runtime of the program for j 0.40840744972229004
column j: 880
Runtime of the program for j 0.4079458713531494
column j: 881
Runtime of the program for j 0.4228370189666748
column j: 882
Runtime of the program for j 0.4304187297821045
column j: 883
Runtime of the program for j 0.43516063690185547
column j: 884
Runtime of the program for j 0.42305922508239746
column j: 885
Runtime of the program for j 0.42728757858276367
column j: 886
Runtime of the program for j 0.4318404197692871
column j: 887
Runtime of the program for j 0.254580020904541
column j: 888
Runtime of the program for j 0.42994022369384766
column j: 889
Runtime of the program for j 0.4298841953277588
column j: 890
Runtime of the program for j 0.5049076080322266
column j: 891
Runtime of the program for j 0.4303436279296875
column j: 892
Runtime of the program for j 0.4062771797180176
column j: 893
Runtime of the program for j 0.4234623908996582
column j: 894
Runtime of the program for j 0.42821478843688965
column j: 895
Runtime of the program for j 0.24781370162963867
column j: 896
Runtime of the program for j 0.419173002243042
column j: 897
Runtime of the program for j 0.426868200302124
column j: 898
Runtime of the program for j 0.42236757278442383
column j: 899
Runtime of the program for j 0.25396275520324707
column j: 900
Runtime of the program for j 0.4477424621582031
column j: 901
Runtime of the program for j 0.4210033416748047
column j: 902
Runtime of the program for j 0.4166736602783203
column j: 903
Runtime of the program for j 0.421292781829834
column j: 904
Runtime of the program for j 0.4121387004852295
column j: 905
Runtime of the program for j 0.40972137451171875
column j: 906
Runtime of the program for j 0.49030089378356934
column j: 907
Runtime of the program for j 0.4150102138519287
column j: 908
Runtime of the program for j 0.4250204563140869
column j: 909
Runtime of the program for j 0.4098522663116455
column j: 910
Runtime of the program for j 0.4066126346588135
column j: 911
Runtime of the program for j 0.43040943145751953
column j: 912
Runtime of the program for j 0.41962242126464844
column j: 913
Runtime of the program for j 0.40012621879577637
column j: 914
Runtime of the program for j 0.3943305015563965
column j: 915
Runtime of the program for j 0.42241883277893066
column j: 916
Runtime of the program for j 0.41880106925964355
column j: 917
Runtime of the program for j 0.41325974464416504
column j: 918
Runtime of the program for j 0.4100668430328369
column j: 919
Runtime of the program for j 0.41017794609069824
column j: 920
Runtime of the program for j 0.4159860610961914
column j: 921
Runtime of the program for j 0.4210648536682129
column j: 922
Runtime of the program for j 0.420243501663208
column j: 923
Runtime of the program for j 0.49994421005249023
column j: 924
Runtime of the program for j 0.4346446990966797

column j: 925
Runtime of the program for j 0.42525458335876465
column j: 926
Runtime of the program for j 0.42094850540161133
column j: 927
Runtime of the program for j 0.412045955657959
column j: 928
Runtime of the program for j 0.4270188808441162
column j: 929
Runtime of the program for j 0.37280964851379395
column j: 930
Runtime of the program for j 0.41940975189208984
column j: 931
Runtime of the program for j 0.4279646873474121
column j: 932
Runtime of the program for j 0.4110407829284668
column j: 933
Runtime of the program for j 0.25869202613830566
column j: 934
Runtime of the program for j 0.4251389503479004
column j: 935
Runtime of the program for j 0.41895389556884766
column j: 936
Runtime of the program for j 0.4060862064361572
column j: 937
Runtime of the program for j 0.4203379154205322
column j: 938
Runtime of the program for j 0.403644323348999
column j: 939
Runtime of the program for j 0.47480344772338867
column j: 940
Runtime of the program for j 0.42363762855529785
column j: 941
Runtime of the program for j 0.4146459102630615
column j: 942
Runtime of the program for j 0.40015411376953125
column j: 943
Runtime of the program for j 0.4116663932800293
column j: 944
Runtime of the program for j 0.4232189655303955
column j: 945
Runtime of the program for j 0.4300367832183838
column j: 946
Runtime of the program for j 0.4400334358215332
column j: 947
Runtime of the program for j 0.4178760051727295
column j: 948
Runtime of the program for j 0.4153721332550049
column j: 949
Runtime of the program for j 0.42109179496765137
column j: 950
Runtime of the program for j 0.4209730625152588
column j: 951
Runtime of the program for j 0.42270612716674805
column j: 952
Runtime of the program for j 0.39979124069213867
column j: 953
Runtime of the program for j 0.41312646865844727
column j: 954
Runtime of the program for j 0.41695356369018555
column j: 955
Runtime of the program for j 0.420396089553833
column j: 956
Runtime of the program for j 0.5016851425170898
column j: 957
Runtime of the program for j 0.4093499183654785
column j: 958
Runtime of the program for j 0.4209761619567871
column j: 959
Runtime of the program for j 0.44794368743896484
column j: 960
Runtime of the program for j 0.42835426330566406
column j: 961
Runtime of the program for j 0.43013906478881836
column j: 962
Runtime of the program for j 0.4242281913757324
column j: 963
Runtime of the program for j 0.40602946281433105
column j: 964
Runtime of the program for j 0.41397786140441895
column j: 965
Runtime of the program for j 0.42568016052246094
column j: 966
Runtime of the program for j 0.41037821769714355
column j: 967
Runtime of the program for j 0.40973973274230957
column j: 968
Runtime of the program for j 0.4116177558898926
column j: 969
Runtime of the program for j 0.448223352432251
column j: 970
Runtime of the program for j 0.4301574230194092
column j: 971
Runtime of the program for j 0.49015164375305176
column j: 972
Runtime of the program for j 0.40329694747924805
column j: 973
Runtime of the program for j 0.41152501106262207
column j: 974
Runtime of the program for j 0.42487263679504395
column j: 975
Runtime of the program for j 0.41504383087158203
column j: 976
Runtime of the program for j 0.41848301887512207
column j: 977
Runtime of the program for j 0.40311145782470703
column j: 978
Runtime of the program for j 0.4299139976501465
column j: 979
Runtime of the program for j 0.4114847183227539
column j: 980
Runtime of the program for j 0.4180927276611328
column j: 981
Runtime of the program for j 0.43039917945861816
column j: 982
Runtime of the program for j 0.4246177673339844
column j: 983
Runtime of the program for j 0.40495848655700684
column j: 984
Runtime of the program for j 0.43044066429138184
column j: 985
Runtime of the program for j 0.419905424118042
column j: 986
Runtime of the program for j 0.5114812850952148
column j: 987
Runtime of the program for j 0.4183778762817383
column j: 988
Runtime of the program for j 0.401317834854126
column j: 989
Runtime of the program for j 0.40860581398010254
column j: 990
Runtime of the program for j 0.4000685214996338
column j: 991
Runtime of the program for j 0.43982672691345215
column j: 992
Runtime of the program for j 0.43019962310791016
column j: 993
Runtime of the program for j 0.42972898483276367
column j: 994
Runtime of the program for j 0.4323391914367676
column j: 995
Runtime of the program for j 0.4195408821105957
column j: 996
Runtime of the program for j 0.41645383834838867
column j: 997
Runtime of the program for j 0.25337958335876465
column j: 998
Runtime of the program for j 0.4165034294128418
column j: 999
Runtime of the program for j 0.4167313575744629
column j: 1000
Runtime of the program for j 0.5245974063873291
column j: 1001
Runtime of the program for j 0.42519092559814453
column j: 1002
Runtime of the program for j 0.4303853511810303
column j: 1003
Runtime of the program for j 0.42279934883117676
column j: 1004
Runtime of the program for j 0.4349486827850342
column j: 1005
Runtime of the program for j 0.4353342056274414
column j: 1006
Runtime of the program for j 0.43143391609191895
column j: 1007
Runtime of the program for j 0.42652416229248047
column j: 1008
Runtime of the program for j 0.42659544944763184
column j: 1009
Runtime of the program for j 0.45032429695129395
column j: 1010
Runtime of the program for j 0.453533411026001
column j: 1011
Runtime of the program for j 0.506467342376709
column j: 1012
Runtime of the program for j 0.453143835067749
column j: 1013
Runtime of the program for j 0.47903013229370117
column j: 1014
Runtime of the program for j 0.4625992774963379
column j: 1015
Runtime of the program for j 0.5766243934631348
column j: 1016
Runtime of the program for j 0.373929500579834
column j: 1017
Runtime of the program for j 0.42979907989501953
column j: 1018
Runtime of the program for j 0.44310879707336426
column j: 1019
Runtime of the program for j 0.43799901008605957
column j: 1020
Runtime of the program for j 0.46883416175842285
column j: 1021
Runtime of the program for j 0.5201666355133057
column j: 1022
Runtime of the program for j 0.29999327659606934
column j: 1023
Runtime of the program for j 0.4210832118988037
column j: 1024
Runtime of the program for j 0.43648600578308105
column j: 1025
Runtime of the program for j 0.48809123039245605
column j: 1026
Runtime of the program for j 0.44121360778808594
column j: 1027
Runtime of the program for j 0.45015478134155273
column j: 1028
Runtime of the program for j 0.5004732608795166
column j: 1029
Runtime of the program for j 0.27773594856262207
column j: 1030
Runtime of the program for j 0.5402603149414062
column j: 1031
Runtime of the program for j 0.48995089530944824
column j: 1032
Runtime of the program for j 0.4884922504425049
column j: 1033
Runtime of the program for j 0.2597222328186035
column j: 1034
Runtime of the program for j 0.43027758598327637
column j: 1035
Runtime of the program for j 0.41626548767089844
column j: 1036
Runtime of the program for j 0.40515923500061035
column j: 1037
Runtime of the program for j 0.3750426769256592
column j: 1038
Runtime of the program for j 0.46825432777404785
column j: 1039
Runtime of the program for j 0.4072866439819336
column j: 1040
Runtime of the program for j 0.43865466117858887
column j: 1041
Runtime of the program for j 0.4782383441925049
column j: 1042
Runtime of the program for j 0.4825174808502197
column j: 1043
Runtime of the program for j 0.4463050365447998
column j: 1044
Runtime of the program for j 0.4320871829986572
column j: 1045
Runtime of the program for j 0.5021538734436035
column j: 1046
Runtime of the program for j 0.5030467510223389
column j: 1047
Runtime of the program for j 0.42223572731018066
column j: 1048
Runtime of the program for j 0.43094778060913086
column j: 1049
Runtime of the program for j 0.42601871490478516
column j: 1050
Runtime of the program for j 0.4248523712158203
column j: 1051
Runtime of the program for j 0.4745311737060547
column j: 1052
Runtime of the program for j 0.4184277057647705
column j: 1053
Runtime of the program for j 0.4383823871612549
column j: 1054
Runtime of the program for j 0.43973875045776367
column j: 1055
Runtime of the program for j 0.42824292182922363

column j: 1056
Runtime of the program for j 0.42028236389160156
column j: 1057
Runtime of the program for j 0.4068446159362793
column j: 1058
Runtime of the program for j 0.5106146335601807
column j: 1059
Runtime of the program for j 0.42596960067749023
column j: 1060
Runtime of the program for j 0.40400195121765137
column j: 1061
Runtime of the program for j 0.42656588554382324
column j: 1062
Runtime of the program for j 0.4300510883331299
column j: 1063
Runtime of the program for j 0.4300081729888916
column j: 1064
Runtime of the program for j 0.48007917404174805
column j: 1065
Runtime of the program for j 0.42981982231140137
column j: 1066
Runtime of the program for j 0.4298422336578369
column j: 1067
Runtime of the program for j 0.30710482597351074
column j: 1068
Runtime of the program for j 0.457705020904541
column j: 1069
Runtime of the program for j 0.433551549911499
column j: 1070
Runtime of the program for j 0.43158960342407227
column j: 1071
Runtime of the program for j 0.5064492225646973
column j: 1072
Runtime of the program for j 0.27351808547973633
column j: 1073
Runtime of the program for j 0.4302701950073242
column j: 1074
Runtime of the program for j 0.4327976703643799
column j: 1075
Runtime of the program for j 0.4680922031402588
column j: 1076
Runtime of the program for j 0.45169615745544434
column j: 1077
Runtime of the program for j 0.42809462547302246
column j: 1078
Runtime of the program for j 0.42404603958129883
column j: 1079
Runtime of the program for j 0.37463998794555664
column j: 1080
Runtime of the program for j 0.4824497699737549
column j: 1081
Runtime of the program for j 0.4176943302154541
column j: 1082
Runtime of the program for j 0.4229719638824463
column j: 1083
Runtime of the program for j 0.4269378185272217
column j: 1084
Runtime of the program for j 0.43018674850463867
column j: 1085
Runtime of the program for j 0.523078441619873
column j: 1086
Runtime of the program for j 0.44697117805480957
column j: 1087
Runtime of the program for j 0.4400010108947754
column j: 1088
Runtime of the program for j 0.42838335037231445
column j: 1089
Runtime of the program for j 0.43678879737854004
column j: 1090
Runtime of the program for j 0.41773009300231934
column j: 1091
Runtime of the program for j 0.4176974296569824
column j: 1092
Runtime of the program for j 0.41933655738830566
column j: 1093
Runtime of the program for j 0.456571102142334
column j: 1094
Runtime of the program for j 0.4301779270172119
column j: 1095
Runtime of the program for j 0.4314994812011719
column j: 1096
Runtime of the program for j 0.433948278427124
column j: 1097
Runtime of the program for j 0.42659592628479004
column j: 1098
Runtime of the program for j 0.5019497871398926
column j: 1099
Runtime of the program for j 0.4357421398162842
column j: 1100
Runtime of the program for j 0.4350755214691162
column j: 1101
Runtime of the program for j 0.4341275691986084
column j: 1102
Runtime of the program for j 0.4113311767578125
column j: 1103
Runtime of the program for j 0.4385645389556885
column j: 1104
Runtime of the program for j 0.4315652847290039
column j: 1105
Runtime of the program for j 0.4383125305175781
column j: 1106
Runtime of the program for j 0.4404122829437256
column j: 1107
Runtime of the program for j 0.41977381706237793
column j: 1108
Runtime of the program for j 0.4264068603515625
column j: 1109
Runtime of the program for j 0.41358160972595215
column j: 1110
Runtime of the program for j 0.4282867908477783
column j: 1111
Runtime of the program for j 0.4986693859100342
column j: 1112
Runtime of the program for j 0.4443521499633789
column j: 1113
Runtime of the program for j 0.41985201835632324
column j: 1114
Runtime of the program for j 0.4371211528778076
column j: 1115
Runtime of the program for j 0.42867565155029297
column j: 1116
Runtime of the program for j 0.41930365562438965
column j: 1117
Runtime of the program for j 0.432697057723999
column j: 1118
Runtime of the program for j 0.4279913902282715
column j: 1119
Runtime of the program for j 0.42707300186157227
column j: 1120
Runtime of the program for j 0.4198720455169678
column j: 1121
Runtime of the program for j 0.43004465103149414
column j: 1122
Runtime of the program for j 0.4186241626739502
column j: 1123
Runtime of the program for j 0.43142127990722656
column j: 1124
Runtime of the program for j 0.4418187141418457
column j: 1125
Runtime of the program for j 0.5281109809875488
column j: 1126
Runtime of the program for j 0.43455076217651367
column j: 1127
Runtime of the program for j 0.43470001220703125
column j: 1128
Runtime of the program for j 0.4371602535247803
column j: 1129
Runtime of the program for j 0.42857885360717773
column j: 1130
Runtime of the program for j 0.4235985279083252
column j: 1131
Runtime of the program for j 0.42566561698913574
column j: 1132
Runtime of the program for j 0.3946981430053711
column j: 1133
Runtime of the program for j 0.4318418502807617
column j: 1134
Runtime of the program for j 0.44759249687194824
column j: 1135
Runtime of the program for j 0.4334738254547119
column j: 1136
Runtime of the program for j 0.4312882423400879
column j: 1137
Runtime of the program for j 0.5038437843322754
column j: 1138
Runtime of the program for j 0.26172852516174316
column j: 1139
Runtime of the program for j 0.256622314453125
column j: 1140
Runtime of the program for j 0.42995262145996094
column j: 1141
Runtime of the program for j 0.42965078353881836
column j: 1142
Runtime of the program for j 0.47390103340148926
column j: 1143
Runtime of the program for j 0.4460461139678955
column j: 1144
Runtime of the program for j 0.42609620094299316
column j: 1145
Runtime of the program for j 0.4421858787536621
column j: 1146
Runtime of the program for j 0.43683362007141113
column j: 1147
Runtime of the program for j 0.43527960777282715
column j: 1148
Runtime of the program for j 0.4278104305267334
column j: 1149
Runtime of the program for j 0.4169631004333496
column j: 1150
Runtime of the program for j 0.5145645141601562
column j: 1151
Runtime of the program for j 0.5399613380432129
column j: 1152
Runtime of the program for j 0.43495941162109375
column j: 1153
Runtime of the program for j 0.4248349666595459
column j: 1154
Runtime of the program for j 0.42014074325561523
column j: 1155
Runtime of the program for j 0.41017818450927734
column j: 1156
Runtime of the program for j 0.43475794792175293
column j: 1157
Runtime of the program for j 0.2719290256500244
column j: 1158
Runtime of the program for j 0.2714509963989258
column j: 1159
Runtime of the program for j 0.27221083641052246
column j: 1160
Runtime of the program for j 0.31650400161743164
column j: 1161
Runtime of the program for j 0.5150482654571533
column j: 1162
Runtime of the program for j 0.44347190856933594
column j: 1163
Runtime of the program for j 0.41462135314941406
column j: 1164
Runtime of the program for j 0.46530652046203613
column j: 1165
Runtime of the program for j 0.4464714527130127
column j: 1166
Runtime of the program for j 0.48741936683654785
column j: 1167
Runtime of the program for j 0.4364778995513916
column j: 1168
Runtime of the program for j 0.43025994300842285
column j: 1169
Runtime of the program for j 0.4233729839324951
column j: 1170
Runtime of the program for j 0.42986178398132324
column j: 1171
Runtime of the program for j 0.43805575370788574
column j: 1172
Runtime of the program for j 0.4354240894317627
column j: 1173
Runtime of the program for j 0.49167823791503906
column j: 1174
Runtime of the program for j 0.5147817134857178
column j: 1175
Runtime of the program for j 0.4253349304199219
column j: 1176
Runtime of the program for j 0.4466712474822998
column j: 1177
Runtime of the program for j 0.5301141738891602
column j: 1178
Runtime of the program for j 0.4689764976501465
column j: 1179
Runtime of the program for j 0.4726247787475586
column j: 1180
Runtime of the program for j 0.41923069953918457
column j: 1181
Runtime of the program for j 0.44132518768310547
column j: 1182
Runtime of the program for j 0.48650145530700684
column j: 1183
Runtime of the program for j 0.4999516010284424
column j: 1184
Runtime of the program for j 0.425173282623291
column j: 1185
Runtime of the program for j 0.5330631732940674

column j: 1186
Runtime of the program for j 0.4498417377471924
column j: 1187
Runtime of the program for j 0.4732227325439453
column j: 1188
Runtime of the program for j 0.4514596462249756
column j: 1189
Runtime of the program for j 0.5154967308044434
column j: 1190
Runtime of the program for j 0.4598708152770996
column j: 1191
Runtime of the program for j 0.4601097106933594
column j: 1192
Runtime of the program for j 0.30190420150756836
column j: 1193
Runtime of the program for j 0.3294639587402344
column j: 1194
Runtime of the program for j 0.5001702308654785
column j: 1195
Runtime of the program for j 0.48155760765075684
column j: 1196
Runtime of the program for j 0.5049147605895996
column j: 1197
Runtime of the program for j 0.5520875453948975
column j: 1198
Runtime of the program for j 0.6373989582061768
column j: 1199
Runtime of the program for j 0.5342791080474854
column j: 1200
Runtime of the program for j 0.43785715103149414
column j: 1201
Runtime of the program for j 0.43820810317993164
column j: 1202
Runtime of the program for j 0.49019789695739746
column j: 1203
Runtime of the program for j 0.42580223083496094
column j: 1204
Runtime of the program for j 0.4581000804901123
column j: 1205
Runtime of the program for j 0.4677927494049072
column j: 1206
Runtime of the program for j 0.4603118896484375
column j: 1207
Runtime of the program for j 0.4754903316497803
column j: 1208
Runtime of the program for j 0.46422481536865234
column j: 1209
Runtime of the program for j 0.5196037292480469
column j: 1210
Runtime of the program for j 0.4490165710449219
column j: 1211
Runtime of the program for j 0.4400503635406494
column j: 1212
Runtime of the program for j 0.27707433700561523
column j: 1213
Runtime of the program for j 0.3176865577697754
column j: 1214
Runtime of the program for j 0.29613375663757324
column j: 1215
Runtime of the program for j 0.44188809394836426
column j: 1216
Runtime of the program for j 0.4799680709838867
column j: 1217
Runtime of the program for j 0.4448506832122803
column j: 1218
Runtime of the program for j 0.4415581226348877
column j: 1219
Runtime of the program for j 0.4985320568084717
column j: 1220
Runtime of the program for j 0.43515729904174805
column j: 1221
Runtime of the program for j 0.424877405166626
column j: 1222
Runtime of the program for j 0.5123546123504639
column j: 1223
Runtime of the program for j 0.44745397567749023
column j: 1224
Runtime of the program for j 0.46982812881469727
column j: 1225
Runtime of the program for j 0.4501817226409912
column j: 1226
Runtime of the program for j 0.44004368782043457
column j: 1227
Runtime of the program for j 0.5475883483886719
column j: 1228
Runtime of the program for j 0.45306849479675293
column j: 1229
Runtime of the program for j 0.4336881637573242
column j: 1230
Runtime of the program for j 0.44144153594970703
column j: 1231
Runtime of the program for j 0.4387950897216797
column j: 1232
Runtime of the program for j 0.5695178508758545
column j: 1233
Runtime of the program for j 0.4276862144470215
column j: 1234
Runtime of the program for j 0.44672155380249023
column j: 1235
Runtime of the program for j 0.4368007183074951
column j: 1236
Runtime of the program for j 0.4517688751220703
column j: 1237
Runtime of the program for j 0.43442201614379883
column j: 1238
Runtime of the program for j 0.4425976276397705
column j: 1239
Runtime of the program for j 0.46994805335998535
column j: 1240
Runtime of the program for j 0.4302525520324707
column j: 1241
Runtime of the program for j 0.44502997398376465
column j: 1242
Runtime of the program for j 0.4331207275390625
column j: 1243
Runtime of the program for j 0.43681788444519043
column j: 1244
Runtime of the program for j 0.483370304107666
column j: 1245
Runtime of the program for j 0.43151354789733887
column j: 1246
Runtime of the program for j 0.2732386589050293
column j: 1247
Runtime of the program for j 0.5002686977386475
column j: 1248
Runtime of the program for j 0.4301292896270752
column j: 1249
Runtime of the program for j 0.4412350654602051
column j: 1250
Runtime of the program for j 0.5185229778289795
column j: 1251
Runtime of the program for j 0.4421861171722412
column j: 1252
Runtime of the program for j 0.4481508731842041
column j: 1253
Runtime of the program for j 0.5380985736846924
column j: 1254
Runtime of the program for j 0.5213568210601807
column j: 1255
Runtime of the program for j 0.4438943862915039
column j: 1256
Runtime of the program for j 0.5162875652313232
column j: 1257
Runtime of the program for j 0.2799196243286133
column j: 1258
Runtime of the program for j 0.44510507583618164
column j: 1259
Runtime of the program for j 0.4330790042877197
column j: 1260
Runtime of the program for j 0.4380512237548828
column j: 1261
Runtime of the program for j 0.4983336925506592
column j: 1262
Runtime of the program for j 0.45298027992248535
column j: 1263
Runtime of the program for j 0.4422414302825928
column j: 1264
Runtime of the program for j 0.44697022438049316
column j: 1265
Runtime of the program for j 0.45189976692199707
column j: 1266
Runtime of the program for j 0.596071720123291
column j: 1267
Runtime of the program for j 0.4453756809234619
column j: 1268
Runtime of the program for j 0.44025754928588867
column j: 1269
Runtime of the program for j 0.4334707260131836
column j: 1270
Runtime of the program for j 0.4461374282836914
column j: 1271
Runtime of the program for j 0.4805586338043213
column j: 1272
Runtime of the program for j 0.4194638729095459
column j: 1273
Runtime of the program for j 0.4333944320678711
column j: 1274
Runtime of the program for j 0.44501209259033203
column j: 1275
Runtime of the program for j 0.38483405113220215
column j: 1276
Runtime of the program for j 0.523627758026123
column j: 1277
Runtime of the program for j 0.4388160705566406
column j: 1278
Runtime of the program for j 0.27446699142456055
column j: 1279
Runtime of the program for j 0.27378225326538086
column j: 1280
Runtime of the program for j 0.4282646179199219
column j: 1281
Runtime of the program for j 0.4434797763824463
column j: 1282
Runtime of the program for j 0.4317905902862549
column j: 1283
Runtime of the program for j 0.4365265369415283
column j: 1284
Runtime of the program for j 0.4338874816894531
column j: 1285
Runtime of the program for j 0.45632481575012207
column j: 1286
Runtime of the program for j 0.4457979202270508
column j: 1287
Runtime of the program for j 0.2774679660797119
column j: 1288
Runtime of the program for j 0.3480517864227295
column j: 1289
Runtime of the program for j 0.4298253059387207
column j: 1290
Runtime of the program for j 0.44013190269470215
column j: 1291
Runtime of the program for j 0.4598724842071533
column j: 1292
Runtime of the program for j 0.4901599884033203
column j: 1293
Runtime of the program for j 0.455672025680542
column j: 1294
Runtime of the program for j 0.44979357719421387
column j: 1295
Runtime of the program for j 0.5099289417266846
column j: 1296
Runtime of the program for j 0.43625307083129883
column j: 1297
Runtime of the program for j 0.4464876651763916
column j: 1298
Runtime of the program for j 0.5371959209442139
column j: 1299
Runtime of the program for j 0.4668114185333252
column j: 1300
Runtime of the program for j 0.29711008071899414
column j: 1301
Runtime of the program for j 0.28606319427490234
column j: 1302
Runtime of the program for j 0.48310136795043945
column j: 1303
Runtime of the program for j 0.2983570098876953
column j: 1304
Runtime of the program for j 0.48210859298706055
column j: 1305
Runtime of the program for j 0.5266423225402832
column j: 1306
Runtime of the program for j 0.5289177894592285
column j: 1307
Runtime of the program for j 0.5000982284545898
column j: 1308
Runtime of the program for j 0.5302853584289551
column j: 1309
Runtime of the program for j 0.5297596454620361
column j: 1310
Runtime of the program for j 0.6215851306915283
column j: 1311
Runtime of the program for j 0.5087249279022217
column j: 1312
Runtime of the program for j 0.5198647975921631
column j: 1313
Runtime of the program for j 0.5675191879272461
column j: 1314
Runtime of the program for j 0.46876001358032227
column j: 1315
Runtime of the program for j 0.46387267112731934

column j: 1316
Runtime of the program for j 0.4997720718383789
column j: 1317
Runtime of the program for j 0.4452838897705078
column j: 1318
Runtime of the program for j 0.4410569667816162
column j: 1319
Runtime of the program for j 0.44421982765197754
column j: 1320
Runtime of the program for j 0.5288262367248535
column j: 1321
Runtime of the program for j 0.43694424629211426
column j: 1322
Runtime of the program for j 0.4623403549194336
column j: 1323
Runtime of the program for j 0.447434663772583
column j: 1324
Runtime of the program for j 0.43013715744018555
column j: 1325
Runtime of the program for j 0.450364351272583
column j: 1326
Runtime of the program for j 0.44254374504089355
column j: 1327
Runtime of the program for j 0.43418288230895996
column j: 1328
Runtime of the program for j 0.47993898391723633
column j: 1329
Runtime of the program for j 0.449840784072876
column j: 1330
Runtime of the program for j 0.5297989845275879
column j: 1331
Runtime of the program for j 0.4511415958404541
column j: 1332
Runtime of the program for j 0.4489610195159912
column j: 1333
Runtime of the program for j 0.4402918815612793
column j: 1334
Runtime of the program for j 0.450742244720459
column j: 1335
Runtime of the program for j 0.4506244659423828
column j: 1336
Runtime of the program for j 0.4432544708251953
column j: 1337
Runtime of the program for j 0.29038166999816895
column j: 1338
Runtime of the program for j 0.4461960792541504
column j: 1339
Runtime of the program for j 0.4479949474334717
column j: 1340
Runtime of the program for j 0.5289256572723389
column j: 1341
Runtime of the program for j 0.44046807289123535
column j: 1342
Runtime of the program for j 0.4082059860229492
column j: 1343
Runtime of the program for j 0.4305286407470703
column j: 1344
Runtime of the program for j 0.5346879959106445
column j: 1345
Runtime of the program for j 0.5439260005950928
column j: 1346
Runtime of the program for j 0.42992353439331055
column j: 1347
Runtime of the program for j 0.44684529304504395
column j: 1348
Runtime of the program for j 0.5599963665008545
column j: 1349
Runtime of the program for j 0.49210619926452637
column j: 1350
Runtime of the program for j 0.5368382930755615
column j: 1351
Runtime of the program for j 0.29229092597961426
column j: 1352
Runtime of the program for j 0.3489542007446289
column j: 1353
Runtime of the program for j 0.5117814540863037
column j: 1354
Runtime of the program for j 0.43724656105041504
column j: 1355
Runtime of the program for j 0.5998470783233643
column j: 1356
Runtime of the program for j 0.5507845878601074
column j: 1357
Runtime of the program for j 0.7749714851379395
column j: 1358
Runtime of the program for j 0.6002078056335449
column j: 1359
Runtime of the program for j 0.6694977283477783
column j: 1360
Runtime of the program for j 0.6262702941894531
column j: 1361
Runtime of the program for j 0.4860963821411133
column j: 1362
Runtime of the program for j 0.5051522254943848
column j: 1363
Runtime of the program for j 0.458728551864624
column j: 1364
Runtime of the program for j 0.28698086738586426
column j: 1365
Runtime of the program for j 0.4498097896575928
column j: 1366
Runtime of the program for j 0.4535374641418457
column j: 1367
Runtime of the program for j 0.44408249855041504
column j: 1368
Runtime of the program for j 0.4387173652648926
column j: 1369
Runtime of the program for j 0.4584207534790039
column j: 1370
Runtime of the program for j 0.45361900329589844
column j: 1371
Runtime of the program for j 0.5236728191375732
column j: 1372
Runtime of the program for j 0.2898099422454834
column j: 1373
Runtime of the program for j 0.4498271942138672
column j: 1374
Runtime of the program for j 0.45024561882019043
column j: 1375
Runtime of the program for j 0.44896507263183594
column j: 1376
Runtime of the program for j 0.44957470893859863
column j: 1377
Runtime of the program for j 0.4476029872894287
column j: 1378
Runtime of the program for j 0.44771695137023926
column j: 1379
Runtime of the program for j 0.43984150886535645
column j: 1380
Runtime of the program for j 0.44495153427124023
column j: 1381
Runtime of the program for j 0.5197248458862305
column j: 1382
Runtime of the program for j 0.4602677822113037
column j: 1383
Runtime of the program for j 0.4598095417022705
column j: 1384
Runtime of the program for j 0.4389657974243164
column j: 1385
Runtime of the program for j 0.4501957893371582
column j: 1386
Runtime of the program for j 0.4709353446960449
column j: 1387
Runtime of the program for j 0.4587993621826172
column j: 1388
Runtime of the program for j 0.45514583587646484
column j: 1389
Runtime of the program for j 0.4564085006713867
column j: 1390
Runtime of the program for j 0.4584004878997803
column j: 1391
Runtime of the program for j 0.5374534130096436
column j: 1392
Runtime of the program for j 0.4490847587585449
column j: 1393
Runtime of the program for j 0.45327138900756836
column j: 1394
Runtime of the program for j 0.46007490158081055
column j: 1395
Runtime of the program for j 0.44676995277404785
column j: 1396
Runtime of the program for j 0.4500608444213867
column j: 1397
Runtime of the program for j 0.44484496116638184
column j: 1398
Runtime of the program for j 0.4548466205596924
column j: 1399
Runtime of the program for j 0.45008182525634766
column j: 1400
Runtime of the program for j 0.5283377170562744
column j: 1401
Runtime of the program for j 0.4463644027709961
column j: 1402
Runtime of the program for j 0.44512295722961426
column j: 1403
Runtime of the program for j 0.7190060615539551
column j: 1404
Runtime of the program for j 0.5622820854187012
column j: 1405
Runtime of the program for j 0.4658048152923584
column j: 1406
Runtime of the program for j 0.48283815383911133
column j: 1407
Runtime of the program for j 0.45987844467163086
column j: 1408
Runtime of the program for j 0.4597949981689453
column j: 1409
Runtime of the program for j 0.5769352912902832
column j: 1410
Runtime of the program for j 0.8316936492919922
column j: 1411
Runtime of the program for j 0.7180271148681641
column j: 1412
Runtime of the program for j 0.7699108123779297
column j: 1413
Runtime of the program for j 0.7001066207885742
column j: 1414
Runtime of the program for j 0.7486624717712402
column j: 1415
Runtime of the program for j 0.5499453544616699
column j: 1416
Runtime of the program for j 0.4496629238128662
column j: 1417
Runtime of the program for j 0.4607365131378174
column j: 1418
Runtime of the program for j 0.6225922107696533
column j: 1419
Runtime of the program for j 0.7107806205749512
column j: 1420
Runtime of the program for j 0.5791969299316406
column j: 1421
Runtime of the program for j 0.5002422332763672
column j: 1422
Runtime of the program for j 0.44300174713134766
column j: 1423
Runtime of the program for j 0.7875854969024658
column j: 1424
Runtime of the program for j 0.4494211673736572
column j: 1425
Runtime of the program for j 0.5278420448303223
column j: 1426
Runtime of the program for j 0.44178056716918945
column j: 1427
Runtime of the program for j 0.5677127838134766
column j: 1428
Runtime of the program for j 0.45999908447265625
column j: 1429
Runtime of the program for j 0.5120193958282471
column j: 1430
Runtime of the program for j 0.45989537239074707
column j: 1431
Runtime of the program for j 0.5000975131988525
column j: 1432
Runtime of the program for j 0.4691801071166992
column j: 1433
Runtime of the program for j 0.8733713626861572
column j: 1434
Runtime of the program for j 0.5473036766052246
column j: 1435
Runtime of the program for j 0.5269467830657959
column j: 1436
Runtime of the program for j 0.3813803195953369
column j: 1437
Runtime of the program for j 0.5370028018951416
column j: 1438
Runtime of the program for j 0.7097411155700684
column j: 1439
Runtime of the program for j 0.5300946235656738
column j: 1440
Runtime of the program for j 0.5250816345214844
column j: 1441
Runtime of the program for j 0.5912325382232666
column j: 1442
Runtime of the program for j 0.5456023216247559
column j: 1443
Runtime of the program for j 0.5294938087463379
column j: 1444
Runtime of the program for j 0.49341678619384766
column j: 1445
Runtime of the program for j 0.5700116157531738

column j: 1446
Runtime of the program for j 0.5247960090637207
column j: 1447
Runtime of the program for j 0.5483555793762207
column j: 1448
Runtime of the program for j 0.5714833736419678
column j: 1449
Runtime of the program for j 0.6049299240112305
column j: 1450
Runtime of the program for j 0.5284197330474854
column j: 1451
Runtime of the program for j 0.47493934631347656
column j: 1452
Runtime of the program for j 0.510216236114502
column j: 1453
Runtime of the program for j 0.5847749710083008
column j: 1454
Runtime of the program for j 0.5371370315551758
column j: 1455
Runtime of the program for j 0.5247797966003418
column j: 1456
Runtime of the program for j 0.4729900360107422
column j: 1457
Runtime of the program for j 0.4951763153076172
column j: 1458
Runtime of the program for j 0.5733940601348877
column j: 1459
Runtime of the program for j 0.5588793754577637
column j: 1460
Runtime of the program for j 0.4812788963317871
column j: 1461
Runtime of the program for j 0.45830512046813965
column j: 1462
Runtime of the program for j 0.6201770305633545
column j: 1463
Runtime of the program for j 0.5745024681091309
column j: 1464
Runtime of the program for j 0.565361738204956
column j: 1465
Runtime of the program for j 0.45715856552124023
column j: 1466
Runtime of the program for j 0.45481061935424805
column j: 1467
Runtime of the program for j 0.5524313449859619
column j: 1468
Runtime of the program for j 0.5343475341796875
column j: 1469
Runtime of the program for j 0.4687211513519287
column j: 1470
Runtime of the program for j 0.45726990699768066
column j: 1471
Runtime of the program for j 0.6194291114807129
column j: 1472
Runtime of the program for j 0.538379430770874
column j: 1473
Runtime of the program for j 0.4614677429199219
column j: 1474
Runtime of the program for j 0.45885324478149414
column j: 1475
Runtime of the program for j 0.5900206565856934
column j: 1476
Runtime of the program for j 0.3869152069091797
column j: 1477
Runtime of the program for j 0.45496225357055664
column j: 1478
Runtime of the program for j 0.4538552761077881
column j: 1479
Runtime of the program for j 0.5451035499572754
column j: 1480
Runtime of the program for j 0.6352777481079102
column j: 1481
Runtime of the program for j 0.4596059322357178
column j: 1482
Runtime of the program for j 0.5125353336334229
column j: 1483
Runtime of the program for j 0.6376018524169922
column j: 1484
Runtime of the program for j 0.5516390800476074
column j: 1485
Runtime of the program for j 0.47971391677856445
column j: 1486
Runtime of the program for j 0.4713480472564697
column j: 1487
Runtime of the program for j 0.49718260765075684
column j: 1488
Runtime of the program for j 0.6440703868865967
column j: 1489
Runtime of the program for j 0.5515191555023193
column j: 1490
Runtime of the program for j 0.5418968200683594
column j: 1491
Runtime of the program for j 0.5052235126495361
column j: 1492
Runtime of the program for j 0.5301940441131592
column j: 1493
Runtime of the program for j 0.5099456310272217
column j: 1494
Runtime of the program for j 0.5397865772247314
column j: 1495
Runtime of the program for j 0.5357644557952881
column j: 1496
Runtime of the program for j 0.5440490245819092
column j: 1497
Runtime of the program for j 0.5503494739532471
column j: 1498
Runtime of the program for j 0.46149110794067383
column j: 1499
Runtime of the program for j 0.5143823623657227
column j: 1500
Runtime of the program for j 0.5292007923126221
column j: 1501
Runtime of the program for j 0.5598850250244141
column j: 1502
Runtime of the program for j 0.5019426345825195
column j: 1503
Runtime of the program for j 0.5176806449890137
column j: 1504
Runtime of the program for j 0.5102853775024414
column j: 1505
Runtime of the program for j 0.6242752075195312
column j: 1506
Runtime of the program for j 0.48563528060913086
column j: 1507
Runtime of the program for j 0.4682731628417969
column j: 1508
Runtime of the program for j 0.54207444190979
column j: 1509
Runtime of the program for j 0.5147016048431396
column j: 1510
Runtime of the program for j 0.46987342834472656
column j: 1511
Runtime of the program for j 0.4622018337249756
column j: 1512
Runtime of the program for j 0.5003275871276855
column j: 1513
Runtime of the program for j 0.5977563858032227
column j: 1514
Runtime of the program for j 0.4696183204650879
column j: 1515
Runtime of the program for j 0.45999646186828613
column j: 1516
Runtime of the program for j 0.5363950729370117
column j: 1517
Runtime of the program for j 0.535527229309082
column j: 1518
Runtime of the program for j 0.4580264091491699
column j: 1519
Runtime of the program for j 0.45242929458618164
column j: 1520
Runtime of the program for j 0.46428823471069336
column j: 1521
Runtime of the program for j 0.46245694160461426
column j: 1522
Runtime of the program for j 0.5536267757415771
column j: 1523
Runtime of the program for j 0.5251972675323486
column j: 1524
Runtime of the program for j 0.5414795875549316
column j: 1525
Runtime of the program for j 0.5417771339416504
column j: 1526
Runtime of the program for j 0.46672868728637695
column j: 1527
Runtime of the program for j 0.45427536964416504
column j: 1528
Runtime of the program for j 0.5664267539978027
column j: 1529
Runtime of the program for j 0.44949960708618164
column j: 1530
Runtime of the program for j 0.5514578819274902
column j: 1531
Runtime of the program for j 0.5374405384063721
column j: 1532
Runtime of the program for j 0.5598227977752686
column j: 1533
Runtime of the program for j 0.47322845458984375
column j: 1534
Runtime of the program for j 0.4716606140136719
column j: 1535
Runtime of the program for j 0.5652444362640381
column j: 1536
Runtime of the program for j 0.5501463413238525
column j: 1537
Runtime of the program for j 0.5149025917053223
column j: 1538
Runtime of the program for j 0.5562615394592285
column j: 1539
Runtime of the program for j 0.5584831237792969
column j: 1540
Runtime of the program for j 0.4866914749145508
column j: 1541
Runtime of the program for j 0.5220983028411865
column j: 1542
Runtime of the program for j 0.5560793876647949
column j: 1543
Runtime of the program for j 0.4914278984069824
column j: 1544
Runtime of the program for j 0.3217127323150635
column j: 1545
Runtime of the program for j 0.5819802284240723
column j: 1546
Runtime of the program for j 0.5751609802246094
column j: 1547
Runtime of the program for j 0.5713951587677002
column j: 1548
Runtime of the program for j 0.5254249572753906
column j: 1549
Runtime of the program for j 0.5248322486877441
column j: 1550
Runtime of the program for j 0.5600450038909912
column j: 1551
Runtime of the program for j 0.4631977081298828
column j: 1552
Runtime of the program for j 0.45819520950317383
column j: 1553
Runtime of the program for j 0.4665822982788086
column j: 1554
Runtime of the program for j 0.4636404514312744
column j: 1555
Runtime of the program for j 0.5503664016723633
column j: 1556
Runtime of the program for j 0.4580655097961426
column j: 1557
Runtime of the program for j 0.46022653579711914
column j: 1558
Runtime of the program for j 0.4500548839569092
column j: 1559
Runtime of the program for j 0.4669785499572754
column j: 1560
Runtime of the program for j 0.46848011016845703
column j: 1561
Runtime of the program for j 0.4503645896911621
column j: 1562
Runtime of the program for j 0.4644930362701416
column j: 1563
Runtime of the program for j 0.3732607364654541
column j: 1564
Runtime of the program for j 0.4671001434326172
column j: 1565
Runtime of the program for j 0.4696962833404541
column j: 1566
Runtime of the program for j 0.4602844715118408
column j: 1567
Runtime of the program for j 0.31010866165161133
column j: 1568
Runtime of the program for j 0.46805691719055176
column j: 1569
Runtime of the program for j 0.45009684562683105
column j: 1570
Runtime of the program for j 0.5019969940185547
column j: 1571
Runtime of the program for j 0.6330368518829346
column j: 1572
Runtime of the program for j 0.4615905284881592
column j: 1573
Runtime of the program for j 0.4544191360473633
column j: 1574
Runtime of the program for j 0.5601217746734619
column j: 1575
Runtime of the program for j 0.5618200302124023

column j: 1576
Runtime of the program for j 0.47129082679748535
column j: 1577
Runtime of the program for j 0.4470663070678711
column j: 1578
Runtime of the program for j 0.5598478317260742
column j: 1579
Runtime of the program for j 0.4300863742828369
column j: 1580
Runtime of the program for j 0.3029780387878418
column j: 1581
Runtime of the program for j 0.4753737449645996
column j: 1582
Runtime of the program for j 0.5254104137420654
column j: 1583
Runtime of the program for j 0.5393998622894287
column j: 1584
Runtime of the program for j 0.4786710739135742
column j: 1585
Runtime of the program for j 0.47620129585266113
column j: 1586
Runtime of the program for j 0.4617300033569336
column j: 1587
Runtime of the program for j 0.49820780754089355
column j: 1588
Runtime of the program for j 0.5614101886749268
column j: 1589
Runtime of the program for j 0.45532774925231934
column j: 1590
Runtime of the program for j 0.4636952877044678
column j: 1591
Runtime of the program for j 0.4599127769470215
column j: 1592
Runtime of the program for j 0.4597775936126709
column j: 1593
Runtime of the program for j 0.3061389923095703
column j: 1594
Runtime of the program for j 0.4624505043029785
column j: 1595
Runtime of the program for j 0.5401456356048584
column j: 1596
Runtime of the program for j 0.46306347846984863
column j: 1597
Runtime of the program for j 0.5529613494873047
column j: 1598
Runtime of the program for j 0.4646718502044678
column j: 1599
Runtime of the program for j 0.4453916549682617
column j: 1600
Runtime of the program for j 0.4662892818450928
column j: 1601
Runtime of the program for j 0.4551105499267578
column j: 1602
Runtime of the program for j 0.4600565433502197
column j: 1603
Runtime of the program for j 0.535146951675415
column j: 1604
Runtime of the program for j 0.5567798614501953
column j: 1605
Runtime of the program for j 0.4829092025756836
column j: 1606
Runtime of the program for j 0.466630220413208
column j: 1607
Runtime of the program for j 0.45766568183898926
column j: 1608
Runtime of the program for j 0.2836329936981201
column j: 1609
Runtime of the program for j 0.460064172744751
column j: 1610
Runtime of the program for j 0.461087703704834
column j: 1611
Runtime of the program for j 0.5294082164764404
column j: 1612
Runtime of the program for j 0.2991459369659424
column j: 1613
Runtime of the program for j 0.4581611156463623
column j: 1614
Runtime of the program for j 0.45877885818481445
column j: 1615
Runtime of the program for j 0.5715756416320801
column j: 1616
Runtime of the program for j 0.49454641342163086
column j: 1617
Runtime of the program for j 0.4761056900024414
column j: 1618
Runtime of the program for j 0.573814868927002
column j: 1619
Runtime of the program for j 0.4701254367828369
column j: 1620
Runtime of the program for j 0.46321988105773926
column j: 1621
Runtime of the program for j 0.4686093330383301
column j: 1622
Runtime of the program for j 0.5602335929870605
column j: 1623
Runtime of the program for j 0.5449247360229492
column j: 1624
Runtime of the program for j 0.47151732444763184
column j: 1625
Runtime of the program for j 0.47357845306396484
column j: 1626
Runtime of the program for j 0.4927332401275635
column j: 1627
Runtime of the program for j 0.5267713069915771
column j: 1628
Runtime of the program for j 0.4603290557861328
column j: 1629
Runtime of the program for j 0.47458314895629883
column j: 1630
Runtime of the program for j 0.5549314022064209
column j: 1631
Runtime of the program for j 0.5855422019958496
column j: 1632
Runtime of the program for j 0.4762732982635498
column j: 1633
Runtime of the program for j 0.473435640335083
column j: 1634
Runtime of the program for j 0.46413755416870117
column j: 1635
Runtime of the program for j 0.31830811500549316
column j: 1636
Runtime of the program for j 0.31018829345703125
column j: 1637
Runtime of the program for j 0.3597886562347412
column j: 1638
Runtime of the program for j 0.32752275466918945
column j: 1639
Runtime of the program for j 0.4778437614440918
column j: 1640
Runtime of the program for j 0.4698171615600586
column j: 1641
Runtime of the program for j 0.4703664779663086
column j: 1642
Runtime of the program for j 0.5512552261352539
column j: 1643
Runtime of the program for j 0.528331995010376
column j: 1644
Runtime of the program for j 0.46831750869750977
column j: 1645
Runtime of the program for j 0.4614996910095215
column j: 1646
Runtime of the program for j 0.4833526611328125
column j: 1647
Runtime of the program for j 0.46669673919677734
column j: 1648
Runtime of the program for j 0.46211910247802734
column j: 1649
Runtime of the program for j 0.4700150489807129
column j: 1650
Runtime of the program for j 0.5596733093261719
column j: 1651
Runtime of the program for j 0.4599459171295166
column j: 1652
Runtime of the program for j 0.46375083923339844
column j: 1653
Runtime of the program for j 0.5139753818511963
column j: 1654
Runtime of the program for j 0.3936333656311035
column j: 1655
Runtime of the program for j 0.5185673236846924
column j: 1656
Runtime of the program for j 0.48111462593078613
column j: 1657
Runtime of the program for j 0.46913933753967285
column j: 1658
Runtime of the program for j 0.6100139617919922
column j: 1659
Runtime of the program for j 0.4600188732147217
column j: 1660
Runtime of the program for j 0.4652218818664551
column j: 1661
Runtime of the program for j 0.5526933670043945
column j: 1662
Runtime of the program for j 0.5773818492889404
column j: 1663
Runtime of the program for j 0.5704600811004639
column j: 1664
Runtime of the program for j 0.45989203453063965
column j: 1665
Runtime of the program for j 0.61183762550354
column j: 1666
Runtime of the program for j 0.5376362800598145
column j: 1667
Runtime of the program for j 0.554114818572998
column j: 1668
Runtime of the program for j 0.5612046718597412
column j: 1669
Runtime of the program for j 0.5396673679351807
column j: 1670
Runtime of the program for j 0.4765970706939697
column j: 1671
Runtime of the program for j 0.46860599517822266
column j: 1672
Runtime of the program for j 0.6731595993041992
column j: 1673
Runtime of the program for j 0.5595667362213135
column j: 1674
Runtime of the program for j 0.46280336380004883
column j: 1675
Runtime of the program for j 0.4719672203063965
column j: 1676
Runtime of the program for j 0.5908889770507812
column j: 1677
Runtime of the program for j 0.5773353576660156
column j: 1678
Runtime of the program for j 0.5078718662261963
column j: 1679
Runtime of the program for j 0.5139975547790527
column j: 1680
Runtime of the program for j 0.6581270694732666
column j: 1681
Runtime of the program for j 0.5809683799743652
column j: 1682
Runtime of the program for j 0.49344396591186523
column j: 1683
Runtime of the program for j 0.48567795753479004
column j: 1684
Runtime of the program for j 0.5674011707305908
column j: 1685
Runtime of the program for j 0.5760397911071777
column j: 1686
Runtime of the program for j 0.5831518173217773
column j: 1687
Runtime of the program for j 0.6916346549987793
column j: 1688
Runtime of the program for j 0.4998025894165039
column j: 1689
Runtime of the program for j 0.4634988307952881
column j: 1690
Runtime of the program for j 0.5820660591125488
column j: 1691
Runtime of the program for j 0.563237190246582
column j: 1692
Runtime of the program for j 0.47005724906921387
column j: 1693
Runtime of the program for j 0.4568004608154297
column j: 1694
Runtime of the program for j 0.4749491214752197
column j: 1695
Runtime of the program for j 0.5538899898529053
column j: 1696
Runtime of the program for j 0.46872878074645996
column j: 1697
Runtime of the program for j 0.48419642448425293
column j: 1698
Runtime of the program for j 0.48839759826660156
column j: 1699
Runtime of the program for j 0.5386707782745361
column j: 1700
Runtime of the program for j 0.5332798957824707
column j: 1701
Runtime of the program for j 0.47731661796569824
column j: 1702
Runtime of the program for j 0.5695807933807373
column j: 1703
Runtime of the program for j 0.552635669708252
column j: 1704
Runtime of the program for j 0.565413236618042
column j: 1705
Runtime of the program for j 0.5497012138366699

column j: 1706
Runtime of the program for j 0.5498485565185547
column j: 1707
Runtime of the program for j 0.4868016242980957
column j: 1708
Runtime of the program for j 0.4883604049682617
column j: 1709
Runtime of the program for j 0.6652474403381348
column j: 1710
Runtime of the program for j 0.569887638092041
column j: 1711
Runtime of the program for j 0.4713590145111084
column j: 1712
Runtime of the program for j 0.45882749557495117
column j: 1713
Runtime of the program for j 0.557182788848877
column j: 1714
Runtime of the program for j 0.5711915493011475
column j: 1715
Runtime of the program for j 0.47905516624450684
column j: 1716
Runtime of the program for j 0.4412972927093506
column j: 1717
Runtime of the program for j 0.6092493534088135
column j: 1718
Runtime of the program for j 0.47409963607788086
column j: 1719
Runtime of the program for j 0.485243558883667
column j: 1720
Runtime of the program for j 0.45993924140930176
column j: 1721
Runtime of the program for j 0.7486903667449951
column j: 1722
Runtime of the program for j 0.4502565860748291
column j: 1723
Runtime of the program for j 0.4064915180206299
column j: 1724
Runtime of the program for j 0.4861271381378174
column j: 1725
Runtime of the program for j 0.4337167739868164
column j: 1726
Runtime of the program for j 0.5564060211181641
column j: 1727
Runtime of the program for j 0.553429126739502
column j: 1728
Runtime of the program for j 0.5146093368530273
column j: 1729
Runtime of the program for j 0.5156595706939697
column j: 1730
Runtime of the program for j 0.5096099376678467
column j: 1731
Runtime of the program for j 0.6520626544952393
column j: 1732
Runtime of the program for j 0.5348212718963623
column j: 1733
Runtime of the program for j 0.5362894535064697
column j: 1734
Runtime of the program for j 0.5514366626739502
column j: 1735
Runtime of the program for j 0.5837907791137695
column j: 1736
Runtime of the program for j 0.5748085975646973
column j: 1737
Runtime of the program for j 0.5630524158477783
column j: 1738
Runtime of the program for j 0.6053280830383301
column j: 1739
Runtime of the program for j 0.6826155185699463
column j: 1740
Runtime of the program for j 0.5889229774475098
column j: 1741
Runtime of the program for j 0.6419484615325928
column j: 1742
Runtime of the program for j 0.5677530765533447
column j: 1743
Runtime of the program for j 0.4700019359588623
column j: 1744
Runtime of the program for j 0.49123120307922363
column j: 1745
Runtime of the program for j 0.3855717182159424
column j: 1746
Runtime of the program for j 0.6323354244232178
column j: 1747
Runtime of the program for j 0.49991798400878906
column j: 1748
Runtime of the program for j 0.49091386795043945
column j: 1749
Runtime of the program for j 0.5609393119812012
column j: 1750
Runtime of the program for j 0.5867807865142822
column j: 1751
Runtime of the program for j 0.5734772682189941
column j: 1752
Runtime of the program for j 0.48508262634277344
column j: 1753
Runtime of the program for j 0.5745644569396973
column j: 1754
Runtime of the program for j 0.5421481132507324
column j: 1755
Runtime of the program for j 0.5782327651977539
column j: 1756
Runtime of the program for j 0.5696680545806885
column j: 1757
Runtime of the program for j 0.5502943992614746
column j: 1758
Runtime of the program for j 0.5383627414703369
column j: 1759
Runtime of the program for j 0.39127564430236816
column j: 1760
Runtime of the program for j 0.4335634708404541
column j: 1761
Runtime of the program for j 0.5307650566101074
column j: 1762
Runtime of the program for j 0.5761432647705078
column j: 1763
Runtime of the program for j 0.5532805919647217
column j: 1764
Runtime of the program for j 0.5029768943786621
column j: 1765
Runtime of the program for j 0.4737272262573242
column j: 1766
Runtime of the program for j 0.5908162593841553
column j: 1767
Runtime of the program for j 0.6497251987457275
column j: 1768
Runtime of the program for j 0.4840068817138672
column j: 1769
Runtime of the program for j 0.4849128723144531
column j: 1770
Runtime of the program for j 0.570458173751831
column j: 1771
Runtime of the program for j 0.6139624118804932
column j: 1772
Runtime of the program for j 0.5517594814300537
column j: 1773
Runtime of the program for j 0.483198881149292
column j: 1774
Runtime of the program for j 0.6431927680969238
column j: 1775
Runtime of the program for j 0.6201293468475342
column j: 1776
Runtime of the program for j 0.5188720226287842
column j: 1777
Runtime of the program for j 0.5099527835845947
column j: 1778
Runtime of the program for j 0.5405459403991699
column j: 1779
Runtime of the program for j 0.5740184783935547
column j: 1780
Runtime of the program for j 0.5096187591552734
column j: 1781
Runtime of the program for j 0.5873651504516602
column j: 1782
Runtime of the program for j 0.5903058052062988
column j: 1783
Runtime of the program for j 0.5867838859558105
column j: 1784
Runtime of the program for j 0.5500881671905518
column j: 1785
Runtime of the program for j 0.5960590839385986
column j: 1786
Runtime of the program for j 0.49363183975219727
column j: 1787
Runtime of the program for j 0.49035215377807617
column j: 1788
Runtime of the program for j 0.6666347980499268
column j: 1789
Runtime of the program for j 0.5828573703765869
column j: 1790
Runtime of the program for j 0.48023557662963867
column j: 1791
Runtime of the program for j 0.46993327140808105
column j: 1792
Runtime of the program for j 0.5600545406341553
column j: 1793
Runtime of the program for j 0.5822341442108154
column j: 1794
Runtime of the program for j 0.5064904689788818
column j: 1795
Runtime of the program for j 0.5631382465362549
column j: 1796
Runtime of the program for j 0.5644345283508301
column j: 1797
Runtime of the program for j 0.5632333755493164
column j: 1798
Runtime of the program for j 0.47174859046936035
column j: 1799
Runtime of the program for j 0.4944941997528076
column j: 1800
Runtime of the program for j 0.5590231418609619
column j: 1801
Runtime of the program for j 0.4951319694519043
column j: 1802
Runtime of the program for j 0.5561082363128662
column j: 1803
Runtime of the program for j 0.5648331642150879
column j: 1804
Runtime of the program for j 0.5853273868560791
column j: 1805
Runtime of the program for j 0.4684922695159912
column j: 1806
Runtime of the program for j 0.47381162643432617
column j: 1807
Runtime of the program for j 0.5798046588897705
column j: 1808
Runtime of the program for j 0.5801544189453125
column j: 1809
Runtime of the program for j 0.582313060760498
column j: 1810
Runtime of the program for j 0.4851858615875244
column j: 1811
Runtime of the program for j 0.5684893131256104
column j: 1812
Runtime of the program for j 0.5898678302764893
column j: 1813
Runtime of the program for j 0.5866172313690186
column j: 1814
Runtime of the program for j 0.5671887397766113
column j: 1815
Runtime of the program for j 0.45847105979919434
column j: 1816
Runtime of the program for j 0.55995774269104
column j: 1817
Runtime of the program for j 0.5676908493041992
column j: 1818
Runtime of the program for j 0.5527820587158203
column j: 1819
Runtime of the program for j 0.4699442386627197
column j: 1820
Runtime of the program for j 0.47970032691955566
column j: 1821
Runtime of the program for j 0.5500321388244629
column j: 1822
Runtime of the program for j 0.5568852424621582
column j: 1823
Runtime of the program for j 0.5804402828216553
column j: 1824
Runtime of the program for j 0.5253331661224365
column j: 1825
Runtime of the program for j 0.5997593402862549
column j: 1826
Runtime of the program for j 0.6001017093658447
column j: 1827
Runtime of the program for j 0.48894453048706055
column j: 1828
Runtime of the program for j 0.4830143451690674
column j: 1829
Runtime of the program for j 0.6033828258514404
column j: 1830
Runtime of the program for j 0.7108137607574463
column j: 1831
Runtime of the program for j 0.7089760303497314
column j: 1832
Runtime of the program for j 0.27994251251220703
column j: 1833
Runtime of the program for j 0.2531280517578125
column j: 1834
Runtime of the program for j 0.20702886581420898
column j: 1835
Runtime of the program for j 0.22990965843200684

column j: 1836
Runtime of the program for j 0.21990299224853516
column j: 1837
Runtime of the program for j 0.3110167980194092
column j: 1838
Runtime of the program for j 0.2289409637451172
column j: 1839
Runtime of the program for j 0.24161624908447266
column j: 1840
Runtime of the program for j 0.22339415550231934
column j: 1841
Runtime of the program for j 0.2497725486755371
column j: 1842
Runtime of the program for j 0.25421142578125
column j: 1843
Runtime of the program for j 0.22601103782653809
column j: 1844
Runtime of the program for j 0.2627103328704834
column j: 1845
Runtime of the program for j 0.2473299503326416
column j: 1846
Runtime of the program for j 0.18338513374328613
column j: 1847
Runtime of the program for j 0.18664169311523438
column j: 1848
Runtime of the program for j 0.24107694625854492
column j: 1849
Runtime of the program for j 0.2539982795715332
column j: 1850
Runtime of the program for j 0.2780337333679199
column j: 1851
Runtime of the program for j 0.19690871238708496
column j: 1852
Runtime of the program for j 0.2543783187866211
column j: 1853
Runtime of the program for j 0.23636960983276367
column j: 1854
Runtime of the program for j 0.20615577697753906
column j: 1855
Runtime of the program for j 0.23334360122680664
column j: 1856
Runtime of the program for j 0.2296466827392578
column j: 1857
Runtime of the program for j 0.3030519485473633
column j: 1858
Runtime of the program for j 0.21249961853027344
column j: 1859
Runtime of the program for j 0.21592259407043457
column j: 1860
Runtime of the program for j 0.2487189769744873
column j: 1861
Runtime of the program for j 0.22986745834350586
column j: 1862
Runtime of the program for j 0.1401674747467041
column j: 1863
Runtime of the program for j 0.25992298126220703
column j: 1864
Runtime of the program for j 0.2600221633911133
column j: 1865
Runtime of the program for j 0.2297508716583252
column j: 1866
Runtime of the program for j 0.19570183753967285
column j: 1867
Runtime of the program for j 0.20419955253601074
column j: 1868
Runtime of the program for j 0.25492215156555176
column j: 1869
Runtime of the program for j 0.2372591495513916
column j: 1870
Runtime of the program for j 0.26193928718566895
column j: 1871
Runtime of the program for j 0.1897597312927246
column j: 1872
Runtime of the program for j 0.2653331756591797
column j: 1873
Runtime of the program for j 0.2246565818786621
column j: 1874
Runtime of the program for j 0.2200629711151123
column j: 1875
Runtime of the program for j 0.2003803253173828
column j: 1876
Runtime of the program for j 0.23976635932922363
column j: 1877
Runtime of the program for j 0.259723424911499
column j: 1878
Runtime of the program for j 0.21444296836853027
column j: 1879
Runtime of the program for j 0.22428083419799805
column j: 1880
Runtime of the program for j 0.2352139949798584
column j: 1881
Runtime of the program for j 0.23709917068481445
column j: 1882
Runtime of the program for j 0.200636625289917
column j: 1883
Runtime of the program for j 0.2609877586364746
column j: 1884
Runtime of the program for j 0.24493002891540527
column j: 1885
Runtime of the program for j 0.30025625228881836
column j: 1886
Runtime of the program for j 0.1495358943939209
column j: 1887
Runtime of the program for j 0.15020990371704102
column j: 1888
Runtime of the program for j 0.23993659019470215
column j: 1889
Runtime of the program for j 0.22159528732299805
column j: 1890
Runtime of the program for j 0.33396196365356445
column j: 1891
Runtime of the program for j 0.20479989051818848
column j: 1892
Runtime of the program for j 0.18460297584533691
column j: 1893
Runtime of the program for j 0.23026490211486816
column j: 1894
Runtime of the program for j 0.19687604904174805
column j: 1895
Runtime of the program for j 0.22035813331604004
column j: 1896
Runtime of the program for j 0.2228257656097412
column j: 1897
Runtime of the program for j 0.2845492362976074
column j: 1898
Runtime of the program for j 0.2143723964691162
column j: 1899
Runtime of the program for j 0.27495837211608887
column j: 1900
Runtime of the program for j 0.2399425506591797
column j: 1901
Runtime of the program for j 0.21025347709655762
column j: 1902
Runtime of the program for j 0.3261120319366455
column j: 1903
Runtime of the program for j 0.5077245235443115
column j: 1904
Runtime of the program for j 0.28674817085266113
column j: 1905
Runtime of the program for j 0.29076218605041504
column j: 1906
Runtime of the program for j 0.2315211296081543
column j: 1907
Runtime of the program for j 0.18686842918395996
column j: 1908
Runtime of the program for j 0.2079002857208252
column j: 1909
Runtime of the program for j 0.2119736671447754
column j: 1910
Runtime of the program for j 0.22853541374206543
column j: 1911
Runtime of the program for j 0.20910310745239258
column j: 1912
Runtime of the program for j 0.20619893074035645
column j: 1913
Runtime of the program for j 0.21119236946105957
column j: 1914
Runtime of the program for j 0.21779322624206543
column j: 1915
Runtime of the program for j 0.1998744010925293
column j: 1916
Runtime of the program for j 0.17824935913085938
column j: 1917
Runtime of the program for j 0.21313047409057617
column j: 1918
Runtime of the program for j 0.22340917587280273
column j: 1919
Runtime of the program for j 0.2167339324951172
column j: 1920
Runtime of the program for j 0.16599321365356445
column j: 1921
Runtime of the program for j 0.16591382026672363
column j: 1922
Runtime of the program for j 0.2025299072265625
column j: 1923
Runtime of the program for j 0.26448941230773926
column j: 1924
Runtime of the program for j 0.19663476943969727
column j: 1925
Runtime of the program for j 0.18664240837097168
column j: 1926
Runtime of the program for j 0.13839960098266602
column j: 1927
Runtime of the program for j 0.1788344383239746
column j: 1928
Runtime of the program for j 0.18781495094299316
column j: 1929
Runtime of the program for j 0.16659307479858398
column j: 1930
Runtime of the program for j 0.2103285789489746
column j: 1931
Runtime of the program for j 0.17862224578857422
column j: 1932
Runtime of the program for j 0.1766035556793213
column j: 1933
Runtime of the program for j 0.1867220401763916
column j: 1934
Runtime of the program for j 0.17663049697875977
column j: 1935
Runtime of the program for j 0.1686093807220459
column j: 1936
Runtime of the program for j 0.2275078296661377
column j: 1937
Runtime of the program for j 0.12322854995727539
column j: 1938
Runtime of the program for j 0.16967487335205078
column j: 1939
Runtime of the program for j 0.17006587982177734

In [7]:
curated_bow['max_noise'] = sss['max_noise']
curated_bow

,id,,.,a,if,return,throw,void,},!,...,"} """,} ',} :,} <,~ /,~ dp0node,class_name,class_value,contents,max_noise
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,1,++ b/README.md,0.725794
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,1,"1,23 @@",0.725794
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,1,This plugin downloads/installs Node and NPM lo...,0.725794
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,1,"It's supposed to work on Windows, OS X and Linux.",0.725794
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,1,NaN,0.725794
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,++ b/frontend-maven-plugin/src/main/java/com/g...,4.420658
4990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,},4.420658
4991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,"39,6 @@ public final class BowerMojo extends A...",5.420658
4992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,this.additionalEnvironment = additiona...,5.420658
4993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,++ b/frontend-plugin-core/src/main/java/com/gi...,8.925107

In [8]:
s = sss.sort_values(by='max_noise', ascending = False)
s = s.drop_duplicates(subset = 'max_noise')

values = []
for x in s['max_noise'].iloc[0:10]:
    values.append(x)

In [9]:
noise_sorted = curated_bow.sort_values(by='max_noise', ascending = False)
noise_sorted.drop(noise_sorted[noise_sorted['max_noise'].isin(values) == True].index, axis = 0, inplace = True)
noise_sorted = noise_sorted.reset_index()
noise_sorted = noise_sorted.drop('index', axis=1)
noise_sorted

,id,,.,a,if,return,throw,void,},!,...,"} """,} ',} :,} <,~ /,~ dp0node,class_name,class_value,contents,max_noise
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,"99,9 @@ final class ProcessExecutor {",0.607043
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,factory.getBowerRunner(proxyConfig).ex...,0.606704
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,"27,7 @@ Include the plugin as a dependency in ...",0.606364
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,"config.getPlatform(),",0.606241
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,++ b/frontend-maven-plugin/src/main/java/com/g...,0.606241
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1056,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,"@Parameter(property = ""skip.karma"", defaul...",0.497558
1057,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,* Additional environment variables to pass ...,0.497558
1058,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,public interface WebpackRunner extends NodeTas...,0.497558
1059,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,++ b/frontend-plugin-core/src/main/java/com/gi...,0.497558
1060,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,"43,7 @@ public final class KarmaRunMojo extend...",0.497558

In [10]:
noise_sorted.to_csv('attribute_noise_cleaned.csv')
noise_sorted

,id,,.,a,if,return,throw,void,},!,...,"} """,} ',} :,} <,~ /,~ dp0node,class_name,class_value,contents,max_noise
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,"99,9 @@ final class ProcessExecutor {",0.607043
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,factory.getBowerRunner(proxyConfig).ex...,0.606704
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,"27,7 @@ Include the plugin as a dependency in ...",0.606364
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,"config.getPlatform(),",0.606241
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,++ b/frontend-maven-plugin/src/main/java/com/g...,0.606241
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1056,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,"@Parameter(property = ""skip.karma"", defaul...",0.497558
1057,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,* Additional environment variables to pass ...,0.497558
1058,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,public interface WebpackRunner extends NodeTas...,0.497558
1059,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,++ b/frontend-plugin-core/src/main/java/com/gi...,0.497558
1060,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,"43,7 @@ public final class KarmaRunMojo extend...",0.497558