In [1]:
import pandas as pd
import time
import numpy as np

In [2]:
# Import Dataset
curated_bow = pd.read_csv('FrontendMavenPlugin.csv', sep='$')
curated_bow.dropna()
# Remove Trailing Spaces in Column Names
curated_bow.columns = [col.strip() for col in curated_bow.columns]
curated_bow

,id,,,,.,a,if,return,throw,void,...,"} """,} ',} :,} <,~,~ /,~ dp0node,class_name,class_value,contents
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,++ b/README.md
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,"1,23 @@"
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,This plugin downloads/installs Node and NPM lo...
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,"It's supposed to work on Windows, OS X and Linux."
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,++ b/frontend-maven-plugin/src/main/java/com/g...
4990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,}
4991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,"39,6 @@ public final class BowerMojo extends A..."
4992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,this.additionalEnvironment = additiona...
4993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,++ b/frontend-plugin-core/src/main/java/com/gi...

In [3]:
# Duplicate Columns Removed
curated_bow = curated_bow.loc[:,~curated_bow.columns.duplicated()].copy()
curated_bow

,id,,.,a,if,return,throw,void,},!,...,| |,"} """,} ',} :,} <,~ /,~ dp0node,class_name,class_value,contents
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,++ b/README.md
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,"1,23 @@"
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,This plugin downloads/installs Node and NPM lo...
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,"It's supposed to work on Windows, OS X and Linux."
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,++ b/frontend-maven-plugin/src/main/java/com/g...
4990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,}
4991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,"39,6 @@ public final class BowerMojo extends A..."
4992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,this.additionalEnvironment = additiona...
4993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,++ b/frontend-plugin-core/src/main/java/com/gi...

In [4]:
partitions_ = 1
bin_size = len(curated_bow.index)//partitions_ 
print(bin_size)

4994

In [5]:
def run_Panda():
    bins_counter = 0
    partition_values = pd.DataFrame()
    j_col= pd.DataFrame()
#     k_col= pd.DataFrame()
    
#     for j in range(len(curated_bow.columns)-3): 
    for j in range(len(curated_bow.columns)-3):
        start_j = time.time()
        clustered_att = curated_bow.sort_values(by = curated_bow.columns[j])
        
        bins_counter = 0
#         if j != j:
        for y in range(partitions_): 
            parition_mean = clustered_att.iloc[bins_counter: bins_counter + bin_size, j].values.mean()
            partition_sd = clustered_att.iloc[bins_counter: bins_counter + bin_size, j].values.std()
            mean_over_sd = parition_mean/partition_sd if partition_sd else 0

            noise_score = pd.DataFrame([np.nan_to_num(abs(x - (mean_over_sd)))
                                        for x in clustered_att.iloc[bins_counter:bins_counter + bin_size, j]])

            partition_values = pd.concat([partition_values, noise_score], axis=0)
                    
            #dropping existing indices with the same name and replacing them with new, using reset index
            partition_values= partition_values.reset_index(drop=True) 
            bins_counter = bins_counter + bin_size
#         else:
#             continue
            
        j_col= pd.concat([j_col, partition_values], axis= 1)
        partition_values.drop(partition_values.index, inplace=True)
        
        end_j = time.time()
        print("column j: " + str(j))
        print(f"Runtime of the program for j {end_j - start_j}")
        
    return j_col

In [6]:
sss = run_Panda()
sss['max_noise'] = sss.max(axis=1)

column j: 0
Runtime of the program for j 0.09156036376953125
column j: 1
Runtime of the program for j 0.09646272659301758
column j: 2
Runtime of the program for j 0.09550833702087402
column j: 3
Runtime of the program for j 0.09200119972229004
column j: 4
Runtime of the program for j 0.09937429428100586
column j: 5
Runtime of the program for j 0.09554839134216309
column j: 6
Runtime of the program for j 0.0943763256072998
column j: 7
Runtime of the program for j 0.09253931045532227
column j: 8
Runtime of the program for j 0.09836149215698242
column j: 9
Runtime of the program for j 0.08854150772094727
column j: 10
Runtime of the program for j 0.0955197811126709
column j: 11
Runtime of the program for j 0.05351853370666504
column j: 12
Runtime of the program for j 0.0925445556640625
column j: 13
Runtime of the program for j 0.08700180053710938
column j: 14
Runtime of the program for j 0.0955190658569336
column j: 15
Runtime of the program for j 0.0885462760925293
column j: 16
Runtime of the program for j 0.09065389633178711
column j: 17
Runtime of the program for j 0.0945127010345459
column j: 18
Runtime of the program for j 0.09691762924194336
column j: 19
Runtime of the program for j 0.09752392768859863
column j: 20
Runtime of the program for j 0.09154725074768066
column j: 21
Runtime of the program for j 0.08752584457397461
column j: 22
Runtime of the program for j 0.09255290031433105
column j: 23
Runtime of the program for j 0.09255361557006836
column j: 24
Runtime of the program for j 0.09255027770996094
column j: 25
Runtime of the program for j 0.09254693984985352
column j: 26
Runtime of the program for j 0.09761643409729004
column j: 27
Runtime of the program for j 0.09100937843322754
column j: 28
Runtime of the program for j 0.09058880805969238
column j: 29
Runtime of the program for j 0.09467864036560059
column j: 30
Runtime of the program for j 0.09854507446289062
column j: 31
Runtime of the program for j 0.09055256843566895
column j: 32
Runtime of the program for j 0.09456729888916016
column j: 33
Runtime of the program for j 0.08752179145812988
column j: 34
Runtime of the program for j 0.08751106262207031
column j: 35
Runtime of the program for j 0.051058292388916016
column j: 36
Runtime of the program for j 0.08812117576599121
column j: 37
Runtime of the program for j 0.08361673355102539
column j: 38
Runtime of the program for j 0.08860135078430176
column j: 39
Runtime of the program for j 0.04853677749633789
column j: 40
Runtime of the program for j 0.08603119850158691
column j: 41
Runtime of the program for j 0.08459067344665527
column j: 42
Runtime of the program for j 0.09114646911621094
column j: 43
Runtime of the program for j 0.08652567863464355
column j: 44
Runtime of the program for j 0.09660220146179199
column j: 45
Runtime of the program for j 0.09511566162109375
column j: 46
Runtime of the program for j 0.0975499153137207
column j: 47
Runtime of the program for j 0.05398440361022949
column j: 48
Runtime of the program for j 0.05652022361755371
column j: 49
Runtime of the program for j 0.09561371803283691
column j: 50
Runtime of the program for j 0.0925436019897461
column j: 51
Runtime of the program for j 0.09454655647277832
column j: 52
Runtime of the program for j 0.09153628349304199
column j: 53
Runtime of the program for j 0.08854055404663086
column j: 54
Runtime of the program for j 0.08849668502807617
column j: 55
Runtime of the program for j 0.09203028678894043
column j: 56
Runtime of the program for j 0.08754849433898926
column j: 57
Runtime of the program for j 0.04953455924987793
column j: 58
Runtime of the program for j 0.08851933479309082
column j: 59
Runtime of the program for j 0.09281420707702637
column j: 60
Runtime of the program for j 0.08892202377319336
column j: 61
Runtime of the program for j 0.0851430892944336
column j: 62
Runtime of the program for j 0.08753132820129395
column j: 63
Runtime of the program for j 0.09051775932312012
column j: 64
Runtime of the program for j 0.049508094787597656
column j: 65
Runtime of the program for j 0.09265851974487305
column j: 66
Runtime of the program for j 0.08902192115783691
column j: 67
Runtime of the program for j 0.08752942085266113
column j: 68
Runtime of the program for j 0.05058765411376953
column j: 69
Runtime of the program for j 0.0867776870727539
column j: 70
Runtime of the program for j 0.08695459365844727
column j: 71
Runtime of the program for j 0.09401535987854004
column j: 72
Runtime of the program for j 0.08853745460510254
column j: 73
Runtime of the program for j 0.08560585975646973
column j: 74
Runtime of the program for j 0.08963918685913086
column j: 75
Runtime of the program for j 0.08666443824768066
column j: 76
Runtime of the program for j 0.08851218223571777
column j: 77
Runtime of the program for j 0.05801248550415039
column j: 78
Runtime of the program for j 0.051735877990722656
column j: 79
Runtime of the program for j 0.08471345901489258
column j: 80
Runtime of the program for j 0.08637332916259766
column j: 81
Runtime of the program for j 0.08901524543762207
column j: 82
Runtime of the program for j 0.0985114574432373
column j: 83
Runtime of the program for j 0.09301424026489258
column j: 84
Runtime of the program for j 0.08953237533569336
column j: 85
Runtime of the program for j 0.09216070175170898
column j: 86
Runtime of the program for j 0.09154224395751953
column j: 87
Runtime of the program for j 0.09053230285644531
column j: 88
Runtime of the program for j 0.09041643142700195
column j: 89
Runtime of the program for j 0.09052371978759766
column j: 90
Runtime of the program for j 0.08855509757995605
column j: 91
Runtime of the program for j 0.08850240707397461
column j: 92
Runtime of the program for j 0.08962750434875488
column j: 93
Runtime of the program for j 0.08599519729614258
column j: 94
Runtime of the program for j 0.08650684356689453
column j: 95
Runtime of the program for j 0.08951807022094727
column j: 96
Runtime of the program for j 0.087554931640625
column j: 97
Runtime of the program for j 0.08651876449584961
column j: 98
Runtime of the program for j 0.08851170539855957
column j: 99
Runtime of the program for j 0.08669447898864746
column j: 100
Runtime of the program for j 0.08859372138977051
column j: 101
Runtime of the program for j 0.09006214141845703
column j: 102
Runtime of the program for j 0.08803033828735352
column j: 103
Runtime of the program for j 0.08651852607727051
column j: 104
Runtime of the program for j 0.08877325057983398
column j: 105
Runtime of the program for j 0.08637428283691406
column j: 106
Runtime of the program for j 0.08561563491821289
column j: 107
Runtime of the program for j 0.08667254447937012
column j: 108
Runtime of the program for j 0.08778905868530273
column j: 109
Runtime of the program for j 0.04894685745239258
column j: 110
Runtime of the program for j 0.08755302429199219
column j: 111
Runtime of the program for j 0.0875539779663086
column j: 112
Runtime of the program for j 0.09055352210998535
column j: 113
Runtime of the program for j 0.08754944801330566
column j: 114
Runtime of the program for j 0.051000118255615234
column j: 115
Runtime of the program for j 0.08517289161682129
column j: 116
Runtime of the program for j 0.08755135536193848
column j: 117
Runtime of the program for j 0.08852529525756836
column j: 118
Runtime of the program for j 0.08877801895141602
column j: 119
Runtime of the program for j 0.08704733848571777
column j: 120
Runtime of the program for j 0.08865618705749512
column j: 121
Runtime of the program for j 0.08563446998596191
column j: 122
Runtime of the program for j 0.08854341506958008
column j: 123
Runtime of the program for j 0.0875403881072998
column j: 124
Runtime of the program for j 0.09551382064819336
column j: 125
Runtime of the program for j 0.08764100074768066
column j: 126
Runtime of the program for j 0.08857512474060059
column j: 127
Runtime of the program for j 0.08544373512268066
column j: 128
Runtime of the program for j 0.09313678741455078
column j: 129
Runtime of the program for j 0.08861470222473145
column j: 130
Runtime of the program for j 0.08760404586791992
column j: 131
Runtime of the program for j 0.05051755905151367
column j: 132
Runtime of the program for j 0.08975481986999512
column j: 133
Runtime of the program for j 0.08563613891601562

column j: 134
Runtime of the program for j 0.09002804756164551
column j: 135
Runtime of the program for j 0.08653688430786133
column j: 136
Runtime of the program for j 0.09059333801269531
column j: 137
Runtime of the program for j 0.08665204048156738
column j: 138
Runtime of the program for j 0.08965849876403809
column j: 139
Runtime of the program for j 0.08655166625976562
column j: 140
Runtime of the program for j 0.09038352966308594
column j: 141
Runtime of the program for j 0.08754897117614746
column j: 142
Runtime of the program for j 0.08801937103271484
column j: 143
Runtime of the program for j 0.08952450752258301
column j: 144
Runtime of the program for j 0.09060502052307129
column j: 145
Runtime of the program for j 0.08856058120727539
column j: 146
Runtime of the program for j 0.09053754806518555
column j: 147
Runtime of the program for j 0.09056329727172852
column j: 148
Runtime of the program for j 0.08854269981384277
column j: 149
Runtime of the program for j 0.08870530128479004
column j: 150
Runtime of the program for j 0.05299997329711914
column j: 151
Runtime of the program for j 0.0855252742767334
column j: 152
Runtime of the program for j 0.08971977233886719
column j: 153
Runtime of the program for j 0.08848929405212402
column j: 154
Runtime of the program for j 0.08855056762695312
column j: 155
Runtime of the program for j 0.08854460716247559
column j: 156
Runtime of the program for j 0.0895535945892334
column j: 157
Runtime of the program for j 0.08699464797973633
column j: 158
Runtime of the program for j 0.09323596954345703
column j: 159
Runtime of the program for j 0.08853721618652344
column j: 160
Runtime of the program for j 0.09351205825805664
column j: 161
Runtime of the program for j 0.08851885795593262
column j: 162
Runtime of the program for j 0.09165382385253906
column j: 163
Runtime of the program for j 0.05555081367492676
column j: 164
Runtime of the program for j 0.09608054161071777
column j: 165
Runtime of the program for j 0.08955049514770508
column j: 166
Runtime of the program for j 0.09151911735534668
column j: 167
Runtime of the program for j 0.08955860137939453
column j: 168
Runtime of the program for j 0.05357694625854492
column j: 169
Runtime of the program for j 0.0876767635345459
column j: 170
Runtime of the program for j 0.09148454666137695
column j: 171
Runtime of the program for j 0.08801460266113281
column j: 172
Runtime of the program for j 0.09453201293945312
column j: 173
Runtime of the program for j 0.08952784538269043
column j: 174
Runtime of the program for j 0.08857512474060059
column j: 175
Runtime of the program for j 0.08616304397583008
column j: 176
Runtime of the program for j 0.09063267707824707
column j: 177
Runtime of the program for j 0.08755087852478027
column j: 178
Runtime of the program for j 0.09053683280944824
column j: 179
Runtime of the program for j 0.09161710739135742
column j: 180
Runtime of the program for j 0.08802437782287598
column j: 181
Runtime of the program for j 0.0885317325592041
column j: 182
Runtime of the program for j 0.09061360359191895
column j: 183
Runtime of the program for j 0.08746910095214844
column j: 184
Runtime of the program for j 0.08865785598754883
column j: 185
Runtime of the program for j 0.08774113655090332
column j: 186
Runtime of the program for j 0.09056353569030762
column j: 187
Runtime of the program for j 0.08750462532043457
column j: 188
Runtime of the program for j 0.056999921798706055
column j: 189
Runtime of the program for j 0.08953571319580078
column j: 190
Runtime of the program for j 0.08754873275756836
column j: 191
Runtime of the program for j 0.08854866027832031
column j: 192
Runtime of the program for j 0.08832836151123047
column j: 193
Runtime of the program for j 0.08950662612915039
column j: 194
Runtime of the program for j 0.0936582088470459
column j: 195
Runtime of the program for j 0.08701467514038086
column j: 196
Runtime of the program for j 0.08852243423461914
column j: 197
Runtime of the program for j 0.08952045440673828
column j: 198
Runtime of the program for j 0.08854269981384277
column j: 199
Runtime of the program for j 0.08757543563842773
column j: 200
Runtime of the program for j 0.09066414833068848
column j: 201
Runtime of the program for j 0.09055089950561523
column j: 202
Runtime of the program for j 0.08776187896728516
column j: 203
Runtime of the program for j 0.0884857177734375
column j: 204
Runtime of the program for j 0.04999947547912598
column j: 205
Runtime of the program for j 0.08753275871276855
column j: 206
Runtime of the program for j 0.08780789375305176
column j: 207
Runtime of the program for j 0.08748483657836914
column j: 208
Runtime of the program for j 0.08750081062316895
column j: 209
Runtime of the program for j 0.12354803085327148
column j: 210
Runtime of the program for j 0.08850431442260742
column j: 211
Runtime of the program for j 0.08950614929199219
column j: 212
Runtime of the program for j 0.0946197509765625
column j: 213
Runtime of the program for j 0.08801436424255371
column j: 214
Runtime of the program for j 0.08952617645263672
column j: 215
Runtime of the program for j 0.08952188491821289
column j: 216
Runtime of the program for j 0.09058666229248047
column j: 217
Runtime of the program for j 0.0866994857788086
column j: 218
Runtime of the program for j 0.09073543548583984
column j: 219
Runtime of the program for j 0.08673453330993652
column j: 220
Runtime of the program for j 0.09254813194274902
column j: 221
Runtime of the program for j 0.09055089950561523
column j: 222
Runtime of the program for j 0.08699393272399902
column j: 223
Runtime of the program for j 0.08752250671386719
column j: 224
Runtime of the program for j 0.09251952171325684
column j: 225
Runtime of the program for j 0.08654546737670898
column j: 226
Runtime of the program for j 0.09106636047363281
column j: 227
Runtime of the program for j 0.09055256843566895
column j: 228
Runtime of the program for j 0.08879637718200684
column j: 229
Runtime of the program for j 0.08564472198486328
column j: 230
Runtime of the program for j 0.08855152130126953
column j: 231
Runtime of the program for j 0.0871279239654541
column j: 232
Runtime of the program for j 0.08853912353515625
column j: 233
Runtime of the program for j 0.08852100372314453
column j: 234
Runtime of the program for j 0.08855009078979492
column j: 235
Runtime of the program for j 0.05053520202636719
column j: 236
Runtime of the program for j 0.08701634407043457
column j: 237
Runtime of the program for j 0.08855700492858887
column j: 238
Runtime of the program for j 0.08765888214111328
column j: 239
Runtime of the program for j 0.09053778648376465
column j: 240
Runtime of the program for j 0.08754682540893555
column j: 241
Runtime of the program for j 0.08950948715209961
column j: 242
Runtime of the program for j 0.09760284423828125
column j: 243
Runtime of the program for j 0.09023880958557129
column j: 244
Runtime of the program for j 0.0935063362121582
column j: 245
Runtime of the program for j 0.05200481414794922
column j: 246
Runtime of the program for j 0.09020400047302246
column j: 247
Runtime of the program for j 0.0865476131439209
column j: 248
Runtime of the program for j 0.09054398536682129
column j: 249
Runtime of the program for j 0.08855390548706055
column j: 250
Runtime of the program for j 0.08755159378051758
column j: 251
Runtime of the program for j 0.08754467964172363
column j: 252
Runtime of the program for j 0.08701539039611816
column j: 253
Runtime of the program for j 0.08753514289855957
column j: 254
Runtime of the program for j 0.0886073112487793
column j: 255
Runtime of the program for j 0.08849430084228516
column j: 256
Runtime of the program for j 0.08850240707397461
column j: 257
Runtime of the program for j 0.09366631507873535
column j: 258
Runtime of the program for j 0.08851313591003418
column j: 259
Runtime of the program for j 0.09150815010070801
column j: 260
Runtime of the program for j 0.09452176094055176
column j: 261
Runtime of the program for j 0.08852410316467285
column j: 262
Runtime of the program for j 0.09299969673156738
column j: 263
Runtime of the program for j 0.051581382751464844
column j: 264
Runtime of the program for j 0.08948659896850586
column j: 265
Runtime of the program for j 0.08851218223571777

column j: 266
Runtime of the program for j 0.09926033020019531
column j: 267
Runtime of the program for j 0.08755111694335938
column j: 268
Runtime of the program for j 0.08754754066467285
column j: 269
Runtime of the program for j 0.08901715278625488
column j: 270
Runtime of the program for j 0.05109047889709473
column j: 271
Runtime of the program for j 0.08777737617492676
column j: 272
Runtime of the program for j 0.08867001533508301
column j: 273
Runtime of the program for j 0.09055662155151367
column j: 274
Runtime of the program for j 0.0891261100769043
column j: 275
Runtime of the program for j 0.050576210021972656
column j: 276
Runtime of the program for j 0.0905601978302002
column j: 277
Runtime of the program for j 0.08753657341003418
column j: 278
Runtime of the program for j 0.08986449241638184
column j: 279
Runtime of the program for j 0.08650946617126465
column j: 280
Runtime of the program for j 0.08800959587097168
column j: 281
Runtime of the program for j 0.09369230270385742
column j: 282
Runtime of the program for j 0.08852386474609375
column j: 283
Runtime of the program for j 0.0895226001739502
column j: 284
Runtime of the program for j 0.09061765670776367
column j: 285
Runtime of the program for j 0.09055089950561523
column j: 286
Runtime of the program for j 0.08951234817504883
column j: 287
Runtime of the program for j 0.088623046875
column j: 288
Runtime of the program for j 0.08754396438598633
column j: 289
Runtime of the program for j 0.09349775314331055
column j: 290
Runtime of the program for j 0.09002423286437988
column j: 291
Runtime of the program for j 0.08758783340454102
column j: 292
Runtime of the program for j 0.08772754669189453
column j: 293
Runtime of the program for j 0.09044551849365234
column j: 294
Runtime of the program for j 0.09153866767883301
column j: 295
Runtime of the program for j 0.0870966911315918
column j: 296
Runtime of the program for j 0.09576272964477539
column j: 297
Runtime of the program for j 0.08949780464172363
column j: 298
Runtime of the program for j 0.09151601791381836
column j: 299
Runtime of the program for j 0.09177184104919434
column j: 300
Runtime of the program for j 0.08909392356872559
column j: 301
Runtime of the program for j 0.08664941787719727
column j: 302
Runtime of the program for j 0.09065508842468262
column j: 303
Runtime of the program for j 0.0885469913482666
column j: 304
Runtime of the program for j 0.08850526809692383
column j: 305
Runtime of the program for j 0.09159421920776367
column j: 306
Runtime of the program for j 0.08655381202697754
column j: 307
Runtime of the program for j 0.09250116348266602
column j: 308
Runtime of the program for j 0.09162592887878418
column j: 309
Runtime of the program for j 0.08654546737670898
column j: 310
Runtime of the program for j 0.0880134105682373
column j: 311
Runtime of the program for j 0.0885934829711914
column j: 312
Runtime of the program for j 0.08953595161437988
column j: 313
Runtime of the program for j 0.08667969703674316
column j: 314
Runtime of the program for j 0.05355429649353027
column j: 315
Runtime of the program for j 0.08612608909606934
column j: 316
Runtime of the program for j 0.0876152515411377
column j: 317
Runtime of the program for j 0.08865571022033691
column j: 318
Runtime of the program for j 0.08955764770507812
column j: 319
Runtime of the program for j 0.09051322937011719
column j: 320
Runtime of the program for j 0.09152626991271973
column j: 321
Runtime of the program for j 0.051003456115722656
column j: 322
Runtime of the program for j 0.09252405166625977
column j: 323
Runtime of the program for j 0.09151577949523926
column j: 324
Runtime of the program for j 0.08962750434875488
column j: 325
Runtime of the program for j 0.08843040466308594
column j: 326
Runtime of the program for j 0.09651327133178711
column j: 327
Runtime of the program for j 0.08853769302368164
column j: 328
Runtime of the program for j 0.08957171440124512
column j: 329
Runtime of the program for j 0.08907365798950195
column j: 330
Runtime of the program for j 0.09314227104187012
column j: 331
Runtime of the program for j 0.09055161476135254
column j: 332
Runtime of the program for j 0.09201526641845703
column j: 333
Runtime of the program for j 0.09152865409851074
column j: 334
Runtime of the program for j 0.09351849555969238
column j: 335
Runtime of the program for j 0.08858251571655273
column j: 336
Runtime of the program for j 0.09246277809143066
column j: 337
Runtime of the program for j 0.08951210975646973
column j: 338
Runtime of the program for j 0.09074759483337402
column j: 339
Runtime of the program for j 0.0885469913482666
column j: 340
Runtime of the program for j 0.11854362487792969
column j: 341
Runtime of the program for j 0.09251904487609863
column j: 342
Runtime of the program for j 0.08870935440063477
column j: 343
Runtime of the program for j 0.053002357482910156
column j: 344
Runtime of the program for j 0.0905463695526123
column j: 345
Runtime of the program for j 0.08852744102478027
column j: 346
Runtime of the program for j 0.08905601501464844
column j: 347
Runtime of the program for j 0.09151673316955566
column j: 348
Runtime of the program for j 0.09450793266296387
column j: 349
Runtime of the program for j 0.08770990371704102
column j: 350
Runtime of the program for j 0.0906367301940918
column j: 351
Runtime of the program for j 0.0549921989440918
column j: 352
Runtime of the program for j 0.09057259559631348
column j: 353
Runtime of the program for j 0.0885934829711914
column j: 354
Runtime of the program for j 0.09361529350280762
column j: 355
Runtime of the program for j 0.09054255485534668
column j: 356
Runtime of the program for j 0.09670686721801758
column j: 357
Runtime of the program for j 0.08754611015319824
column j: 358
Runtime of the program for j 0.08954453468322754
column j: 359
Runtime of the program for j 0.09351873397827148
column j: 360
Runtime of the program for j 0.05607795715332031
column j: 361
Runtime of the program for j 0.08670568466186523
column j: 362
Runtime of the program for j 0.0916135311126709
column j: 363
Runtime of the program for j 0.10234522819519043
column j: 364
Runtime of the program for j 0.10051584243774414
column j: 365
Runtime of the program for j 0.09453701972961426
column j: 366
Runtime of the program for j 0.09549832344055176
column j: 367
Runtime of the program for j 0.09250688552856445
column j: 368
Runtime of the program for j 0.09447550773620605
column j: 369
Runtime of the program for j 0.09050679206848145
column j: 370
Runtime of the program for j 0.09099960327148438
column j: 371
Runtime of the program for j 0.09353232383728027
column j: 372
Runtime of the program for j 0.09654355049133301
column j: 373
Runtime of the program for j 0.09710264205932617
column j: 374
Runtime of the program for j 0.09354853630065918
column j: 375
Runtime of the program for j 0.08774542808532715
column j: 376
Runtime of the program for j 0.09369421005249023
column j: 377
Runtime of the program for j 0.09453821182250977
column j: 378
Runtime of the program for j 0.0905601978302002
column j: 379
Runtime of the program for j 0.08708977699279785
column j: 380
Runtime of the program for j 0.09772205352783203
column j: 381
Runtime of the program for j 0.0905463695526123
column j: 382
Runtime of the program for j 0.09155035018920898
column j: 383
Runtime of the program for j 0.09191155433654785
column j: 384
Runtime of the program for j 0.08999872207641602
column j: 385
Runtime of the program for j 0.09150886535644531
column j: 386
Runtime of the program for j 0.09851503372192383
column j: 387
Runtime of the program for j 0.09455013275146484
column j: 388
Runtime of the program for j 0.09360504150390625
column j: 389
Runtime of the program for j 0.08866286277770996
column j: 390
Runtime of the program for j 0.08754611015319824
column j: 391
Runtime of the program for j 0.09169602394104004
column j: 392
Runtime of the program for j 0.09254288673400879
column j: 393
Runtime of the program for j 0.05501532554626465
column j: 394
Runtime of the program for j 0.055536746978759766
column j: 395
Runtime of the program for j 0.08754467964172363
column j: 396
Runtime of the program for j 0.09308695793151855
column j: 397
Runtime of the program for j 0.05699467658996582
column j: 398
Runtime of the program for j 0.09155869483947754

column j: 399
Runtime of the program for j 0.09354805946350098
column j: 400
Runtime of the program for j 0.09256911277770996
column j: 401
Runtime of the program for j 0.08669447898864746
column j: 402
Runtime of the program for j 0.0896444320678711
column j: 403
Runtime of the program for j 0.09254789352416992
column j: 404
Runtime of the program for j 0.09651303291320801
column j: 405
Runtime of the program for j 0.09455752372741699
column j: 406
Runtime of the program for j 0.09076619148254395
column j: 407
Runtime of the program for j 0.11246109008789062
column j: 408
Runtime of the program for j 0.09351563453674316
column j: 409
Runtime of the program for j 0.08877158164978027
column j: 410
Runtime of the program for j 0.09299969673156738
column j: 411
Runtime of the program for j 0.09169650077819824
column j: 412
Runtime of the program for j 0.09352445602416992
column j: 413
Runtime of the program for j 0.09186720848083496
column j: 414
Runtime of the program for j 0.0925748348236084
column j: 415
Runtime of the program for j 0.08748650550842285
column j: 416
Runtime of the program for j 0.0895380973815918
column j: 417
Runtime of the program for j 0.09155154228210449
column j: 418
Runtime of the program for j 0.09272909164428711
column j: 419
Runtime of the program for j 0.09351396560668945
column j: 420
Runtime of the program for j 0.09470343589782715
column j: 421
Runtime of the program for j 0.09154725074768066
column j: 422
Runtime of the program for j 0.08800625801086426
column j: 423
Runtime of the program for j 0.08852052688598633
column j: 424
Runtime of the program for j 0.08954572677612305
column j: 425
Runtime of the program for j 0.09050989151000977
column j: 426
Runtime of the program for j 0.09473562240600586
column j: 427
Runtime of the program for j 0.09254097938537598
column j: 428
Runtime of the program for j 0.09651446342468262
column j: 429
Runtime of the program for j 0.09537315368652344
column j: 430
Runtime of the program for j 0.057534217834472656
column j: 431
Runtime of the program for j 0.052016496658325195
column j: 432
Runtime of the program for j 0.05053210258483887
column j: 433
Runtime of the program for j 0.0900115966796875
column j: 434
Runtime of the program for j 0.09355783462524414
column j: 435
Runtime of the program for j 0.09252262115478516
column j: 436
Runtime of the program for j 0.09356117248535156
column j: 437
Runtime of the program for j 0.0915212631225586
column j: 438
Runtime of the program for j 0.055776119232177734
column j: 439
Runtime of the program for j 0.0915992259979248
column j: 440
Runtime of the program for j 0.09255313873291016
column j: 441
Runtime of the program for j 0.08800125122070312
column j: 442
Runtime of the program for j 0.09653759002685547
column j: 443
Runtime of the program for j 0.05254387855529785
column j: 444
Runtime of the program for j 0.0900430679321289
column j: 445
Runtime of the program for j 0.09955024719238281
column j: 446
Runtime of the program for j 0.09852051734924316
column j: 447
Runtime of the program for j 0.09751486778259277
column j: 448
Runtime of the program for j 0.10155200958251953
column j: 449
Runtime of the program for j 0.09954595565795898
column j: 450
Runtime of the program for j 0.09356117248535156
column j: 451
Runtime of the program for j 0.10257172584533691
column j: 452
Runtime of the program for j 0.09455394744873047
column j: 453
Runtime of the program for j 0.09851408004760742
column j: 454
Runtime of the program for j 0.09555912017822266
column j: 455
Runtime of the program for j 0.09250473976135254
column j: 456
Runtime of the program for j 0.09956812858581543
column j: 457
Runtime of the program for j 0.11751794815063477
column j: 458
Runtime of the program for j 0.09856104850769043
column j: 459
Runtime of the program for j 0.1256103515625
column j: 460
Runtime of the program for j 0.09351229667663574
column j: 461
Runtime of the program for j 0.09251236915588379
column j: 462
Runtime of the program for j 0.09856057167053223
column j: 463
Runtime of the program for j 0.09854793548583984
column j: 464
Runtime of the program for j 0.09178566932678223
column j: 465
Runtime of the program for j 0.09368300437927246
column j: 466
Runtime of the program for j 0.09635066986083984
column j: 467
Runtime of the program for j 0.09352397918701172
column j: 468
Runtime of the program for j 0.09577322006225586
column j: 469
Runtime of the program for j 0.09793400764465332
column j: 470
Runtime of the program for j 0.10506653785705566
column j: 471
Runtime of the program for j 0.11053895950317383
column j: 472
Runtime of the program for j 0.10152149200439453
column j: 473
Runtime of the program for j 0.06299996376037598
column j: 474
Runtime of the program for j 0.10452985763549805
column j: 475
Runtime of the program for j 0.09953618049621582
column j: 476
Runtime of the program for j 0.09727811813354492
column j: 477
Runtime of the program for j 0.09853959083557129
column j: 478
Runtime of the program for j 0.09497475624084473
column j: 479
Runtime of the program for j 0.09453010559082031
column j: 480
Runtime of the program for j 0.09464693069458008
column j: 481
Runtime of the program for j 0.0974876880645752
column j: 482
Runtime of the program for j 0.0945577621459961
column j: 483
Runtime of the program for j 0.09666061401367188
column j: 484
Runtime of the program for j 0.10164690017700195
column j: 485
Runtime of the program for j 0.09752345085144043
column j: 486
Runtime of the program for j 0.09805989265441895
column j: 487
Runtime of the program for j 0.0946044921875
column j: 488
Runtime of the program for j 0.09363150596618652
column j: 489
Runtime of the program for j 0.09864354133605957
column j: 490
Runtime of the program for j 0.09758996963500977
column j: 491
Runtime of the program for j 0.10620355606079102
column j: 492
Runtime of the program for j 0.1005556583404541
column j: 493
Runtime of the program for j 0.10513138771057129
column j: 494
Runtime of the program for j 0.10154342651367188
column j: 495
Runtime of the program for j 0.09955668449401855
column j: 496
Runtime of the program for j 0.09656763076782227
column j: 497
Runtime of the program for j 0.06046748161315918
column j: 498
Runtime of the program for j 0.10070204734802246
column j: 499
Runtime of the program for j 0.0995025634765625
column j: 500
Runtime of the program for j 0.09855246543884277
column j: 501
Runtime of the program for j 0.1015021800994873
column j: 502
Runtime of the program for j 0.061064720153808594
column j: 503
Runtime of the program for j 0.12355542182922363
column j: 504
Runtime of the program for j 0.09853982925415039
column j: 505
Runtime of the program for j 0.09854483604431152
column j: 506
Runtime of the program for j 0.09653878211975098
column j: 507
Runtime of the program for j 0.09752273559570312
column j: 508
Runtime of the program for j 0.09155583381652832
column j: 509
Runtime of the program for j 0.09201741218566895
column j: 510
Runtime of the program for j 0.0935211181640625
column j: 511
Runtime of the program for j 0.09454870223999023
column j: 512
Runtime of the program for j 0.09454107284545898
column j: 513
Runtime of the program for j 0.09865593910217285
column j: 514
Runtime of the program for j 0.09455370903015137
column j: 515
Runtime of the program for j 0.06354761123657227
column j: 516
Runtime of the program for j 0.09601116180419922
column j: 517
Runtime of the program for j 0.09852910041809082
column j: 518
Runtime of the program for j 0.09452986717224121
column j: 519
Runtime of the program for j 0.09952783584594727
column j: 520
Runtime of the program for j 0.095184326171875
column j: 521
Runtime of the program for j 0.10051202774047852
column j: 522
Runtime of the program for j 0.1105337142944336
column j: 523
Runtime of the program for j 0.09654664993286133
column j: 524
Runtime of the program for j 0.0961306095123291
column j: 525
Runtime of the program for j 0.057619333267211914
column j: 526
Runtime of the program for j 0.09458255767822266
column j: 527
Runtime of the program for j 0.1014399528503418
column j: 528
Runtime of the program for j 0.09673953056335449
column j: 529
Runtime of the program for j 0.10154509544372559
column j: 530
Runtime of the program for j 0.09856152534484863

column j: 531
Runtime of the program for j 0.10154080390930176
column j: 532
Runtime of the program for j 0.10055041313171387
column j: 533
Runtime of the program for j 0.10060358047485352
column j: 534
Runtime of the program for j 0.09819245338439941
column j: 535
Runtime of the program for j 0.05713939666748047
column j: 536
Runtime of the program for j 0.09370112419128418
column j: 537
Runtime of the program for j 0.0986177921295166
column j: 538
Runtime of the program for j 0.059514522552490234
column j: 539
Runtime of the program for j 0.057717084884643555
column j: 540
Runtime of the program for j 0.0589442253112793
column j: 541
Runtime of the program for j 0.09772467613220215
column j: 542
Runtime of the program for j 0.0961921215057373
column j: 543
Runtime of the program for j 0.09458374977111816
column j: 544
Runtime of the program for j 0.11218786239624023
column j: 545
Runtime of the program for j 0.10051822662353516
column j: 546
Runtime of the program for j 0.10660672187805176
column j: 547
Runtime of the program for j 0.10553860664367676
column j: 548
Runtime of the program for j 0.146071195602417
column j: 549
Runtime of the program for j 0.10753202438354492
column j: 550
Runtime of the program for j 0.06659340858459473
column j: 551
Runtime of the program for j 0.07201480865478516
column j: 552
Runtime of the program for j 0.10454154014587402
column j: 553
Runtime of the program for j 0.0985112190246582
column j: 554
Runtime of the program for j 0.10272765159606934
column j: 555
Runtime of the program for j 0.10449433326721191
column j: 556
Runtime of the program for j 0.11282658576965332
column j: 557
Runtime of the program for j 0.1110684871673584
column j: 558
Runtime of the program for j 0.10154891014099121
column j: 559
Runtime of the program for j 0.10049200057983398
column j: 560
Runtime of the program for j 0.10559272766113281
column j: 561
Runtime of the program for j 0.10077834129333496
column j: 562
Runtime of the program for j 0.0915076732635498
column j: 563
Runtime of the program for j 0.09955906867980957
column j: 564
Runtime of the program for j 0.10252881050109863
column j: 565
Runtime of the program for j 0.1105349063873291
column j: 566
Runtime of the program for j 0.09851861000061035
column j: 567
Runtime of the program for j 0.10351443290710449
column j: 568
Runtime of the program for j 0.10652780532836914
column j: 569
Runtime of the program for j 0.10055303573608398
column j: 570
Runtime of the program for j 0.10155367851257324
column j: 571
Runtime of the program for j 0.06401729583740234
column j: 572
Runtime of the program for j 0.10152912139892578
column j: 573
Runtime of the program for j 0.10153365135192871
column j: 574
Runtime of the program for j 0.09752607345581055
column j: 575
Runtime of the program for j 0.09473395347595215
column j: 576
Runtime of the program for j 0.09157419204711914
column j: 577
Runtime of the program for j 0.10852527618408203
column j: 578
Runtime of the program for j 0.09655618667602539
column j: 579
Runtime of the program for j 0.09553408622741699
column j: 580
Runtime of the program for j 0.11804676055908203
column j: 581
Runtime of the program for j 0.10451936721801758
column j: 582
Runtime of the program for j 0.10280275344848633
column j: 583
Runtime of the program for j 0.09348297119140625
column j: 584
Runtime of the program for j 0.09299850463867188
column j: 585
Runtime of the program for j 0.09765815734863281
column j: 586
Runtime of the program for j 0.11954236030578613
column j: 587
Runtime of the program for j 0.10355877876281738
column j: 588
Runtime of the program for j 0.09254717826843262
column j: 589
Runtime of the program for j 0.09201669692993164
column j: 590
Runtime of the program for j 0.10108447074890137
column j: 591
Runtime of the program for j 0.09200549125671387
column j: 592
Runtime of the program for j 0.09751200675964355
column j: 593
Runtime of the program for j 0.09057354927062988
column j: 594
Runtime of the program for j 0.09964990615844727
column j: 595
Runtime of the program for j 0.07054495811462402
column j: 596
Runtime of the program for j 0.09169721603393555
column j: 597
Runtime of the program for j 0.09864950180053711
column j: 598
Runtime of the program for j 0.09752082824707031
column j: 599
Runtime of the program for j 0.09570741653442383
column j: 600
Runtime of the program for j 0.09545302391052246
column j: 601
Runtime of the program for j 0.06300115585327148
column j: 602
Runtime of the program for j 0.0972440242767334
column j: 603
Runtime of the program for j 0.09760403633117676
column j: 604
Runtime of the program for j 0.0925145149230957
column j: 605
Runtime of the program for j 0.10158729553222656
column j: 606
Runtime of the program for j 0.08873844146728516
column j: 607
Runtime of the program for j 0.09944462776184082
column j: 608
Runtime of the program for j 0.09851646423339844
column j: 609
Runtime of the program for j 0.09558963775634766
column j: 610
Runtime of the program for j 0.09565234184265137
column j: 611
Runtime of the program for j 0.10056352615356445
column j: 612
Runtime of the program for j 0.09064245223999023
column j: 613
Runtime of the program for j 0.09854245185852051
column j: 614
Runtime of the program for j 0.09056878089904785
column j: 615
Runtime of the program for j 0.09576869010925293
column j: 616
Runtime of the program for j 0.09370565414428711
column j: 617
Runtime of the program for j 0.0966644287109375
column j: 618
Runtime of the program for j 0.09522294998168945
column j: 619
Runtime of the program for j 0.10550999641418457
column j: 620
Runtime of the program for j 0.11867642402648926
column j: 621
Runtime of the program for j 0.1041409969329834
column j: 622
Runtime of the program for j 0.08951973915100098
column j: 623
Runtime of the program for j 0.09871053695678711
column j: 624
Runtime of the program for j 0.09277772903442383
column j: 625
Runtime of the program for j 0.09555935859680176
column j: 626
Runtime of the program for j 0.09877443313598633
column j: 627
Runtime of the program for j 0.09774541854858398
column j: 628
Runtime of the program for j 0.0904541015625
column j: 629
Runtime of the program for j 0.10677909851074219
column j: 630
Runtime of the program for j 0.09549665451049805
column j: 631
Runtime of the program for j 0.09554910659790039
column j: 632
Runtime of the program for j 0.09655308723449707
column j: 633
Runtime of the program for j 0.09804725646972656
column j: 634
Runtime of the program for j 0.09201931953430176
column j: 635
Runtime of the program for j 0.09765267372131348
column j: 636
Runtime of the program for j 0.09066438674926758
column j: 637
Runtime of the program for j 0.08971571922302246
column j: 638
Runtime of the program for j 0.09567689895629883
column j: 639
Runtime of the program for j 0.05753684043884277
column j: 640
Runtime of the program for j 0.0945744514465332
column j: 641
Runtime of the program for j 0.10469675064086914
column j: 642
Runtime of the program for j 0.09172344207763672
column j: 643
Runtime of the program for j 0.09972786903381348
column j: 644
Runtime of the program for j 0.09605979919433594
column j: 645
Runtime of the program for j 0.09655642509460449
column j: 646
Runtime of the program for j 0.09653806686401367
column j: 647
Runtime of the program for j 0.1005849838256836
column j: 648
Runtime of the program for j 0.09354925155639648
column j: 649
Runtime of the program for j 0.10112977027893066
column j: 650
Runtime of the program for j 0.10015702247619629
column j: 651
Runtime of the program for j 0.06299996376037598
column j: 652
Runtime of the program for j 0.14305901527404785
column j: 653
Runtime of the program for j 0.11352825164794922
column j: 654
Runtime of the program for j 0.10454559326171875
column j: 655
Runtime of the program for j 0.11650657653808594
column j: 656
Runtime of the program for j 0.10954666137695312
column j: 657
Runtime of the program for j 0.10653162002563477
column j: 658
Runtime of the program for j 0.11066603660583496
column j: 659
Runtime of the program for j 0.12356185913085938
column j: 660
Runtime of the program for j 0.10255193710327148
column j: 661
Runtime of the program for j 0.11306476593017578

column j: 662
Runtime of the program for j 0.1012110710144043
column j: 663
Runtime of the program for j 0.10201358795166016
column j: 664
Runtime of the program for j 0.10455536842346191
column j: 665
Runtime of the program for j 0.10855364799499512
column j: 666
Runtime of the program for j 0.09955716133117676
column j: 667
Runtime of the program for j 0.10861444473266602
column j: 668
Runtime of the program for j 0.1025693416595459
column j: 669
Runtime of the program for j 0.10555505752563477
column j: 670
Runtime of the program for j 0.11154341697692871
column j: 671
Runtime of the program for j 0.10953092575073242
column j: 672
Runtime of the program for j 0.10055232048034668
column j: 673
Runtime of the program for j 0.10351753234863281
column j: 674
Runtime of the program for j 0.09551191329956055
column j: 675
Runtime of the program for j 0.10151958465576172
column j: 676
Runtime of the program for j 0.09952449798583984
column j: 677
Runtime of the program for j 0.10961151123046875
column j: 678
Runtime of the program for j 0.10690855979919434
column j: 679
Runtime of the program for j 0.0975334644317627
column j: 680
Runtime of the program for j 0.0975501537322998
column j: 681
Runtime of the program for j 0.06454944610595703
column j: 682
Runtime of the program for j 0.09550952911376953
column j: 683
Runtime of the program for j 0.10850930213928223
column j: 684
Runtime of the program for j 0.09761309623718262
column j: 685
Runtime of the program for j 0.09850478172302246
column j: 686
Runtime of the program for j 0.11757302284240723
column j: 687
Runtime of the program for j 0.10065698623657227
column j: 688
Runtime of the program for j 0.09344696998596191
column j: 689
Runtime of the program for j 0.09965157508850098
column j: 690
Runtime of the program for j 0.09660029411315918
column j: 691
Runtime of the program for j 0.10057497024536133
column j: 692
Runtime of the program for j 0.09168219566345215
column j: 693
Runtime of the program for j 0.10001850128173828
column j: 694
Runtime of the program for j 0.09654664993286133
column j: 695
Runtime of the program for j 0.09661650657653809
column j: 696
Runtime of the program for j 0.10151314735412598
column j: 697
Runtime of the program for j 0.10151147842407227
column j: 698
Runtime of the program for j 0.10555005073547363
column j: 699
Runtime of the program for j 0.09455299377441406
column j: 700
Runtime of the program for j 0.10552763938903809
column j: 701
Runtime of the program for j 0.10956001281738281
column j: 702
Runtime of the program for j 0.10553312301635742
column j: 703
Runtime of the program for j 0.11254000663757324
column j: 704
Runtime of the program for j 0.10562372207641602
column j: 705
Runtime of the program for j 0.10155129432678223
column j: 706
Runtime of the program for j 0.10154104232788086
column j: 707
Runtime of the program for j 0.10412073135375977
column j: 708
Runtime of the program for j 0.10060882568359375
column j: 709
Runtime of the program for j 0.0915534496307373
column j: 710
Runtime of the program for j 0.1225275993347168
column j: 711
Runtime of the program for j 0.0976722240447998
column j: 712
Runtime of the program for j 0.0975809097290039
column j: 713
Runtime of the program for j 0.09363436698913574
column j: 714
Runtime of the program for j 0.09866118431091309
column j: 715
Runtime of the program for j 0.09473013877868652
column j: 716
Runtime of the program for j 0.09266543388366699
column j: 717
Runtime of the program for j 0.09254813194274902
column j: 718
Runtime of the program for j 0.1085209846496582
column j: 719
Runtime of the program for j 0.10152173042297363
column j: 720
Runtime of the program for j 0.09755563735961914
column j: 721
Runtime of the program for j 0.10353899002075195
column j: 722
Runtime of the program for j 0.10518932342529297
column j: 723
Runtime of the program for j 0.1066133975982666
column j: 724
Runtime of the program for j 0.09754037857055664
column j: 725
Runtime of the program for j 0.1065528392791748
column j: 726
Runtime of the program for j 0.10260272026062012
column j: 727
Runtime of the program for j 0.10463261604309082
column j: 728
Runtime of the program for j 0.09754753112792969
column j: 729
Runtime of the program for j 0.10259485244750977
column j: 730
Runtime of the program for j 0.09653162956237793
column j: 731
Runtime of the program for j 0.0965566635131836
column j: 732
Runtime of the program for j 0.12809443473815918
column j: 733
Runtime of the program for j 0.10272598266601562
column j: 734
Runtime of the program for j 0.09858202934265137
column j: 735
Runtime of the program for j 0.09548282623291016
column j: 736
Runtime of the program for j 0.09255146980285645
column j: 737
Runtime of the program for j 0.10009527206420898
column j: 738
Runtime of the program for j 0.10054922103881836
column j: 739
Runtime of the program for j 0.09355711936950684
column j: 740
Runtime of the program for j 0.09199762344360352
column j: 741
Runtime of the program for j 0.1045379638671875
column j: 742
Runtime of the program for j 0.06007075309753418
column j: 743
Runtime of the program for j 0.09551811218261719
column j: 744
Runtime of the program for j 0.09424352645874023
column j: 745
Runtime of the program for j 0.10064315795898438
column j: 746
Runtime of the program for j 0.09573578834533691
column j: 747
Runtime of the program for j 0.09470129013061523
column j: 748
Runtime of the program for j 0.09265995025634766
column j: 749
Runtime of the program for j 0.1095120906829834
column j: 750
Runtime of the program for j 0.0997774600982666
column j: 751
Runtime of the program for j 0.0986948013305664
column j: 752
Runtime of the program for j 0.09546089172363281
column j: 753
Runtime of the program for j 0.10381841659545898
column j: 754
Runtime of the program for j 0.12664079666137695
column j: 755
Runtime of the program for j 0.10654902458190918
column j: 756
Runtime of the program for j 0.09352326393127441
column j: 757
Runtime of the program for j 0.10651135444641113
column j: 758
Runtime of the program for j 0.11055326461791992
column j: 759
Runtime of the program for j 0.1055288314819336
column j: 760
Runtime of the program for j 0.09251618385314941
column j: 761
Runtime of the program for j 0.09751701354980469
column j: 762
Runtime of the program for j 0.10663676261901855
column j: 763
Runtime of the program for j 0.10755443572998047
column j: 764
Runtime of the program for j 0.09554648399353027
column j: 765
Runtime of the program for j 0.09652996063232422
column j: 766
Runtime of the program for j 0.06755208969116211
column j: 767
Runtime of the program for j 0.1045379638671875
column j: 768
Runtime of the program for j 0.061003923416137695
column j: 769
Runtime of the program for j 0.10380005836486816
column j: 770
Runtime of the program for j 0.09754705429077148
column j: 771
Runtime of the program for j 0.10948872566223145
column j: 772
Runtime of the program for j 0.11054158210754395
column j: 773
Runtime of the program for j 0.10255718231201172
column j: 774
Runtime of the program for j 0.10054731369018555
column j: 775
Runtime of the program for j 0.11454129219055176
column j: 776
Runtime of the program for j 0.13956332206726074
column j: 777
Runtime of the program for j 0.10154938697814941
column j: 778
Runtime of the program for j 0.09465479850769043
column j: 779
Runtime of the program for j 0.0955958366394043
column j: 780
Runtime of the program for j 0.06552934646606445
column j: 781
Runtime of the program for j 0.10270071029663086
column j: 782
Runtime of the program for j 0.09875226020812988
column j: 783
Runtime of the program for j 0.09766960144042969
column j: 784
Runtime of the program for j 0.09454679489135742
column j: 785
Runtime of the program for j 0.10354232788085938
column j: 786
Runtime of the program for j 0.10171127319335938
column j: 787
Runtime of the program for j 0.10062575340270996
column j: 788
Runtime of the program for j 0.09466791152954102
column j: 789
Runtime of the program for j 0.10570812225341797
column j: 790
Runtime of the program for j 0.09781289100646973
column j: 791
Runtime of the program for j 0.10646510124206543
column j: 792
Runtime of the program for j 0.10355353355407715
column j: 793
Runtime of the program for j 0.09854245185852051
column j: 794
Runtime of the program for j 0.10251235961914062

column j: 795
Runtime of the program for j 0.10366678237915039
column j: 796
Runtime of the program for j 0.12856078147888184
column j: 797
Runtime of the program for j 0.10094118118286133
column j: 798
Runtime of the program for j 0.09455513954162598
column j: 799
Runtime of the program for j 0.09652137756347656
column j: 800
Runtime of the program for j 0.1026761531829834
column j: 801
Runtime of the program for j 0.10167479515075684
column j: 802
Runtime of the program for j 0.09777951240539551
column j: 803
Runtime of the program for j 0.09559822082519531
column j: 804
Runtime of the program for j 0.09455394744873047
column j: 805
Runtime of the program for j 0.10353660583496094
column j: 806
Runtime of the program for j 0.09974789619445801
column j: 807
Runtime of the program for j 0.10653829574584961
column j: 808
Runtime of the program for j 0.1025385856628418
column j: 809
Runtime of the program for j 0.09752631187438965
column j: 810
Runtime of the program for j 0.1025700569152832
column j: 811
Runtime of the program for j 0.10452961921691895
column j: 812
Runtime of the program for j 0.09931349754333496
column j: 813
Runtime of the program for j 0.10251307487487793
column j: 814
Runtime of the program for j 0.09251260757446289
column j: 815
Runtime of the program for j 0.12329435348510742
column j: 816
Runtime of the program for j 0.10171699523925781
column j: 817
Runtime of the program for j 0.10247039794921875
column j: 818
Runtime of the program for j 0.10251498222351074
column j: 819
Runtime of the program for j 0.10078811645507812
column j: 820
Runtime of the program for j 0.09248542785644531
column j: 821
Runtime of the program for j 0.0968008041381836
column j: 822
Runtime of the program for j 0.1024467945098877
column j: 823
Runtime of the program for j 0.10850715637207031
column j: 824
Runtime of the program for j 0.10070419311523438
column j: 825
Runtime of the program for j 0.09579610824584961
column j: 826
Runtime of the program for j 0.09448695182800293
column j: 827
Runtime of the program for j 0.10435843467712402
column j: 828
Runtime of the program for j 0.10251045227050781
column j: 829
Runtime of the program for j 0.10378599166870117
column j: 830
Runtime of the program for j 0.09847187995910645
column j: 831
Runtime of the program for j 0.09558534622192383
column j: 832
Runtime of the program for j 0.09281063079833984
column j: 833
Runtime of the program for j 0.09504961967468262
column j: 834
Runtime of the program for j 0.12427115440368652
column j: 835
Runtime of the program for j 0.09769487380981445
column j: 836
Runtime of the program for j 0.09444236755371094
column j: 837
Runtime of the program for j 0.10277819633483887
column j: 838
Runtime of the program for j 0.0974574089050293
column j: 839
Runtime of the program for j 0.09651446342468262
column j: 840
Runtime of the program for j 0.10076045989990234
column j: 841
Runtime of the program for j 0.09849095344543457
column j: 842
Runtime of the program for j 0.10101318359375
column j: 843
Runtime of the program for j 0.09950613975524902
column j: 844
Runtime of the program for j 0.09976983070373535
column j: 845
Runtime of the program for j 0.09107494354248047
column j: 846
Runtime of the program for j 0.09473299980163574
column j: 847
Runtime of the program for j 0.10073423385620117
column j: 848
Runtime of the program for j 0.09662294387817383
column j: 849
Runtime of the program for j 0.06659102439880371
column j: 850
Runtime of the program for j 0.09464836120605469
column j: 851
Runtime of the program for j 0.10054588317871094
column j: 852
Runtime of the program for j 0.09458136558532715
column j: 853
Runtime of the program for j 0.1226503849029541
column j: 854
Runtime of the program for j 0.10017514228820801
column j: 855
Runtime of the program for j 0.09845638275146484
column j: 856
Runtime of the program for j 0.1015174388885498
column j: 857
Runtime of the program for j 0.10014581680297852
column j: 858
Runtime of the program for j 0.10271930694580078
column j: 859
Runtime of the program for j 0.09651327133178711
column j: 860
Runtime of the program for j 0.09450578689575195
column j: 861
Runtime of the program for j 0.1007838249206543
column j: 862
Runtime of the program for j 0.0936729907989502
column j: 863
Runtime of the program for j 0.10254573822021484
column j: 864
Runtime of the program for j 0.09454965591430664
column j: 865
Runtime of the program for j 0.10053586959838867
column j: 866
Runtime of the program for j 0.0936579704284668
column j: 867
Runtime of the program for j 0.0945441722869873
column j: 868
Runtime of the program for j 0.09354662895202637
column j: 869
Runtime of the program for j 0.09780716896057129
column j: 870
Runtime of the program for j 0.10070371627807617
column j: 871
Runtime of the program for j 0.12465333938598633
column j: 872
Runtime of the program for j 0.09955072402954102
column j: 873
Runtime of the program for j 0.0989389419555664
column j: 874
Runtime of the program for j 0.10151100158691406
column j: 875
Runtime of the program for j 0.09558224678039551
column j: 876
Runtime of the program for j 0.0935063362121582
column j: 877
Runtime of the program for j 0.10170817375183105
column j: 878
Runtime of the program for j 0.09768557548522949
column j: 879
Runtime of the program for j 0.10050773620605469
column j: 880
Runtime of the program for j 0.09578323364257812
column j: 881
Runtime of the program for j 0.1004946231842041
column j: 882
Runtime of the program for j 0.09554505348205566
column j: 883
Runtime of the program for j 0.10224366188049316
column j: 884
Runtime of the program for j 0.0917668342590332
column j: 885
Runtime of the program for j 0.09748244285583496
column j: 886
Runtime of the program for j 0.10355114936828613
column j: 887
Runtime of the program for j 0.06201529502868652
column j: 888
Runtime of the program for j 0.1286017894744873
column j: 889
Runtime of the program for j 0.10054993629455566
column j: 890
Runtime of the program for j 0.1016240119934082
column j: 891
Runtime of the program for j 0.0975499153137207
column j: 892
Runtime of the program for j 0.10254597663879395
column j: 893
Runtime of the program for j 0.09754300117492676
column j: 894
Runtime of the program for j 0.09450554847717285
column j: 895
Runtime of the program for j 0.0600581169128418
column j: 896
Runtime of the program for j 0.09459805488586426
column j: 897
Runtime of the program for j 0.10565018653869629
column j: 898
Runtime of the program for j 0.0945279598236084
column j: 899
Runtime of the program for j 0.07172918319702148
column j: 900
Runtime of the program for j 0.09650540351867676
column j: 901
Runtime of the program for j 0.10271883010864258
column j: 902
Runtime of the program for j 0.09445500373840332
column j: 903
Runtime of the program for j 0.10150980949401855
column j: 904
Runtime of the program for j 0.12012386322021484
column j: 905
Runtime of the program for j 0.09667634963989258
column j: 906
Runtime of the program for j 0.10055017471313477
column j: 907
Runtime of the program for j 0.0965414047241211
column j: 908
Runtime of the program for j 0.10161471366882324
column j: 909
Runtime of the program for j 0.10054993629455566
column j: 910
Runtime of the program for j 0.1035451889038086
column j: 911
Runtime of the program for j 0.09954977035522461
column j: 912
Runtime of the program for j 0.09754467010498047
column j: 913
Runtime of the program for j 0.09982824325561523
column j: 914
Runtime of the program for j 0.09969425201416016
column j: 915
Runtime of the program for j 0.09549617767333984
column j: 916
Runtime of the program for j 0.09369444847106934
column j: 917
Runtime of the program for j 0.09250283241271973
column j: 918
Runtime of the program for j 0.09551191329956055
column j: 919
Runtime of the program for j 0.10522866249084473
column j: 920
Runtime of the program for j 0.0935523509979248
column j: 921
Runtime of the program for j 0.1335463523864746
column j: 922
Runtime of the program for j 0.09454703330993652
column j: 923
Runtime of the program for j 0.10254454612731934
column j: 924
Runtime of the program for j 0.09555220603942871
column j: 925
Runtime of the program for j 0.10254645347595215
column j: 926
Runtime of the program for j 0.0955507755279541

column j: 927
Runtime of the program for j 0.10133790969848633
column j: 928
Runtime of the program for j 0.09565305709838867
column j: 929
Runtime of the program for j 0.10563302040100098
column j: 930
Runtime of the program for j 0.09654760360717773
column j: 931
Runtime of the program for j 0.0935506820678711
column j: 932
Runtime of the program for j 0.09259724617004395
column j: 933
Runtime of the program for j 0.06171250343322754
column j: 934
Runtime of the program for j 0.09997749328613281
column j: 935
Runtime of the program for j 0.09954619407653809
column j: 936
Runtime of the program for j 0.10251832008361816
column j: 937
Runtime of the program for j 0.0931553840637207
column j: 938
Runtime of the program for j 0.12830829620361328
column j: 939
Runtime of the program for j 0.10054826736450195
column j: 940
Runtime of the program for j 0.10251259803771973
column j: 941
Runtime of the program for j 0.09977436065673828
column j: 942
Runtime of the program for j 0.10144233703613281
column j: 943
Runtime of the program for j 0.0990138053894043
column j: 944
Runtime of the program for j 0.11153721809387207
column j: 945
Runtime of the program for j 0.10651326179504395
column j: 946
Runtime of the program for j 0.1225132942199707
column j: 947
Runtime of the program for j 0.10354280471801758
column j: 948
Runtime of the program for j 0.10378623008728027
column j: 949
Runtime of the program for j 0.10518479347229004
column j: 950
Runtime of the program for j 0.10857558250427246
column j: 951
Runtime of the program for j 0.1035163402557373
column j: 952
Runtime of the program for j 0.10453128814697266
column j: 953
Runtime of the program for j 0.11007404327392578
column j: 954
Runtime of the program for j 0.13952302932739258
column j: 955
Runtime of the program for j 0.10454130172729492
column j: 956
Runtime of the program for j 0.1006019115447998
column j: 957
Runtime of the program for j 0.10064315795898438
column j: 958
Runtime of the program for j 0.10849785804748535
column j: 959
Runtime of the program for j 0.11653947830200195
column j: 960
Runtime of the program for j 0.10953712463378906
column j: 961
Runtime of the program for j 0.10555052757263184
column j: 962
Runtime of the program for j 0.09575557708740234
column j: 963
Runtime of the program for j 0.10365581512451172
column j: 964
Runtime of the program for j 0.09459757804870605
column j: 965
Runtime of the program for j 0.10453152656555176
column j: 966
Runtime of the program for j 0.09855151176452637
column j: 967
Runtime of the program for j 0.10155391693115234
column j: 968
Runtime of the program for j 0.09951353073120117
column j: 969
Runtime of the program for j 0.1303567886352539
column j: 970
Runtime of the program for j 0.09563708305358887
column j: 971
Runtime of the program for j 0.10244536399841309
column j: 972
Runtime of the program for j 0.09572958946228027
column j: 973
Runtime of the program for j 0.1064295768737793
column j: 974
Runtime of the program for j 0.10351157188415527
column j: 975
Runtime of the program for j 0.10160970687866211
column j: 976
Runtime of the program for j 0.0957190990447998
column j: 977
Runtime of the program for j 0.1103212833404541
column j: 978
Runtime of the program for j 0.09449195861816406
column j: 979
Runtime of the program for j 0.09854459762573242
column j: 980
Runtime of the program for j 0.10452818870544434
column j: 981
Runtime of the program for j 0.11052775382995605
column j: 982
Runtime of the program for j 0.10648131370544434
column j: 983
Runtime of the program for j 0.10555672645568848
column j: 984
Runtime of the program for j 0.15114426612854004
column j: 985
Runtime of the program for j 0.10326194763183594
column j: 986
Runtime of the program for j 0.1045384407043457
column j: 987
Runtime of the program for j 0.1045687198638916
column j: 988
Runtime of the program for j 0.09952664375305176
column j: 989
Runtime of the program for j 0.10254836082458496
column j: 990
Runtime of the program for j 0.09854269027709961
column j: 991
Runtime of the program for j 0.10183858871459961
column j: 992
Runtime of the program for j 0.10955142974853516
column j: 993
Runtime of the program for j 0.10554289817810059
column j: 994
Runtime of the program for j 0.10456228256225586
column j: 995
Runtime of the program for j 0.1075596809387207
column j: 996
Runtime of the program for j 0.10656523704528809
column j: 997
Runtime of the program for j 0.06653666496276855
column j: 998
Runtime of the program for j 0.10152840614318848
column j: 999
Runtime of the program for j 0.1385974884033203
column j: 1000
Runtime of the program for j 0.10055232048034668
column j: 1001
Runtime of the program for j 0.10453104972839355
column j: 1002
Runtime of the program for j 0.10056185722351074
column j: 1003
Runtime of the program for j 0.10152435302734375
column j: 1004
Runtime of the program for j 0.10354089736938477
column j: 1005
Runtime of the program for j 0.09877276420593262
column j: 1006
Runtime of the program for j 0.10455584526062012
column j: 1007
Runtime of the program for j 0.09652495384216309
column j: 1008
Runtime of the program for j 0.09951424598693848
column j: 1009
Runtime of the program for j 0.0935831069946289
column j: 1010
Runtime of the program for j 0.10353565216064453
column j: 1011
Runtime of the program for j 0.10952281951904297
column j: 1012
Runtime of the program for j 0.1035609245300293
column j: 1013
Runtime of the program for j 0.12061810493469238
column j: 1014
Runtime of the program for j 0.13055086135864258
column j: 1015
Runtime of the program for j 0.10654830932617188
column j: 1016
Runtime of the program for j 0.09874510765075684
column j: 1017
Runtime of the program for j 0.1067512035369873
column j: 1018
Runtime of the program for j 0.09952425956726074
column j: 1019
Runtime of the program for j 0.11054325103759766
column j: 1020
Runtime of the program for j 0.0980687141418457
column j: 1021
Runtime of the program for j 0.11671304702758789
column j: 1022
Runtime of the program for j 0.09359884262084961
column j: 1023
Runtime of the program for j 0.10657477378845215
column j: 1024
Runtime of the program for j 0.09752750396728516
column j: 1025
Runtime of the program for j 0.10467648506164551
column j: 1026
Runtime of the program for j 0.09754133224487305
column j: 1027
Runtime of the program for j 0.11451911926269531
column j: 1028
Runtime of the program for j 0.12610602378845215
column j: 1029
Runtime of the program for j 0.08501219749450684
column j: 1030
Runtime of the program for j 0.11105036735534668
column j: 1031
Runtime of the program for j 0.11853981018066406
column j: 1032
Runtime of the program for j 0.10551285743713379
column j: 1033
Runtime of the program for j 0.07555127143859863
column j: 1034
Runtime of the program for j 0.1018381118774414
column j: 1035
Runtime of the program for j 0.1135549545288086
column j: 1036
Runtime of the program for j 0.10250616073608398
column j: 1037
Runtime of the program for j 0.10650992393493652
column j: 1038
Runtime of the program for j 0.10260653495788574
column j: 1039
Runtime of the program for j 0.11051249504089355
column j: 1040
Runtime of the program for j 0.10352134704589844
column j: 1041
Runtime of the program for j 0.11654877662658691
column j: 1042
Runtime of the program for j 0.10951590538024902
column j: 1043
Runtime of the program for j 0.12855124473571777
column j: 1044
Runtime of the program for j 0.10125732421875
column j: 1045
Runtime of the program for j 0.1014559268951416
column j: 1046
Runtime of the program for j 0.10867810249328613
column j: 1047
Runtime of the program for j 0.10752391815185547
column j: 1048
Runtime of the program for j 0.11400389671325684
column j: 1049
Runtime of the program for j 0.09551811218261719
column j: 1050
Runtime of the program for j 0.10979270935058594
column j: 1051
Runtime of the program for j 0.09650039672851562
column j: 1052
Runtime of the program for j 0.11171221733093262
column j: 1053
Runtime of the program for j 0.1015312671661377
column j: 1054
Runtime of the program for j 0.1136929988861084
column j: 1055
Runtime of the program for j 0.09954619407653809
column j: 1056
Runtime of the program for j 0.11070060729980469
column j: 1057
Runtime of the program for j 0.13402915000915527

column j: 1058
Runtime of the program for j 0.1126241683959961
column j: 1059
Runtime of the program for j 0.10155248641967773
column j: 1060
Runtime of the program for j 0.10773968696594238
column j: 1061
Runtime of the program for j 0.09855008125305176
column j: 1062
Runtime of the program for j 0.10753488540649414
column j: 1063
Runtime of the program for j 0.11559343338012695
column j: 1064
Runtime of the program for j 0.10454010963439941
column j: 1065
Runtime of the program for j 0.11152052879333496
column j: 1066
Runtime of the program for j 0.10454583168029785
column j: 1067
Runtime of the program for j 0.08154749870300293
column j: 1068
Runtime of the program for j 0.10859870910644531
column j: 1069
Runtime of the program for j 0.1155400276184082
column j: 1070
Runtime of the program for j 0.13974833488464355
column j: 1071
Runtime of the program for j 0.11551666259765625
column j: 1072
Runtime of the program for j 0.0755772590637207
column j: 1073
Runtime of the program for j 0.11655282974243164
column j: 1074
Runtime of the program for j 0.1035163402557373
column j: 1075
Runtime of the program for j 0.12171053886413574
column j: 1076
Runtime of the program for j 0.10255241394042969
column j: 1077
Runtime of the program for j 0.10565423965454102
column j: 1078
Runtime of the program for j 0.11063313484191895
column j: 1079
Runtime of the program for j 0.10411596298217773
column j: 1080
Runtime of the program for j 0.11318135261535645
column j: 1081
Runtime of the program for j 0.10756921768188477
column j: 1082
Runtime of the program for j 0.12109160423278809
column j: 1083
Runtime of the program for j 0.13454961776733398
column j: 1084
Runtime of the program for j 0.1105504035949707
column j: 1085
Runtime of the program for j 0.10551190376281738
column j: 1086
Runtime of the program for j 0.11629796028137207
column j: 1087
Runtime of the program for j 0.09973597526550293
column j: 1088
Runtime of the program for j 0.11349964141845703
column j: 1089
Runtime of the program for j 0.11196732521057129
column j: 1090
Runtime of the program for j 0.09853410720825195
column j: 1091
Runtime of the program for j 0.11050248146057129
column j: 1092
Runtime of the program for j 0.09651041030883789
column j: 1093
Runtime of the program for j 0.10860824584960938
column j: 1094
Runtime of the program for j 0.09655070304870605
column j: 1095
Runtime of the program for j 0.1225290298461914
column j: 1096
Runtime of the program for j 0.12054896354675293
column j: 1097
Runtime of the program for j 0.14053964614868164
column j: 1098
Runtime of the program for j 0.1008615493774414
column j: 1099
Runtime of the program for j 0.10351228713989258
column j: 1100
Runtime of the program for j 0.11156368255615234
column j: 1101
Runtime of the program for j 0.09772086143493652
column j: 1102
Runtime of the program for j 0.10939955711364746
column j: 1103
Runtime of the program for j 0.10015869140625
column j: 1104
Runtime of the program for j 0.10795903205871582
column j: 1105
Runtime of the program for j 0.10236716270446777
column j: 1106
Runtime of the program for j 0.10894536972045898
column j: 1107
Runtime of the program for j 0.09623503684997559
column j: 1108
Runtime of the program for j 0.11229515075683594
column j: 1109
Runtime of the program for j 0.10734033584594727
column j: 1110
Runtime of the program for j 0.1296372413635254
column j: 1111
Runtime of the program for j 0.10567045211791992
column j: 1112
Runtime of the program for j 0.10146498680114746
column j: 1113
Runtime of the program for j 0.10351848602294922
column j: 1114
Runtime of the program for j 0.1025846004486084
column j: 1115
Runtime of the program for j 0.10840487480163574
column j: 1116
Runtime of the program for j 0.09668755531311035
column j: 1117
Runtime of the program for j 0.12923431396484375
column j: 1118
Runtime of the program for j 1.7034037113189697
column j: 1119
Runtime of the program for j 0.16905665397644043
column j: 1120
Runtime of the program for j 0.17961335182189941
column j: 1121
Runtime of the program for j 0.17389321327209473
column j: 1122
Runtime of the program for j 0.168426513671875
column j: 1123
Runtime of the program for j 0.19898676872253418
column j: 1124
Runtime of the program for j 0.18222641944885254
column j: 1125
Runtime of the program for j 0.14859724044799805
column j: 1126
Runtime of the program for j 0.16184401512145996
column j: 1127
Runtime of the program for j 0.16472673416137695
column j: 1128
Runtime of the program for j 0.16638731956481934
column j: 1129
Runtime of the program for j 0.19208860397338867
column j: 1130
Runtime of the program for j 0.1752316951751709
column j: 1131
Runtime of the program for j 0.18358922004699707
column j: 1132
Runtime of the program for j 0.18899011611938477
column j: 1133
Runtime of the program for j 0.16318058967590332
column j: 1134
Runtime of the program for j 0.14707541465759277
column j: 1135
Runtime of the program for j 0.1291043758392334
column j: 1136
Runtime of the program for j 0.18436837196350098
column j: 1137
Runtime of the program for j 0.11845970153808594
column j: 1138
Runtime of the program for j 0.10570621490478516
column j: 1139
Runtime of the program for j 0.09042668342590332
column j: 1140
Runtime of the program for j 0.1536555290222168
column j: 1141
Runtime of the program for j 0.1343090534210205
column j: 1142
Runtime of the program for j 0.13592100143432617
column j: 1143
Runtime of the program for j 0.14674830436706543
column j: 1144
Runtime of the program for j 0.12738704681396484
column j: 1145
Runtime of the program for j 0.12980413436889648
column j: 1146
Runtime of the program for j 0.13004374504089355
column j: 1147
Runtime of the program for j 0.1314694881439209
column j: 1148
Runtime of the program for j 0.17286038398742676
column j: 1149
Runtime of the program for j 0.11820864677429199
column j: 1150
Runtime of the program for j 0.19826817512512207
column j: 1151
Runtime of the program for j 0.16036462783813477
column j: 1152
Runtime of the program for j 0.17610764503479004
column j: 1153
Runtime of the program for j 0.1237955093383789
column j: 1154
Runtime of the program for j 0.14351129531860352
column j: 1155
Runtime of the program for j 0.12706470489501953
column j: 1156
Runtime of the program for j 0.13898992538452148
column j: 1157
Runtime of the program for j 0.10877203941345215
column j: 1158
Runtime of the program for j 0.10660171508789062
column j: 1159
Runtime of the program for j 0.09785580635070801
column j: 1160
Runtime of the program for j 0.08460235595703125
column j: 1161
Runtime of the program for j 0.18134570121765137
column j: 1162
Runtime of the program for j 0.15450310707092285
column j: 1163
Runtime of the program for j 0.1306917667388916
column j: 1164
Runtime of the program for j 0.13460016250610352
column j: 1165
Runtime of the program for j 0.12860631942749023
column j: 1166
Runtime of the program for j 0.13436245918273926
column j: 1167
Runtime of the program for j 0.16997838020324707
column j: 1168
Runtime of the program for j 0.14281630516052246
column j: 1169
Runtime of the program for j 0.1367955207824707
column j: 1170
Runtime of the program for j 0.12847423553466797
column j: 1171
Runtime of the program for j 0.1527879238128662
column j: 1172
Runtime of the program for j 0.16453242301940918
column j: 1173
Runtime of the program for j 0.11978960037231445
column j: 1174
Runtime of the program for j 0.19301676750183105
column j: 1175
Runtime of the program for j 0.13381314277648926
column j: 1176
Runtime of the program for j 0.14024877548217773
column j: 1177
Runtime of the program for j 0.12294745445251465
column j: 1178
Runtime of the program for j 0.134443998336792
column j: 1179
Runtime of the program for j 0.12949490547180176
column j: 1180
Runtime of the program for j 0.1185450553894043
column j: 1181
Runtime of the program for j 0.1315770149230957
column j: 1182
Runtime of the program for j 0.12446284294128418
column j: 1183
Runtime of the program for j 0.1360797882080078
column j: 1184
Runtime of the program for j 0.1299433708190918
column j: 1185
Runtime of the program for j 0.15385055541992188
column j: 1186
Runtime of the program for j 0.12945008277893066

column j: 1187
Runtime of the program for j 0.1297159194946289
column j: 1188
Runtime of the program for j 0.12874412536621094
column j: 1189
Runtime of the program for j 0.12143278121948242
column j: 1190
Runtime of the program for j 0.12984061241149902
column j: 1191
Runtime of the program for j 0.13558077812194824
column j: 1192
Runtime of the program for j 0.08654117584228516
column j: 1193
Runtime of the program for j 0.10148358345031738
column j: 1194
Runtime of the program for j 0.1334996223449707
column j: 1195
Runtime of the program for j 0.1187126636505127
column j: 1196
Runtime of the program for j 0.1766972541809082
column j: 1197
Runtime of the program for j 0.1268324851989746
column j: 1198
Runtime of the program for j 0.14147257804870605
column j: 1199
Runtime of the program for j 0.11552000045776367
column j: 1200
Runtime of the program for j 0.12434053421020508
column j: 1201
Runtime of the program for j 0.1292734146118164
column j: 1202
Runtime of the program for j 0.1295626163482666
column j: 1203
Runtime of the program for j 0.1302051544189453
column j: 1204
Runtime of the program for j 0.1294865608215332
column j: 1205
Runtime of the program for j 0.12505507469177246
column j: 1206
Runtime of the program for j 0.13472366333007812
column j: 1207
Runtime of the program for j 0.11773419380187988
column j: 1208
Runtime of the program for j 0.12955760955810547
column j: 1209
Runtime of the program for j 0.14879155158996582
column j: 1210
Runtime of the program for j 0.1187129020690918
column j: 1211
Runtime of the program for j 0.12120938301086426
column j: 1212
Runtime of the program for j 0.07808971405029297
column j: 1213
Runtime of the program for j 0.08781075477600098
column j: 1214
Runtime of the program for j 0.10744047164916992
column j: 1215
Runtime of the program for j 0.12471294403076172
column j: 1216
Runtime of the program for j 0.13702821731567383
column j: 1217
Runtime of the program for j 0.12284660339355469
column j: 1218
Runtime of the program for j 0.13172268867492676
column j: 1219
Runtime of the program for j 0.1322646141052246
column j: 1220
Runtime of the program for j 0.14885830879211426
column j: 1221
Runtime of the program for j 0.1278684139251709
column j: 1222
Runtime of the program for j 0.12047100067138672
column j: 1223
Runtime of the program for j 0.13875818252563477
column j: 1224
Runtime of the program for j 0.13288640975952148
column j: 1225
Runtime of the program for j 0.11988997459411621
column j: 1226
Runtime of the program for j 0.13076543807983398
column j: 1227
Runtime of the program for j 0.11669540405273438
column j: 1228
Runtime of the program for j 0.15512585639953613
column j: 1229
Runtime of the program for j 0.16578149795532227
column j: 1230
Runtime of the program for j 0.15439677238464355
column j: 1231
Runtime of the program for j 0.1587233543395996
column j: 1232
Runtime of the program for j 0.18284249305725098
column j: 1233
Runtime of the program for j 0.13410019874572754
column j: 1234
Runtime of the program for j 0.12577104568481445
column j: 1235
Runtime of the program for j 0.13453078269958496
column j: 1236
Runtime of the program for j 0.16043686866760254
column j: 1237
Runtime of the program for j 0.15163540840148926
column j: 1238
Runtime of the program for j 0.14151835441589355
column j: 1239
Runtime of the program for j 0.13451862335205078
column j: 1240
Runtime of the program for j 0.12686920166015625
column j: 1241
Runtime of the program for j 0.14417409896850586
column j: 1242
Runtime of the program for j 0.19205689430236816
column j: 1243
Runtime of the program for j 0.1970834732055664
column j: 1244
Runtime of the program for j 0.14987921714782715
column j: 1245
Runtime of the program for j 0.1736917495727539
column j: 1246
Runtime of the program for j 0.10347533226013184
column j: 1247
Runtime of the program for j 0.2186729907989502
column j: 1248
Runtime of the program for j 0.15347671508789062
column j: 1249
Runtime of the program for j 0.14470171928405762
column j: 1250
Runtime of the program for j 0.18411588668823242
column j: 1251
Runtime of the program for j 0.14771413803100586
column j: 1252
Runtime of the program for j 0.16913604736328125
column j: 1253
Runtime of the program for j 0.12788724899291992
column j: 1254
Runtime of the program for j 0.19371271133422852
column j: 1255
Runtime of the program for j 0.1395714282989502
column j: 1256
Runtime of the program for j 0.1839771270751953
column j: 1257
Runtime of the program for j 0.13672852516174316
column j: 1258
Runtime of the program for j 0.14795255661010742
column j: 1259
Runtime of the program for j 0.1394646167755127
column j: 1260
Runtime of the program for j 0.13866376876831055
column j: 1261
Runtime of the program for j 0.16321277618408203
column j: 1262
Runtime of the program for j 0.14450502395629883
column j: 1263
Runtime of the program for j 0.18938803672790527
column j: 1264
Runtime of the program for j 0.16856169700622559
column j: 1265
Runtime of the program for j 0.20952081680297852
column j: 1266
Runtime of the program for j 0.15067100524902344
column j: 1267
Runtime of the program for j 0.14440107345581055
column j: 1268
Runtime of the program for j 0.19726061820983887
column j: 1269
Runtime of the program for j 0.1885051727294922
column j: 1270
Runtime of the program for j 0.15018653869628906
column j: 1271
Runtime of the program for j 0.14431047439575195
column j: 1272
Runtime of the program for j 0.11743974685668945
column j: 1273
Runtime of the program for j 0.12650346755981445
column j: 1274
Runtime of the program for j 0.1312699317932129
column j: 1275
Runtime of the program for j 0.12245774269104004
column j: 1276
Runtime of the program for j 0.16771364212036133
column j: 1277
Runtime of the program for j 0.13727879524230957
column j: 1278
Runtime of the program for j 0.08208465576171875
column j: 1279
Runtime of the program for j 0.0977640151977539
column j: 1280
Runtime of the program for j 0.12943243980407715
column j: 1281
Runtime of the program for j 0.12481117248535156
column j: 1282
Runtime of the program for j 0.14586758613586426
column j: 1283
Runtime of the program for j 0.12455129623413086
column j: 1284
Runtime of the program for j 0.12278127670288086
column j: 1285
Runtime of the program for j 0.1743018627166748
column j: 1286
Runtime of the program for j 0.1569070816040039
column j: 1287
Runtime of the program for j 0.12285256385803223
column j: 1288
Runtime of the program for j 0.09083294868469238
column j: 1289
Runtime of the program for j 0.12942934036254883
column j: 1290
Runtime of the program for j 0.14742159843444824
column j: 1291
Runtime of the program for j 0.20365333557128906
column j: 1292
Runtime of the program for j 0.18277359008789062
column j: 1293
Runtime of the program for j 0.14284110069274902
column j: 1294
Runtime of the program for j 0.13133716583251953
column j: 1295
Runtime of the program for j 0.1682753562927246
column j: 1296
Runtime of the program for j 0.1818234920501709
column j: 1297
Runtime of the program for j 0.157667875289917
column j: 1298
Runtime of the program for j 0.19627141952514648
column j: 1299
Runtime of the program for j 0.13283801078796387
column j: 1300
Runtime of the program for j 0.08354067802429199
column j: 1301
Runtime of the program for j 0.07477068901062012
column j: 1302
Runtime of the program for j 0.15376925468444824
column j: 1303
Runtime of the program for j 0.09464764595031738
column j: 1304
Runtime of the program for j 0.17506623268127441
column j: 1305
Runtime of the program for j 0.1559610366821289
column j: 1306
Runtime of the program for j 0.15902423858642578
column j: 1307
Runtime of the program for j 0.1539771556854248
column j: 1308
Runtime of the program for j 0.18096423149108887
column j: 1309
Runtime of the program for j 0.17942214012145996
column j: 1310
Runtime of the program for j 0.1453697681427002
column j: 1311
Runtime of the program for j 0.15071702003479004
column j: 1312
Runtime of the program for j 0.17077994346618652
column j: 1313
Runtime of the program for j 0.1298513412475586
column j: 1314
Runtime of the program for j 0.13747072219848633
column j: 1315
Runtime of the program for j 0.12256741523742676

column j: 1316
Runtime of the program for j 0.1437375545501709
column j: 1317
Runtime of the program for j 0.12376165390014648
column j: 1318
Runtime of the program for j 0.12306070327758789
column j: 1319
Runtime of the program for j 0.15180587768554688
column j: 1320
Runtime of the program for j 0.12769842147827148
column j: 1321
Runtime of the program for j 0.11346840858459473
column j: 1322
Runtime of the program for j 0.12377667427062988
column j: 1323
Runtime of the program for j 0.11394762992858887
column j: 1324
Runtime of the program for j 0.1217496395111084
column j: 1325
Runtime of the program for j 0.13184833526611328
column j: 1326
Runtime of the program for j 0.12151074409484863
column j: 1327
Runtime of the program for j 0.11342191696166992
column j: 1328
Runtime of the program for j 0.11864161491394043
column j: 1329
Runtime of the program for j 0.1507093906402588
column j: 1330
Runtime of the program for j 0.12238550186157227
column j: 1331
Runtime of the program for j 0.11168217658996582
column j: 1332
Runtime of the program for j 0.12451553344726562
column j: 1333
Runtime of the program for j 0.1299741268157959
column j: 1334
Runtime of the program for j 0.12142062187194824
column j: 1335
Runtime of the program for j 0.11675047874450684
column j: 1336
Runtime of the program for j 0.13753080368041992
column j: 1337
Runtime of the program for j 0.08342432975769043
column j: 1338
Runtime of the program for j 0.12377572059631348
column j: 1339
Runtime of the program for j 0.17511510848999023
column j: 1340
Runtime of the program for j 0.1150977611541748
column j: 1341
Runtime of the program for j 0.13830947875976562
column j: 1342
Runtime of the program for j 0.1748964786529541
column j: 1343
Runtime of the program for j 0.14455938339233398
column j: 1344
Runtime of the program for j 0.15546870231628418
column j: 1345
Runtime of the program for j 0.151015043258667
column j: 1346
Runtime of the program for j 0.12972545623779297
column j: 1347
Runtime of the program for j 0.12257742881774902
column j: 1348
Runtime of the program for j 0.13652539253234863
column j: 1349
Runtime of the program for j 0.20440936088562012
column j: 1350
Runtime of the program for j 0.13134121894836426
column j: 1351
Runtime of the program for j 0.09659194946289062
column j: 1352
Runtime of the program for j 0.08452391624450684
column j: 1353
Runtime of the program for j 0.1334667205810547
column j: 1354
Runtime of the program for j 0.14717483520507812
column j: 1355
Runtime of the program for j 0.14053869247436523
column j: 1356
Runtime of the program for j 0.12760257720947266
column j: 1357
Runtime of the program for j 0.11771059036254883
column j: 1358
Runtime of the program for j 0.12305593490600586
column j: 1359
Runtime of the program for j 0.13254189491271973
column j: 1360
Runtime of the program for j 0.1486213207244873
column j: 1361
Runtime of the program for j 0.12039566040039062
column j: 1362
Runtime of the program for j 0.14461827278137207
column j: 1363
Runtime of the program for j 0.11965632438659668
column j: 1364
Runtime of the program for j 0.07650947570800781
column j: 1365
Runtime of the program for j 0.1473522186279297
column j: 1366
Runtime of the program for j 0.1277635097503662
column j: 1367
Runtime of the program for j 0.15660834312438965
column j: 1368
Runtime of the program for j 0.15071940422058105
column j: 1369
Runtime of the program for j 0.1355898380279541
column j: 1370
Runtime of the program for j 0.17166590690612793
column j: 1371
Runtime of the program for j 0.13744115829467773
column j: 1372
Runtime of the program for j 0.06868553161621094
column j: 1373
Runtime of the program for j 0.1244208812713623
column j: 1374
Runtime of the program for j 0.13146686553955078
column j: 1375
Runtime of the program for j 0.11176848411560059
column j: 1376
Runtime of the program for j 0.11560654640197754
column j: 1377
Runtime of the program for j 0.13159394264221191
column j: 1378
Runtime of the program for j 0.11772465705871582
column j: 1379
Runtime of the program for j 0.126572847366333
column j: 1380
Runtime of the program for j 0.16791272163391113
column j: 1381
Runtime of the program for j 0.12142205238342285
column j: 1382
Runtime of the program for j 0.1177678108215332
column j: 1383
Runtime of the program for j 0.12741494178771973
column j: 1384
Runtime of the program for j 0.1275489330291748
column j: 1385
Runtime of the program for j 0.16765642166137695
column j: 1386
Runtime of the program for j 0.1745297908782959
column j: 1387
Runtime of the program for j 0.15472817420959473
column j: 1388
Runtime of the program for j 0.143402099609375
column j: 1389
Runtime of the program for j 0.13376808166503906
column j: 1390
Runtime of the program for j 0.1612563133239746
column j: 1391
Runtime of the program for j 0.12087273597717285
column j: 1392
Runtime of the program for j 0.13065671920776367
column j: 1393
Runtime of the program for j 0.18117904663085938
column j: 1394
Runtime of the program for j 0.23506450653076172
column j: 1395
Runtime of the program for j 0.16418147087097168
column j: 1396
Runtime of the program for j 0.14895176887512207
column j: 1397
Runtime of the program for j 0.16397356986999512
column j: 1398
Runtime of the program for j 0.16061782836914062
column j: 1399
Runtime of the program for j 0.1408689022064209
column j: 1400
Runtime of the program for j 0.20029973983764648
column j: 1401
Runtime of the program for j 0.13083338737487793
column j: 1402
Runtime of the program for j 0.1463015079498291
column j: 1403
Runtime of the program for j 0.15379071235656738
column j: 1404
Runtime of the program for j 0.14030051231384277
column j: 1405
Runtime of the program for j 0.13874006271362305
column j: 1406
Runtime of the program for j 0.15722370147705078
column j: 1407
Runtime of the program for j 0.13886260986328125
column j: 1408
Runtime of the program for j 0.13784408569335938
column j: 1409
Runtime of the program for j 0.19321179389953613
column j: 1410
Runtime of the program for j 0.14436125755310059
column j: 1411
Runtime of the program for j 0.14067316055297852
column j: 1412
Runtime of the program for j 0.15925097465515137
column j: 1413
Runtime of the program for j 0.14956021308898926
column j: 1414
Runtime of the program for j 0.1906261444091797
column j: 1415
Runtime of the program for j 0.1360161304473877
column j: 1416
Runtime of the program for j 0.16221261024475098
column j: 1417
Runtime of the program for j 0.25277066230773926
column j: 1418
Runtime of the program for j 0.1615738868713379
column j: 1419
Runtime of the program for j 0.14554286003112793
column j: 1420
Runtime of the program for j 0.12352895736694336
column j: 1421
Runtime of the program for j 0.16906285285949707
column j: 1422
Runtime of the program for j 0.19822311401367188
column j: 1423
Runtime of the program for j 0.16934585571289062
column j: 1424
Runtime of the program for j 0.15022015571594238
column j: 1425
Runtime of the program for j 0.14060688018798828
column j: 1426
Runtime of the program for j 0.2261052131652832
column j: 1427
Runtime of the program for j 0.1408381462097168
column j: 1428
Runtime of the program for j 0.1778411865234375
column j: 1429
Runtime of the program for j 0.202162504196167
column j: 1430
Runtime of the program for j 0.1606895923614502
column j: 1431
Runtime of the program for j 0.1637587547302246
column j: 1432
Runtime of the program for j 0.1633303165435791
column j: 1433
Runtime of the program for j 0.1454930305480957
column j: 1434
Runtime of the program for j 0.18287086486816406
column j: 1435
Runtime of the program for j 0.19308090209960938
column j: 1436
Runtime of the program for j 0.08759140968322754
column j: 1437
Runtime of the program for j 0.14244627952575684
column j: 1438
Runtime of the program for j 0.1266160011291504
column j: 1439
Runtime of the program for j 0.1342165470123291
column j: 1440
Runtime of the program for j 0.13261151313781738
column j: 1441
Runtime of the program for j 0.11252069473266602
column j: 1442
Runtime of the program for j 0.12897825241088867
column j: 1443
Runtime of the program for j 0.13653302192687988
column j: 1444
Runtime of the program for j 0.16821813583374023
column j: 1445
Runtime of the program for j 0.14451146125793457

column j: 1446
Runtime of the program for j 0.11851334571838379
column j: 1447
Runtime of the program for j 0.12478137016296387
column j: 1448
Runtime of the program for j 0.14826297760009766
column j: 1449
Runtime of the program for j 0.12679171562194824
column j: 1450
Runtime of the program for j 0.1384892463684082
column j: 1451
Runtime of the program for j 0.18961596488952637
column j: 1452
Runtime of the program for j 0.15825581550598145
column j: 1453
Runtime of the program for j 0.16705822944641113
column j: 1454
Runtime of the program for j 0.13050174713134766
column j: 1455
Runtime of the program for j 0.11963319778442383
column j: 1456
Runtime of the program for j 0.13740825653076172
column j: 1457
Runtime of the program for j 0.11986565589904785
column j: 1458
Runtime of the program for j 0.1316063404083252
column j: 1459
Runtime of the program for j 0.13343167304992676
column j: 1460
Runtime of the program for j 0.12201809883117676
column j: 1461
Runtime of the program for j 0.12251615524291992
column j: 1462
Runtime of the program for j 0.15752077102661133
column j: 1463
Runtime of the program for j 0.12634968757629395
column j: 1464
Runtime of the program for j 0.1344296932220459
column j: 1465
Runtime of the program for j 0.13753890991210938
column j: 1466
Runtime of the program for j 0.11906909942626953
column j: 1467
Runtime of the program for j 0.1267867088317871
column j: 1468
Runtime of the program for j 0.1305243968963623
column j: 1469
Runtime of the program for j 0.11852645874023438
column j: 1470
Runtime of the program for j 0.13332724571228027
column j: 1471
Runtime of the program for j 0.18001222610473633
column j: 1472
Runtime of the program for j 0.11702156066894531
column j: 1473
Runtime of the program for j 0.14101552963256836
column j: 1474
Runtime of the program for j 0.12752771377563477
column j: 1475
Runtime of the program for j 0.13228821754455566
column j: 1476
Runtime of the program for j 0.10460710525512695
column j: 1477
Runtime of the program for j 0.13713622093200684
column j: 1478
Runtime of the program for j 0.19365382194519043
column j: 1479
Runtime of the program for j 0.19124603271484375
column j: 1480
Runtime of the program for j 0.16433358192443848
column j: 1481
Runtime of the program for j 0.18247342109680176
column j: 1482
Runtime of the program for j 0.16537046432495117
column j: 1483
Runtime of the program for j 0.16620397567749023
column j: 1484
Runtime of the program for j 0.1815650463104248
column j: 1485
Runtime of the program for j 0.1496579647064209
column j: 1486
Runtime of the program for j 0.15039277076721191
column j: 1487
Runtime of the program for j 0.15462422370910645
column j: 1488
Runtime of the program for j 0.22327446937561035
column j: 1489
Runtime of the program for j 0.16727972030639648
column j: 1490
Runtime of the program for j 0.1526949405670166
column j: 1491
Runtime of the program for j 0.15134334564208984
column j: 1492
Runtime of the program for j 0.1831073760986328
column j: 1493
Runtime of the program for j 0.13172173500061035
column j: 1494
Runtime of the program for j 0.13680768013000488
column j: 1495
Runtime of the program for j 0.18876051902770996
column j: 1496
Runtime of the program for j 0.19611072540283203
column j: 1497
Runtime of the program for j 0.13237714767456055
column j: 1498
Runtime of the program for j 0.13046622276306152
column j: 1499
Runtime of the program for j 0.11150455474853516
column j: 1500
Runtime of the program for j 0.13954734802246094
column j: 1501
Runtime of the program for j 0.1214284896850586
column j: 1502
Runtime of the program for j 0.1367497444152832
column j: 1503
Runtime of the program for j 0.12954187393188477
column j: 1504
Runtime of the program for j 0.13764357566833496
column j: 1505
Runtime of the program for j 0.1689150333404541
column j: 1506
Runtime of the program for j 0.13547086715698242
column j: 1507
Runtime of the program for j 0.13061308860778809
column j: 1508
Runtime of the program for j 0.16549396514892578
column j: 1509
Runtime of the program for j 0.14451003074645996
column j: 1510
Runtime of the program for j 0.14296579360961914
column j: 1511
Runtime of the program for j 0.1315152645111084
column j: 1512
Runtime of the program for j 0.13452553749084473
column j: 1513
Runtime of the program for j 0.24182653427124023
column j: 1514
Runtime of the program for j 0.16710114479064941
column j: 1515
Runtime of the program for j 0.12902593612670898
column j: 1516
Runtime of the program for j 0.13952088356018066
column j: 1517
Runtime of the program for j 0.13152027130126953
column j: 1518
Runtime of the program for j 0.13904619216918945
column j: 1519
Runtime of the program for j 0.1720128059387207
column j: 1520
Runtime of the program for j 0.15326356887817383
column j: 1521
Runtime of the program for j 0.19705748558044434
column j: 1522
Runtime of the program for j 0.11250758171081543
column j: 1523
Runtime of the program for j 0.1430509090423584
column j: 1524
Runtime of the program for j 0.14396142959594727
column j: 1525
Runtime of the program for j 0.13756084442138672
column j: 1526
Runtime of the program for j 0.13929295539855957
column j: 1527
Runtime of the program for j 0.16489863395690918
column j: 1528
Runtime of the program for j 0.1419672966003418
column j: 1529
Runtime of the program for j 0.1545553207397461
column j: 1530
Runtime of the program for j 0.17514705657958984
column j: 1531
Runtime of the program for j 0.16192412376403809
column j: 1532
Runtime of the program for j 0.1930701732635498
column j: 1533
Runtime of the program for j 0.13370132446289062
column j: 1534
Runtime of the program for j 0.13552260398864746
column j: 1535
Runtime of the program for j 0.12604594230651855
column j: 1536
Runtime of the program for j 0.1328892707824707
column j: 1537
Runtime of the program for j 0.13668441772460938
column j: 1538
Runtime of the program for j 0.15394926071166992
column j: 1539
Runtime of the program for j 0.12050318717956543
column j: 1540
Runtime of the program for j 0.144287109375
column j: 1541
Runtime of the program for j 0.1416633129119873
column j: 1542
Runtime of the program for j 0.15281152725219727
column j: 1543
Runtime of the program for j 0.14315104484558105
column j: 1544
Runtime of the program for j 0.09254574775695801
column j: 1545
Runtime of the program for j 0.14969992637634277
column j: 1546
Runtime of the program for j 0.16826725006103516
column j: 1547
Runtime of the program for j 0.11770963668823242
column j: 1548
Runtime of the program for j 0.1206817626953125
column j: 1549
Runtime of the program for j 0.13113069534301758
column j: 1550
Runtime of the program for j 0.13066649436950684
column j: 1551
Runtime of the program for j 0.13378000259399414
column j: 1552
Runtime of the program for j 0.1610870361328125
column j: 1553
Runtime of the program for j 0.1509544849395752
column j: 1554
Runtime of the program for j 0.18230891227722168
column j: 1555
Runtime of the program for j 0.14052033424377441
column j: 1556
Runtime of the program for j 0.146622896194458
column j: 1557
Runtime of the program for j 0.14328861236572266
column j: 1558
Runtime of the program for j 0.16670489311218262
column j: 1559
Runtime of the program for j 0.1583256721496582
column j: 1560
Runtime of the program for j 0.15069317817687988
column j: 1561
Runtime of the program for j 0.16986823081970215
column j: 1562
Runtime of the program for j 0.16744542121887207
column j: 1563
Runtime of the program for j 0.13757896423339844
column j: 1564
Runtime of the program for j 0.13997435569763184
column j: 1565
Runtime of the program for j 0.12503480911254883
column j: 1566
Runtime of the program for j 0.1365206241607666
column j: 1567
Runtime of the program for j 0.07553267478942871
column j: 1568
Runtime of the program for j 0.1418771743774414
column j: 1569
Runtime of the program for j 0.1267857551574707
column j: 1570
Runtime of the program for j 0.13540077209472656
column j: 1571
Runtime of the program for j 0.15852904319763184
column j: 1572
Runtime of the program for j 0.12904644012451172
column j: 1573
Runtime of the program for j 0.12750744819641113
column j: 1574
Runtime of the program for j 0.13855266571044922
column j: 1575
Runtime of the program for j 0.11807560920715332

column j: 1576
Runtime of the program for j 0.1371138095855713
column j: 1577
Runtime of the program for j 0.11149239540100098
column j: 1578
Runtime of the program for j 0.12978744506835938
column j: 1579
Runtime of the program for j 0.10853314399719238
column j: 1580
Runtime of the program for j 0.08150744438171387
column j: 1581
Runtime of the program for j 0.1440412998199463
column j: 1582
Runtime of the program for j 0.13610410690307617
column j: 1583
Runtime of the program for j 0.12277555465698242
column j: 1584
Runtime of the program for j 0.13937163352966309
column j: 1585
Runtime of the program for j 0.12951922416687012
column j: 1586
Runtime of the program for j 0.14452648162841797
column j: 1587
Runtime of the program for j 0.15609121322631836
column j: 1588
Runtime of the program for j 0.12950825691223145
column j: 1589
Runtime of the program for j 0.15195798873901367
column j: 1590
Runtime of the program for j 0.15921616554260254
column j: 1591
Runtime of the program for j 0.1412353515625
column j: 1592
Runtime of the program for j 0.11952042579650879
column j: 1593
Runtime of the program for j 0.10464000701904297
column j: 1594
Runtime of the program for j 0.20833730697631836
column j: 1595
Runtime of the program for j 0.14563226699829102
column j: 1596
Runtime of the program for j 0.17888092994689941
column j: 1597
Runtime of the program for j 0.16225123405456543
column j: 1598
Runtime of the program for j 0.15317368507385254
column j: 1599
Runtime of the program for j 0.13851237297058105
column j: 1600
Runtime of the program for j 0.12854528427124023
column j: 1601
Runtime of the program for j 0.1480696201324463
column j: 1602
Runtime of the program for j 0.17054176330566406
column j: 1603
Runtime of the program for j 0.12401485443115234
column j: 1604
Runtime of the program for j 0.13251447677612305
column j: 1605
Runtime of the program for j 0.1195061206817627
column j: 1606
Runtime of the program for j 0.15404629707336426
column j: 1607
Runtime of the program for j 0.13989925384521484
column j: 1608
Runtime of the program for j 0.11732888221740723
column j: 1609
Runtime of the program for j 0.16736841201782227
column j: 1610
Runtime of the program for j 0.21170973777770996
column j: 1611
Runtime of the program for j 0.14464902877807617
column j: 1612
Runtime of the program for j 0.09772253036499023
column j: 1613
Runtime of the program for j 0.15374493598937988
column j: 1614
Runtime of the program for j 0.14473462104797363
column j: 1615
Runtime of the program for j 0.12422680854797363
column j: 1616
Runtime of the program for j 0.13963079452514648
column j: 1617
Runtime of the program for j 0.12461090087890625
column j: 1618
Runtime of the program for j 0.18723011016845703
column j: 1619
Runtime of the program for j 0.16279220581054688
column j: 1620
Runtime of the program for j 0.16052579879760742
column j: 1621
Runtime of the program for j 0.12404203414916992
column j: 1622
Runtime of the program for j 0.13980889320373535
column j: 1623
Runtime of the program for j 0.1700577735900879
column j: 1624
Runtime of the program for j 0.174574613571167
column j: 1625
Runtime of the program for j 0.12201666831970215
column j: 1626
Runtime of the program for j 0.15074896812438965
column j: 1627
Runtime of the program for j 0.12054228782653809
column j: 1628
Runtime of the program for j 0.13682913780212402
column j: 1629
Runtime of the program for j 0.14939665794372559
column j: 1630
Runtime of the program for j 0.1530611515045166
column j: 1631
Runtime of the program for j 0.1667308807373047
column j: 1632
Runtime of the program for j 0.15505170822143555
column j: 1633
Runtime of the program for j 0.15144801139831543
column j: 1634
Runtime of the program for j 0.14545369148254395
column j: 1635
Runtime of the program for j 0.08276987075805664
column j: 1636
Runtime of the program for j 0.10141754150390625
column j: 1637
Runtime of the program for j 0.08052730560302734
column j: 1638
Runtime of the program for j 0.08402442932128906
column j: 1639
Runtime of the program for j 0.14321088790893555
column j: 1640
Runtime of the program for j 0.12051010131835938
column j: 1641
Runtime of the program for j 0.16904687881469727
column j: 1642
Runtime of the program for j 0.11751866340637207
column j: 1643
Runtime of the program for j 0.11451411247253418
column j: 1644
Runtime of the program for j 0.11951041221618652
column j: 1645
Runtime of the program for j 0.12616419792175293
column j: 1646
Runtime of the program for j 0.1538395881652832
column j: 1647
Runtime of the program for j 0.1385948657989502
column j: 1648
Runtime of the program for j 0.1320207118988037
column j: 1649
Runtime of the program for j 0.148512601852417
column j: 1650
Runtime of the program for j 0.12842941284179688
column j: 1651
Runtime of the program for j 0.15363669395446777
column j: 1652
Runtime of the program for j 0.13753843307495117
column j: 1653
Runtime of the program for j 0.13645195960998535
column j: 1654
Runtime of the program for j 0.07852745056152344
column j: 1655
Runtime of the program for j 0.1195058822631836
column j: 1656
Runtime of the program for j 0.13652396202087402
column j: 1657
Runtime of the program for j 0.1667158603668213
column j: 1658
Runtime of the program for j 0.14161372184753418
column j: 1659
Runtime of the program for j 0.11961698532104492
column j: 1660
Runtime of the program for j 0.13329386711120605
column j: 1661
Runtime of the program for j 0.11550569534301758
column j: 1662
Runtime of the program for j 0.12351202964782715
column j: 1663
Runtime of the program for j 0.12651872634887695
column j: 1664
Runtime of the program for j 0.16490745544433594
column j: 1665
Runtime of the program for j 0.13252496719360352
column j: 1666
Runtime of the program for j 0.12165427207946777
column j: 1667
Runtime of the program for j 0.12250876426696777
column j: 1668
Runtime of the program for j 0.13551664352416992
column j: 1669
Runtime of the program for j 0.12552237510681152
column j: 1670
Runtime of the program for j 0.13190221786499023
column j: 1671
Runtime of the program for j 0.11851191520690918
column j: 1672
Runtime of the program for j 0.16828608512878418
column j: 1673
Runtime of the program for j 0.13051843643188477
column j: 1674
Runtime of the program for j 0.1275184154510498
column j: 1675
Runtime of the program for j 0.13607382774353027
column j: 1676
Runtime of the program for j 0.14969706535339355
column j: 1677
Runtime of the program for j 0.12787723541259766
column j: 1678
Runtime of the program for j 0.12911772727966309
column j: 1679
Runtime of the program for j 0.15851521492004395
column j: 1680
Runtime of the program for j 0.13303375244140625
column j: 1681
Runtime of the program for j 0.12250542640686035
column j: 1682
Runtime of the program for j 0.1405162811279297
column j: 1683
Runtime of the program for j 0.11553215980529785
column j: 1684
Runtime of the program for j 0.12909317016601562
column j: 1685
Runtime of the program for j 0.13053512573242188
column j: 1686
Runtime of the program for j 0.1373751163482666
column j: 1687
Runtime of the program for j 0.1650388240814209
column j: 1688
Runtime of the program for j 0.13216781616210938
column j: 1689
Runtime of the program for j 0.16064858436584473
column j: 1690
Runtime of the program for j 0.17072176933288574
column j: 1691
Runtime of the program for j 0.1576993465423584
column j: 1692
Runtime of the program for j 0.17100858688354492
column j: 1693
Runtime of the program for j 0.14969849586486816
column j: 1694
Runtime of the program for j 0.23823785781860352
column j: 1695
Runtime of the program for j 0.1609961986541748
column j: 1696
Runtime of the program for j 0.15826654434204102
column j: 1697
Runtime of the program for j 0.13341593742370605
column j: 1698
Runtime of the program for j 0.13605928421020508
column j: 1699
Runtime of the program for j 0.1457977294921875
column j: 1700
Runtime of the program for j 0.13718867301940918
column j: 1701
Runtime of the program for j 0.18803691864013672
column j: 1702
Runtime of the program for j 0.1313920021057129
column j: 1703
Runtime of the program for j 0.1337735652923584
column j: 1704
Runtime of the program for j 0.1482241153717041
column j: 1705
Runtime of the program for j 0.13356637954711914

column j: 1706
Runtime of the program for j 0.1447889804840088
column j: 1707
Runtime of the program for j 0.13354253768920898
column j: 1708
Runtime of the program for j 0.14560675621032715
column j: 1709
Runtime of the program for j 0.15703988075256348
column j: 1710
Runtime of the program for j 0.11950898170471191
column j: 1711
Runtime of the program for j 0.13550662994384766
column j: 1712
Runtime of the program for j 0.12452220916748047
column j: 1713
Runtime of the program for j 0.14344048500061035
column j: 1714
Runtime of the program for j 0.12542986869812012
column j: 1715
Runtime of the program for j 0.12369513511657715
column j: 1716
Runtime of the program for j 0.1630098819732666
column j: 1717
Runtime of the program for j 0.12151050567626953
column j: 1718
Runtime of the program for j 0.13903260231018066
column j: 1719
Runtime of the program for j 0.13550758361816406
column j: 1720
Runtime of the program for j 0.13351917266845703
column j: 1721
Runtime of the program for j 0.1304950714111328
column j: 1722
Runtime of the program for j 0.13076472282409668
column j: 1723
Runtime of the program for j 0.1525270938873291
column j: 1724
Runtime of the program for j 0.12406754493713379
column j: 1725
Runtime of the program for j 0.14098620414733887
column j: 1726
Runtime of the program for j 0.1355271339416504
column j: 1727
Runtime of the program for j 0.13103222846984863
column j: 1728
Runtime of the program for j 0.13881731033325195
column j: 1729
Runtime of the program for j 0.11552691459655762
column j: 1730
Runtime of the program for j 0.13219666481018066
column j: 1731
Runtime of the program for j 0.15750646591186523
column j: 1732
Runtime of the program for j 0.14004230499267578
column j: 1733
Runtime of the program for j 0.12050890922546387
column j: 1734
Runtime of the program for j 0.13351821899414062
column j: 1735
Runtime of the program for j 0.11850976943969727
column j: 1736
Runtime of the program for j 0.1220242977142334
column j: 1737
Runtime of the program for j 0.11553502082824707
column j: 1738
Runtime of the program for j 0.169708251953125
column j: 1739
Runtime of the program for j 0.14623808860778809
column j: 1740
Runtime of the program for j 0.12443017959594727
column j: 1741
Runtime of the program for j 0.14082884788513184
column j: 1742
Runtime of the program for j 0.12401819229125977
column j: 1743
Runtime of the program for j 0.11751794815063477
column j: 1744
Runtime of the program for j 0.11252999305725098
column j: 1745
Runtime of the program for j 0.0858449935913086
column j: 1746
Runtime of the program for j 0.18814826011657715
column j: 1747
Runtime of the program for j 0.12364673614501953
column j: 1748
Runtime of the program for j 0.15718698501586914
column j: 1749
Runtime of the program for j 0.11955499649047852
column j: 1750
Runtime of the program for j 0.15985321998596191
column j: 1751
Runtime of the program for j 0.1190187931060791
column j: 1752
Runtime of the program for j 0.1175241470336914
column j: 1753
Runtime of the program for j 0.17252850532531738
column j: 1754
Runtime of the program for j 0.13007211685180664
column j: 1755
Runtime of the program for j 0.13249969482421875
column j: 1756
Runtime of the program for j 0.12651824951171875
column j: 1757
Runtime of the program for j 0.13704538345336914
column j: 1758
Runtime of the program for j 0.12251448631286621
column j: 1759
Runtime of the program for j 0.11550164222717285
column j: 1760
Runtime of the program for j 0.09451150894165039
column j: 1761
Runtime of the program for j 0.12554192543029785
column j: 1762
Runtime of the program for j 0.1478571891784668
column j: 1763
Runtime of the program for j 0.11957025527954102
column j: 1764
Runtime of the program for j 0.16521072387695312
column j: 1765
Runtime of the program for j 0.16269183158874512
column j: 1766
Runtime of the program for j 0.21222686767578125
column j: 1767
Runtime of the program for j 0.1293649673461914
column j: 1768
Runtime of the program for j 0.15274930000305176
column j: 1769
Runtime of the program for j 0.14427423477172852
column j: 1770
Runtime of the program for j 0.14752554893493652
column j: 1771
Runtime of the program for j 0.15862154960632324
column j: 1772
Runtime of the program for j 0.1911787986755371
column j: 1773
Runtime of the program for j 0.2568655014038086
column j: 1774
Runtime of the program for j 0.15750670433044434
column j: 1775
Runtime of the program for j 0.1464526653289795
column j: 1776
Runtime of the program for j 0.15871596336364746
column j: 1777
Runtime of the program for j 0.16169524192810059
column j: 1778
Runtime of the program for j 0.2051677703857422
column j: 1779
Runtime of the program for j 0.16096854209899902
column j: 1780
Runtime of the program for j 0.26511335372924805
column j: 1781
Runtime of the program for j 0.17255902290344238
column j: 1782
Runtime of the program for j 0.1792440414428711
column j: 1783
Runtime of the program for j 0.14523601531982422
column j: 1784
Runtime of the program for j 0.14771533012390137
column j: 1785
Runtime of the program for j 0.15093302726745605
column j: 1786
Runtime of the program for j 0.14788174629211426
column j: 1787
Runtime of the program for j 0.21220946311950684
column j: 1788
Runtime of the program for j 0.16971611976623535
column j: 1789
Runtime of the program for j 0.16638612747192383
column j: 1790
Runtime of the program for j 0.12445306777954102
column j: 1791
Runtime of the program for j 0.14150643348693848
column j: 1792
Runtime of the program for j 0.1274571418762207
column j: 1793
Runtime of the program for j 0.12777066230773926
column j: 1794
Runtime of the program for j 0.17293572425842285
column j: 1795
Runtime of the program for j 0.13052058219909668
column j: 1796
Runtime of the program for j 0.14661264419555664
column j: 1797
Runtime of the program for j 0.17027735710144043
column j: 1798
Runtime of the program for j 0.19846773147583008
column j: 1799
Runtime of the program for j 0.1542980670928955
column j: 1800
Runtime of the program for j 0.15390706062316895
column j: 1801
Runtime of the program for j 0.17623019218444824
column j: 1802
Runtime of the program for j 0.1395435333251953
column j: 1803
Runtime of the program for j 0.15707731246948242
column j: 1804
Runtime of the program for j 0.1485438346862793
column j: 1805
Runtime of the program for j 0.17404675483703613
column j: 1806
Runtime of the program for j 0.15789246559143066
column j: 1807
Runtime of the program for j 0.1817798614501953
column j: 1808
Runtime of the program for j 0.21523308753967285
column j: 1809
Runtime of the program for j 0.14481139183044434
column j: 1810
Runtime of the program for j 0.12541532516479492
column j: 1811
Runtime of the program for j 0.11552762985229492
column j: 1812
Runtime of the program for j 0.12309885025024414
column j: 1813
Runtime of the program for j 0.13987493515014648
column j: 1814
Runtime of the program for j 0.13344478607177734
column j: 1815
Runtime of the program for j 0.16712498664855957
column j: 1816
Runtime of the program for j 0.13454055786132812
column j: 1817
Runtime of the program for j 0.1219944953918457
column j: 1818
Runtime of the program for j 0.14644694328308105
column j: 1819
Runtime of the program for j 0.14428043365478516
column j: 1820
Runtime of the program for j 0.14250946044921875
column j: 1821
Runtime of the program for j 0.12882733345031738
column j: 1822
Runtime of the program for j 0.17462444305419922
column j: 1823
Runtime of the program for j 0.1427314281463623
column j: 1824
Runtime of the program for j 0.1291334629058838
column j: 1825
Runtime of the program for j 0.1487102508544922
column j: 1826
Runtime of the program for j 0.12603497505187988
column j: 1827
Runtime of the program for j 0.13954615592956543
column j: 1828
Runtime of the program for j 0.1345810890197754
column j: 1829
Runtime of the program for j 0.19006037712097168
column j: 1830
Runtime of the program for j 0.11842632293701172
column j: 1831
Runtime of the program for j 0.12214112281799316
column j: 1832
Runtime of the program for j 0.12859702110290527
column j: 1833
Runtime of the program for j 0.13571524620056152
column j: 1834
Runtime of the program for j 0.14243721961975098

column j: 1835
Runtime of the program for j 0.13058686256408691
column j: 1836
Runtime of the program for j 0.1934366226196289
column j: 1837
Runtime of the program for j 0.1437520980834961
column j: 1838
Runtime of the program for j 0.15659523010253906
column j: 1839
Runtime of the program for j 0.13783001899719238
column j: 1840
Runtime of the program for j 0.1410360336303711
column j: 1841
Runtime of the program for j 0.12176012992858887
column j: 1842
Runtime of the program for j 0.13471293449401855
column j: 1843
Runtime of the program for j 0.16228914260864258
column j: 1844
Runtime of the program for j 0.08441162109375
column j: 1845
Runtime of the program for j 0.1326296329498291
column j: 1846
Runtime of the program for j 0.09981060028076172
column j: 1847
Runtime of the program for j 0.09847688674926758
column j: 1848
Runtime of the program for j 0.1368706226348877
column j: 1849
Runtime of the program for j 0.15246319770812988
column j: 1850
Runtime of the program for j 0.17041802406311035
column j: 1851
Runtime of the program for j 0.1523277759552002
column j: 1852
Runtime of the program for j 0.12966609001159668
column j: 1853
Runtime of the program for j 0.13956809043884277
column j: 1854
Runtime of the program for j 0.13362956047058105
column j: 1855
Runtime of the program for j 0.12278342247009277
column j: 1856
Runtime of the program for j 0.18158555030822754
column j: 1857
Runtime of the program for j 0.12482357025146484
column j: 1858
Runtime of the program for j 0.1423342227935791
column j: 1859
Runtime of the program for j 0.1288743019104004
column j: 1860
Runtime of the program for j 0.14137816429138184
column j: 1861
Runtime of the program for j 0.13227033615112305
column j: 1862
Runtime of the program for j 0.10478043556213379
column j: 1863
Runtime of the program for j 0.15784287452697754
column j: 1864
Runtime of the program for j 0.14364027976989746
column j: 1865
Runtime of the program for j 0.12270450592041016
column j: 1866
Runtime of the program for j 0.14545416831970215
column j: 1867
Runtime of the program for j 0.122802734375
column j: 1868
Runtime of the program for j 0.13771939277648926
column j: 1869
Runtime of the program for j 0.1796426773071289
column j: 1870
Runtime of the program for j 0.1358025074005127
column j: 1871
Runtime of the program for j 0.13860034942626953
column j: 1872
Runtime of the program for j 0.13185501098632812
column j: 1873
Runtime of the program for j 0.13988280296325684
column j: 1874
Runtime of the program for j 0.1203756332397461
column j: 1875
Runtime of the program for j 0.1364274024963379
column j: 1876
Runtime of the program for j 0.17068004608154297
column j: 1877
Runtime of the program for j 0.14378023147583008
column j: 1878
Runtime of the program for j 0.12968087196350098
column j: 1879
Runtime of the program for j 0.14151763916015625
column j: 1880
Runtime of the program for j 0.12676048278808594
column j: 1881
Runtime of the program for j 0.11860013008117676
column j: 1882
Runtime of the program for j 0.12932753562927246
column j: 1883
Runtime of the program for j 0.16092491149902344
column j: 1884
Runtime of the program for j 0.1443779468536377
column j: 1885
Runtime of the program for j 0.12875604629516602
column j: 1886
Runtime of the program for j 0.1038048267364502
column j: 1887
Runtime of the program for j 0.0857703685760498
column j: 1888
Runtime of the program for j 0.14869189262390137
column j: 1889
Runtime of the program for j 0.15923666954040527
column j: 1890
Runtime of the program for j 0.15599346160888672
column j: 1891
Runtime of the program for j 0.1244654655456543
column j: 1892
Runtime of the program for j 0.10131216049194336
column j: 1893
Runtime of the program for j 0.12479209899902344
column j: 1894
Runtime of the program for j 0.14260292053222656
column j: 1895
Runtime of the program for j 0.11730051040649414
column j: 1896
Runtime of the program for j 0.15660524368286133
column j: 1897
Runtime of the program for j 0.12379574775695801
column j: 1898
Runtime of the program for j 0.14555764198303223
column j: 1899
Runtime of the program for j 0.13675713539123535
column j: 1900
Runtime of the program for j 0.1335744857788086
column j: 1901
Runtime of the program for j 0.13825297355651855
column j: 1902
Runtime of the program for j 0.13759374618530273
column j: 1903
Runtime of the program for j 0.17104029655456543
column j: 1904
Runtime of the program for j 0.1288161277770996
column j: 1905
Runtime of the program for j 0.1464521884918213
column j: 1906
Runtime of the program for j 0.13490843772888184
column j: 1907
Runtime of the program for j 0.14193391799926758
column j: 1908
Runtime of the program for j 0.12837457656860352
column j: 1909
Runtime of the program for j 0.1795804500579834
column j: 1910
Runtime of the program for j 0.13448095321655273
column j: 1911
Runtime of the program for j 0.1374378204345703
column j: 1912
Runtime of the program for j 0.1383194923400879
column j: 1913
Runtime of the program for j 0.14379024505615234
column j: 1914
Runtime of the program for j 0.13176393508911133
column j: 1915
Runtime of the program for j 0.1192009449005127
column j: 1916
Runtime of the program for j 0.16384649276733398
column j: 1917
Runtime of the program for j 0.15520715713500977
column j: 1918
Runtime of the program for j 0.14375662803649902
column j: 1919
Runtime of the program for j 0.12972426414489746
column j: 1920
Runtime of the program for j 0.1493854522705078
column j: 1921
Runtime of the program for j 0.1267557144165039
column j: 1922
Runtime of the program for j 0.16547298431396484
column j: 1923
Runtime of the program for j 0.1975390911102295
column j: 1924
Runtime of the program for j 0.16536855697631836
column j: 1925
Runtime of the program for j 0.13893485069274902
column j: 1926
Runtime of the program for j 0.11172175407409668
column j: 1927
Runtime of the program for j 0.1419064998626709
column j: 1928
Runtime of the program for j 0.15735244750976562
column j: 1929
Runtime of the program for j 0.2086496353149414
column j: 1930
Runtime of the program for j 0.19756793975830078
column j: 1931
Runtime of the program for j 0.17148470878601074
column j: 1932
Runtime of the program for j 0.1707935333251953
column j: 1933
Runtime of the program for j 0.19541645050048828
column j: 1934
Runtime of the program for j 0.2014479637145996
column j: 1935
Runtime of the program for j 0.25748109817504883
column j: 1936
Runtime of the program for j 0.16421175003051758
column j: 1937
Runtime of the program for j 0.08878493309020996
column j: 1938
Runtime of the program for j 0.1390237808227539
column j: 1939
Runtime of the program for j 0.17841410636901855

In [7]:
curated_bow['max_noise'] = sss['max_noise']
curated_bow['noise'] = 0
curated_bow

,id,,.,a,if,return,throw,void,},!,...,} ',} :,} <,~ /,~ dp0node,class_name,class_value,contents,max_noise,noise
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,++ b/README.md,0.725794,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,"1,23 @@",0.725794,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,This plugin downloads/installs Node and NPM lo...,0.725794,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,"It's supposed to work on Windows, OS X and Linux.",0.725794,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,NaN,0.725794,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,++ b/frontend-maven-plugin/src/main/java/com/g...,4.420658,0
4990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,},4.420658,0
4991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,"39,6 @@ public final class BowerMojo extends A...",5.420658,0
4992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,this.additionalEnvironment = additiona...,5.420658,0
4993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,++ b/frontend-plugin-core/src/main/java/com/gi...,8.925107,0

In [8]:
s = sss.sort_values(by='max_noise', ascending = False)
s = s.drop_duplicates(subset = 'max_noise')

values = []
for x in s['max_noise'].iloc[0:10]:
    values.append(x)

In [9]:
# noise_sorted = curated_bow.sort_values(by='max_noise', ascending = False)
noise_sorted = curated_bow

for df in noise_sorted.index:
    for val in values:
        if noise_sorted['max_noise'][df] == val:
            noise_sorted.loc[df, 'noise'] = 1
#             noise_sorted['noise'][df] = 1
# noise_sorted.drop(noise_sorted[noise_sorted['max_noise'].isin(values) == True].index, axis = 0, inplace = True)
noise_sorted['noise'] = noise_sorted['noise'] // 1
noise_sorted = noise_sorted.reset_index()
noise_sorted = noise_sorted.drop('index', axis=1)
noise_sorted

,id,,.,a,if,return,throw,void,},!,...,} ',} :,} <,~ /,~ dp0node,class_name,class_value,contents,max_noise,noise
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,++ b/README.md,0.725794,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,"1,23 @@",0.725794,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,This plugin downloads/installs Node and NPM lo...,0.725794,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,"It's supposed to work on Windows, OS X and Linux.",0.725794,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,NaN,0.725794,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,++ b/frontend-maven-plugin/src/main/java/com/g...,4.420658,1
4990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,},4.420658,1
4991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,"39,6 @@ public final class BowerMojo extends A...",5.420658,1
4992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,this.additionalEnvironment = additiona...,5.420658,1
4993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,++ b/frontend-plugin-core/src/main/java/com/gi...,8.925107,1

In [10]:
zeros = int(0)
ones = int(0)

for df in noise_sorted.index:
    if noise_sorted['noise'][df] == 0:
        zeros += 1
    elif noise_sorted['noise'][df] == 1:
        ones += 1

print('Zeros: ', zeros)
print('Ones: ', ones)

Zeros:  1061
Ones:  3933

In [11]:
noise_sorted.to_csv('attribute_noise_cleaned.csv')
noise_sorted

,id,,.,a,if,return,throw,void,},!,...,} ',} :,} <,~ /,~ dp0node,class_name,class_value,contents,max_noise,noise
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,++ b/README.md,0.725794,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,"1,23 @@",0.725794,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,This plugin downloads/installs Node and NPM lo...,0.725794,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,"It's supposed to work on Windows, OS X and Linux.",0.725794,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,1,NaN,0.725794,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,++ b/frontend-maven-plugin/src/main/java/com/g...,4.420658,1
4990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,},4.420658,1
4991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,"39,6 @@ public final class BowerMojo extends A...",5.420658,1
4992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,this.additionalEnvironment = additiona...,5.420658,1
4993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,build_status,0,++ b/frontend-plugin-core/src/main/java/com/gi...,8.925107,1