In [1]:
import pandas as pd
import time
import numpy as np

In [2]:
# Import Dataset
curated_bow = pd.read_csv('FrontendMavenPlugin.csv', sep='$')
curated_bow.dropna()
# Remove Trailing Spaces in Column Names
curated_bow.columns = [col.strip() for col in curated_bow.columns]
curated_bow

,id,,,,.,a,if,return,throw,void,...,"} """,} ',} :,} <,~,~ /,~ dp0node,class_name,class_value,contents
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,++ b/README.md
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,"1,23 @@"
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,This plugin downloads/installs Node and NPM lo...
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,"It's supposed to work on Windows, OS X and Linux."
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,++ b/frontend-maven-plugin/src/main/java/com/g...
4990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,}
4991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,"39,6 @@ public final class BowerMojo extends A..."
4992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,this.additionalEnvironment = additiona...
4993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,++ b/frontend-plugin-core/src/main/java/com/gi...

In [3]:
# Duplicate Columns Removed
curated_bow = curated_bow.loc[:,~curated_bow.columns.duplicated()].copy()
curated_bow

,id,,.,a,if,return,throw,void,},!,...,| |,"} """,} ',} :,} <,~ /,~ dp0node,class_name,class_value,contents
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,++ b/README.md
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,"1,23 @@"
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,This plugin downloads/installs Node and NPM lo...
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,"It's supposed to work on Windows, OS X and Linux."
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,++ b/frontend-maven-plugin/src/main/java/com/g...
4990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,}
4991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,"39,6 @@ public final class BowerMojo extends A..."
4992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,this.additionalEnvironment = additiona...
4993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,build_status,0,++ b/frontend-plugin-core/src/main/java/com/gi...

In [4]:
partitions_ = 1
bin_size = len(curated_bow.index)//partitions_ 
print(bin_size)

4994

In [13]:
def run_Panda():
    bins_counter = 0
    partition_values = pd.DataFrame()
    j_col= pd.DataFrame()
#     k_col= pd.DataFrame()
    
#     for j in range(len(curated_bow.columns)-3): 
    for j in range(len(curated_bow.columns)-3):
        start_j = time.time()
        clustered_att = curated_bow.sort_values(by = curated_bow.columns[j])
        
        bins_counter = 0
#         if j != j:
        for y in range(partitions_): 
            parition_mean = clustered_att.iloc[bins_counter: bins_counter + bin_size, j].values.mean()
            partition_sd = clustered_att.iloc[bins_counter: bins_counter + bin_size, j].values.std()
            mean_over_sd = parition_mean/partition_sd if partition_sd else 0

            noise_score = pd.DataFrame([np.nan_to_num(abs(x - (mean_over_sd)))
                                        for x in clustered_att.iloc[bins_counter:bins_counter + bin_size, j]])

            partition_values = pd.concat([partition_values, noise_score], axis=0)
                    
            #dropping existing indices with the same name and replacing them with new, using reset index
            partition_values= partition_values.reset_index(drop=True) 
            bins_counter = bins_counter + bin_size
#         else:
#             continue
            
        j_col= pd.concat([j_col, partition_values], axis= 1)
        partition_values.drop(partition_values.index, inplace=True)
        
        end_j = time.time()
        print("column j: " + str(j))
        print(f"Runtime of the program for j {end_j - start_j}")
        
    return j_col

In [14]:
sss = run_Panda()
sss['max_noise'] = sss.max(axis=1)

column j: 0
Runtime of the program for j 0.3453238010406494
column j: 1
Runtime of the program for j 0.4051182270050049
column j: 2
Runtime of the program for j 0.41078662872314453
column j: 3
Runtime of the program for j 0.4290776252746582
column j: 4
Runtime of the program for j 0.42580533027648926
column j: 5
Runtime of the program for j 0.4091658592224121
column j: 6
Runtime of the program for j 0.462658166885376
column j: 7
Runtime of the program for j 0.47762155532836914
column j: 8
Runtime of the program for j 0.5016074180603027
column j: 9
Runtime of the program for j 0.4784369468688965
column j: 10
Runtime of the program for j 0.4160435199737549
column j: 11
Runtime of the program for j 0.13626480102539062
column j: 12
Runtime of the program for j 0.4275977611541748
column j: 13
Runtime of the program for j 0.43269944190979004
column j: 14
Runtime of the program for j 0.435565710067749
column j: 15
Runtime of the program for j 0.4237065315246582
column j: 16
Runtime of the program for j 0.438814640045166
column j: 17
Runtime of the program for j 0.41208624839782715
column j: 18
Runtime of the program for j 0.428269624710083
column j: 19
Runtime of the program for j 0.4173705577850342
column j: 20
Runtime of the program for j 0.4201676845550537
column j: 21
Runtime of the program for j 0.4247705936431885
column j: 22
Runtime of the program for j 0.42061734199523926
column j: 23
Runtime of the program for j 0.40992283821105957
column j: 24
Runtime of the program for j 0.42535924911499023
column j: 25
Runtime of the program for j 0.41336631774902344
column j: 26
Runtime of the program for j 0.40247035026550293
column j: 27
Runtime of the program for j 0.41942381858825684
column j: 28
Runtime of the program for j 0.4096965789794922
column j: 29
Runtime of the program for j 0.4396016597747803
column j: 30
Runtime of the program for j 0.42041468620300293
column j: 31
Runtime of the program for j 0.42319393157958984
column j: 32
Runtime of the program for j 0.4292621612548828
column j: 33
Runtime of the program for j 0.43726420402526855
column j: 34
Runtime of the program for j 0.4302799701690674
column j: 35
Runtime of the program for j 0.14118361473083496
column j: 36
Runtime of the program for j 0.40892601013183594
column j: 37
Runtime of the program for j 0.41972994804382324
column j: 38
Runtime of the program for j 0.4902074337005615
column j: 39
Runtime of the program for j 0.13257837295532227
column j: 40
Runtime of the program for j 0.42702317237854004
column j: 41
Runtime of the program for j 0.4252889156341553
column j: 42
Runtime of the program for j 0.4250051975250244
column j: 43
Runtime of the program for j 0.4123094081878662
column j: 44
Runtime of the program for j 0.4192018508911133
column j: 45
Runtime of the program for j 0.4215078353881836
column j: 46
Runtime of the program for j 0.39649391174316406
column j: 47
Runtime of the program for j 0.15274786949157715
column j: 48
Runtime of the program for j 0.13750481605529785
column j: 49
Runtime of the program for j 0.41972994804382324
column j: 50
Runtime of the program for j 0.43285489082336426
column j: 51
Runtime of the program for j 0.4143712520599365
column j: 52
Runtime of the program for j 0.43990635871887207
column j: 53
Runtime of the program for j 0.4298889636993408
column j: 54
Runtime of the program for j 0.45494723320007324
column j: 55
Runtime of the program for j 0.4250319004058838
column j: 56
Runtime of the program for j 0.4249570369720459
column j: 57
Runtime of the program for j 0.13490986824035645
column j: 58
Runtime of the program for j 0.42032623291015625
column j: 59
Runtime of the program for j 0.4299740791320801
column j: 60
Runtime of the program for j 0.42994046211242676
column j: 61
Runtime of the program for j 0.42009496688842773
column j: 62
Runtime of the program for j 0.43358445167541504
column j: 63
Runtime of the program for j 0.42121386528015137
column j: 64
Runtime of the program for j 0.1454601287841797
column j: 65
Runtime of the program for j 0.41765928268432617
column j: 66
Runtime of the program for j 0.41202759742736816
column j: 67
Runtime of the program for j 0.41723012924194336
column j: 68
Runtime of the program for j 0.12764263153076172
column j: 69
Runtime of the program for j 0.41025853157043457
column j: 70
Runtime of the program for j 0.4401116371154785
column j: 71
Runtime of the program for j 0.4146432876586914
column j: 72
Runtime of the program for j 0.4301896095275879
column j: 73
Runtime of the program for j 0.410064697265625
column j: 74
Runtime of the program for j 0.4298884868621826
column j: 75
Runtime of the program for j 0.412092924118042
column j: 76
Runtime of the program for j 0.4264190196990967
column j: 77
Runtime of the program for j 0.12150144577026367
column j: 78
Runtime of the program for j 0.14368963241577148
column j: 79
Runtime of the program for j 0.4114224910736084
column j: 80
Runtime of the program for j 0.42623353004455566
column j: 81
Runtime of the program for j 0.4386444091796875
column j: 82
Runtime of the program for j 0.423433780670166
column j: 83
Runtime of the program for j 0.419400691986084
column j: 84
Runtime of the program for j 0.4295463562011719
column j: 85
Runtime of the program for j 0.4177999496459961
column j: 86
Runtime of the program for j 0.4318232536315918
column j: 87
Runtime of the program for j 0.43707871437072754
column j: 88
Runtime of the program for j 0.4302363395690918
column j: 89
Runtime of the program for j 0.42232298851013184
column j: 90
Runtime of the program for j 0.43889665603637695
column j: 91
Runtime of the program for j 0.4239950180053711
column j: 92
Runtime of the program for j 0.4250059127807617
column j: 93
Runtime of the program for j 0.42001938819885254
column j: 94
Runtime of the program for j 0.433363676071167
column j: 95
Runtime of the program for j 0.4385678768157959
column j: 96
Runtime of the program for j 0.42780065536499023
column j: 97
Runtime of the program for j 0.4299595355987549
column j: 98
Runtime of the program for j 0.44152379035949707
column j: 99
Runtime of the program for j 0.44892072677612305
column j: 100
Runtime of the program for j 0.4122030735015869
column j: 101
Runtime of the program for j 0.44763708114624023
column j: 102
Runtime of the program for j 0.4496901035308838
column j: 103
Runtime of the program for j 0.43004941940307617
column j: 104
Runtime of the program for j 0.41710829734802246
column j: 105
Runtime of the program for j 0.40387654304504395
column j: 106
Runtime of the program for j 0.4151754379272461
column j: 107
Runtime of the program for j 0.43375515937805176
column j: 108
Runtime of the program for j 0.4401977062225342
column j: 109
Runtime of the program for j 0.1362462043762207
column j: 110
Runtime of the program for j 0.39971184730529785
column j: 111
Runtime of the program for j 0.439131498336792
column j: 112
Runtime of the program for j 0.4497189521789551
column j: 113
Runtime of the program for j 0.4302535057067871
column j: 114
Runtime of the program for j 0.12975716590881348
column j: 115
Runtime of the program for j 0.4202256202697754
column j: 116
Runtime of the program for j 0.4398963451385498
column j: 117
Runtime of the program for j 0.44033074378967285
column j: 118
Runtime of the program for j 0.44940829277038574
column j: 119
Runtime of the program for j 0.4338703155517578
column j: 120
Runtime of the program for j 0.4403855800628662
column j: 121
Runtime of the program for j 0.41986560821533203
column j: 122
Runtime of the program for j 0.4402194023132324
column j: 123
Runtime of the program for j 0.4448540210723877
column j: 124
Runtime of the program for j 0.44481468200683594
column j: 125
Runtime of the program for j 0.42050766944885254
column j: 126
Runtime of the program for j 0.422025203704834
column j: 127
Runtime of the program for j 0.42023372650146484
column j: 128
Runtime of the program for j 0.4174327850341797
column j: 129
Runtime of the program for j 0.4197275638580322
column j: 130
Runtime of the program for j 0.4423692226409912
column j: 131
Runtime of the program for j 0.138014554977417
column j: 132
Runtime of the program for j 0.4348282814025879
column j: 133
Runtime of the program for j 0.4172384738922119

column j: 134
Runtime of the program for j 0.43323826789855957
column j: 135
Runtime of the program for j 0.42453598976135254
column j: 136
Runtime of the program for j 0.4949760437011719
column j: 137
Runtime of the program for j 0.4348146915435791
column j: 138
Runtime of the program for j 0.4039640426635742
column j: 139
Runtime of the program for j 0.4315505027770996
column j: 140
Runtime of the program for j 0.437298059463501
column j: 141
Runtime of the program for j 0.427509069442749
column j: 142
Runtime of the program for j 0.42488861083984375
column j: 143
Runtime of the program for j 0.42772674560546875
column j: 144
Runtime of the program for j 0.42218875885009766
column j: 145
Runtime of the program for j 0.46298909187316895
column j: 146
Runtime of the program for j 0.44448113441467285
column j: 147
Runtime of the program for j 0.43099451065063477
column j: 148
Runtime of the program for j 0.4376661777496338
column j: 149
Runtime of the program for j 0.43903017044067383
column j: 150
Runtime of the program for j 0.15888643264770508
column j: 151
Runtime of the program for j 0.45438241958618164
column j: 152
Runtime of the program for j 0.4363703727722168
column j: 153
Runtime of the program for j 0.43639659881591797
column j: 154
Runtime of the program for j 0.4403526782989502
column j: 155
Runtime of the program for j 0.4510829448699951
column j: 156
Runtime of the program for j 0.4287285804748535
column j: 157
Runtime of the program for j 0.44536757469177246
column j: 158
Runtime of the program for j 0.4251899719238281
column j: 159
Runtime of the program for j 0.43961405754089355
column j: 160
Runtime of the program for j 0.419954776763916
column j: 161
Runtime of the program for j 0.4399728775024414
column j: 162
Runtime of the program for j 0.4499638080596924
column j: 163
Runtime of the program for j 0.15983891487121582
column j: 164
Runtime of the program for j 0.45024776458740234
column j: 165
Runtime of the program for j 0.46586036682128906
column j: 166
Runtime of the program for j 0.4469175338745117
column j: 167
Runtime of the program for j 0.450087308883667
column j: 168
Runtime of the program for j 0.13759255409240723
column j: 169
Runtime of the program for j 0.4497373104095459
column j: 170
Runtime of the program for j 0.45986056327819824
column j: 171
Runtime of the program for j 0.45000433921813965
column j: 172
Runtime of the program for j 0.42516469955444336
column j: 173
Runtime of the program for j 0.4375736713409424
column j: 174
Runtime of the program for j 0.4571866989135742
column j: 175
Runtime of the program for j 0.41010189056396484
column j: 176
Runtime of the program for j 0.4274897575378418
column j: 177
Runtime of the program for j 0.43242716789245605
column j: 178
Runtime of the program for j 0.41451096534729004
column j: 179
Runtime of the program for j 0.43558216094970703
column j: 180
Runtime of the program for j 0.42977118492126465
column j: 181
Runtime of the program for j 0.4201688766479492
column j: 182
Runtime of the program for j 0.43015241622924805
column j: 183
Runtime of the program for j 0.43198108673095703
column j: 184
Runtime of the program for j 0.43807530403137207
column j: 185
Runtime of the program for j 0.4204239845275879
column j: 186
Runtime of the program for j 0.4073903560638428
column j: 187
Runtime of the program for j 0.41045570373535156
column j: 188
Runtime of the program for j 0.12114357948303223
column j: 189
Runtime of the program for j 0.42374444007873535
column j: 190
Runtime of the program for j 0.42478251457214355
column j: 191
Runtime of the program for j 0.4438793659210205
column j: 192
Runtime of the program for j 0.42627739906311035
column j: 193
Runtime of the program for j 0.42592811584472656
column j: 194
Runtime of the program for j 0.43395543098449707
column j: 195
Runtime of the program for j 0.407228946685791
column j: 196
Runtime of the program for j 0.4201698303222656
column j: 197
Runtime of the program for j 0.42546534538269043
column j: 198
Runtime of the program for j 0.4345536231994629
column j: 199
Runtime of the program for j 0.4401516914367676
column j: 200
Runtime of the program for j 0.43387556076049805
column j: 201
Runtime of the program for j 0.4261934757232666
column j: 202
Runtime of the program for j 0.40998291969299316
column j: 203
Runtime of the program for j 0.4224514961242676
column j: 204
Runtime of the program for j 0.14760375022888184
column j: 205
Runtime of the program for j 0.4096856117248535
column j: 206
Runtime of the program for j 0.46413087844848633
column j: 207
Runtime of the program for j 0.4497239589691162
column j: 208
Runtime of the program for j 0.40621352195739746
column j: 209
Runtime of the program for j 0.439816951751709
column j: 210
Runtime of the program for j 0.40779924392700195
column j: 211
Runtime of the program for j 0.4331095218658447
column j: 212
Runtime of the program for j 0.4493672847747803
column j: 213
Runtime of the program for j 0.42015790939331055
column j: 214
Runtime of the program for j 0.40471863746643066
column j: 215
Runtime of the program for j 0.43494749069213867
column j: 216
Runtime of the program for j 0.4202604293823242
column j: 217
Runtime of the program for j 0.46091723442077637
column j: 218
Runtime of the program for j 0.4288773536682129
column j: 219
Runtime of the program for j 0.43993473052978516
column j: 220
Runtime of the program for j 0.44014787673950195
column j: 221
Runtime of the program for j 0.4201633930206299
column j: 222
Runtime of the program for j 0.44999003410339355
column j: 223
Runtime of the program for j 0.44974780082702637
column j: 224
Runtime of the program for j 0.4329357147216797
column j: 225
Runtime of the program for j 0.4370596408843994
column j: 226
Runtime of the program for j 0.4302380084991455
column j: 227
Runtime of the program for j 0.43483591079711914
column j: 228
Runtime of the program for j 0.42531275749206543
column j: 229
Runtime of the program for j 0.4421346187591553
column j: 230
Runtime of the program for j 0.41735363006591797
column j: 231
Runtime of the program for j 0.4351773262023926
column j: 232
Runtime of the program for j 0.439502477645874
column j: 233
Runtime of the program for j 0.40584778785705566
column j: 234
Runtime of the program for j 0.43207597732543945
column j: 235
Runtime of the program for j 0.127532958984375
column j: 236
Runtime of the program for j 0.44202232360839844
column j: 237
Runtime of the program for j 0.43781232833862305
column j: 238
Runtime of the program for j 0.42254114151000977
column j: 239
Runtime of the program for j 0.4276578426361084
column j: 240
Runtime of the program for j 0.4303152561187744
column j: 241
Runtime of the program for j 0.4334390163421631
column j: 242
Runtime of the program for j 0.4564096927642822
column j: 243
Runtime of the program for j 0.3896658420562744
column j: 244
Runtime of the program for j 0.4404032230377197
column j: 245
Runtime of the program for j 0.11957502365112305
column j: 246
Runtime of the program for j 0.43996262550354004
column j: 247
Runtime of the program for j 0.4230220317840576
column j: 248
Runtime of the program for j 0.41608452796936035
column j: 249
Runtime of the program for j 0.4303154945373535
column j: 250
Runtime of the program for j 0.41222071647644043
column j: 251
Runtime of the program for j 0.43757081031799316
column j: 252
Runtime of the program for j 0.4459555149078369
column j: 253
Runtime of the program for j 0.4272313117980957
column j: 254
Runtime of the program for j 0.4666633605957031
column j: 255
Runtime of the program for j 0.43050265312194824
column j: 256
Runtime of the program for j 0.4208946228027344
column j: 257
Runtime of the program for j 0.4265458583831787
column j: 258
Runtime of the program for j 0.42344236373901367
column j: 259
Runtime of the program for j 0.44234538078308105
column j: 260
Runtime of the program for j 0.41773080825805664
column j: 261
Runtime of the program for j 0.4398784637451172
column j: 262
Runtime of the program for j 0.44013357162475586
column j: 263
Runtime of the program for j 0.12489461898803711
column j: 264
Runtime of the program for j 0.43511319160461426
column j: 265
Runtime of the program for j 0.4200289249420166

column j: 266
Runtime of the program for j 0.4197995662689209
column j: 267
Runtime of the program for j 0.4257519245147705
column j: 268
Runtime of the program for j 0.4299037456512451
column j: 269
Runtime of the program for j 0.4580364227294922
column j: 270
Runtime of the program for j 0.13202643394470215
column j: 271
Runtime of the program for j 0.440021276473999
column j: 272
Runtime of the program for j 0.42307472229003906
column j: 273
Runtime of the program for j 0.45694923400878906
column j: 274
Runtime of the program for j 0.43997669219970703
column j: 275
Runtime of the program for j 0.13306522369384766
column j: 276
Runtime of the program for j 0.43703174591064453
column j: 277
Runtime of the program for j 0.42966556549072266
column j: 278
Runtime of the program for j 0.4332246780395508
column j: 279
Runtime of the program for j 0.4267406463623047
column j: 280
Runtime of the program for j 0.43397092819213867
column j: 281
Runtime of the program for j 0.45008349418640137
column j: 282
Runtime of the program for j 0.42484521865844727
column j: 283
Runtime of the program for j 0.4302685260772705
column j: 284
Runtime of the program for j 0.42972731590270996
column j: 285
Runtime of the program for j 0.42009949684143066
column j: 286
Runtime of the program for j 0.43308448791503906
column j: 287
Runtime of the program for j 0.4369516372680664
column j: 288
Runtime of the program for j 0.4255385398864746
column j: 289
Runtime of the program for j 0.4346151351928711
column j: 290
Runtime of the program for j 0.4200446605682373
column j: 291
Runtime of the program for j 0.46477556228637695
column j: 292
Runtime of the program for j 0.4262809753417969
column j: 293
Runtime of the program for j 0.4398539066314697
column j: 294
Runtime of the program for j 0.4202601909637451
column j: 295
Runtime of the program for j 0.42391347885131836
column j: 296
Runtime of the program for j 0.4462242126464844
column j: 297
Runtime of the program for j 0.41608738899230957
column j: 298
Runtime of the program for j 0.40460777282714844
column j: 299
Runtime of the program for j 0.4296548366546631
column j: 300
Runtime of the program for j 0.43967771530151367
column j: 301
Runtime of the program for j 0.42331910133361816
column j: 302
Runtime of the program for j 0.4414486885070801
column j: 303
Runtime of the program for j 0.42488980293273926
column j: 304
Runtime of the program for j 0.4304168224334717
column j: 305
Runtime of the program for j 0.43213415145874023
column j: 306
Runtime of the program for j 0.41739368438720703
column j: 307
Runtime of the program for j 0.44017601013183594
column j: 308
Runtime of the program for j 0.4403812885284424
column j: 309
Runtime of the program for j 0.4399290084838867
column j: 310
Runtime of the program for j 0.439868688583374
column j: 311
Runtime of the program for j 0.4527604579925537
column j: 312
Runtime of the program for j 0.42710328102111816
column j: 313
Runtime of the program for j 0.4399597644805908
column j: 314
Runtime of the program for j 0.14231634140014648
column j: 315
Runtime of the program for j 0.4373800754547119
column j: 316
Runtime of the program for j 0.44242286682128906
column j: 317
Runtime of the program for j 0.44771289825439453
column j: 318
Runtime of the program for j 0.4199092388153076
column j: 319
Runtime of the program for j 0.44661426544189453
column j: 320
Runtime of the program for j 0.4334380626678467
column j: 321
Runtime of the program for j 0.14124464988708496
column j: 322
Runtime of the program for j 0.4646580219268799
column j: 323
Runtime of the program for j 0.44524526596069336
column j: 324
Runtime of the program for j 0.4396185874938965
column j: 325
Runtime of the program for j 0.4277153015136719
column j: 326
Runtime of the program for j 0.45513343811035156
column j: 327
Runtime of the program for j 0.4623558521270752
column j: 328
Runtime of the program for j 0.4352290630340576
column j: 329
Runtime of the program for j 0.46030402183532715
column j: 330
Runtime of the program for j 0.4397585391998291
column j: 331
Runtime of the program for j 0.4371976852416992
column j: 332
Runtime of the program for j 0.44033122062683105
column j: 333
Runtime of the program for j 0.4299137592315674
column j: 334
Runtime of the program for j 0.4397158622741699
column j: 335
Runtime of the program for j 0.4527466297149658
column j: 336
Runtime of the program for j 0.42740797996520996
column j: 337
Runtime of the program for j 0.42261219024658203
column j: 338
Runtime of the program for j 0.43645763397216797
column j: 339
Runtime of the program for j 0.4228169918060303
column j: 340
Runtime of the program for j 0.43978118896484375
column j: 341
Runtime of the program for j 0.41814470291137695
column j: 342
Runtime of the program for j 0.43138551712036133
column j: 343
Runtime of the program for j 0.14877963066101074
column j: 344
Runtime of the program for j 0.4103364944458008
column j: 345
Runtime of the program for j 0.43947672843933105
column j: 346
Runtime of the program for j 0.4302635192871094
column j: 347
Runtime of the program for j 0.45068359375
column j: 348
Runtime of the program for j 0.42354679107666016
column j: 349
Runtime of the program for j 0.4226822853088379
column j: 350
Runtime of the program for j 0.44019055366516113
column j: 351
Runtime of the program for j 0.1425614356994629
column j: 352
Runtime of the program for j 0.4311189651489258
column j: 353
Runtime of the program for j 0.429858922958374
column j: 354
Runtime of the program for j 0.4302690029144287
column j: 355
Runtime of the program for j 0.42001819610595703
column j: 356
Runtime of the program for j 0.4238412380218506
column j: 357
Runtime of the program for j 0.43613314628601074
column j: 358
Runtime of the program for j 0.4497184753417969
column j: 359
Runtime of the program for j 0.41321587562561035
column j: 360
Runtime of the program for j 0.13681864738464355
column j: 361
Runtime of the program for j 0.4399256706237793
column j: 362
Runtime of the program for j 0.42818760871887207
column j: 363
Runtime of the program for j 0.43988895416259766
column j: 364
Runtime of the program for j 0.4324779510498047
column j: 365
Runtime of the program for j 0.43758225440979004
column j: 366
Runtime of the program for j 0.4351530075073242
column j: 367
Runtime of the program for j 0.44765281677246094
column j: 368
Runtime of the program for j 0.4470789432525635
column j: 369
Runtime of the program for j 0.43021368980407715
column j: 370
Runtime of the program for j 0.4797704219818115
column j: 371
Runtime of the program for j 0.4446282386779785
column j: 372
Runtime of the program for j 0.4172041416168213
column j: 373
Runtime of the program for j 0.42818689346313477
column j: 374
Runtime of the program for j 0.4314393997192383
column j: 375
Runtime of the program for j 0.44442200660705566
column j: 376
Runtime of the program for j 0.4455127716064453
column j: 377
Runtime of the program for j 0.41867637634277344
column j: 378
Runtime of the program for j 0.43019986152648926
column j: 379
Runtime of the program for j 0.42955899238586426
column j: 380
Runtime of the program for j 0.45999813079833984
column j: 381
Runtime of the program for j 0.45038890838623047
column j: 382
Runtime of the program for j 0.44980335235595703
column j: 383
Runtime of the program for j 0.4597916603088379
column j: 384
Runtime of the program for j 0.4528346061706543
column j: 385
Runtime of the program for j 0.4472329616546631
column j: 386
Runtime of the program for j 0.434833288192749
column j: 387
Runtime of the program for j 0.4723958969116211
column j: 388
Runtime of the program for j 0.49268388748168945
column j: 389
Runtime of the program for j 0.4700338840484619
column j: 390
Runtime of the program for j 0.46089911460876465
column j: 391
Runtime of the program for j 0.44185566902160645
column j: 392
Runtime of the program for j 0.4313948154449463
column j: 393
Runtime of the program for j 0.12880849838256836
column j: 394
Runtime of the program for j 0.1674365997314453
column j: 395
Runtime of the program for j 0.4448556900024414
column j: 396
Runtime of the program for j 0.4145951271057129
column j: 397
Runtime of the program for j 0.12037134170532227

column j: 398
Runtime of the program for j 0.4298398494720459
column j: 399
Runtime of the program for j 0.43000340461730957
column j: 400
Runtime of the program for j 0.44711947441101074
column j: 401
Runtime of the program for j 0.4535694122314453
column j: 402
Runtime of the program for j 0.4467332363128662
column j: 403
Runtime of the program for j 0.427349328994751
column j: 404
Runtime of the program for j 0.4217979907989502
column j: 405
Runtime of the program for j 0.420623779296875
column j: 406
Runtime of the program for j 0.4310016632080078
column j: 407
Runtime of the program for j 0.4347195625305176
column j: 408
Runtime of the program for j 0.46212291717529297
column j: 409
Runtime of the program for j 0.4395570755004883
column j: 410
Runtime of the program for j 0.4473452568054199
column j: 411
Runtime of the program for j 0.422745943069458
column j: 412
Runtime of the program for j 0.4503154754638672
column j: 413
Runtime of the program for j 0.4630253314971924
column j: 414
Runtime of the program for j 0.4568297863006592
column j: 415
Runtime of the program for j 0.43995094299316406
column j: 416
Runtime of the program for j 0.4498584270477295
column j: 417
Runtime of the program for j 0.4332001209259033
column j: 418
Runtime of the program for j 0.4300038814544678
column j: 419
Runtime of the program for j 0.4442265033721924
column j: 420
Runtime of the program for j 0.4301314353942871
column j: 421
Runtime of the program for j 0.4721808433532715
column j: 422
Runtime of the program for j 0.44762420654296875
column j: 423
Runtime of the program for j 0.44030117988586426
column j: 424
Runtime of the program for j 0.4735450744628906
column j: 425
Runtime of the program for j 0.4064052104949951
column j: 426
Runtime of the program for j 0.42975711822509766
column j: 427
Runtime of the program for j 0.4526793956756592
column j: 428
Runtime of the program for j 0.42971372604370117
column j: 429
Runtime of the program for j 0.43781304359436035
column j: 430
Runtime of the program for j 0.15998148918151855
column j: 431
Runtime of the program for j 0.14507222175598145
column j: 432
Runtime of the program for j 0.14473581314086914
column j: 433
Runtime of the program for j 0.42299962043762207
column j: 434
Runtime of the program for j 0.4201037883758545
column j: 435
Runtime of the program for j 0.38730955123901367
column j: 436
Runtime of the program for j 0.3994140625
column j: 437
Runtime of the program for j 0.4626467227935791
column j: 438
Runtime of the program for j 0.15101218223571777
column j: 439
Runtime of the program for j 0.42681288719177246
column j: 440
Runtime of the program for j 0.4399220943450928
column j: 441
Runtime of the program for j 0.44254374504089355
column j: 442
Runtime of the program for j 0.4501955509185791
column j: 443
Runtime of the program for j 0.14711236953735352
column j: 444
Runtime of the program for j 0.4802234172821045
column j: 445
Runtime of the program for j 0.4196445941925049
column j: 446
Runtime of the program for j 0.4527418613433838
column j: 447
Runtime of the program for j 0.43746495246887207
column j: 448
Runtime of the program for j 0.4501826763153076
column j: 449
Runtime of the program for j 0.4461038112640381
column j: 450
Runtime of the program for j 0.43284010887145996
column j: 451
Runtime of the program for j 0.44028615951538086
column j: 452
Runtime of the program for j 0.4424140453338623
column j: 453
Runtime of the program for j 0.4502584934234619
column j: 454
Runtime of the program for j 0.4469730854034424
column j: 455
Runtime of the program for j 0.5178971290588379
column j: 456
Runtime of the program for j 0.44987964630126953
column j: 457
Runtime of the program for j 0.47474241256713867
column j: 458
Runtime of the program for j 0.45264244079589844
column j: 459
Runtime of the program for j 0.4382784366607666
column j: 460
Runtime of the program for j 0.4444241523742676
column j: 461
Runtime of the program for j 0.41001057624816895
column j: 462
Runtime of the program for j 0.45998692512512207
column j: 463
Runtime of the program for j 0.42223477363586426
column j: 464
Runtime of the program for j 0.44744062423706055
column j: 465
Runtime of the program for j 0.4526491165161133
column j: 466
Runtime of the program for j 0.45096540451049805
column j: 467
Runtime of the program for j 0.456493616104126
column j: 468
Runtime of the program for j 0.4398531913757324
column j: 469
Runtime of the program for j 0.47589707374572754
column j: 470
Runtime of the program for j 0.4298999309539795
column j: 471
Runtime of the program for j 0.4442713260650635
column j: 472
Runtime of the program for j 0.47020959854125977
column j: 473
Runtime of the program for j 0.14472174644470215
column j: 474
Runtime of the program for j 0.4307272434234619
column j: 475
Runtime of the program for j 0.42731809616088867
column j: 476
Runtime of the program for j 0.43727779388427734
column j: 477
Runtime of the program for j 0.5398275852203369
column j: 478
Runtime of the program for j 0.44293713569641113
column j: 479
Runtime of the program for j 0.439786434173584
column j: 480
Runtime of the program for j 0.4774031639099121
column j: 481
Runtime of the program for j 0.452197790145874
column j: 482
Runtime of the program for j 0.5078690052032471
column j: 483
Runtime of the program for j 0.45970821380615234
column j: 484
Runtime of the program for j 0.45995330810546875
column j: 485
Runtime of the program for j 0.42044973373413086
column j: 486
Runtime of the program for j 0.4495737552642822
column j: 487
Runtime of the program for j 0.4400668144226074
column j: 488
Runtime of the program for j 0.4401891231536865
column j: 489
Runtime of the program for j 0.4311065673828125
column j: 490
Runtime of the program for j 0.4687659740447998
column j: 491
Runtime of the program for j 0.4536459445953369
column j: 492
Runtime of the program for j 0.4785475730895996
column j: 493
Runtime of the program for j 0.4988248348236084
column j: 494
Runtime of the program for j 0.44890737533569336
column j: 495
Runtime of the program for j 0.4702110290527344
column j: 496
Runtime of the program for j 0.44003820419311523
column j: 497
Runtime of the program for j 0.15306377410888672
column j: 498
Runtime of the program for j 0.43954014778137207
column j: 499
Runtime of the program for j 0.4277377128601074
column j: 500
Runtime of the program for j 0.4497249126434326
column j: 501
Runtime of the program for j 0.5023283958435059
column j: 502
Runtime of the program for j 0.1506214141845703
column j: 503
Runtime of the program for j 0.4394190311431885
column j: 504
Runtime of the program for j 0.4503312110900879
column j: 505
Runtime of the program for j 0.42796897888183594
column j: 506
Runtime of the program for j 0.46198010444641113
column j: 507
Runtime of the program for j 0.41750097274780273
column j: 508
Runtime of the program for j 0.462374210357666
column j: 509
Runtime of the program for j 0.4203815460205078
column j: 510
Runtime of the program for j 0.3770942687988281
column j: 511
Runtime of the program for j 0.4401686191558838
column j: 512
Runtime of the program for j 0.4224112033843994
column j: 513
Runtime of the program for j 0.43738698959350586
column j: 514
Runtime of the program for j 0.4698967933654785
column j: 515
Runtime of the program for j 0.15012598037719727
column j: 516
Runtime of the program for j 0.451108455657959
column j: 517
Runtime of the program for j 0.4452998638153076
column j: 518
Runtime of the program for j 0.4222252368927002
column j: 519
Runtime of the program for j 0.453000545501709
column j: 520
Runtime of the program for j 0.428342342376709
column j: 521
Runtime of the program for j 0.4398031234741211
column j: 522
Runtime of the program for j 0.4303548336029053
column j: 523
Runtime of the program for j 0.4175105094909668
column j: 524
Runtime of the program for j 0.41205668449401855
column j: 525
Runtime of the program for j 0.14009499549865723
column j: 526
Runtime of the program for j 0.4176025390625
column j: 527
Runtime of the program for j 0.4402456283569336
column j: 528
Runtime of the program for j 0.4725918769836426
column j: 529
Runtime of the program for j 0.48726797103881836

column j: 530
Runtime of the program for j 0.4676330089569092
column j: 531
Runtime of the program for j 0.4148397445678711
column j: 532
Runtime of the program for j 0.47157716751098633
column j: 533
Runtime of the program for j 0.42575597763061523
column j: 534
Runtime of the program for j 0.44444918632507324
column j: 535
Runtime of the program for j 0.13567352294921875
column j: 536
Runtime of the program for j 0.4501683712005615
column j: 537
Runtime of the program for j 0.42046451568603516
column j: 538
Runtime of the program for j 0.14207220077514648
column j: 539
Runtime of the program for j 0.15764379501342773
column j: 540
Runtime of the program for j 0.14169764518737793
column j: 541
Runtime of the program for j 0.4520716667175293
column j: 542
Runtime of the program for j 0.4157252311706543
column j: 543
Runtime of the program for j 0.44269824028015137
column j: 544
Runtime of the program for j 0.4260683059692383
column j: 545
Runtime of the program for j 0.43705248832702637
column j: 546
Runtime of the program for j 0.4391658306121826
column j: 547
Runtime of the program for j 0.46680521965026855
column j: 548
Runtime of the program for j 0.47106099128723145
column j: 549
Runtime of the program for j 0.4807753562927246
column j: 550
Runtime of the program for j 0.17255353927612305
column j: 551
Runtime of the program for j 0.1687009334564209
column j: 552
Runtime of the program for j 0.464522123336792
column j: 553
Runtime of the program for j 0.4199073314666748
column j: 554
Runtime of the program for j 0.4462742805480957
column j: 555
Runtime of the program for j 0.4798014163970947
column j: 556
Runtime of the program for j 0.4647862911224365
column j: 557
Runtime of the program for j 0.46456074714660645
column j: 558
Runtime of the program for j 0.5098040103912354
column j: 559
Runtime of the program for j 0.4577310085296631
column j: 560
Runtime of the program for j 0.5120754241943359
column j: 561
Runtime of the program for j 0.45741915702819824
column j: 562
Runtime of the program for j 0.422945499420166
column j: 563
Runtime of the program for j 0.4194831848144531
column j: 564
Runtime of the program for j 0.46004247665405273
column j: 565
Runtime of the program for j 0.43015599250793457
column j: 566
Runtime of the program for j 0.44956064224243164
column j: 567
Runtime of the program for j 0.45952749252319336
column j: 568
Runtime of the program for j 0.46334338188171387
column j: 569
Runtime of the program for j 0.4669678211212158
column j: 570
Runtime of the program for j 0.4524812698364258
column j: 571
Runtime of the program for j 0.15781402587890625
column j: 572
Runtime of the program for j 0.4425358772277832
column j: 573
Runtime of the program for j 0.45025205612182617
column j: 574
Runtime of the program for j 0.4329383373260498
column j: 575
Runtime of the program for j 0.4538304805755615
column j: 576
Runtime of the program for j 0.43049097061157227
column j: 577
Runtime of the program for j 0.4300670623779297
column j: 578
Runtime of the program for j 0.4418060779571533
column j: 579
Runtime of the program for j 0.4879887104034424
column j: 580
Runtime of the program for j 0.43965792655944824
column j: 581
Runtime of the program for j 0.46163034439086914
column j: 582
Runtime of the program for j 0.4285757541656494
column j: 583
Runtime of the program for j 0.4533042907714844
column j: 584
Runtime of the program for j 0.4465792179107666
column j: 585
Runtime of the program for j 0.4502091407775879
column j: 586
Runtime of the program for j 0.44014644622802734
column j: 587
Runtime of the program for j 0.45965075492858887
column j: 588
Runtime of the program for j 0.475635290145874
column j: 589
Runtime of the program for j 0.457247257232666
column j: 590
Runtime of the program for j 0.46308398246765137
column j: 591
Runtime of the program for j 0.4312613010406494
column j: 592
Runtime of the program for j 0.4401125907897949
column j: 593
Runtime of the program for j 0.4425997734069824
column j: 594
Runtime of the program for j 0.4369974136352539
column j: 595
Runtime of the program for j 0.1642601490020752
column j: 596
Runtime of the program for j 0.42236971855163574
column j: 597
Runtime of the program for j 0.4154689311981201
column j: 598
Runtime of the program for j 0.4501330852508545
column j: 599
Runtime of the program for j 0.4444124698638916
column j: 600
Runtime of the program for j 0.4590573310852051
column j: 601
Runtime of the program for j 0.1466965675354004
column j: 602
Runtime of the program for j 0.43007493019104004
column j: 603
Runtime of the program for j 0.4207801818847656
column j: 604
Runtime of the program for j 0.42903757095336914
column j: 605
Runtime of the program for j 0.4499669075012207
column j: 606
Runtime of the program for j 0.46024560928344727
column j: 607
Runtime of the program for j 0.4311835765838623
column j: 608
Runtime of the program for j 0.46865105628967285
column j: 609
Runtime of the program for j 0.42092394828796387
column j: 610
Runtime of the program for j 0.4391806125640869
column j: 611
Runtime of the program for j 0.4399235248565674
column j: 612
Runtime of the program for j 0.4346010684967041
column j: 613
Runtime of the program for j 0.43675732612609863
column j: 614
Runtime of the program for j 0.46831750869750977
column j: 615
Runtime of the program for j 0.42273592948913574
column j: 616
Runtime of the program for j 0.44249916076660156
column j: 617
Runtime of the program for j 0.43255615234375
column j: 618
Runtime of the program for j 0.4422643184661865
column j: 619
Runtime of the program for j 0.46250319480895996
column j: 620
Runtime of the program for j 0.4403512477874756
column j: 621
Runtime of the program for j 0.4509894847869873
column j: 622
Runtime of the program for j 0.4664950370788574
column j: 623
Runtime of the program for j 0.4322330951690674
column j: 624
Runtime of the program for j 0.45284342765808105
column j: 625
Runtime of the program for j 0.41611766815185547
column j: 626
Runtime of the program for j 0.439075231552124
column j: 627
Runtime of the program for j 0.4396488666534424
column j: 628
Runtime of the program for j 0.4264683723449707
column j: 629
Runtime of the program for j 0.4331648349761963
column j: 630
Runtime of the program for j 0.44552040100097656
column j: 631
Runtime of the program for j 0.41475653648376465
column j: 632
Runtime of the program for j 0.4542660713195801
column j: 633
Runtime of the program for j 0.4628715515136719
column j: 634
Runtime of the program for j 0.4350471496582031
column j: 635
Runtime of the program for j 0.45757603645324707
column j: 636
Runtime of the program for j 0.46271538734436035
column j: 637
Runtime of the program for j 0.42743825912475586
column j: 638
Runtime of the program for j 0.4826624393463135
column j: 639
Runtime of the program for j 0.13959193229675293
column j: 640
Runtime of the program for j 0.4377555847167969
column j: 641
Runtime of the program for j 0.43969297409057617
column j: 642
Runtime of the program for j 0.4444289207458496
column j: 643
Runtime of the program for j 0.4111626148223877
column j: 644
Runtime of the program for j 0.44460487365722656
column j: 645
Runtime of the program for j 0.4237494468688965
column j: 646
Runtime of the program for j 0.4495382308959961
column j: 647
Runtime of the program for j 0.4422450065612793
column j: 648
Runtime of the program for j 0.4406721591949463
column j: 649
Runtime of the program for j 0.4534938335418701
column j: 650
Runtime of the program for j 0.4467613697052002
column j: 651
Runtime of the program for j 0.13345670700073242
column j: 652
Runtime of the program for j 0.4509098529815674
column j: 653
Runtime of the program for j 0.439342737197876
column j: 654
Runtime of the program for j 0.4478273391723633
column j: 655
Runtime of the program for j 0.44438982009887695
column j: 656
Runtime of the program for j 0.45995211601257324
column j: 657
Runtime of the program for j 0.43600940704345703
column j: 658
Runtime of the program for j 0.456540584564209
column j: 659
Runtime of the program for j 0.46411609649658203
column j: 660
Runtime of the program for j 0.42079782485961914
column j: 661
Runtime of the program for j 0.4501829147338867

column j: 662
Runtime of the program for j 0.4599175453186035
column j: 663
Runtime of the program for j 0.4201991558074951
column j: 664
Runtime of the program for j 0.4722292423248291
column j: 665
Runtime of the program for j 0.4376230239868164
column j: 666
Runtime of the program for j 0.4539608955383301
column j: 667
Runtime of the program for j 0.46126675605773926
column j: 668
Runtime of the program for j 0.45957422256469727
column j: 669
Runtime of the program for j 0.5058455467224121
column j: 670
Runtime of the program for j 0.45735955238342285
column j: 671
Runtime of the program for j 0.45186805725097656
column j: 672
Runtime of the program for j 0.44986414909362793
column j: 673
Runtime of the program for j 0.4752004146575928
column j: 674
Runtime of the program for j 0.4600536823272705
column j: 675
Runtime of the program for j 0.43372082710266113
column j: 676
Runtime of the program for j 0.43005943298339844
column j: 677
Runtime of the program for j 0.4703695774078369
column j: 678
Runtime of the program for j 0.4194447994232178
column j: 679
Runtime of the program for j 0.4253554344177246
column j: 680
Runtime of the program for j 0.46504712104797363
column j: 681
Runtime of the program for j 0.16965913772583008
column j: 682
Runtime of the program for j 0.4399878978729248
column j: 683
Runtime of the program for j 0.46518969535827637
column j: 684
Runtime of the program for j 0.46802639961242676
column j: 685
Runtime of the program for j 0.42612195014953613
column j: 686
Runtime of the program for j 0.4501504898071289
column j: 687
Runtime of the program for j 0.4498300552368164
column j: 688
Runtime of the program for j 0.4358186721801758
column j: 689
Runtime of the program for j 0.4288005828857422
column j: 690
Runtime of the program for j 0.4699580669403076
column j: 691
Runtime of the program for j 0.44715118408203125
column j: 692
Runtime of the program for j 0.4364776611328125
column j: 693
Runtime of the program for j 0.49259161949157715
column j: 694
Runtime of the program for j 0.4542355537414551
column j: 695
Runtime of the program for j 0.4480767250061035
column j: 696
Runtime of the program for j 0.49014759063720703
column j: 697
Runtime of the program for j 0.47977185249328613
column j: 698
Runtime of the program for j 0.470428466796875
column j: 699
Runtime of the program for j 0.46986985206604004
column j: 700
Runtime of the program for j 0.4954991340637207
column j: 701
Runtime of the program for j 0.469423770904541
column j: 702
Runtime of the program for j 0.45508551597595215
column j: 703
Runtime of the program for j 0.4698779582977295
column j: 704
Runtime of the program for j 0.4466133117675781
column j: 705
Runtime of the program for j 0.45345282554626465
column j: 706
Runtime of the program for j 0.4849131107330322
column j: 707
Runtime of the program for j 0.4697244167327881
column j: 708
Runtime of the program for j 0.4501819610595703
column j: 709
Runtime of the program for j 0.42035603523254395
column j: 710
Runtime of the program for j 0.4699251651763916
column j: 711
Runtime of the program for j 0.4950597286224365
column j: 712
Runtime of the program for j 0.4448738098144531
column j: 713
Runtime of the program for j 0.46956777572631836
column j: 714
Runtime of the program for j 0.4499082565307617
column j: 715
Runtime of the program for j 0.45015907287597656
column j: 716
Runtime of the program for j 0.44524526596069336
column j: 717
Runtime of the program for j 0.45763182640075684
column j: 718
Runtime of the program for j 0.4420738220214844
column j: 719
Runtime of the program for j 0.4299182891845703
column j: 720
Runtime of the program for j 0.4565706253051758
column j: 721
Runtime of the program for j 0.46877121925354004
column j: 722
Runtime of the program for j 0.46007633209228516
column j: 723
Runtime of the program for j 0.44486165046691895
column j: 724
Runtime of the program for j 0.4385488033294678
column j: 725
Runtime of the program for j 0.4566187858581543
column j: 726
Runtime of the program for j 0.459975004196167
column j: 727
Runtime of the program for j 0.3318500518798828
column j: 728
Runtime of the program for j 0.4329533576965332
column j: 729
Runtime of the program for j 0.3819284439086914
column j: 730
Runtime of the program for j 0.43265795707702637
column j: 731
Runtime of the program for j 0.45615291595458984
column j: 732
Runtime of the program for j 0.4844212532043457
column j: 733
Runtime of the program for j 0.46308445930480957
column j: 734
Runtime of the program for j 0.42171216011047363
column j: 735
Runtime of the program for j 0.4652369022369385
column j: 736
Runtime of the program for j 0.43993496894836426
column j: 737
Runtime of the program for j 0.5799345970153809
column j: 738
Runtime of the program for j 0.5227541923522949
column j: 739
Runtime of the program for j 0.5040459632873535
column j: 740
Runtime of the program for j 0.5252087116241455
column j: 741
Runtime of the program for j 0.4880523681640625
column j: 742
Runtime of the program for j 0.14996647834777832
column j: 743
Runtime of the program for j 0.47988128662109375
column j: 744
Runtime of the program for j 0.49504590034484863
column j: 745
Runtime of the program for j 0.5252499580383301
column j: 746
Runtime of the program for j 0.5036189556121826
column j: 747
Runtime of the program for j 0.43093156814575195
column j: 748
Runtime of the program for j 0.1971447467803955
column j: 749
Runtime of the program for j 0.17312288284301758
column j: 750
Runtime of the program for j 0.14651226997375488
column j: 751
Runtime of the program for j 0.1583256721496582
column j: 752
Runtime of the program for j 0.23480892181396484
column j: 753
Runtime of the program for j 0.24521923065185547
column j: 754
Runtime of the program for j 0.19012212753295898
column j: 755
Runtime of the program for j 0.19219470024108887
column j: 756
Runtime of the program for j 0.22055697441101074
column j: 757
Runtime of the program for j 0.17693805694580078
column j: 758
Runtime of the program for j 0.15990138053894043
column j: 759
Runtime of the program for j 0.1357555389404297
column j: 760
Runtime of the program for j 0.2311265468597412
column j: 761
Runtime of the program for j 0.17364168167114258
column j: 762
Runtime of the program for j 0.21984505653381348
column j: 763
Runtime of the program for j 0.15736722946166992
column j: 764
Runtime of the program for j 0.22263526916503906
column j: 765
Runtime of the program for j 0.2373034954071045
column j: 766
Runtime of the program for j 0.08234906196594238
column j: 767
Runtime of the program for j 0.20008301734924316
column j: 768
Runtime of the program for j 0.07082796096801758
column j: 769
Runtime of the program for j 0.18300175666809082
column j: 770
Runtime of the program for j 0.16665863990783691
column j: 771
Runtime of the program for j 0.16968870162963867
column j: 772
Runtime of the program for j 0.20307707786560059
column j: 773
Runtime of the program for j 0.17681431770324707
column j: 774
Runtime of the program for j 0.180161714553833
column j: 775
Runtime of the program for j 0.3814656734466553
column j: 776
Runtime of the program for j 0.49175143241882324
column j: 777
Runtime of the program for j 0.40680980682373047
column j: 778
Runtime of the program for j 0.43006277084350586
column j: 779
Runtime of the program for j 0.433868408203125
column j: 780
Runtime of the program for j 0.13779520988464355
column j: 781
Runtime of the program for j 0.438457727432251
column j: 782
Runtime of the program for j 0.4642333984375
column j: 783
Runtime of the program for j 0.43917322158813477
column j: 784
Runtime of the program for j 0.4472377300262451
column j: 785
Runtime of the program for j 0.4488799571990967
column j: 786
Runtime of the program for j 0.42406249046325684
column j: 787
Runtime of the program for j 0.49611783027648926
column j: 788
Runtime of the program for j 0.4253571033477783
column j: 789
Runtime of the program for j 0.45419788360595703
column j: 790
Runtime of the program for j 0.4315052032470703
column j: 791
Runtime of the program for j 0.4178333282470703
column j: 792
Runtime of the program for j 0.47438716888427734
column j: 793
Runtime of the program for j 0.48253583908081055

column j: 794
Runtime of the program for j 0.495302677154541
column j: 795
Runtime of the program for j 0.4417726993560791
column j: 796
Runtime of the program for j 0.45841503143310547
column j: 797
Runtime of the program for j 0.4778294563293457
column j: 798
Runtime of the program for j 0.43175458908081055
column j: 799
Runtime of the program for j 0.44987058639526367
column j: 800
Runtime of the program for j 0.4017174243927002
column j: 801
Runtime of the program for j 0.4163777828216553
column j: 802
Runtime of the program for j 0.4750838279724121
column j: 803
Runtime of the program for j 0.4503364562988281
column j: 804
Runtime of the program for j 0.4634995460510254
column j: 805
Runtime of the program for j 0.44019007682800293
column j: 806
Runtime of the program for j 0.4499502182006836
column j: 807
Runtime of the program for j 0.47668981552124023
column j: 808
Runtime of the program for j 0.45287609100341797
column j: 809
Runtime of the program for j 0.4764273166656494
column j: 810
Runtime of the program for j 0.4036836624145508
column j: 811
Runtime of the program for j 0.4403374195098877
column j: 812
Runtime of the program for j 0.4698188304901123
column j: 813
Runtime of the program for j 0.4249565601348877
column j: 814
Runtime of the program for j 0.45047497749328613
column j: 815
Runtime of the program for j 0.43219995498657227
column j: 816
Runtime of the program for j 0.4141983985900879
column j: 817
Runtime of the program for j 0.41826534271240234
column j: 818
Runtime of the program for j 0.44994258880615234
column j: 819
Runtime of the program for j 0.4562950134277344
column j: 820
Runtime of the program for j 0.42664480209350586
column j: 821
Runtime of the program for j 0.4333949089050293
column j: 822
Runtime of the program for j 0.44429969787597656
column j: 823
Runtime of the program for j 0.46966052055358887
column j: 824
Runtime of the program for j 0.4198005199432373
column j: 825
Runtime of the program for j 0.480236291885376
column j: 826
Runtime of the program for j 0.5096991062164307
column j: 827
Runtime of the program for j 0.4500846862792969
column j: 828
Runtime of the program for j 0.4449009895324707
column j: 829
Runtime of the program for j 0.4649815559387207
column j: 830
Runtime of the program for j 0.42484283447265625
column j: 831
Runtime of the program for j 0.4499378204345703
column j: 832
Runtime of the program for j 0.420459508895874
column j: 833
Runtime of the program for j 0.45937204360961914
column j: 834
Runtime of the program for j 0.43047666549682617
column j: 835
Runtime of the program for j 0.4409012794494629
column j: 836
Runtime of the program for j 0.4492826461791992
column j: 837
Runtime of the program for j 0.4300203323364258
column j: 838
Runtime of the program for j 0.4597947597503662
column j: 839
Runtime of the program for j 0.4172511100769043
column j: 840
Runtime of the program for j 0.40765953063964844
column j: 841
Runtime of the program for j 0.4349782466888428
column j: 842
Runtime of the program for j 0.45427441596984863
column j: 843
Runtime of the program for j 0.4668285846710205
column j: 844
Runtime of the program for j 0.49879980087280273
column j: 845
Runtime of the program for j 0.49497008323669434
column j: 846
Runtime of the program for j 0.4680502414703369
column j: 847
Runtime of the program for j 0.46689295768737793
column j: 848
Runtime of the program for j 0.4502131938934326
column j: 849
Runtime of the program for j 0.16733193397521973
column j: 850
Runtime of the program for j 0.4626765251159668
column j: 851
Runtime of the program for j 0.4236946105957031
column j: 852
Runtime of the program for j 0.43601536750793457
column j: 853
Runtime of the program for j 0.38005733489990234
column j: 854
Runtime of the program for j 0.44244933128356934
column j: 855
Runtime of the program for j 0.4273247718811035
column j: 856
Runtime of the program for j 0.400299072265625
column j: 857
Runtime of the program for j 0.431488037109375
column j: 858
Runtime of the program for j 0.4437577724456787
column j: 859
Runtime of the program for j 0.4740123748779297
column j: 860
Runtime of the program for j 0.5063493251800537
column j: 861
Runtime of the program for j 0.4341011047363281
column j: 862
Runtime of the program for j 0.41920900344848633
column j: 863
Runtime of the program for j 0.43173909187316895
column j: 864
Runtime of the program for j 0.45964956283569336
column j: 865
Runtime of the program for j 0.45116686820983887
column j: 866
Runtime of the program for j 0.47403502464294434
column j: 867
Runtime of the program for j 0.43631529808044434
column j: 868
Runtime of the program for j 0.44469189643859863
column j: 869
Runtime of the program for j 0.4450070858001709
column j: 870
Runtime of the program for j 0.4305109977722168
column j: 871
Runtime of the program for j 0.4541647434234619
column j: 872
Runtime of the program for j 0.4357724189758301
column j: 873
Runtime of the program for j 0.45992159843444824
column j: 874
Runtime of the program for j 0.43385934829711914
column j: 875
Runtime of the program for j 0.48099184036254883
column j: 876
Runtime of the program for j 0.4148440361022949
column j: 877
Runtime of the program for j 0.4403071403503418
column j: 878
Runtime of the program for j 0.46482110023498535
column j: 879
Runtime of the program for j 0.444810152053833
column j: 880
Runtime of the program for j 0.4650719165802002
column j: 881
Runtime of the program for j 0.4501841068267822
column j: 882
Runtime of the program for j 0.4699552059173584
column j: 883
Runtime of the program for j 0.4247913360595703
column j: 884
Runtime of the program for j 0.47204065322875977
column j: 885
Runtime of the program for j 0.43285107612609863
column j: 886
Runtime of the program for j 0.4302713871002197
column j: 887
Runtime of the program for j 0.1653003692626953
column j: 888
Runtime of the program for j 0.4156510829925537
column j: 889
Runtime of the program for j 0.43873047828674316
column j: 890
Runtime of the program for j 0.4400670528411865
column j: 891
Runtime of the program for j 0.4450371265411377
column j: 892
Runtime of the program for j 0.47495341300964355
column j: 893
Runtime of the program for j 0.45997166633605957
column j: 894
Runtime of the program for j 0.43514227867126465
column j: 895
Runtime of the program for j 0.14982080459594727
column j: 896
Runtime of the program for j 0.46021056175231934
column j: 897
Runtime of the program for j 0.44452428817749023
column j: 898
Runtime of the program for j 0.5403656959533691
column j: 899
Runtime of the program for j 0.15047645568847656
column j: 900
Runtime of the program for j 0.4546520709991455
column j: 901
Runtime of the program for j 0.43976497650146484
column j: 902
Runtime of the program for j 0.5099961757659912
column j: 903
Runtime of the program for j 0.4498403072357178
column j: 904
Runtime of the program for j 0.42191553115844727
column j: 905
Runtime of the program for j 0.42340683937072754
column j: 906
Runtime of the program for j 0.41742658615112305
column j: 907
Runtime of the program for j 0.45224833488464355
column j: 908
Runtime of the program for j 0.4451131820678711
column j: 909
Runtime of the program for j 0.4803140163421631
column j: 910
Runtime of the program for j 0.4377756118774414
column j: 911
Runtime of the program for j 0.4756050109863281
column j: 912
Runtime of the program for j 0.4365580081939697
column j: 913
Runtime of the program for j 0.46993112564086914
column j: 914
Runtime of the program for j 0.4698028564453125
column j: 915
Runtime of the program for j 0.4750697612762451
column j: 916
Runtime of the program for j 0.41513609886169434
column j: 917
Runtime of the program for j 0.4557361602783203
column j: 918
Runtime of the program for j 0.463961124420166
column j: 919
Runtime of the program for j 0.4400343894958496
column j: 920
Runtime of the program for j 0.461719274520874
column j: 921
Runtime of the program for j 0.4233584403991699
column j: 922
Runtime of the program for j 0.4599618911743164
column j: 923
Runtime of the program for j 0.44009971618652344
column j: 924
Runtime of the program for j 0.4598684310913086
column j: 925
Runtime of the program for j 0.4651210308074951

column j: 926
Runtime of the program for j 0.4647252559661865
column j: 927
Runtime of the program for j 0.4348258972167969
column j: 928
Runtime of the program for j 0.46846723556518555
column j: 929
Runtime of the program for j 0.43679141998291016
column j: 930
Runtime of the program for j 0.43013811111450195
column j: 931
Runtime of the program for j 0.43972158432006836
column j: 932
Runtime of the program for j 0.44188499450683594
column j: 933
Runtime of the program for j 0.17512297630310059
column j: 934
Runtime of the program for j 0.43844056129455566
column j: 935
Runtime of the program for j 0.4599123001098633
column j: 936
Runtime of the program for j 0.4296302795410156
column j: 937
Runtime of the program for j 0.47923779487609863
column j: 938
Runtime of the program for j 0.4509284496307373
column j: 939
Runtime of the program for j 0.4451103210449219
column j: 940
Runtime of the program for j 0.4198269844055176
column j: 941
Runtime of the program for j 0.4597475528717041
column j: 942
Runtime of the program for j 0.45202064514160156
column j: 943
Runtime of the program for j 0.4743785858154297
column j: 944
Runtime of the program for j 0.42041945457458496
column j: 945
Runtime of the program for j 0.42494869232177734
column j: 946
Runtime of the program for j 0.41996240615844727
column j: 947
Runtime of the program for j 0.43480491638183594
column j: 948
Runtime of the program for j 0.4247763156890869
column j: 949
Runtime of the program for j 0.45533108711242676
column j: 950
Runtime of the program for j 0.46472930908203125
column j: 951
Runtime of the program for j 0.5103580951690674
column j: 952
Runtime of the program for j 0.48993611335754395
column j: 953
Runtime of the program for j 0.4416506290435791
column j: 954
Runtime of the program for j 0.46816444396972656
column j: 955
Runtime of the program for j 0.4383735656738281
column j: 956
Runtime of the program for j 0.4537663459777832
column j: 957
Runtime of the program for j 0.430255651473999
column j: 958
Runtime of the program for j 0.46626949310302734
column j: 959
Runtime of the program for j 0.4450368881225586
column j: 960
Runtime of the program for j 0.4598715305328369
column j: 961
Runtime of the program for j 0.43684959411621094
column j: 962
Runtime of the program for j 0.46065735816955566
column j: 963
Runtime of the program for j 0.44110631942749023
column j: 964
Runtime of the program for j 0.4614243507385254
column j: 965
Runtime of the program for j 0.4399406909942627
column j: 966
Runtime of the program for j 0.48513102531433105
column j: 967
Runtime of the program for j 0.4546995162963867
column j: 968
Runtime of the program for j 0.4601585865020752
column j: 969
Runtime of the program for j 0.4247772693634033
column j: 970
Runtime of the program for j 0.4260718822479248
column j: 971
Runtime of the program for j 0.4391653537750244
column j: 972
Runtime of the program for j 0.4148404598236084
column j: 973
Runtime of the program for j 0.4401373863220215
column j: 974
Runtime of the program for j 0.45135927200317383
column j: 975
Runtime of the program for j 0.4734165668487549
column j: 976
Runtime of the program for j 0.44938158988952637
column j: 977
Runtime of the program for j 0.47088003158569336
column j: 978
Runtime of the program for j 0.44489026069641113
column j: 979
Runtime of the program for j 0.4751865863800049
column j: 980
Runtime of the program for j 0.45988011360168457
column j: 981
Runtime of the program for j 0.46499156951904297
column j: 982
Runtime of the program for j 0.452984094619751
column j: 983
Runtime of the program for j 0.46176719665527344
column j: 984
Runtime of the program for j 0.44522833824157715
column j: 985
Runtime of the program for j 0.48004817962646484
column j: 986
Runtime of the program for j 0.43502140045166016
column j: 987
Runtime of the program for j 0.4848906993865967
column j: 988
Runtime of the program for j 0.42610740661621094
column j: 989
Runtime of the program for j 0.4986710548400879
column j: 990
Runtime of the program for j 0.43755292892456055
column j: 991
Runtime of the program for j 0.4775688648223877
column j: 992
Runtime of the program for j 0.445096492767334
column j: 993
Runtime of the program for j 0.47548866271972656
column j: 994
Runtime of the program for j 0.4497873783111572
column j: 995
Runtime of the program for j 0.4799339771270752
column j: 996
Runtime of the program for j 0.43976569175720215
column j: 997
Runtime of the program for j 0.17978954315185547
column j: 998
Runtime of the program for j 0.44057750701904297
column j: 999
Runtime of the program for j 0.47981691360473633
column j: 1000
Runtime of the program for j 0.4446375370025635
column j: 1001
Runtime of the program for j 0.47524476051330566
column j: 1002
Runtime of the program for j 0.4300539493560791
column j: 1003
Runtime of the program for j 0.4646127223968506
column j: 1004
Runtime of the program for j 0.43272852897644043
column j: 1005
Runtime of the program for j 0.47742748260498047
column j: 1006
Runtime of the program for j 0.42792820930480957
column j: 1007
Runtime of the program for j 0.4718058109283447
column j: 1008
Runtime of the program for j 0.43625736236572266
column j: 1009
Runtime of the program for j 0.47404050827026367
column j: 1010
Runtime of the program for j 0.46483492851257324
column j: 1011
Runtime of the program for j 0.46486401557922363
column j: 1012
Runtime of the program for j 0.4403834342956543
column j: 1013
Runtime of the program for j 0.4595825672149658
column j: 1014
Runtime of the program for j 0.4601418972015381
column j: 1015
Runtime of the program for j 0.47213268280029297
column j: 1016
Runtime of the program for j 0.4509451389312744
column j: 1017
Runtime of the program for j 0.46721744537353516
column j: 1018
Runtime of the program for j 0.45271801948547363
column j: 1019
Runtime of the program for j 0.46212100982666016
column j: 1020
Runtime of the program for j 0.43517231941223145
column j: 1021
Runtime of the program for j 0.5013461112976074
column j: 1022
Runtime of the program for j 0.15000414848327637
column j: 1023
Runtime of the program for j 0.4663271903991699
column j: 1024
Runtime of the program for j 0.43360471725463867
column j: 1025
Runtime of the program for j 0.4690413475036621
column j: 1026
Runtime of the program for j 0.42580342292785645
column j: 1027
Runtime of the program for j 0.45023202896118164
column j: 1028
Runtime of the program for j 0.41956019401550293
column j: 1029
Runtime of the program for j 0.15439414978027344
column j: 1030
Runtime of the program for j 0.4676017761230469
column j: 1031
Runtime of the program for j 0.43857359886169434
column j: 1032
Runtime of the program for j 0.4696474075317383
column j: 1033
Runtime of the program for j 0.14988374710083008
column j: 1034
Runtime of the program for j 0.4720735549926758
column j: 1035
Runtime of the program for j 0.43314075469970703
column j: 1036
Runtime of the program for j 0.45473265647888184
column j: 1037
Runtime of the program for j 0.44536423683166504
column j: 1038
Runtime of the program for j 0.4495406150817871
column j: 1039
Runtime of the program for j 0.4502291679382324
column j: 1040
Runtime of the program for j 0.5547487735748291
column j: 1041
Runtime of the program for j 0.45369482040405273
column j: 1042
Runtime of the program for j 0.46642255783081055
column j: 1043
Runtime of the program for j 0.4353313446044922
column j: 1044
Runtime of the program for j 0.4596707820892334
column j: 1045
Runtime of the program for j 0.41721415519714355
column j: 1046
Runtime of the program for j 0.4830973148345947
column j: 1047
Runtime of the program for j 0.4648323059082031
column j: 1048
Runtime of the program for j 0.49011683464050293
column j: 1049
Runtime of the program for j 0.48253893852233887
column j: 1050
Runtime of the program for j 0.4928441047668457
column j: 1051
Runtime of the program for j 0.4498016834259033
column j: 1052
Runtime of the program for j 0.4499819278717041
column j: 1053
Runtime of the program for j 0.42502617835998535
column j: 1054
Runtime of the program for j 0.45479369163513184
column j: 1055
Runtime of the program for j 0.48015689849853516
column j: 1056
Runtime of the program for j 0.4448575973510742

column j: 1057
Runtime of the program for j 0.4703793525695801
column j: 1058
Runtime of the program for j 0.5078206062316895
column j: 1059
Runtime of the program for j 0.4757819175720215
column j: 1060
Runtime of the program for j 0.47794413566589355
column j: 1061
Runtime of the program for j 0.5334091186523438
column j: 1062
Runtime of the program for j 0.4451313018798828
column j: 1063
Runtime of the program for j 0.5144822597503662
column j: 1064
Runtime of the program for j 0.46488356590270996
column j: 1065
Runtime of the program for j 0.48166537284851074
column j: 1066
Runtime of the program for j 0.4387192726135254
column j: 1067
Runtime of the program for j 0.19012784957885742
column j: 1068
Runtime of the program for j 0.4341905117034912
column j: 1069
Runtime of the program for j 0.42061734199523926
column j: 1070
Runtime of the program for j 0.4998335838317871
column j: 1071
Runtime of the program for j 0.4502437114715576
column j: 1072
Runtime of the program for j 0.18492984771728516
column j: 1073
Runtime of the program for j 0.45182132720947266
column j: 1074
Runtime of the program for j 0.4730241298675537
column j: 1075
Runtime of the program for j 0.4568958282470703
column j: 1076
Runtime of the program for j 0.4781339168548584
column j: 1077
Runtime of the program for j 0.44045066833496094
column j: 1078
Runtime of the program for j 0.46953821182250977
column j: 1079
Runtime of the program for j 0.4599339962005615
column j: 1080
Runtime of the program for j 0.4954409599304199
column j: 1081
Runtime of the program for j 0.46979379653930664
column j: 1082
Runtime of the program for j 0.5399587154388428
column j: 1083
Runtime of the program for j 0.5177381038665771
column j: 1084
Runtime of the program for j 0.4769890308380127
column j: 1085
Runtime of the program for j 0.4804997444152832
column j: 1086
Runtime of the program for j 0.4695925712585449
column j: 1087
Runtime of the program for j 0.5101099014282227
column j: 1088
Runtime of the program for j 0.4502534866333008
column j: 1089
Runtime of the program for j 0.47990989685058594
column j: 1090
Runtime of the program for j 0.44502758979797363
column j: 1091
Runtime of the program for j 0.4747922420501709
column j: 1092
Runtime of the program for j 0.44985389709472656
column j: 1093
Runtime of the program for j 0.4646790027618408
column j: 1094
Runtime of the program for j 0.500218391418457
column j: 1095
Runtime of the program for j 0.4471113681793213
column j: 1096
Runtime of the program for j 0.4913663864135742
column j: 1097
Runtime of the program for j 0.4588043689727783
column j: 1098
Runtime of the program for j 0.48284006118774414
column j: 1099
Runtime of the program for j 0.4297928810119629
column j: 1100
Runtime of the program for j 0.4752969741821289
column j: 1101
Runtime of the program for j 0.47437500953674316
column j: 1102
Runtime of the program for j 0.4890329837799072
column j: 1103
Runtime of the program for j 0.5213565826416016
column j: 1104
Runtime of the program for j 0.4958021640777588
column j: 1105
Runtime of the program for j 0.4740452766418457
column j: 1106
Runtime of the program for j 0.45513367652893066
column j: 1107
Runtime of the program for j 0.466005802154541
column j: 1108
Runtime of the program for j 0.4441347122192383
column j: 1109
Runtime of the program for j 0.4697763919830322
column j: 1110
Runtime of the program for j 0.45510268211364746
column j: 1111
Runtime of the program for j 0.4738888740539551
column j: 1112
Runtime of the program for j 0.4561648368835449
column j: 1113
Runtime of the program for j 0.4715566635131836
column j: 1114
Runtime of the program for j 0.49317193031311035
column j: 1115
Runtime of the program for j 0.4464082717895508
column j: 1116
Runtime of the program for j 0.47916460037231445
column j: 1117
Runtime of the program for j 0.5014026165008545
column j: 1118
Runtime of the program for j 0.4840817451477051
column j: 1119
Runtime of the program for j 0.4435536861419678
column j: 1120
Runtime of the program for j 0.4701855182647705
column j: 1121
Runtime of the program for j 0.44508957862854004
column j: 1122
Runtime of the program for j 0.5019805431365967
column j: 1123
Runtime of the program for j 0.5140671730041504
column j: 1124
Runtime of the program for j 0.46897125244140625
column j: 1125
Runtime of the program for j 0.48831939697265625
column j: 1126
Runtime of the program for j 0.4447786808013916
column j: 1127
Runtime of the program for j 0.47681474685668945
column j: 1128
Runtime of the program for j 0.4553260803222656
column j: 1129
Runtime of the program for j 0.45988917350769043
column j: 1130
Runtime of the program for j 0.4548025131225586
column j: 1131
Runtime of the program for j 0.43494629859924316
column j: 1132
Runtime of the program for j 0.48497438430786133
column j: 1133
Runtime of the program for j 0.4495561122894287
column j: 1134
Runtime of the program for j 0.46924424171447754
column j: 1135
Runtime of the program for j 0.4364461898803711
column j: 1136
Runtime of the program for j 0.46986913681030273
column j: 1137
Runtime of the program for j 0.44016170501708984
column j: 1138
Runtime of the program for j 0.16300249099731445
column j: 1139
Runtime of the program for j 0.1868276596069336
column j: 1140
Runtime of the program for j 0.46520400047302246
column j: 1141
Runtime of the program for j 0.4648399353027344
column j: 1142
Runtime of the program for j 0.43486499786376953
column j: 1143
Runtime of the program for j 0.475893497467041
column j: 1144
Runtime of the program for j 0.4393196105957031
column j: 1145
Runtime of the program for j 0.482649564743042
column j: 1146
Runtime of the program for j 0.4674997329711914
column j: 1147
Runtime of the program for j 0.45009803771972656
column j: 1148
Runtime of the program for j 0.4799344539642334
column j: 1149
Runtime of the program for j 0.45116281509399414
column j: 1150
Runtime of the program for j 0.47504687309265137
column j: 1151
Runtime of the program for j 0.44300293922424316
column j: 1152
Runtime of the program for j 0.4873013496398926
column j: 1153
Runtime of the program for j 0.4799814224243164
column j: 1154
Runtime of the program for j 0.4397432804107666
column j: 1155
Runtime of the program for j 0.4825162887573242
column j: 1156
Runtime of the program for j 0.43778538703918457
column j: 1157
Runtime of the program for j 0.1793520450592041
column j: 1158
Runtime of the program for j 0.1501598358154297
column j: 1159
Runtime of the program for j 0.1450812816619873
column j: 1160
Runtime of the program for j 0.19525909423828125
column j: 1161
Runtime of the program for j 0.45118045806884766
column j: 1162
Runtime of the program for j 0.4687187671661377
column j: 1163
Runtime of the program for j 0.479877233505249
column j: 1164
Runtime of the program for j 0.47246575355529785
column j: 1165
Runtime of the program for j 0.4702141284942627
column j: 1166
Runtime of the program for j 0.4323759078979492
column j: 1167
Runtime of the program for j 0.495025634765625
column j: 1168
Runtime of the program for j 0.43996644020080566
column j: 1169
Runtime of the program for j 0.4696464538574219
column j: 1170
Runtime of the program for j 0.45050787925720215
column j: 1171
Runtime of the program for j 0.5000810623168945
column j: 1172
Runtime of the program for j 0.47946882247924805
column j: 1173
Runtime of the program for j 0.46485185623168945
column j: 1174
Runtime of the program for j 0.46146512031555176
column j: 1175
Runtime of the program for j 0.4340519905090332
column j: 1176
Runtime of the program for j 0.4754469394683838
column j: 1177
Runtime of the program for j 0.46195125579833984
column j: 1178
Runtime of the program for j 0.44674015045166016
column j: 1179
Runtime of the program for j 0.4698152542114258
column j: 1180
Runtime of the program for j 0.4504702091217041
column j: 1181
Runtime of the program for j 0.45956921577453613
column j: 1182
Runtime of the program for j 0.4203031063079834
column j: 1183
Runtime of the program for j 0.4498889446258545
column j: 1184
Runtime of the program for j 0.47275328636169434
column j: 1185
Runtime of the program for j 0.4269237518310547
column j: 1186
Runtime of the program for j 0.47397613525390625

column j: 1187
Runtime of the program for j 0.4384493827819824
column j: 1188
Runtime of the program for j 0.48817896842956543
column j: 1189
Runtime of the program for j 0.4797701835632324
column j: 1190
Runtime of the program for j 0.44005537033081055
column j: 1191
Runtime of the program for j 0.4900076389312744
column j: 1192
Runtime of the program for j 0.15000247955322266
column j: 1193
Runtime of the program for j 0.22988224029541016
column j: 1194
Runtime of the program for j 0.5101063251495361
column j: 1195
Runtime of the program for j 0.44487643241882324
column j: 1196
Runtime of the program for j 0.4648575782775879
column j: 1197
Runtime of the program for j 0.46498537063598633
column j: 1198
Runtime of the program for j 0.46989011764526367
column j: 1199
Runtime of the program for j 0.5100693702697754
column j: 1200
Runtime of the program for j 0.46990466117858887
column j: 1201
Runtime of the program for j 0.4902374744415283
column j: 1202
Runtime of the program for j 0.4527566432952881
column j: 1203
Runtime of the program for j 0.4892714023590088
column j: 1204
Runtime of the program for j 0.46959519386291504
column j: 1205
Runtime of the program for j 0.44238734245300293
column j: 1206
Runtime of the program for j 0.4708423614501953
column j: 1207
Runtime of the program for j 0.43465566635131836
column j: 1208
Runtime of the program for j 0.5109963417053223
column j: 1209
Runtime of the program for j 0.4791529178619385
column j: 1210
Runtime of the program for j 0.4403517246246338
column j: 1211
Runtime of the program for j 0.4829692840576172
column j: 1212
Runtime of the program for j 0.15691757202148438
column j: 1213
Runtime of the program for j 0.20999765396118164
column j: 1214
Runtime of the program for j 0.18248629570007324
column j: 1215
Runtime of the program for j 0.45769214630126953
column j: 1216
Runtime of the program for j 0.4923081398010254
column j: 1217
Runtime of the program for j 0.44746828079223633
column j: 1218
Runtime of the program for j 0.4997379779815674
column j: 1219
Runtime of the program for j 0.5101521015167236
column j: 1220
Runtime of the program for j 0.45003199577331543
column j: 1221
Runtime of the program for j 0.4900383949279785
column j: 1222
Runtime of the program for j 0.4397413730621338
column j: 1223
Runtime of the program for j 0.45749688148498535
column j: 1224
Runtime of the program for j 0.4799468517303467
column j: 1225
Runtime of the program for j 0.46311068534851074
column j: 1226
Runtime of the program for j 0.48833775520324707
column j: 1227
Runtime of the program for j 0.4846611022949219
column j: 1228
Runtime of the program for j 0.4924025535583496
column j: 1229
Runtime of the program for j 0.6712996959686279
column j: 1230
Runtime of the program for j 0.4579124450683594
column j: 1231
Runtime of the program for j 0.5918519496917725
column j: 1232
Runtime of the program for j 0.5726127624511719
column j: 1233
Runtime of the program for j 0.497283935546875
column j: 1234
Runtime of the program for j 0.5697386264801025
column j: 1235
Runtime of the program for j 0.4846677780151367
column j: 1236
Runtime of the program for j 0.5307974815368652
column j: 1237
Runtime of the program for j 0.5148375034332275
column j: 1238
Runtime of the program for j 0.44617772102355957
column j: 1239
Runtime of the program for j 0.49671363830566406
column j: 1240
Runtime of the program for j 0.4320974349975586
column j: 1241
Runtime of the program for j 0.43524956703186035
column j: 1242
Runtime of the program for j 0.500014066696167
column j: 1243
Runtime of the program for j 0.43004441261291504
column j: 1244
Runtime of the program for j 0.4958007335662842
column j: 1245
Runtime of the program for j 0.49640536308288574
column j: 1246
Runtime of the program for j 0.16267895698547363
column j: 1247
Runtime of the program for j 0.48737645149230957
column j: 1248
Runtime of the program for j 0.44222283363342285
column j: 1249
Runtime of the program for j 0.4351832866668701
column j: 1250
Runtime of the program for j 0.5002315044403076
column j: 1251
Runtime of the program for j 0.4799156188964844
column j: 1252
Runtime of the program for j 0.5201506614685059
column j: 1253
Runtime of the program for j 0.4896841049194336
column j: 1254
Runtime of the program for j 0.439831018447876
column j: 1255
Runtime of the program for j 0.519690752029419
column j: 1256
Runtime of the program for j 0.44991564750671387
column j: 1257
Runtime of the program for j 0.23049449920654297
column j: 1258
Runtime of the program for j 0.5196881294250488
column j: 1259
Runtime of the program for j 0.4505889415740967
column j: 1260
Runtime of the program for j 0.4998626708984375
column j: 1261
Runtime of the program for j 0.4848971366882324
column j: 1262
Runtime of the program for j 0.4354376792907715
column j: 1263
Runtime of the program for j 0.5113718509674072
column j: 1264
Runtime of the program for j 0.43077802658081055
column j: 1265
Runtime of the program for j 0.45731401443481445
column j: 1266
Runtime of the program for j 0.49985599517822266
column j: 1267
Runtime of the program for j 0.4425950050354004
column j: 1268
Runtime of the program for j 0.4874439239501953
column j: 1269
Runtime of the program for j 0.48006105422973633
column j: 1270
Runtime of the program for j 0.4396555423736572
column j: 1271
Runtime of the program for j 0.49524474143981934
column j: 1272
Runtime of the program for j 0.44519639015197754
column j: 1273
Runtime of the program for j 0.4400291442871094
column j: 1274
Runtime of the program for j 0.47994041442871094
column j: 1275
Runtime of the program for j 0.4648714065551758
column j: 1276
Runtime of the program for j 0.6150891780853271
column j: 1277
Runtime of the program for j 0.5416815280914307
column j: 1278
Runtime of the program for j 0.2726013660430908
column j: 1279
Runtime of the program for j 0.2025623321533203
column j: 1280
Runtime of the program for j 0.49373865127563477
column j: 1281
Runtime of the program for j 0.43886685371398926
column j: 1282
Runtime of the program for j 0.46758198738098145
column j: 1283
Runtime of the program for j 0.4398794174194336
column j: 1284
Runtime of the program for j 0.4441983699798584
column j: 1285
Runtime of the program for j 0.485637903213501
column j: 1286
Runtime of the program for j 0.45270705223083496
column j: 1287
Runtime of the program for j 0.20240449905395508
column j: 1288
Runtime of the program for j 0.19495272636413574
column j: 1289
Runtime of the program for j 0.4699974060058594
column j: 1290
Runtime of the program for j 0.4921994209289551
column j: 1291
Runtime of the program for j 0.477710485458374
column j: 1292
Runtime of the program for j 0.45009899139404297
column j: 1293
Runtime of the program for j 0.4702033996582031
column j: 1294
Runtime of the program for j 0.4623394012451172
column j: 1295
Runtime of the program for j 0.4276108741760254
column j: 1296
Runtime of the program for j 0.49977803230285645
column j: 1297
Runtime of the program for j 0.4299609661102295
column j: 1298
Runtime of the program for j 0.439955472946167
column j: 1299
Runtime of the program for j 0.4400179386138916
column j: 1300
Runtime of the program for j 0.1552133560180664
column j: 1301
Runtime of the program for j 0.22516632080078125
column j: 1302
Runtime of the program for j 0.42977094650268555
column j: 1303
Runtime of the program for j 0.16019392013549805
column j: 1304
Runtime of the program for j 0.48009395599365234
column j: 1305
Runtime of the program for j 0.4393770694732666
column j: 1306
Runtime of the program for j 0.4500713348388672
column j: 1307
Runtime of the program for j 0.5030560493469238
column j: 1308
Runtime of the program for j 0.42735815048217773
column j: 1309
Runtime of the program for j 0.4410359859466553
column j: 1310
Runtime of the program for j 0.49892616271972656
column j: 1311
Runtime of the program for j 0.4249086380004883
column j: 1312
Runtime of the program for j 0.444838285446167
column j: 1313
Runtime of the program for j 0.5227077007293701
column j: 1314
Runtime of the program for j 0.40961289405822754
column j: 1315
Runtime of the program for j 0.4498615264892578
column j: 1316
Runtime of the program for j 0.5077836513519287

column j: 1317
Runtime of the program for j 0.4474143981933594
column j: 1318
Runtime of the program for j 0.44490575790405273
column j: 1319
Runtime of the program for j 0.5114901065826416
column j: 1320
Runtime of the program for j 0.4404580593109131
column j: 1321
Runtime of the program for j 0.44580912590026855
column j: 1322
Runtime of the program for j 0.5076804161071777
column j: 1323
Runtime of the program for j 0.43231940269470215
column j: 1324
Runtime of the program for j 0.44483017921447754
column j: 1325
Runtime of the program for j 0.48505187034606934
column j: 1326
Runtime of the program for j 0.4301896095275879
column j: 1327
Runtime of the program for j 0.43406081199645996
column j: 1328
Runtime of the program for j 0.49599313735961914
column j: 1329
Runtime of the program for j 0.4500267505645752
column j: 1330
Runtime of the program for j 0.42978429794311523
column j: 1331
Runtime of the program for j 0.48667049407958984
column j: 1332
Runtime of the program for j 0.4399688243865967
column j: 1333
Runtime of the program for j 0.4540064334869385
column j: 1334
Runtime of the program for j 0.49454736709594727
column j: 1335
Runtime of the program for j 0.42983031272888184
column j: 1336
Runtime of the program for j 0.4461207389831543
column j: 1337
Runtime of the program for j 0.22309184074401855
column j: 1338
Runtime of the program for j 0.4360311031341553
column j: 1339
Runtime of the program for j 0.44800424575805664
column j: 1340
Runtime of the program for j 0.5120768547058105
column j: 1341
Runtime of the program for j 0.4299123287200928
column j: 1342
Runtime of the program for j 0.43968939781188965
column j: 1343
Runtime of the program for j 0.5104203224182129
column j: 1344
Runtime of the program for j 0.44994020462036133
column j: 1345
Runtime of the program for j 0.4400177001953125
column j: 1346
Runtime of the program for j 0.5126204490661621
column j: 1347
Runtime of the program for j 0.42736220359802246
column j: 1348
Runtime of the program for j 0.43976855278015137
column j: 1349
Runtime of the program for j 0.4899280071258545
column j: 1350
Runtime of the program for j 0.40034961700439453
column j: 1351
Runtime of the program for j 0.16006016731262207
column j: 1352
Runtime of the program for j 0.2228851318359375
column j: 1353
Runtime of the program for j 0.4396669864654541
column j: 1354
Runtime of the program for j 0.45258569717407227
column j: 1355
Runtime of the program for j 0.5199413299560547
column j: 1356
Runtime of the program for j 0.4375488758087158
column j: 1357
Runtime of the program for j 0.4561765193939209
column j: 1358
Runtime of the program for j 0.508901834487915
column j: 1359
Runtime of the program for j 0.42488527297973633
column j: 1360
Runtime of the program for j 0.4447035789489746
column j: 1361
Runtime of the program for j 0.535320520401001
column j: 1362
Runtime of the program for j 0.43035149574279785
column j: 1363
Runtime of the program for j 0.4443073272705078
column j: 1364
Runtime of the program for j 0.23803377151489258
column j: 1365
Runtime of the program for j 0.4300191402435303
column j: 1366
Runtime of the program for j 0.4389526844024658
column j: 1367
Runtime of the program for j 0.5335218906402588
column j: 1368
Runtime of the program for j 0.4272332191467285
column j: 1369
Runtime of the program for j 0.4378840923309326
column j: 1370
Runtime of the program for j 0.5401396751403809
column j: 1371
Runtime of the program for j 0.4393599033355713
column j: 1372
Runtime of the program for j 0.16007733345031738
column j: 1373
Runtime of the program for j 0.510366678237915
column j: 1374
Runtime of the program for j 0.42987680435180664
column j: 1375
Runtime of the program for j 0.43436121940612793
column j: 1376
Runtime of the program for j 0.5083975791931152
column j: 1377
Runtime of the program for j 0.4573476314544678
column j: 1378
Runtime of the program for j 0.5296869277954102
column j: 1379
Runtime of the program for j 0.5204269886016846
column j: 1380
Runtime of the program for j 0.5094437599182129
column j: 1381
Runtime of the program for j 0.4801657199859619
column j: 1382
Runtime of the program for j 0.48288822174072266
column j: 1383
Runtime of the program for j 0.4768970012664795
column j: 1384
Runtime of the program for j 0.591360330581665
column j: 1385
Runtime of the program for j 0.48874855041503906
column j: 1386
Runtime of the program for j 0.5001296997070312
column j: 1387
Runtime of the program for j 0.5499172210693359
column j: 1388
Runtime of the program for j 0.49980616569519043
column j: 1389
Runtime of the program for j 0.44548559188842773
column j: 1390
Runtime of the program for j 0.5207877159118652
column j: 1391
Runtime of the program for j 0.4440932273864746
column j: 1392
Runtime of the program for j 0.48284912109375
column j: 1393
Runtime of the program for j 0.5182344913482666
column j: 1394
Runtime of the program for j 0.45863866806030273
column j: 1395
Runtime of the program for j 0.45032787322998047
column j: 1396
Runtime of the program for j 0.5053505897521973
column j: 1397
Runtime of the program for j 0.43021202087402344
column j: 1398
Runtime of the program for j 0.4371352195739746
column j: 1399
Runtime of the program for j 0.529958963394165
column j: 1400
Runtime of the program for j 0.43318653106689453
column j: 1401
Runtime of the program for j 0.4567089080810547
column j: 1402
Runtime of the program for j 0.5101943016052246
column j: 1403
Runtime of the program for j 0.529930830001831
column j: 1404
Runtime of the program for j 0.45560741424560547
column j: 1405
Runtime of the program for j 0.5581295490264893
column j: 1406
Runtime of the program for j 0.4396035671234131
column j: 1407
Runtime of the program for j 0.4567580223083496
column j: 1408
Runtime of the program for j 0.46010661125183105
column j: 1409
Runtime of the program for j 0.4145090579986572
column j: 1410
Runtime of the program for j 0.5405941009521484
column j: 1411
Runtime of the program for j 0.42504382133483887
column j: 1412
Runtime of the program for j 0.4346916675567627
column j: 1413
Runtime of the program for j 0.5182480812072754
column j: 1414
Runtime of the program for j 0.4478325843811035
column j: 1415
Runtime of the program for j 0.4638538360595703
column j: 1416
Runtime of the program for j 0.5408992767333984
column j: 1417
Runtime of the program for j 0.4754476547241211
column j: 1418
Runtime of the program for j 0.4824962615966797
column j: 1419
Runtime of the program for j 0.5172078609466553
column j: 1420
Runtime of the program for j 0.1400003433227539
column j: 1421
Runtime of the program for j 0.44030284881591797
column j: 1422
Runtime of the program for j 0.5651071071624756
column j: 1423
Runtime of the program for j 0.43642497062683105
column j: 1424
Runtime of the program for j 0.4581308364868164
column j: 1425
Runtime of the program for j 0.4424755573272705
column j: 1426
Runtime of the program for j 0.4476621150970459
column j: 1427
Runtime of the program for j 0.5026946067810059
column j: 1428
Runtime of the program for j 0.42706990242004395
column j: 1429
Runtime of the program for j 0.45226597785949707
column j: 1430
Runtime of the program for j 0.5003411769866943
column j: 1431
Runtime of the program for j 0.4180335998535156
column j: 1432
Runtime of the program for j 0.46237826347351074
column j: 1433
Runtime of the program for j 0.4873197078704834
column j: 1434
Runtime of the program for j 0.44014763832092285
column j: 1435
Runtime of the program for j 0.45336270332336426
column j: 1436
Runtime of the program for j 0.19612932205200195
column j: 1437
Runtime of the program for j 0.4403550624847412
column j: 1438
Runtime of the program for j 0.4447743892669678
column j: 1439
Runtime of the program for j 0.5348706245422363
column j: 1440
Runtime of the program for j 0.45032620429992676
column j: 1441
Runtime of the program for j 0.48973965644836426
column j: 1442
Runtime of the program for j 0.4327576160430908
column j: 1443
Runtime of the program for j 0.4521012306213379
column j: 1444
Runtime of the program for j 0.4872465133666992
column j: 1445
Runtime of the program for j 0.42803144454956055
column j: 1446
Runtime of the program for j 0.42996954917907715

column j: 1447
Runtime of the program for j 0.47013020515441895
column j: 1448
Runtime of the program for j 0.4297184944152832
column j: 1449
Runtime of the program for j 0.45026469230651855
column j: 1450
Runtime of the program for j 0.48490357398986816
column j: 1451
Runtime of the program for j 0.4279952049255371
column j: 1452
Runtime of the program for j 0.42060065269470215
column j: 1453
Runtime of the program for j 0.43663978576660156
column j: 1454
Runtime of the program for j 0.44022130966186523
column j: 1455
Runtime of the program for j 0.5382416248321533
column j: 1456
Runtime of the program for j 0.43950319290161133
column j: 1457
Runtime of the program for j 0.45006680488586426
column j: 1458
Runtime of the program for j 0.45615482330322266
column j: 1459
Runtime of the program for j 0.4298224449157715
column j: 1460
Runtime of the program for j 0.444042444229126
column j: 1461
Runtime of the program for j 0.5212912559509277
column j: 1462
Runtime of the program for j 0.4299933910369873
column j: 1463
Runtime of the program for j 0.4532957077026367
column j: 1464
Runtime of the program for j 0.547121524810791
column j: 1465
Runtime of the program for j 0.45169949531555176
column j: 1466
Runtime of the program for j 0.47779369354248047
column j: 1467
Runtime of the program for j 0.43619871139526367
column j: 1468
Runtime of the program for j 0.4295985698699951
column j: 1469
Runtime of the program for j 0.50433349609375
column j: 1470
Runtime of the program for j 0.4421505928039551
column j: 1471
Runtime of the program for j 0.44774842262268066
column j: 1472
Runtime of the program for j 0.5325298309326172
column j: 1473
Runtime of the program for j 0.4376652240753174
column j: 1474
Runtime of the program for j 0.4598124027252197
column j: 1475
Runtime of the program for j 0.508037805557251
column j: 1476
Runtime of the program for j 0.16174077987670898
column j: 1477
Runtime of the program for j 0.48987722396850586
column j: 1478
Runtime of the program for j 0.4205186367034912
column j: 1479
Runtime of the program for j 0.45200371742248535
column j: 1480
Runtime of the program for j 0.48783230781555176
column j: 1481
Runtime of the program for j 0.42892980575561523
column j: 1482
Runtime of the program for j 0.45178890228271484
column j: 1483
Runtime of the program for j 0.4984452724456787
column j: 1484
Runtime of the program for j 0.43010973930358887
column j: 1485
Runtime of the program for j 0.43434977531433105
column j: 1486
Runtime of the program for j 0.45665860176086426
column j: 1487
Runtime of the program for j 0.4988095760345459
column j: 1488
Runtime of the program for j 0.5298600196838379
column j: 1489
Runtime of the program for j 0.4399230480194092
column j: 1490
Runtime of the program for j 0.47182703018188477
column j: 1491
Runtime of the program for j 0.5457618236541748
column j: 1492
Runtime of the program for j 0.4398624897003174
column j: 1493
Runtime of the program for j 0.45041751861572266
column j: 1494
Runtime of the program for j 0.5399169921875
column j: 1495
Runtime of the program for j 0.5324733257293701
column j: 1496
Runtime of the program for j 0.5273840427398682
column j: 1497
Runtime of the program for j 0.44994306564331055
column j: 1498
Runtime of the program for j 0.4601004123687744
column j: 1499
Runtime of the program for j 0.5296659469604492
column j: 1500
Runtime of the program for j 0.4401087760925293
column j: 1501
Runtime of the program for j 0.4624488353729248
column j: 1502
Runtime of the program for j 0.5312728881835938
column j: 1503
Runtime of the program for j 0.4563770294189453
column j: 1504
Runtime of the program for j 0.5400209426879883
column j: 1505
Runtime of the program for j 0.42302489280700684
column j: 1506
Runtime of the program for j 0.4520292282104492
column j: 1507
Runtime of the program for j 0.5273125171661377
column j: 1508
Runtime of the program for j 0.4501924514770508
column j: 1509
Runtime of the program for j 0.4423973560333252
column j: 1510
Runtime of the program for j 0.5324287414550781
column j: 1511
Runtime of the program for j 0.45506978034973145
column j: 1512
Runtime of the program for j 0.5001668930053711
column j: 1513
Runtime of the program for j 0.4397156238555908
column j: 1514
Runtime of the program for j 0.4538004398345947
column j: 1515
Runtime of the program for j 0.5322556495666504
column j: 1516
Runtime of the program for j 0.44400835037231445
column j: 1517
Runtime of the program for j 0.43640923500061035
column j: 1518
Runtime of the program for j 0.5599796772003174
column j: 1519
Runtime of the program for j 0.4597458839416504
column j: 1520
Runtime of the program for j 0.5030560493469238
column j: 1521
Runtime of the program for j 0.4717719554901123
column j: 1522
Runtime of the program for j 0.4483053684234619
column j: 1523
Runtime of the program for j 0.5395081043243408
column j: 1524
Runtime of the program for j 0.45122838020324707
column j: 1525
Runtime of the program for j 0.4314234256744385
column j: 1526
Runtime of the program for j 0.5250911712646484
column j: 1527
Runtime of the program for j 0.4322528839111328
column j: 1528
Runtime of the program for j 0.49063634872436523
column j: 1529
Runtime of the program for j 0.39058470726013184
column j: 1530
Runtime of the program for j 0.48922038078308105
column j: 1531
Runtime of the program for j 0.5297555923461914
column j: 1532
Runtime of the program for j 0.5503556728363037
column j: 1533
Runtime of the program for j 0.45987510681152344
column j: 1534
Runtime of the program for j 0.4400041103363037
column j: 1535
Runtime of the program for j 0.5032098293304443
column j: 1536
Runtime of the program for j 0.48340606689453125
column j: 1537
Runtime of the program for j 0.4033219814300537
column j: 1538
Runtime of the program for j 0.5297582149505615
column j: 1539
Runtime of the program for j 0.5401062965393066
column j: 1540
Runtime of the program for j 0.40991735458374023
column j: 1541
Runtime of the program for j 0.5110945701599121
column j: 1542
Runtime of the program for j 0.4291698932647705
column j: 1543
Runtime of the program for j 0.44205760955810547
column j: 1544
Runtime of the program for j 0.25803470611572266
column j: 1545
Runtime of the program for j 0.4323549270629883
column j: 1546
Runtime of the program for j 0.4337882995605469
column j: 1547
Runtime of the program for j 0.6004881858825684
column j: 1548
Runtime of the program for j 0.44940805435180664
column j: 1549
Runtime of the program for j 0.5202555656433105
column j: 1550
Runtime of the program for j 0.4301590919494629
column j: 1551
Runtime of the program for j 0.46009397506713867
column j: 1552
Runtime of the program for j 0.5200846195220947
column j: 1553
Runtime of the program for j 0.4499778747558594
column j: 1554
Runtime of the program for j 0.5027344226837158
column j: 1555
Runtime of the program for j 0.43728017807006836
column j: 1556
Runtime of the program for j 0.4598407745361328
column j: 1557
Runtime of the program for j 0.5217320919036865
column j: 1558
Runtime of the program for j 0.438201904296875
column j: 1559
Runtime of the program for j 0.43024253845214844
column j: 1560
Runtime of the program for j 0.501704216003418
column j: 1561
Runtime of the program for j 0.43100857734680176
column j: 1562
Runtime of the program for j 0.5092098712921143
column j: 1563
Runtime of the program for j 0.14751219749450684
column j: 1564
Runtime of the program for j 0.46036767959594727
column j: 1565
Runtime of the program for j 0.5000629425048828
column j: 1566
Runtime of the program for j 0.44985532760620117
column j: 1567
Runtime of the program for j 0.22020411491394043
column j: 1568
Runtime of the program for j 0.4498405456542969
column j: 1569
Runtime of the program for j 0.44986748695373535
column j: 1570
Runtime of the program for j 0.49013400077819824
column j: 1571
Runtime of the program for j 0.45265913009643555
column j: 1572
Runtime of the program for j 0.4973297119140625
column j: 1573
Runtime of the program for j 0.43167781829833984
column j: 1574
Runtime of the program for j 0.43989014625549316
column j: 1575
Runtime of the program for j 0.49200892448425293
column j: 1576
Runtime of the program for j 0.43071770668029785

column j: 1577
Runtime of the program for j 0.42729711532592773
column j: 1578
Runtime of the program for j 0.43990087509155273
column j: 1579
Runtime of the program for j 0.16630291938781738
column j: 1580
Runtime of the program for j 0.2139904499053955
column j: 1581
Runtime of the program for j 0.4597053527832031
column j: 1582
Runtime of the program for j 0.45034360885620117
column j: 1583
Runtime of the program for j 0.49976038932800293
column j: 1584
Runtime of the program for j 0.4526491165161133
column j: 1585
Runtime of the program for j 0.5592200756072998
column j: 1586
Runtime of the program for j 0.4482247829437256
column j: 1587
Runtime of the program for j 0.45535945892333984
column j: 1588
Runtime of the program for j 0.4927184581756592
column j: 1589
Runtime of the program for j 0.4436075687408447
column j: 1590
Runtime of the program for j 0.49944138526916504
column j: 1591
Runtime of the program for j 0.42711305618286133
column j: 1592
Runtime of the program for j 0.45048046112060547
column j: 1593
Runtime of the program for j 0.2096879482269287
column j: 1594
Runtime of the program for j 0.44004011154174805
column j: 1595
Runtime of the program for j 0.4852011203765869
column j: 1596
Runtime of the program for j 0.4474043846130371
column j: 1597
Runtime of the program for j 0.44722843170166016
column j: 1598
Runtime of the program for j 0.5235507488250732
column j: 1599
Runtime of the program for j 0.5067293643951416
column j: 1600
Runtime of the program for j 0.4997432231903076
column j: 1601
Runtime of the program for j 0.44420671463012695
column j: 1602
Runtime of the program for j 0.4559483528137207
column j: 1603
Runtime of the program for j 0.4894587993621826
column j: 1604
Runtime of the program for j 0.44641542434692383
column j: 1605
Runtime of the program for j 0.49394750595092773
column j: 1606
Runtime of the program for j 0.43987488746643066
column j: 1607
Runtime of the program for j 0.440427303314209
column j: 1608
Runtime of the program for j 0.2095034122467041
column j: 1609
Runtime of the program for j 0.44060754776000977
column j: 1610
Runtime of the program for j 0.4795076847076416
column j: 1611
Runtime of the program for j 0.426105260848999
column j: 1612
Runtime of the program for j 0.15421295166015625
column j: 1613
Runtime of the program for j 0.49959683418273926
column j: 1614
Runtime of the program for j 0.4426765441894531
column j: 1615
Runtime of the program for j 0.4673027992248535
column j: 1616
Runtime of the program for j 0.4330928325653076
column j: 1617
Runtime of the program for j 0.4570949077606201
column j: 1618
Runtime of the program for j 0.4949209690093994
column j: 1619
Runtime of the program for j 0.44409608840942383
column j: 1620
Runtime of the program for j 0.48993754386901855
column j: 1621
Runtime of the program for j 0.4401259422302246
column j: 1622
Runtime of the program for j 0.4517848491668701
column j: 1623
Runtime of the program for j 0.4979417324066162
column j: 1624
Runtime of the program for j 0.44016337394714355
column j: 1625
Runtime of the program for j 0.49288487434387207
column j: 1626
Runtime of the program for j 0.15269970893859863
column j: 1627
Runtime of the program for j 0.4443678855895996
column j: 1628
Runtime of the program for j 0.4801504611968994
column j: 1629
Runtime of the program for j 0.4594719409942627
column j: 1630
Runtime of the program for j 0.49559879302978516
column j: 1631
Runtime of the program for j 0.4390101432800293
column j: 1632
Runtime of the program for j 0.46959710121154785
column j: 1633
Runtime of the program for j 0.5162050724029541
column j: 1634
Runtime of the program for j 0.18226313591003418
column j: 1635
Runtime of the program for j 0.24743914604187012
column j: 1636
Runtime of the program for j 0.19048810005187988
column j: 1637
Runtime of the program for j 0.1699061393737793
column j: 1638
Runtime of the program for j 0.21022319793701172
column j: 1639
Runtime of the program for j 0.44977760314941406
column j: 1640
Runtime of the program for j 0.5050613880157471
column j: 1641
Runtime of the program for j 0.44463109970092773
column j: 1642
Runtime of the program for j 0.44997692108154297
column j: 1643
Runtime of the program for j 0.48979759216308594
column j: 1644
Runtime of the program for j 0.46020936965942383
column j: 1645
Runtime of the program for j 0.5217411518096924
column j: 1646
Runtime of the program for j 0.4534420967102051
column j: 1647
Runtime of the program for j 0.45223164558410645
column j: 1648
Runtime of the program for j 0.5024542808532715
column j: 1649
Runtime of the program for j 0.44960546493530273
column j: 1650
Runtime of the program for j 0.495516300201416
column j: 1651
Runtime of the program for j 0.46285510063171387
column j: 1652
Runtime of the program for j 0.46924328804016113
column j: 1653
Runtime of the program for j 0.4378926753997803
column j: 1654
Runtime of the program for j 0.19024395942687988
column j: 1655
Runtime of the program for j 0.5198194980621338
column j: 1656
Runtime of the program for j 0.5098111629486084
column j: 1657
Runtime of the program for j 0.5452456474304199
column j: 1658
Runtime of the program for j 0.5252971649169922
column j: 1659
Runtime of the program for j 0.5793752670288086
column j: 1660
Runtime of the program for j 0.529954195022583
column j: 1661
Runtime of the program for j 0.46027088165283203
column j: 1662
Runtime of the program for j 0.5697071552276611
column j: 1663
Runtime of the program for j 0.47273802757263184
column j: 1664
Runtime of the program for j 0.5275328159332275
column j: 1665
Runtime of the program for j 0.6011862754821777
column j: 1666
Runtime of the program for j 0.48122406005859375
column j: 1667
Runtime of the program for j 0.5667405128479004
column j: 1668
Runtime of the program for j 0.4801468849182129
column j: 1669
Runtime of the program for j 0.4799189567565918
column j: 1670
Runtime of the program for j 0.6123881340026855
column j: 1671
Runtime of the program for j 0.520129919052124
column j: 1672
Runtime of the program for j 0.5101356506347656
column j: 1673
Runtime of the program for j 0.44469475746154785
column j: 1674
Runtime of the program for j 0.5050883293151855
column j: 1675
Runtime of the program for j 0.440410852432251
column j: 1676
Runtime of the program for j 0.5096786022186279
column j: 1677
Runtime of the program for j 0.5101296901702881
column j: 1678
Runtime of the program for j 0.4801058769226074
column j: 1679
Runtime of the program for j 0.522045373916626
column j: 1680
Runtime of the program for j 0.4379093647003174
column j: 1681
Runtime of the program for j 0.429790735244751
column j: 1682
Runtime of the program for j 0.4598402976989746
column j: 1683
Runtime of the program for j 0.45505690574645996
column j: 1684
Runtime of the program for j 0.5076932907104492
column j: 1685
Runtime of the program for j 0.4465458393096924
column j: 1686
Runtime of the program for j 0.5277884006500244
column j: 1687
Runtime of the program for j 0.4424703121185303
column j: 1688
Runtime of the program for j 0.44727420806884766
column j: 1689
Runtime of the program for j 0.5002093315124512
column j: 1690
Runtime of the program for j 0.45979785919189453
column j: 1691
Runtime of the program for j 0.5201740264892578
column j: 1692
Runtime of the program for j 0.4502861499786377
column j: 1693
Runtime of the program for j 0.45190858840942383
column j: 1694
Runtime of the program for j 0.4379713535308838
column j: 1695
Runtime of the program for j 0.43398308753967285
column j: 1696
Runtime of the program for j 0.44565558433532715
column j: 1697
Runtime of the program for j 0.4529540538787842
column j: 1698
Runtime of the program for j 0.5271849632263184
column j: 1699
Runtime of the program for j 0.4502592086791992
column j: 1700
Runtime of the program for j 0.4430367946624756
column j: 1701
Runtime of the program for j 0.48947882652282715
column j: 1702
Runtime of the program for j 0.4698758125305176
column j: 1703
Runtime of the program for j 0.5004425048828125
column j: 1704
Runtime of the program for j 0.4456489086151123
column j: 1705
Runtime of the program for j 0.4915499687194824
column j: 1706
Runtime of the program for j 0.42997097969055176

column j: 1707
Runtime of the program for j 0.46112871170043945
column j: 1708
Runtime of the program for j 0.4971964359283447
column j: 1709
Runtime of the program for j 0.46519899368286133
column j: 1710
Runtime of the program for j 0.5001835823059082
column j: 1711
Runtime of the program for j 0.44446420669555664
column j: 1712
Runtime of the program for j 0.49010419845581055
column j: 1713
Runtime of the program for j 0.4252898693084717
column j: 1714
Runtime of the program for j 0.4595756530761719
column j: 1715
Runtime of the program for j 0.49391961097717285
column j: 1716
Runtime of the program for j 0.44816112518310547
column j: 1717
Runtime of the program for j 0.5000989437103271
column j: 1718
Runtime of the program for j 0.42983102798461914
column j: 1719
Runtime of the program for j 0.4359445571899414
column j: 1720
Runtime of the program for j 0.43203163146972656
column j: 1721
Runtime of the program for j 0.4477694034576416
column j: 1722
Runtime of the program for j 0.49521470069885254
column j: 1723
Runtime of the program for j 0.46875572204589844
column j: 1724
Runtime of the program for j 0.5200555324554443
column j: 1725
Runtime of the program for j 0.439910888671875
column j: 1726
Runtime of the program for j 0.43995094299316406
column j: 1727
Runtime of the program for j 0.44023680686950684
column j: 1728
Runtime of the program for j 0.4352109432220459
column j: 1729
Runtime of the program for j 0.4880409240722656
column j: 1730
Runtime of the program for j 0.43648815155029297
column j: 1731
Runtime of the program for j 0.509943962097168
column j: 1732
Runtime of the program for j 0.44532275199890137
column j: 1733
Runtime of the program for j 0.44500231742858887
column j: 1734
Runtime of the program for j 0.4402341842651367
column j: 1735
Runtime of the program for j 0.4421865940093994
column j: 1736
Runtime of the program for j 0.4976460933685303
column j: 1737
Runtime of the program for j 0.4500911235809326
column j: 1738
Runtime of the program for j 0.5096068382263184
column j: 1739
Runtime of the program for j 0.4398634433746338
column j: 1740
Runtime of the program for j 0.4431033134460449
column j: 1741
Runtime of the program for j 0.4302980899810791
column j: 1742
Runtime of the program for j 0.5268974304199219
column j: 1743
Runtime of the program for j 0.4998795986175537
column j: 1744
Runtime of the program for j 0.4451315402984619
column j: 1745
Runtime of the program for j 0.21252703666687012
column j: 1746
Runtime of the program for j 0.4323709011077881
column j: 1747
Runtime of the program for j 0.4373469352722168
column j: 1748
Runtime of the program for j 0.4573037624359131
column j: 1749
Runtime of the program for j 0.45012927055358887
column j: 1750
Runtime of the program for j 0.5039505958557129
column j: 1751
Runtime of the program for j 0.4513869285583496
column j: 1752
Runtime of the program for j 0.4874098300933838
column j: 1753
Runtime of the program for j 0.44719862937927246
column j: 1754
Runtime of the program for j 0.521364688873291
column j: 1755
Runtime of the program for j 0.4437880516052246
column j: 1756
Runtime of the program for j 0.46497344970703125
column j: 1757
Runtime of the program for j 0.5102400779724121
column j: 1758
Runtime of the program for j 0.4700198173522949
column j: 1759
Runtime of the program for j 0.21997284889221191
column j: 1760
Runtime of the program for j 0.1695423126220703
column j: 1761
Runtime of the program for j 0.5003628730773926
column j: 1762
Runtime of the program for j 0.43387722969055176
column j: 1763
Runtime of the program for j 0.44781970977783203
column j: 1764
Runtime of the program for j 0.5030093193054199
column j: 1765
Runtime of the program for j 0.46746397018432617
column j: 1766
Runtime of the program for j 0.4979438781738281
column j: 1767
Runtime of the program for j 0.44963526725769043
column j: 1768
Runtime of the program for j 0.49984288215637207
column j: 1769
Runtime of the program for j 0.450244665145874
column j: 1770
Runtime of the program for j 0.4896364212036133
column j: 1771
Runtime of the program for j 0.45041584968566895
column j: 1772
Runtime of the program for j 0.45235371589660645
column j: 1773
Runtime of the program for j 0.49738049507141113
column j: 1774
Runtime of the program for j 0.4544074535369873
column j: 1775
Runtime of the program for j 0.509244441986084
column j: 1776
Runtime of the program for j 0.44991016387939453
column j: 1777
Runtime of the program for j 0.4864790439605713
column j: 1778
Runtime of the program for j 0.4221951961517334
column j: 1779
Runtime of the program for j 0.4414234161376953
column j: 1780
Runtime of the program for j 0.4362039566040039
column j: 1781
Runtime of the program for j 0.48969459533691406
column j: 1782
Runtime of the program for j 0.510770320892334
column j: 1783
Runtime of the program for j 0.44962406158447266
column j: 1784
Runtime of the program for j 0.5124294757843018
column j: 1785
Runtime of the program for j 0.4872548580169678
column j: 1786
Runtime of the program for j 0.5399632453918457
column j: 1787
Runtime of the program for j 0.4602525234222412
column j: 1788
Runtime of the program for j 0.46027445793151855
column j: 1789
Runtime of the program for j 0.5320868492126465
column j: 1790
Runtime of the program for j 0.47094202041625977
column j: 1791
Runtime of the program for j 0.5092556476593018
column j: 1792
Runtime of the program for j 0.4807100296020508
column j: 1793
Runtime of the program for j 0.5080137252807617
column j: 1794
Runtime of the program for j 0.4491565227508545
column j: 1795
Runtime of the program for j 0.4854893684387207
column j: 1796
Runtime of the program for j 0.42000412940979004
column j: 1797
Runtime of the program for j 0.45999670028686523
column j: 1798
Runtime of the program for j 0.48963165283203125
column j: 1799
Runtime of the program for j 0.44292640686035156
column j: 1800
Runtime of the program for j 0.49741411209106445
column j: 1801
Runtime of the program for j 0.46258068084716797
column j: 1802
Runtime of the program for j 0.49728918075561523
column j: 1803
Runtime of the program for j 0.4701831340789795
column j: 1804
Runtime of the program for j 0.46945738792419434
column j: 1805
Runtime of the program for j 0.44008827209472656
column j: 1806
Runtime of the program for j 0.45005273818969727
column j: 1807
Runtime of the program for j 0.5000746250152588
column j: 1808
Runtime of the program for j 0.4507887363433838
column j: 1809
Runtime of the program for j 0.559323787689209
column j: 1810
Runtime of the program for j 0.4527432918548584
column j: 1811
Runtime of the program for j 0.5070664882659912
column j: 1812
Runtime of the program for j 0.45707178115844727
column j: 1813
Runtime of the program for j 0.5231692790985107
column j: 1814
Runtime of the program for j 0.4399073123931885
column j: 1815
Runtime of the program for j 0.4396097660064697
column j: 1816
Runtime of the program for j 0.46009016036987305
column j: 1817
Runtime of the program for j 0.4601011276245117
column j: 1818
Runtime of the program for j 0.5003981590270996
column j: 1819
Runtime of the program for j 0.4625866413116455
column j: 1820
Runtime of the program for j 0.5071895122528076
column j: 1821
Runtime of the program for j 0.4537196159362793
column j: 1822
Runtime of the program for j 0.5212652683258057
column j: 1823
Runtime of the program for j 0.4549124240875244
column j: 1824
Runtime of the program for j 0.5000991821289062
column j: 1825
Runtime of the program for j 0.48594093322753906
column j: 1826
Runtime of the program for j 0.4637174606323242
column j: 1827
Runtime of the program for j 0.5003364086151123
column j: 1828
Runtime of the program for j 0.44423604011535645
column j: 1829
Runtime of the program for j 0.509451150894165
column j: 1830
Runtime of the program for j 0.4505620002746582
column j: 1831
Runtime of the program for j 0.5098361968994141
column j: 1832
Runtime of the program for j 0.44240498542785645
column j: 1833
Runtime of the program for j 0.5098476409912109
column j: 1834
Runtime of the program for j 0.4374401569366455
column j: 1835
Runtime of the program for j 0.5101528167724609
column j: 1836
Runtime of the program for j 0.4327864646911621

column j: 1837
Runtime of the program for j 0.4546792507171631
column j: 1838
Runtime of the program for j 0.49735593795776367
column j: 1839
Runtime of the program for j 0.44533848762512207
column j: 1840
Runtime of the program for j 0.5097355842590332
column j: 1841
Runtime of the program for j 0.44534945487976074
column j: 1842
Runtime of the program for j 0.5033671855926514
column j: 1843
Runtime of the program for j 0.4413876533508301
column j: 1844
Runtime of the program for j 0.211212158203125
column j: 1845
Runtime of the program for j 0.4684946537017822
column j: 1846
Runtime of the program for j 0.21776914596557617
column j: 1847
Runtime of the program for j 0.1571953296661377
column j: 1848
Runtime of the program for j 0.4613211154937744
column j: 1849
Runtime of the program for j 0.49910664558410645
column j: 1850
Runtime of the program for j 0.47295141220092773
column j: 1851
Runtime of the program for j 0.497175931930542
column j: 1852
Runtime of the program for j 0.4556410312652588
column j: 1853
Runtime of the program for j 0.5042705535888672
column j: 1854
Runtime of the program for j 0.46337890625
column j: 1855
Runtime of the program for j 0.5161590576171875
column j: 1856
Runtime of the program for j 0.4551260471343994
column j: 1857
Runtime of the program for j 0.508446455001831
column j: 1858
Runtime of the program for j 0.4486849308013916
column j: 1859
Runtime of the program for j 0.42797136306762695
column j: 1860
Runtime of the program for j 0.4371914863586426
column j: 1861
Runtime of the program for j 0.44481849670410156
column j: 1862
Runtime of the program for j 0.21818161010742188
column j: 1863
Runtime of the program for j 0.4599473476409912
column j: 1864
Runtime of the program for j 0.519646406173706
column j: 1865
Runtime of the program for j 0.4572896957397461
column j: 1866
Runtime of the program for j 0.5026178359985352
column j: 1867
Runtime of the program for j 0.4603734016418457
column j: 1868
Runtime of the program for j 0.5302574634552002
column j: 1869
Runtime of the program for j 0.4596986770629883
column j: 1870
Runtime of the program for j 0.49982571601867676
column j: 1871
Runtime of the program for j 0.4334709644317627
column j: 1872
Runtime of the program for j 0.4441065788269043
column j: 1873
Runtime of the program for j 0.43247032165527344
column j: 1874
Runtime of the program for j 0.4701712131500244
column j: 1875
Runtime of the program for j 0.49494409561157227
column j: 1876
Runtime of the program for j 0.4451894760131836
column j: 1877
Runtime of the program for j 0.49732303619384766
column j: 1878
Runtime of the program for j 0.41472315788269043
column j: 1879
Runtime of the program for j 0.5337033271789551
column j: 1880
Runtime of the program for j 0.46645283699035645
column j: 1881
Runtime of the program for j 0.5097627639770508
column j: 1882
Runtime of the program for j 0.46008777618408203
column j: 1883
Runtime of the program for j 0.5200390815734863
column j: 1884
Runtime of the program for j 0.45331358909606934
column j: 1885
Runtime of the program for j 0.5065758228302002
column j: 1886
Runtime of the program for j 0.1650257110595703
column j: 1887
Runtime of the program for j 0.1600785255432129
column j: 1888
Runtime of the program for j 0.43807363510131836
column j: 1889
Runtime of the program for j 0.42826318740844727
column j: 1890
Runtime of the program for j 0.5086205005645752
column j: 1891
Runtime of the program for j 0.46013712882995605
column j: 1892
Runtime of the program for j 0.2237873077392578
column j: 1893
Runtime of the program for j 0.5259208679199219
column j: 1894
Runtime of the program for j 0.5047965049743652
column j: 1895
Runtime of the program for j 0.44512033462524414
column j: 1896
Runtime of the program for j 0.5203547477722168
column j: 1897
Runtime of the program for j 0.4446687698364258
column j: 1898
Runtime of the program for j 0.545313835144043
column j: 1899
Runtime of the program for j 0.4625082015991211
column j: 1900
Runtime of the program for j 0.5074222087860107
column j: 1901
Runtime of the program for j 0.42988038063049316
column j: 1902
Runtime of the program for j 0.4596982002258301
column j: 1903
Runtime of the program for j 0.44025111198425293
column j: 1904
Runtime of the program for j 0.4519972801208496
column j: 1905
Runtime of the program for j 0.5079677104949951
column j: 1906
Runtime of the program for j 0.4500699043273926
column j: 1907
Runtime of the program for j 0.5051572322845459
column j: 1908
Runtime of the program for j 0.44980549812316895
column j: 1909
Runtime of the program for j 0.49503159523010254
column j: 1910
Runtime of the program for j 0.4451611042022705
column j: 1911
Runtime of the program for j 0.5195713043212891
column j: 1912
Runtime of the program for j 0.47487521171569824
column j: 1913
Runtime of the program for j 0.5178093910217285
column j: 1914
Runtime of the program for j 0.46831321716308594
column j: 1915
Runtime of the program for j 0.5391430854797363
column j: 1916
Runtime of the program for j 0.4618406295776367
column j: 1917
Runtime of the program for j 0.5557327270507812
column j: 1918
Runtime of the program for j 0.47574639320373535
column j: 1919
Runtime of the program for j 0.516653299331665
column j: 1920
Runtime of the program for j 0.42976808547973633
column j: 1921
Runtime of the program for j 0.44304943084716797
column j: 1922
Runtime of the program for j 0.4271664619445801
column j: 1923
Runtime of the program for j 0.4599144458770752
column j: 1924
Runtime of the program for j 0.5027990341186523
column j: 1925
Runtime of the program for j 0.4686751365661621
column j: 1926
Runtime of the program for j 0.2286074161529541
column j: 1927
Runtime of the program for j 0.44383716583251953
column j: 1928
Runtime of the program for j 0.5060408115386963
column j: 1929
Runtime of the program for j 0.4800269603729248
column j: 1930
Runtime of the program for j 0.5098557472229004
column j: 1931
Runtime of the program for j 0.4609248638153076
column j: 1932
Runtime of the program for j 0.5367021560668945
column j: 1933
Runtime of the program for j 0.45743560791015625
column j: 1934
Runtime of the program for j 0.5283985137939453
column j: 1935
Runtime of the program for j 0.4668591022491455
column j: 1936
Runtime of the program for j 0.5196478366851807
column j: 1937
Runtime of the program for j 0.1699514389038086
column j: 1938
Runtime of the program for j 0.5103623867034912
column j: 1939
Runtime of the program for j 0.45255327224731445

In [22]:
curated_bow['max_noise'] = sss['max_noise']
curated_bow

,id,,.,a,if,return,throw,void,},!,...,"} """,} ',} :,} <,~ /,~ dp0node,class_name,class_value,contents,max_noise
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,1,++ b/README.md,0.725794
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,1,"1,23 @@",0.725794
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,1,This plugin downloads/installs Node and NPM lo...,0.725794
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,1,"It's supposed to work on Windows, OS X and Linux.",0.725794
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,1,NaN,0.725794
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,++ b/frontend-maven-plugin/src/main/java/com/g...,4.420658
4990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,},4.420658
4991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,"39,6 @@ public final class BowerMojo extends A...",5.420658
4992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,this.additionalEnvironment = additiona...,5.420658
4993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,++ b/frontend-plugin-core/src/main/java/com/gi...,8.925107

In [28]:
s = sss.sort_values(by='max_noise', ascending = False)
s = s.drop_duplicates(subset = 'max_noise')

values = []
for x in s['max_noise'][0:10]:
    values.append(x)

In [39]:
noise_sorted = curated_bow.sort_values(by='max_noise', ascending = False)
# df = df[df.rebounds.isin(values) == False]
noise_sorted.drop(noise_sorted[noise_sorted['max_noise'].isin(values) == True].index, axis = 0, inplace = True)
noise_sorted

,id,,.,a,if,return,throw,void,},!,...,"} """,} ',} :,} <,~ /,~ dp0node,class_name,class_value,contents,max_noise
4326,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,"99,9 @@ final class ProcessExecutor {",0.607043
4325,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,factory.getBowerRunner(proxyConfig).ex...,0.606704
4324,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,"27,7 @@ Include the plugin as a dependency in ...",0.606364
4323,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,"config.getPlatform(),",0.606241
4321,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,++ b/frontend-maven-plugin/src/main/java/com/g...,0.606241
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3971,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,"@Parameter(property = ""skip.karma"", defaul...",0.497558
3973,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,* Additional environment variables to pass ...,0.497558
3974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,public interface WebpackRunner extends NodeTas...,0.497558
3975,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,++ b/frontend-plugin-core/src/main/java/com/gi...,0.497558
3972,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,build_status,0,"43,7 @@ public final class KarmaRunMojo extend...",0.497558